-- ============================================================================
-- DB2 INDEX RECOMMENDATIONS FOR GMP APP MOBILIDAD - JAVIER SCHEMA
-- Generated by Agent 6: DB2/ODBC Query Optimizer
-- Target: Optimize vendedorCodes=ALL queries (Jefe de Ventas critical path)
-- ============================================================================

-- Check existing indexes first:
-- SELECT INDEX_NAME, TABLE_NAME FROM QSYS2.SYSINDEXES WHERE TABLE_SCHEMA = 'JAVIER';

-- ============================================================================
-- P1: LACLAE - Sales data table (PRIMARY bottleneck for ALL queries)
-- ============================================================================

-- Composite index for vendor + date filtering (most common query pattern)
CREATE INDEX JAVIER.IDX_LACLAE_VEN_FECHA 
  ON JAVIER.LACLAE (VENDEDOR, FECHA DESC);

-- Index for client lookups within vendor scope
CREATE INDEX JAVIER.IDX_LACLAE_CODIGO_VEN 
  ON JAVIER.LACLAE (CODIGO, VENDEDOR, FECHA DESC);

-- Index for product analysis
CREATE INDEX JAVIER.IDX_LACLAE_ART_VEN 
  ON JAVIER.LACLAE (CODART, VENDEDOR, FECHA DESC);

-- Covering index for dashboard metrics (avoids table scan)
CREATE INDEX JAVIER.IDX_LACLAE_DASHBOARD 
  ON JAVIER.LACLAE (VENDEDOR, FECHA DESC) 
  INCLUDE (CODIGO, CODART, IMPORTE, COSTE, CANTIDAD, NUMDOC, BULTOS);

-- ============================================================================
-- P1: CLI - Clients table
-- ============================================================================

CREATE INDEX JAVIER.IDX_CLI_VENDEDOR 
  ON JAVIER.CLI (CODVEN, NOMCLI);

CREATE INDEX JAVIER.IDX_CLI_CODIGO 
  ON JAVIER.CLI (CODCLI);

-- ============================================================================
-- P2: CAC - Delivery/Invoice headers
-- ============================================================================

CREATE INDEX JAVIER.IDX_CAC_VENDEDOR_FECHA 
  ON JAVIER.CAC (VENDEDOR, FECHA DESC);

CREATE INDEX JAVIER.IDX_CAC_NUMALB 
  ON JAVIER.CAC (NUMALB);

-- ============================================================================
-- P2: CPC - Delivery lines
-- ============================================================================

CREATE INDEX JAVIER.IDX_CPC_NUMALB 
  ON JAVIER.CPC (NUMALB, LINEA);

-- ============================================================================
-- P2: ART - Products
-- ============================================================================

CREATE INDEX JAVIER.IDX_ART_FAMILIA 
  ON JAVIER.ART (CODFAM, DESCART);

CREATE INDEX JAVIER.IDX_ART_CODART 
  ON JAVIER.ART (CODART);

-- ============================================================================
-- P3: PMRL1/PMPL1 - Promotions
-- ============================================================================

CREATE INDEX JAVIER.IDX_PMRL1_FECHA 
  ON JAVIER.PMRL1 (FECHAINICIO, FECHAFIN, CODIGOCLIENTE);

CREATE INDEX JAVIER.IDX_PMPL1_IDPROMO 
  ON JAVIER.PMPL1 (IDPROMO);

-- ============================================================================
-- P3: RUTERO_CONFIG
-- ============================================================================

CREATE INDEX JAVIER.IDX_RUTERO_VEN_DIA 
  ON JAVIER.RUTERO_CONFIG (VENDEDOR, DIA, ORDEN);

-- ============================================================================
-- P3: VENTAS_COM - Commissions
-- ============================================================================

CREATE INDEX JAVIER.IDX_VENTAS_COM_VEN_FECHA 
  ON JAVIER.VENTAS_COM (VENDEDOR, FECHA DESC);

-- ============================================================================
-- P3: OBJETIVOS
-- ============================================================================

CREATE INDEX JAVIER.IDX_OBJETIVOS_VEN_ANIO 
  ON JAVIER.OBJETIVOS (VENDEDOR, ANIO, MES);

-- ============================================================================
-- RUNSTATS - Update statistics after creating indexes
-- ============================================================================
-- CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE JAVIER.LACLAE WITH DISTRIBUTION AND DETAILED INDEXES ALL');
-- CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE JAVIER.CLI WITH DISTRIBUTION AND DETAILED INDEXES ALL');
-- CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE JAVIER.ART WITH DISTRIBUTION AND DETAILED INDEXES ALL');
-- CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE JAVIER.CAC WITH DISTRIBUTION AND DETAILED INDEXES ALL');
