-- PILAR 2 pre-prod audit: additive DEFAULT alignment JAVIER -> DSEDAC
-- Generated: 2026-06-11T21:33:34.307Z
-- Both sides NOT NULL; only the default differed (catalog-verified).
-- SET DEFAULT touches no data. JAVIER only.

ALTER TABLE JAVIER.PEDIDOS_CAB ALTER COLUMN NUMEROPEDIDO SET DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ALTER COLUMN CODIGOVENDEDOR SET DEFAULT ' ';
ALTER TABLE JAVIER.PEDIDOS_LIN ALTER COLUMN CODIGOARTICULO SET DEFAULT ' ';
