-- Forward migration, production only. Manual execution after QSYS2 preflight.
-- Stores only real mobile events; no seed data and no customer copy.
SET CURRENT SCHEMA = 'JAVIER';

CREATE TABLE JAVIER.REPARTIDOR_RUTERO_TRACKING (
  SESSION_ID VARCHAR(64) NOT NULL,
  EVENT_ID VARCHAR(128) NOT NULL,
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  ROUTE_DATE DATE NOT NULL,
  EVENT_TYPE VARCHAR(12) NOT NULL,
  LATITUDE DECIMAL(10, 7),
  LONGITUDE DECIMAL(10, 7),
  ACCURACY_METERS DECIMAL(8, 2),
  SPEED_KMH DECIMAL(8, 2),
  HEADING_DEGREES DECIMAL(7, 2),
  RECORDED_AT TIMESTAMP NOT NULL,
  RECEIVED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT CK_REP_TRACKING_EVENT_TYPE CHECK (EVENT_TYPE IN ('START', 'POSITION', 'STOP')),
  CONSTRAINT PK_REP_TRACKING PRIMARY KEY (SESSION_ID, EVENT_ID)
);

CREATE INDEX JAVIER.IX_REP_TRACKING_LATEST
  ON JAVIER.REPARTIDOR_RUTERO_TRACKING
     (REPARTIDOR_ID, ROUTE_DATE, EVENT_TYPE, RECORDED_AT);
