-- Forward migration, production only. Manual execution after QSYS2 preflight.
-- Source of route data remains DSEDAC; these tables are empty overlays/audit.
SET CURRENT SCHEMA = 'JAVIER';

CREATE TABLE JAVIER.REPARTIDOR_RUTERO_DIA_OVERRIDE (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  WEEK_START DATE NOT NULL,
  DOCUMENT_ID VARCHAR(80) NOT NULL,
  SOURCE_DATE DATE NOT NULL,
  TARGET_DATE DATE NOT NULL,
  TARGET_POSITION INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT CK_REP_RUT_DIA_POSITION CHECK (TARGET_POSITION BETWEEN 0 AND 499),
  CONSTRAINT PK_REP_RUT_DIA PRIMARY KEY
    (REPARTIDOR_ID, WEEK_START, DOCUMENT_ID)
);

CREATE INDEX JAVIER.IX_REP_RUT_DIA_TARGET
  ON JAVIER.REPARTIDOR_RUTERO_DIA_OVERRIDE
     (REPARTIDOR_ID, WEEK_START, TARGET_DATE, TARGET_POSITION);

CREATE TABLE JAVIER.REPARTIDOR_RUTERO_MOVE_REQUESTS (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  WEEK_START DATE NOT NULL,
  IDEMPOTENCY_KEY VARCHAR(128) NOT NULL,
  REQUEST_HASH CHAR(64) NOT NULL,
  STATUS VARCHAR(12) NOT NULL,
  DOCUMENT_IDS VARCHAR(12000) NOT NULL,
  TARGET_DATE DATE NOT NULL,
  TARGET_POSITION INTEGER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  COMPLETED_AT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT CK_REP_RUT_MOVE_POSITION CHECK (TARGET_POSITION BETWEEN 0 AND 499),
  CONSTRAINT CK_REP_RUT_MOVE_STATUS CHECK (STATUS IN ('APPLIED', 'PENDING', 'FAILED')),
  CONSTRAINT PK_REP_RUT_MOVE PRIMARY KEY
    (REPARTIDOR_ID, WEEK_START, IDEMPOTENCY_KEY)
);
