CREATE OR REPLACE VIEW JAVIER.V_DIM_CLIENTE AS
SELECT
  CLIL1.CODIGOCLIENTE,
  CLIL1.NOMBRECLIENTE,
  CLIL1.DIRECCION,
  CLIL1.CODIGOPOSTAL,
  CLIL1.POBLACION,
  CLIL1.PROVINCIA,
  CLIL1.NIF,
  CLIL1.TELEFONO1,
  CLIL1.TELEFONO2,
  CLIL1.TELEFONOFAX,
  CLIL1.TIPOEMPRESA,
  CLIL1.EXENTOIVASN,
  CLIL1.CODIGORUTA,
  CLIL1.RECARGOSN,
  CLIL1.CODIGODELEGACION,
  CLIL1.NOMBREALTERNATIVO AS NOMBRE_COMERCIAL,
  CASE
    WHEN CLIL1.CLFCAL > 0 THEN DATE(SUBSTR(DIGITS(CLIL1.CLFCAL),1,4)||'-'||SUBSTR(DIGITS(CLIL1.CLFCAL),5,2)||'-'||SUBSTR(DIGITS(CLIL1.CLFCAL),7,2))
    ELSE NULL
  END AS FECHA_ALTA,
  CASE
    WHEN CLIL1.CLFCBJ > 0 THEN DATE(SUBSTR(DIGITS(CLIL1.CLFCBJ),1,4)||'-'||SUBSTR(DIGITS(CLIL1.CLFCBJ),5,2)||'-'||SUBSTR(DIGITS(CLIL1.CLFCBJ),7,2))
    ELSE NULL
  END AS FECHA_BAJA,
  CASE
    WHEN CLIL1.DIABAJA>0 OR CLIL1.MESBAJA>0 OR CLIL1.ANOBAJA>0 THEN 'BAJA'
    ELSE 'ACTIVO'
  END AS ESTADO_CLIENTE,
  CLCL1.CODIGOTARIFA,
  CLCL1.CODIGOFORMAPAGO1,
  CLCL1.CODIGOFORMAPAGO2,
  CLCL1.BLOQUEADOSN,
  CLCL1.DIASLIMITECREDITO,
  CLCL1.MAXIMONUMEROFACTURASPENDIENT,
  CLCL1.PORCENTAJEDECUENTO1,
  CLXL1.CADENA,
  CLXL1.CORREOELECTRONICOCLIENTE,
  CLXL1.IMPORTEMINIMOPEDIDO,
  CLXL1.PORCENTAJEMAXIMODEVOLUCION,
  CLXL1.SITIOWEB,
  CLP.IMPORTELIMITERIESGO,
  CLP.SEGUROCREDITOSN,
  CLP.VENDEDORCOBRO,
  CLP.VENDEDORCOMERCIAL,
  CLP.VENDEDORPREVENTISTA,
  CLP.VENDEDORREPARTIDOR
FROM DSEDAC.CLIL1 CLIL1
LEFT JOIN DSEDAC.CLCL1 CLCL1 ON TRIM(CLCL1.CODIGOCLIENTE)=TRIM(CLIL1.CODIGOCLIENTE)
LEFT JOIN DSEDAC.CLXL1 CLXL1 ON TRIM(CLXL1.CODIGOCLIENTE)=TRIM(CLIL1.CODIGOCLIENTE)
LEFT JOIN DSEDAC.CLP CLP ON TRIM(CLP.CODIGOCLIENTE)=TRIM(CLIL1.CODIGOCLIENTE);
