CREATE OR REPLACE VIEW JAVIER.V_DIM_CLIENTE AS
SELECT
  CLI.CODIGOCLIENTE,
  CLI.NOMBRECLIENTE,
  CLI.DIRECCION,
  CLI.CODIGOPOSTAL,
  CLI.POBLACION,
  CLI.PROVINCIA,
  CLI.NIF,
  CLI.TELEFONO1,
  CLI.TELEFONO2,
  CLI.TELEFONOFAX,
  CLI.TIPOEMPRESA,
  CLI.EXENTOIVASN,
  CLI.CODIGORUTA,
  CLI.RECARGOSN,
  CLI.CODIGODELEGACION,
  CLI.NOMBREALTERNATIVO AS NOMBRE_COMERCIAL,
  CASE
    WHEN CLI.ANOALTA > 0 AND CLI.MESALTA BETWEEN 1 AND 12 AND CLI.DIAALTA BETWEEN 1 AND 31
    THEN DATE(LPAD(CAST(CLI.ANOALTA AS VARCHAR(4)),4,'0')||'-'||LPAD(CAST(CLI.MESALTA AS VARCHAR(2)),2,'0')||'-'||LPAD(CAST(CLI.DIAALTA AS VARCHAR(2)),2,'0'))
    ELSE NULL
  END AS FECHA_ALTA,
  CASE
    WHEN CLI.ANOBAJA > 0 AND CLI.MESBAJA BETWEEN 1 AND 12 AND CLI.DIABAJA BETWEEN 1 AND 31
    THEN DATE(LPAD(CAST(CLI.ANOBAJA AS VARCHAR(4)),4,'0')||'-'||LPAD(CAST(CLI.MESBAJA AS VARCHAR(2)),2,'0')||'-'||LPAD(CAST(CLI.DIABAJA AS VARCHAR(2)),2,'0'))
    ELSE NULL
  END AS FECHA_BAJA,
  CASE
    WHEN CLI.DIABAJA>0 OR CLI.MESBAJA>0 OR CLI.ANOBAJA>0 THEN 'BAJA'
    ELSE 'ACTIVO'
  END AS ESTADO_CLIENTE,
  CLC.CODIGOTARIFA,
  CLC.CODIGOFORMAPAGO1,
  CLC.CODIGOFORMAPAGO2,
  CLC.BLOQUEADOSN,
  CLC.DIASLIMITECREDITO,
  CLC.MAXIMONUMEROFACTURASPENDIENT,
  CLC.PORCENTAJEDECUENTO1,
  CLX.CADENA,
  CLX.CORREOELECTRONICOCLIENTE,
  CLX.IMPORTEMINIMOPEDIDO,
  CLX.PORCENTAJEMAXIMODEVOLUCION,
  CLX.SITIOWEB,
  CLP.IMPORTELIMITERIESGO,
  CLP.SEGUROCREDITOSN,
  CLP.VENDEDORCOBRO,
  CLP.VENDEDORCOMERCIAL,
  CLP.VENDEDORPREVENTISTA,
  CLP.VENDEDORREPARTIDOR
FROM DSEDAC.CLI CLI
LEFT JOIN DSEDAC.CLC CLC ON TRIM(CLC.CODIGOCLIENTE)=TRIM(CLI.CODIGOCLIENTE)
LEFT JOIN DSEDAC.CLX CLX ON TRIM(CLX.CODIGOCLIENTE)=TRIM(CLI.CODIGOCLIENTE)
LEFT JOIN DSEDAC.CLP CLP ON TRIM(CLP.CODIGOCLIENTE)=TRIM(CLI.CODIGOCLIENTE);
