-- schema_db2.sql: Esquema DB2 para el sistema KPI Glacius
-- Ejecutar con IBM Access Client Solutions (ACS) contra DSN='GMP', schema JAVIER
-- Ejecutar cada bloque por separado si hay errores de sintaxis

-- ============================================================
-- 1. Tabla de cargas (idempotencia semanal)
-- ============================================================
CREATE TABLE JAVIER.KPI_LOADS (
    ID              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOAD_ID         VARCHAR(32) NOT NULL,
    STATUS          VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    FILES_PROCESSED VARCHAR(1024) DEFAULT '',
    TOTAL_ALERTS    INTEGER DEFAULT 0,
    ERRORS          VARCHAR(4096) DEFAULT '[]',
    STARTED_AT      TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    COMPLETED_AT    TIMESTAMP,
    CHECKSUM        VARCHAR(128),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT UQ_KPI_LOADS_LOADID UNIQUE (LOAD_ID)
);

CREATE INDEX JAVIER.IDX_KPI_LOADS_STATUS ON JAVIER.KPI_LOADS (STATUS);

-- ============================================================
-- 2. Tabla de alertas KPI por cliente
-- ============================================================
CREATE TABLE JAVIER.KPI_ALERTS (
    ID              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOAD_ID         VARCHAR(32) NOT NULL,
    CLIENT_CODE     VARCHAR(20) NOT NULL,
    ALERT_TYPE      VARCHAR(40) NOT NULL,
    SEVERITY        VARCHAR(10) NOT NULL DEFAULT 'warning',
    MESSAGE         VARCHAR(2048) NOT NULL,
    RAW_DATA        CLOB(64K) DEFAULT '{}',
    SOURCE_FILE     VARCHAR(100) NOT NULL,
    IS_ACTIVE       SMALLINT NOT NULL DEFAULT 1,
    EXPIRES_AT      TIMESTAMP,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT FK_KPI_ALERTS_LOAD FOREIGN KEY (LOAD_ID)
        REFERENCES JAVIER.KPI_LOADS(LOAD_ID) ON DELETE CASCADE
);

CREATE INDEX JAVIER.IDX_KPI_ALERTS_CLIENT ON JAVIER.KPI_ALERTS (CLIENT_CODE);
CREATE INDEX JAVIER.IDX_KPI_ALERTS_LOAD ON JAVIER.KPI_ALERTS (LOAD_ID);
CREATE INDEX JAVIER.IDX_KPI_ALERTS_TYPE ON JAVIER.KPI_ALERTS (ALERT_TYPE);
CREATE INDEX JAVIER.IDX_KPI_ALERTS_ACTIVE ON JAVIER.KPI_ALERTS (IS_ACTIVE, CLIENT_CODE);
CREATE INDEX JAVIER.IDX_KPI_ALERTS_SEV ON JAVIER.KPI_ALERTS (SEVERITY);
CREATE INDEX JAVIER.IDX_KPI_ALERTS_CREATED ON JAVIER.KPI_ALERTS (CREATED_AT DESC);

-- Índice compuesto para la consulta principal de la API
CREATE INDEX JAVIER.IDX_KPI_ALERTS_MAIN ON JAVIER.KPI_ALERTS (CLIENT_CODE, IS_ACTIVE, SEVERITY, CREATED_AT DESC);

-- ============================================================
-- 3. Tabla de auditoría de archivos procesados
-- ============================================================
CREATE TABLE JAVIER.KPI_FILE_AUDIT (
    ID              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOAD_ID         VARCHAR(32) NOT NULL,
    FILENAME        VARCHAR(100) NOT NULL,
    FILE_SIZE       BIGINT DEFAULT 0,
    FILE_HASH       VARCHAR(128),
    ROWS_TOTAL      INTEGER DEFAULT 0,
    ROWS_PARSED     INTEGER DEFAULT 0,
    ROWS_SKIPPED    INTEGER DEFAULT 0,
    ALERTS_GENERATED INTEGER DEFAULT 0,
    PARSE_ERRORS    VARCHAR(4096) DEFAULT '[]',
    PROCESSED_AT    TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT FK_KPI_AUDIT_LOAD FOREIGN KEY (LOAD_ID)
        REFERENCES JAVIER.KPI_LOADS(LOAD_ID) ON DELETE CASCADE
);

CREATE INDEX JAVIER.IDX_KPI_AUDIT_LOAD ON JAVIER.KPI_FILE_AUDIT (LOAD_ID);

-- ============================================================
-- 4. Tabla de migraciones aplicadas
-- ============================================================
CREATE TABLE JAVIER.KPI_MIGRATIONS (
    ID              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL,
    APPLIED_AT      TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT UQ_KPI_MIGRATIONS_NAME UNIQUE (NAME)
);
