-- Additive talón columns on app cobros tables (CRC-aligned names).
-- JAVIER only. NEVER DSEDAC.
-- Run after QSYS2 compare: add only MISSING columns.

ALTER TABLE JAVIER.TEST_REPARTIDOR_COBROS ADD COLUMN NUMEROTALON CHAR(10);
ALTER TABLE JAVIER.TEST_REPARTIDOR_COBROS ADD COLUMN CODIGOENTIDADBANCARIA CHAR(4);
ALTER TABLE JAVIER.TEST_REPARTIDOR_COBROS ADD COLUMN NOMBREENTIDADBANCARIA VARCHAR(40);
ALTER TABLE JAVIER.TEST_REPARTIDOR_COBROS ADD COLUMN DIAVENCIMIENTO NUMERIC(2, 0);
ALTER TABLE JAVIER.TEST_REPARTIDOR_COBROS ADD COLUMN MESVENCIMIENTO NUMERIC(2, 0);
ALTER TABLE JAVIER.TEST_REPARTIDOR_COBROS ADD COLUMN ANOVENCIMIENTO NUMERIC(4, 0);
ALTER TABLE JAVIER.TEST_REPARTIDOR_COBROS ADD COLUMN EFECTIVOTALON CHAR(1);

ALTER TABLE JAVIER.REPARTIDOR_COBROS ADD COLUMN NUMEROTALON CHAR(10);
ALTER TABLE JAVIER.REPARTIDOR_COBROS ADD COLUMN CODIGOENTIDADBANCARIA CHAR(4);
ALTER TABLE JAVIER.REPARTIDOR_COBROS ADD COLUMN NOMBREENTIDADBANCARIA VARCHAR(40);
ALTER TABLE JAVIER.REPARTIDOR_COBROS ADD COLUMN DIAVENCIMIENTO NUMERIC(2, 0);
ALTER TABLE JAVIER.REPARTIDOR_COBROS ADD COLUMN MESVENCIMIENTO NUMERIC(2, 0);
ALTER TABLE JAVIER.REPARTIDOR_COBROS ADD COLUMN ANOVENCIMIENTO NUMERIC(4, 0);
ALTER TABLE JAVIER.REPARTIDOR_COBROS ADD COLUMN EFECTIVOTALON CHAR(1);
