-- Allow delivering MORE units than planned (still non-negative).
-- Isolated test first; production table only after QSYS2 compare.

ALTER TABLE JAVIER.TEST_REPARTO_LINEAS DROP CONSTRAINT CK_TEST_REP_LINEAS_TOTAL;
ALTER TABLE JAVIER.TEST_REPARTO_LINEAS ADD CONSTRAINT CK_TEST_REP_LINEAS_TOTAL CHECK
  (
    (CANTIDAD_ENTREGADA <= CANTIDAD_PEDIDA
      AND CANTIDAD_PEDIDA = CANTIDAD_ENTREGADA + CANTIDAD_RECHAZADA + CANTIDAD_PENDIENTE)
    OR (CANTIDAD_ENTREGADA > CANTIDAD_PEDIDA
      AND CANTIDAD_RECHAZADA = 0
      AND CANTIDAD_PENDIENTE = 0)
  );
