-- JAVIER.LACLAE_MONTHLY — agregado mensual de ventas (schema JAVIER only).
-- Source SELECT: comercialErpTable('LACLAE') = JAVIER.TEST_LACLAE in isolated_test,
-- DSED.LACLAE in prod (read-only). NEVER DDL on DSED/DSEDAC.
-- Rollback: DROP TABLE JAVIER.LACLAE_MONTHLY;

CREATE TABLE JAVIER.LACLAE_MONTHLY (
  ANO NUMERIC(4, 0) NOT NULL,
  MES NUMERIC(2, 0) NOT NULL,
  VENDEDOR CHAR(2) NOT NULL,
  VENDEDOR_R1 CHAR(2) NOT NULL,
  CLIENTE CHAR(10) NOT NULL,
  SALES NUMERIC(14, 2) NOT NULL,
  COST NUMERIC(14, 2) NOT NULL,
  UNITS NUMERIC(16, 5) NOT NULL,
  BOXES NUMERIC(14, 2) NOT NULL,
  LINEAS INTEGER NOT NULL,
  PEDIDOS INTEGER NOT NULL
);

CREATE INDEX JAVIER.IX_LACLAE_M_YM ON JAVIER.LACLAE_MONTHLY (ANO, MES);
CREATE INDEX JAVIER.IX_LACLAE_M_YMC ON JAVIER.LACLAE_MONTHLY (ANO, MES, CLIENTE);
CREATE INDEX JAVIER.IX_LACLAE_M_YMV ON JAVIER.LACLAE_MONTHLY (ANO, MES, VENDEDOR);
