-- Idempotent intent for JAVIER isolated_test only.
-- The runner backend/migrations/048_javier_test_evidence_capture_and_precio_competitivo.js
-- checks QSYS2.SYSCOLUMNS / SYSTABLES / SYSINDEXES before each statement.
-- Do not run this file against production. Do not target DSEDAC or DSED.
--
-- Verified 2026-10-01 via QSYS2:
--   DSEDAC.ART.CODIGOARTICULO CHAR(10) NOT NULL
--   DSEDAC.CLC.CODIGOCLIENTE CHAR(10) NOT NULL
--   DSEDAC.CLC.CODIGOTARIFA NUMERIC(2,0) NOT NULL
--   DSEDAC.ARA.PRECIOTARIFA NUMERIC(9,4) NOT NULL
--   JAVIER.TEST_PRECIO_COMPETITIVO did not exist.
--   JAVIER.PRECIO_COMPETITIVO did not exist (production does not have this table).
--
-- Evidence limits: photo 4 MiB, signature 1 MiB. Upload idempotency is sha256.
-- Photo window: same weekday of the following week, inclusive, until 23:59:59 Europe/Madrid.
-- DST: spring last Sunday of March 02:00 CET -> 03:00 CEST; fall last Sunday of October
-- 03:00 CEST -> 02:00 CET. Deadline is civil Madrid time, not +168 hours.

ALTER TABLE JAVIER.TEST_REPARTO_EVIDENCIAS ADD COLUMN CAPTURED_AT TIMESTAMP;
ALTER TABLE JAVIER.TEST_REPARTO_EVIDENCIAS ADD COLUMN DEVICE_ID VARCHAR(80);

CREATE TABLE JAVIER.TEST_PRECIO_COMPETITIVO (
  ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
  CODIGOARTICULO CHAR(10) NOT NULL,
  CODIGOCLIENTE CHAR(10) NOT NULL,
  CODIGOTARIFA NUMERIC(2, 0) NOT NULL,
  PRECIO_COMPETITIVO NUMERIC(9, 4) NOT NULL,
  MARGEN_PCT DECIMAL(5, 2) NOT NULL,
  VALIDO_DESDE DATE NOT NULL,
  VALIDO_HASTA DATE,
  USUARIO VARCHAR(40) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  CONSTRAINT PK_TEST_PRECIO_COMPETITIVO PRIMARY KEY (ID),
  CONSTRAINT CK_TEST_PC_MARGEN CHECK (MARGEN_PCT >= 0 AND MARGEN_PCT <= 100),
  CONSTRAINT CK_TEST_PC_PRECIO CHECK (PRECIO_COMPETITIVO > 0),
  CONSTRAINT CK_TEST_PC_VIGENCIA CHECK (VALIDO_HASTA IS NULL OR VALIDO_HASTA >= VALIDO_DESDE)
);

CREATE INDEX JAVIER.IX_TEST_PC_LOOKUP
  ON JAVIER.TEST_PRECIO_COMPETITIVO (CODIGOARTICULO, CODIGOCLIENTE, VALIDO_DESDE);
