'use strict';

/**
 * INIT-TABLES — Centralized, idempotent creation of APP-SPECIFIC tables
 * =====================================================================
 * Only creates auxiliary tables the app itself manages (pedidos, cobros
 * tracking, bolsa comercial, liquidaciones, etc.) in JAVIER schema.
 *
 * ERP tables (CVC, CPC, CLI, ART, STA, CLC, CLP, LACLAE…) already exist
 * in DSEDAC and are NEVER created or modified by this script.
 *
 * Usage:
 *   node backend/migrations/init-tables.js
 *   Called from server.js on startup.
 */

const logger = require('../middleware/logger');
const { db2Schema, db2Identifier } = require('../utils/db2-identifiers');

const APP_SCHEMA = db2Schema(process.env.PEDIDOS_CONFIRMATION_SCHEMA || 'JAVIER', 'PEDIDOS_CONFIRMATION_SCHEMA');
const BOLSA_SCHEMA = 'JAVIER';
const FIXED_TABLE_SCHEMAS = Object.freeze({
  BOLSA_COMERCIAL: BOLSA_SCHEMA,
  MOVIMIENTOS_BOLSA: BOLSA_SCHEMA,
});

function schemaForTable(tableName) {
  return FIXED_TABLE_SCHEMAS[tableName] || APP_SCHEMA;
}

// ─── TABLE DDL (app-specific only) ──────────────────────────────────

const TABLE_DDL = {
  PEDIDOS_CAB: `
    CREATE TABLE ${APP_SCHEMA}.PEDIDOS_CAB (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      SUBEMPRESA CHAR(3) DEFAULT 'GMP',
      EJERCICIO NUMERIC(4) NOT NULL,
      NUMEROPEDIDO NUMERIC(6) NOT NULL,
      SERIEPEDIDO CHAR(1) DEFAULT 'M',
      TERMINAL NUMERIC(3) DEFAULT 999,
      DIADOCUMENTO NUMERIC(2),
      MESDOCUMENTO NUMERIC(2),
      ANODOCUMENTO NUMERIC(4),
      HORADOCUMENTO NUMERIC(6) DEFAULT 0,
      CODIGOCLIENTE CHAR(10) NOT NULL,
      NOMBRECLIENTE VARCHAR(60),
      CODIGOVENDEDOR CHAR(2) NOT NULL,
      CODIGOFORMAPAGO CHAR(2) DEFAULT '02',
      CODIGOTARIFA NUMERIC(2) DEFAULT 1,
      CODIGOALMACEN NUMERIC(4) DEFAULT 1,
      TIPOVENTA CHAR(2) DEFAULT 'CC',
      ESTADO VARCHAR(12) DEFAULT 'BORRADOR',
      IMPORTETOTAL NUMERIC(11,2) DEFAULT 0,
      IMPORTEBASE NUMERIC(11,2) DEFAULT 0,
      IMPORTEIVA NUMERIC(11,2) DEFAULT 0,
      IMPORTECOSTO NUMERIC(11,2) DEFAULT 0,
      IMPORTEMARGEN NUMERIC(11,2) DEFAULT 0,
      DESCUENTO_GLOBAL DECIMAL(5,2) DEFAULT 0,
      OBSERVACIONES VARCHAR(200) DEFAULT '',
      ORIGEN CHAR(1) DEFAULT 'A',
      FECHAREPARTO DATE,
      DIAREPARTO NUMERIC(2) DEFAULT 0,
      MESREPARTO NUMERIC(2) DEFAULT 0,
      ANOREPARTO NUMERIC(4) DEFAULT 0,
      CODIGOREPARTIDOR CHAR(2) DEFAULT ' ',
      CODIGOVEHICULO CHAR(10) DEFAULT ' ',
      RUTA VARCHAR(10) DEFAULT '',
      DIASREPARTO VARCHAR(80) DEFAULT '',
      REPARTO_VALIDADO_SN CHAR(1) DEFAULT 'N',
      REPARTO_VALIDADO_AT TIMESTAMP,
      TARGET_SCHEMA CHAR(10) DEFAULT 'JAVIER',
      SYNC_STATUS VARCHAR(16) DEFAULT 'LOCAL',
      SYNC_AT TIMESTAMP,
      SYSTEM_SUBEMPRESAPEDIDO CHAR(3) DEFAULT ' ',
      SYSTEM_EJERCICIOPEDIDO NUMERIC(4) DEFAULT 0,
      SYSTEM_SERIEPEDIDO CHAR(1) DEFAULT ' ',
      SYSTEM_TERMINALPEDIDO NUMERIC(3) DEFAULT 0,
      SYSTEM_NUMEROPEDIDO NUMERIC(6) DEFAULT 0,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

  PEDIDOS_LIN: `
    CREATE TABLE ${APP_SCHEMA}.PEDIDOS_LIN (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      PEDIDO_ID INTEGER NOT NULL,
      SECUENCIA NUMERIC(4) DEFAULT 1,
      CODIGOARTICULO CHAR(10) NOT NULL,
      DESCRIPCION CHAR(40),
      CANTIDADENVASES NUMERIC(7,2) DEFAULT 0,
      CANTIDADUNIDADES NUMERIC(10,5) DEFAULT 0,
      UNIDADMEDIDA VARCHAR(12) DEFAULT 'CAJAS',
      UNIDADESCAJA NUMERIC(10,5) DEFAULT 1,
      UNIDADESFRACCION NUMERIC(10,5) DEFAULT 0,
      PRECIOVENTA NUMERIC(9,4) DEFAULT 0,
      PRECIOCOSTO NUMERIC(9,4) DEFAULT 0,
      PRECIOTARIFA NUMERIC(9,4) DEFAULT 0,
      PRECIOTARIFACLIENTE NUMERIC(9,4) DEFAULT 0,
      PRECIOMINIMO NUMERIC(9,4) DEFAULT 0,
      IMPORTEVENTA NUMERIC(10,2) DEFAULT 0,
      IMPORTECOSTO NUMERIC(10,2) DEFAULT 0,
      IMPORTEMARGEN NUMERIC(10,2) DEFAULT 0,
      PORCENTAJEMARGEN NUMERIC(7,2) DEFAULT 0,
      DESCUENTO_LINEA DECIMAL(5,2) DEFAULT 0,
      TIPOLINEA CHAR(1) DEFAULT 'R',
      TIPOVENTA CHAR(2) DEFAULT 'CC',
      CLASELINEA CHAR(2) DEFAULT 'VT',
      ORDEN NUMERIC(4) DEFAULT 0,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

  PEDIDOS_SEQ: `
    CREATE TABLE ${APP_SCHEMA}.PEDIDOS_SEQ (
      EJERCICIO NUMERIC(4) NOT NULL PRIMARY KEY,
      ULTIMO_NUMERO NUMERIC(6) DEFAULT 0
    )`,

  PEDIDOS_STOCK_RESERVE: `
    CREATE TABLE ${APP_SCHEMA}.PEDIDOS_STOCK_RESERVE (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      PEDIDO_ID INTEGER NOT NULL,
      CODIGOARTICULO CHAR(10) NOT NULL,
      CANTIDADENVASES NUMERIC(7,2) DEFAULT 0,
      CANTIDADUNIDADES NUMERIC(10,5) DEFAULT 0,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

  COBROS: `
    CREATE TABLE ${APP_SCHEMA}.COBROS (
      ID VARCHAR(64) NOT NULL PRIMARY KEY,
      CODIGO_CLIENTE VARCHAR(20) NOT NULL,
      REFERENCIA VARCHAR(100),
      IMPORTE DECIMAL(11,2) NOT NULL DEFAULT 0,
      FORMA_PAGO VARCHAR(50) DEFAULT 'CONTADO',
      TIPO_VENTA VARCHAR(20) DEFAULT 'CC',
      TIPO_MODO VARCHAR(20) DEFAULT 'NORMAL',
      TIPO_USUARIO VARCHAR(20) DEFAULT 'COMERCIAL',
      CODIGO_USUARIO VARCHAR(20),
      OBSERVACIONES VARCHAR(500),
      IDEMPOTENCY_TOKEN VARCHAR(128),
      FECHA TIMESTAMP DEFAULT CURRENT TIMESTAMP,
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  DELIVERY_STATUS: `
    CREATE TABLE ${APP_SCHEMA}.DELIVERY_STATUS (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      ITEM_ID VARCHAR(160) NOT NULL,
      REPARTIDOR_ID VARCHAR(20) NOT NULL,
      STATUS VARCHAR(20) DEFAULT 'PENDIENTE',
      OBSERVACIONES VARCHAR(1000),
      FIRMA VARCHAR(500),
      FOTOS VARCHAR(2000),
      LATITUD DECIMAL(10,7),
      LONGITUD DECIMAL(10,7),
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  CLIENT_NOTES: `
    CREATE TABLE ${APP_SCHEMA}.CLIENT_NOTES (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      CLIENT_CODE VARCHAR(20) NOT NULL,
      VENDEDOR_CODE VARCHAR(10),
      NOTE_TEXT VARCHAR(2000) NOT NULL,
      NOTE_TYPE VARCHAR(20) DEFAULT 'GENERAL',
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  KPI_ALERTS: `
    CREATE TABLE ${APP_SCHEMA}.KPI_ALERTS (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      ALERT_TYPE VARCHAR(50) NOT NULL,
      SEVERITY VARCHAR(20) DEFAULT 'INFO',
      TITLE VARCHAR(200),
      MESSAGE VARCHAR(2000),
      VENDEDOR_CODE VARCHAR(10),
      CLIENT_CODE VARCHAR(20),
      METRIC_VALUE DECIMAL(15,4),
      THRESHOLD_VALUE DECIMAL(15,4),
      STATUS VARCHAR(20) DEFAULT 'ACTIVE',
      ACKNOWLEDGED_BY VARCHAR(20),
      ACKNOWLEDGED_AT TIMESTAMP,
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  KPI_LOADS: `
    CREATE TABLE ${APP_SCHEMA}.KPI_LOADS (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      LOAD_TYPE VARCHAR(50) NOT NULL,
      STATUS VARCHAR(20) DEFAULT 'PENDING',
      RECORDS_PROCESSED INTEGER DEFAULT 0,
      RECORDS_FAILED INTEGER DEFAULT 0,
      ERROR_MESSAGE VARCHAR(2000),
      STARTED_AT TIMESTAMP,
      COMPLETED_AT TIMESTAMP,
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  KPI_FILE_AUDIT: `
    CREATE TABLE ${APP_SCHEMA}.KPI_FILE_AUDIT (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      FILE_NAME VARCHAR(200) NOT NULL,
      FILE_HASH VARCHAR(64),
      FILE_SIZE INTEGER,
      STATUS VARCHAR(20) DEFAULT 'PENDING',
      PROCESSED_AT TIMESTAMP,
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  REPARTIDOR_FINANCIAL_BALANCES: `
    CREATE TABLE ${APP_SCHEMA}.REPARTIDOR_FINANCIAL_BALANCES (
      CODIGOVENDEDOR CHAR(10) NOT NULL PRIMARY KEY,
      SALDO_PENDIENTE DECIMAL(11,2) DEFAULT 0,
      UPDATED_BY VARCHAR(20),
      UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  LQD_LIQUIDACIONES: `
    CREATE TABLE ${APP_SCHEMA}.LQD_LIQUIDACIONES (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      CODIGO_REPARTIDOR VARCHAR(10) NOT NULL,
      FECHA DATE NOT NULL,
      IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL,
      MATRICULA VARCHAR(20),
      CODIGO_VEHICULO VARCHAR(10),
      TOTAL_EFECTIVO DECIMAL(11,2) DEFAULT 0,
      TOTAL_CHEQUES DECIMAL(11,2) DEFAULT 0,
      TOTAL_TARJETA DECIMAL(11,2) DEFAULT 0,
      TOTAL_POSTDATADOS DECIMAL(11,2) DEFAULT 0,
      SALDO_ACTUAL DECIMAL(11,2) DEFAULT 0,
      TOTAL_COBROS_DIA DECIMAL(11,2) DEFAULT 0,
      TOTAL_A_INGRESAR DECIMAL(11,2) DEFAULT 0,
      INGRESO_BANCO DECIMAL(11,2) DEFAULT 0,
      GASTOS DECIMAL(11,2) DEFAULT 0,
      EFECTIVO2 DECIMAL(11,2) DEFAULT 0,
      ENTREGADO2 DECIMAL(11,2) DEFAULT 0,
      STATUS VARCHAR(20) DEFAULT 'OPEN',
      CREATED_BY VARCHAR(20),
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  LQD: `
    CREATE TABLE ${APP_SCHEMA}.LQD (
      SUBEMPRESALIQUIDACION CHAR(3) NOT NULL,
      EJERCICIOLIQUIDACION NUMERIC(4) NOT NULL,
      SERIELIQUIDACION CHAR(1) NOT NULL,
      TERMINALLIQUIDACION NUMERIC(3) NOT NULL,
      NUMEROLIQUIDACION NUMERIC(10) NOT NULL,
      DIALIQUIDACION NUMERIC(2) NOT NULL,
      MESLIQUIDACION NUMERIC(2) NOT NULL,
      ANOLIQUIDACION NUMERIC(4) NOT NULL,
      HORALIQUIDACION NUMERIC(6) NOT NULL,
      CODIGOVENDEDOR CHAR(10) NOT NULL,
      CODIGOVENDEDORUSUARIO CHAR(10) NOT NULL,
      CODIGOUSUARIO CHAR(10) NOT NULL,
      MATRICULA CHAR(20) NOT NULL,
      KILOMETROSSALIDA NUMERIC(11,3) NOT NULL,
      KILOMETROSLLEGADA NUMERIC(11,3) NOT NULL,
      KILOMETROSRECORRIDOS NUMERIC(11,3) NOT NULL,
      IMPORTEEFECTIVO NUMERIC(10,2) NOT NULL,
      IMPORTECHEQUES NUMERIC(10,2) NOT NULL,
      IMPORTEPOSTDATADOS NUMERIC(10,2) NOT NULL,
      IMPORTESALDOACTUAL NUMERIC(10,2) NOT NULL,
      IMPORTETOTALAINGRESAR NUMERIC(10,2) NOT NULL,
      IMPORTEINGRESOENBANCO NUMERIC(10,2) NOT NULL,
      IMPORTEGASTOS NUMERIC(10,2) NOT NULL,
      IMPRESOSN CHAR(1) NOT NULL,
      CODIGOVEHICULO CHAR(10) NOT NULL,
      REVISADOSN CHAR(1) NOT NULL,
      IDMARCALIQUIDACION CHAR(30) NOT NULL,
      IMPORTEEFECTIVO2 NUMERIC(10,2) NOT NULL,
      IMPORTEENTREGADO2 NUMERIC(10,2) NOT NULL,
      IMPORTETARJETA NUMERIC(10,2) NOT NULL,
      ID INTEGER NOT NULL,
      MARCAACTUALIZACION VARCHAR(50) NOT NULL
    )`,

  LQD_IDEMPOTENCY: `
    CREATE TABLE ${APP_SCHEMA}.LQD_IDEMPOTENCY (
      TOKEN VARCHAR(128) NOT NULL PRIMARY KEY,
      RESULT_TYPE VARCHAR(20),
      RESULT_ID INTEGER,
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  LQD_COMMISSION_TIERS: `
    CREATE TABLE ${APP_SCHEMA}.LQD_COMMISSION_TIERS (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      THRESHOLD_PCT DECIMAL(5,2) NOT NULL,
      COMMISSION_PCT DECIMAL(5,2) NOT NULL,
      UPDATED_BY VARCHAR(20),
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  // BOLSA_COMERCIAL y MOVIMIENTOS_BOLSA viven SIEMPRE en JAVIER, incluso cuando
  // APP_SCHEMA=DSEDAC en produccion. Es una decision de negocio: la bolsa es
  // una tabla auxiliar de control interno que no se replica al ERP.
  BOLSA_COMERCIAL: `
    CREATE TABLE JAVIER.BOLSA_COMERCIAL (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      CODIGOVENDEDOR VARCHAR(10) NOT NULL,
      EJERCICIO NUMERIC(4) NOT NULL,
      MES NUMERIC(2) NOT NULL,
      LIMITE_PCT DECIMAL(5,2) DEFAULT 3.00,
      LIMITE_IMPORTE DECIMAL(11,2) DEFAULT 0,
      SALDO_DISPONIBLE DECIMAL(11,2) DEFAULT 300.00,
      CONSUMIDO DECIMAL(11,2) DEFAULT 0,
      ACUMULADO DECIMAL(11,2) DEFAULT 0,
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
      CONSTRAINT UQ_BOLSA_VND_MES UNIQUE (CODIGOVENDEDOR, EJERCICIO, MES)
    )`,

  MOVIMIENTOS_BOLSA: `
    CREATE TABLE JAVIER.MOVIMIENTOS_BOLSA (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      BOLSA_ID INTEGER NOT NULL,
      CODIGOVENDEDOR VARCHAR(10),
      PEDIDO_ID INTEGER,
      LINEA_ID INTEGER,
      TIPO VARCHAR(20) NOT NULL,
      IMPORTE DECIMAL(11,2) NOT NULL,
      SALDO_ANTERIOR DECIMAL(11,2),
      SALDO_POSTERIOR DECIMAL(11,2),
      CODIGO_ARTICULO VARCHAR(20),
      DESCRIPCION VARCHAR(200),
      PRECIO_MINIMO_CONGELADO DECIMAL(9,4),
      PRECIO_VENTA DECIMAL(9,4),
      CANTIDAD DECIMAL(12,5),
      UNIDAD_MEDIDA VARCHAR(12),
      IDEMPOTENCY_KEY VARCHAR(128),
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  REPARTIDOR_LIQUIDACION_OPS: `
    CREATE TABLE ${APP_SCHEMA}.REPARTIDOR_LIQUIDACION_OPS (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL,
      SUBEMPRESALIQUIDACION CHAR(3),
      EJERCICIOLIQUIDACION NUMERIC(4),
      SERIELIQUIDACION CHAR(1),
      TERMINALLIQUIDACION NUMERIC(3),
      NUMEROLIQUIDACION NUMERIC(10),
      CODIGOVENDEDOR CHAR(10),
      IMPORTEEFECTIVO NUMERIC(10,2),
      IMPORTECHEQUES NUMERIC(10,2),
      IMPORTETARJETA NUMERIC(10,2),
      IMPORTEPOSTDATADOS NUMERIC(10,2),
      IMPORTESALDOACTUAL NUMERIC(10,2),
      IMPORTEGASTOS NUMERIC(10,2),
      IMPORTETOTALAINGRESAR NUMERIC(10,2),
      IMPORTEINGRESOENBANCO NUMERIC(10,2),
      IMPORTEEFECTIVO2 NUMERIC(10,2),
      IMPORTEENTREGADO2 NUMERIC(10,2),
      CODIGOUSUARIO CHAR(10),
      REVISADOSN CHAR(1),
      STATUS VARCHAR(20) DEFAULT 'PENDING',
      OPERADOR VARCHAR(20),
      CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
    )`,

  REPARTIDOR_COMMISSION_TIERS: `
    CREATE TABLE ${APP_SCHEMA}.REPARTIDOR_COMMISSION_TIERS (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      THRESHOLD_PCT DECIMAL(5,2) NOT NULL,
      COMMISSION_PCT DECIMAL(5,2) NOT NULL,
      SORT_ORDER INTEGER DEFAULT 0,
      ACTIVE_SN CHAR(1) DEFAULT 'S',
      CREATED_BY VARCHAR(20),
      UPDATED_BY VARCHAR(20),
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

  CLIENT_SIGNERS: `
    CREATE TABLE ${APP_SCHEMA}.CLIENT_SIGNERS (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      CODIGOCLIENTE VARCHAR(20) NOT NULL,
      DNI VARCHAR(20) NOT NULL,
      NOMBRE VARCHAR(100) NOT NULL,
      LAST_USED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,

  CUENTAS_LIQUIDACION: `
    CREATE TABLE ${APP_SCHEMA}.CUENTAS_LIQUIDACION (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      CODIGO_REPARTIDOR VARCHAR(10) NOT NULL,
      EJERCICIO NUMERIC(4) NOT NULL,
      SALDO_ACUMULADO DECIMAL(11,2) DEFAULT 0,
      ULTIMO_CIERRE DATE,
      ULTIMO_TOKEN VARCHAR(128),
      NUM_CIERRES INTEGER DEFAULT 0,
      TOTAL_COBRADO_ANO DECIMAL(13,2) DEFAULT 0,
      TOTAL_INGRESADO_ANO DECIMAL(13,2) DEFAULT 0,
      OBSERVACIONES VARCHAR(500),
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT UQ_CL_REP_EJER UNIQUE (CODIGO_REPARTIDOR, EJERCICIO)
    )`,

  REPARTIDOR_COBROS_AUDIT: `
    CREATE TABLE ${APP_SCHEMA}.REPARTIDOR_COBROS_AUDIT (
      ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      EVENT_TYPE VARCHAR(40) NOT NULL,
      OPERADOR VARCHAR(40),
      CODIGO_REPARTIDOR VARCHAR(10),
      IDEMPOTENCY_TOKEN_PREVIEW VARCHAR(40),
      DOCUMENTO_PREVIEW VARCHAR(120),
      PAYLOAD_PREVIEW VARCHAR(500),
      ERROR_CODE VARCHAR(40),
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
};

// ─── INDEXES ────────────────────────────────────────────────────────

const INDEXES = [
  `CREATE INDEX ${APP_SCHEMA}.IDX_PCAB_CLI ON ${APP_SCHEMA}.PEDIDOS_CAB (CODIGOCLIENTE)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_PCAB_VND ON ${APP_SCHEMA}.PEDIDOS_CAB (CODIGOVENDEDOR)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_PCAB_ESTADO ON ${APP_SCHEMA}.PEDIDOS_CAB (ESTADO)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_PLIN_PID ON ${APP_SCHEMA}.PEDIDOS_LIN (PEDIDO_ID)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_PLIN_ART ON ${APP_SCHEMA}.PEDIDOS_LIN (CODIGOARTICULO)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_PSR_PID ON ${APP_SCHEMA}.PEDIDOS_STOCK_RESERVE (PEDIDO_ID)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_COBROS_CLI ON ${APP_SCHEMA}.COBROS (CODIGO_CLIENTE)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_COBROS_IDEM ON ${APP_SCHEMA}.COBROS (IDEMPOTENCY_TOKEN)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_DS_ITEM ON ${APP_SCHEMA}.DELIVERY_STATUS (ITEM_ID)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_DS_REP ON ${APP_SCHEMA}.DELIVERY_STATUS (REPARTIDOR_ID)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_CN_CLI ON ${APP_SCHEMA}.CLIENT_NOTES (CLIENT_CODE)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_KPIA_TYPE ON ${APP_SCHEMA}.KPI_ALERTS (ALERT_TYPE)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_RFB_VND ON ${APP_SCHEMA}.REPARTIDOR_FINANCIAL_BALANCES (CODIGOVENDEDOR)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_RLO_TOKEN ON ${APP_SCHEMA}.REPARTIDOR_LIQUIDACION_OPS (IDEMPOTENCY_TOKEN)`,
  // Bolsa siempre en JAVIER (ver DDL arriba).
  `CREATE INDEX JAVIER.IDX_BOLSA_VND ON JAVIER.BOLSA_COMERCIAL (CODIGOVENDEDOR, EJERCICIO)`,
  `CREATE INDEX JAVIER.IDX_MOV_BOLSA ON JAVIER.MOVIMIENTOS_BOLSA (BOLSA_ID)`,
  `CREATE INDEX JAVIER.IDX_MOV_PED ON JAVIER.MOVIMIENTOS_BOLSA (PEDIDO_ID)`,
  `CREATE UNIQUE INDEX JAVIER.UQ_MOV_BOLSA_IDEMP ON JAVIER.MOVIMIENTOS_BOLSA (IDEMPOTENCY_KEY)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_CS_CLI ON ${APP_SCHEMA}.CLIENT_SIGNERS (CODIGOCLIENTE)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_CL_REP ON ${APP_SCHEMA}.CUENTAS_LIQUIDACION (CODIGO_REPARTIDOR)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_RCA_TOKEN ON ${APP_SCHEMA}.REPARTIDOR_COBROS_AUDIT (IDEMPOTENCY_TOKEN_PREVIEW)`,
  `CREATE INDEX ${APP_SCHEMA}.IDX_RCA_REP ON ${APP_SCHEMA}.REPARTIDOR_COBROS_AUDIT (CODIGO_REPARTIDOR, CREATED_AT)`,
];

// ─── CORE LOGIC ─────────────────────────────────────────────────────

async function tableExists(queryFn, schema, tableName) {
  try {
    const safeSchema = db2Schema(schema, 'tableExists schema');
    const safeTable = db2Identifier(tableName, 'tableExists table');
    const rows = await queryFn(
      'SELECT TABLE_NAME FROM QSYS2.SYSTABLES ' +
      'WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? FETCH FIRST 1 ROW ONLY',
      [safeSchema, safeTable]
    );
    return Array.isArray(rows) && rows.length > 0;
  } catch (_) {
    return false;
  }
}

async function createIfNotExists(queryFn, tableName, ddl) {
  const schema = schemaForTable(tableName);
  if (await tableExists(queryFn, schema, tableName)) {
    return { table: `${schema}.${tableName}`, status: 'EXISTS' };
  }
  try {
    await queryFn(ddl);
    logger.info(`[INIT-TABLES] Created ${schema}.${tableName}`);
    return { table: `${schema}.${tableName}`, status: 'CREATED' };
  } catch (err) {
    const state = (err.odbcErrors || []).map(e => e.state).join(',');
    if (state.includes('42S01')) {
      return { table: `${schema}.${tableName}`, status: 'EXISTS' };
    }
    logger.error(`[INIT-TABLES] Failed ${schema}.${tableName}: ${err.message}`);
    return { table: `${schema}.${tableName}`, status: 'ERROR', error: err.message };
  }
}

async function ensureColumnInSchema(queryFn, schema, table, column, definition) {
  try {
    const check = await queryFn(
      `SELECT COLUMN_NAME FROM QSYS2.SYSCOLUMNS2
       WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?
       FETCH FIRST 1 ROW ONLY`,
      [schema, table, column]
    );
    if (check && check.length > 0) return false;
  } catch (_) { /* try ALTER anyway */ }
  try {
    await queryFn(`ALTER TABLE ${schema}.${table} ADD COLUMN ${column} ${definition}`);
    logger.info(`[INIT-TABLES] Added column ${column} to ${schema}.${table}`);
    return true;
  } catch (_) {
    return false;
  }
}

async function ensureColumn(queryFn, table, column, definition) {
  return ensureColumnInSchema(queryFn, APP_SCHEMA, table, column, definition);
}

async function migrateBolsaIfNeeded(queryFn) {
  const bolsaExists = await tableExists(queryFn, BOLSA_SCHEMA, 'BOLSA_COMERCIAL');
  if (bolsaExists) {
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'BOLSA_COMERCIAL', 'LIMITE_IMPORTE', 'DECIMAL(11,2) DEFAULT 0');
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'BOLSA_COMERCIAL', 'CONSUMIDO', 'DECIMAL(11,2) DEFAULT 0');
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'BOLSA_COMERCIAL', 'ACUMULADO', 'DECIMAL(11,2) DEFAULT 0');
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'BOLSA_COMERCIAL', 'UPDATED_AT', 'TIMESTAMP DEFAULT CURRENT TIMESTAMP');
  }

  const movementsExists = await tableExists(queryFn, BOLSA_SCHEMA, 'MOVIMIENTOS_BOLSA');
  if (movementsExists) {
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'MOVIMIENTOS_BOLSA', 'CODIGOVENDEDOR', 'VARCHAR(10)');
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'MOVIMIENTOS_BOLSA', 'LINEA_ID', 'INTEGER');
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'MOVIMIENTOS_BOLSA', 'PRECIO_MINIMO_CONGELADO', 'DECIMAL(9,4)');
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'MOVIMIENTOS_BOLSA', 'PRECIO_VENTA', 'DECIMAL(9,4)');
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'MOVIMIENTOS_BOLSA', 'CANTIDAD', 'DECIMAL(12,5)');
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'MOVIMIENTOS_BOLSA', 'UNIDAD_MEDIDA', 'VARCHAR(12)');
    await ensureColumnInSchema(queryFn, BOLSA_SCHEMA, 'MOVIMIENTOS_BOLSA', 'IDEMPOTENCY_KEY', 'VARCHAR(128)');
  }

  return 'OK';
}

async function migrateCobrosIfNeeded(queryFn) {
  // Main COBROS table (commercials)
  const exists = await tableExists(queryFn, APP_SCHEMA, 'COBROS');
  if (exists) {
    await ensureColumn(queryFn, 'COBROS', 'IDEMPOTENCY_TOKEN', 'VARCHAR(128)');
    await ensureColumn(queryFn, 'COBROS', 'CREATED_AT', 'TIMESTAMP DEFAULT CURRENT TIMESTAMP');
  }

  // REPARTIDOR_COBROS table (professional bridge table)
  const existsRep = await tableExists(queryFn, APP_SCHEMA, 'REPARTIDOR_COBROS');
  if (existsRep) {
    await ensureColumn(queryFn, 'REPARTIDOR_COBROS', 'IDEMPOTENCY_TOKEN', 'VARCHAR(128)');
    await ensureColumn(queryFn, 'REPARTIDOR_COBROS', 'CREATED_AT', 'TIMESTAMP DEFAULT CURRENT TIMESTAMP');
    await ensureColumn(queryFn, 'REPARTIDOR_COBROS', 'LIQUIDADO_SN', "CHAR(1) DEFAULT 'N'");
    await ensureColumn(queryFn, 'REPARTIDOR_COBROS', 'LIQUIDACION_TOKEN', 'VARCHAR(128)');
    await ensureColumn(queryFn, 'REPARTIDOR_COBROS', 'NUMEROLIQUIDACION', 'NUMERIC(10)');
  }

  return 'OK';
}

async function initAllTables(queryFn) {
  const results = [];
  logger.info(`[INIT-TABLES] Initializing app tables in ${APP_SCHEMA}`);

  // Migrate COBROS first (preserve data)
  const cobrosStatus = await migrateCobrosIfNeeded(queryFn);
  results.push({ table: `${APP_SCHEMA}.COBROS`, migration: cobrosStatus });
  const bolsaStatus = await migrateBolsaIfNeeded(queryFn);
  results.push({ table: `${BOLSA_SCHEMA}.BOLSA_*`, migration: bolsaStatus });

  // Create all tables. Keep serial order for IBM i DDL safety; this helper runs only during migrations/startup.
  const tableResults = await Object.entries(TABLE_DDL).reduce(
    function chain(previous, entry) {
      return previous.then(async function appendCreatedTable(acc) {
        const tableName = entry[0];
        const ddl = entry[1];
        acc.push(await createIfNotExists(queryFn, tableName, ddl));
        return acc;
      });
    },
    Promise.resolve([])
  );
  results.push(...tableResults);

  // Ensure backward-compat columns on existing tables
  await ensureColumn(queryFn, 'PEDIDOS_CAB', 'DESCUENTO_GLOBAL', 'DECIMAL(5,2) DEFAULT 0');
  await ensureColumn(queryFn, 'PEDIDOS_CAB', 'ORIGEN', "CHAR(1) DEFAULT 'A'");
  await ensureColumn(queryFn, 'PEDIDOS_LIN', 'DESCUENTO_LINEA', 'DECIMAL(5,2) DEFAULT 0');
  await ensureColumn(queryFn, 'PEDIDOS_LIN', 'UNIDADESFRACCION', 'NUMERIC(10,5) DEFAULT 0');

  // Create indexes (silent fail if exist)
  for (const idx of INDEXES) {
    try { await queryFn(idx); } catch (_) { logger.debug(`[INIT-TABLES] Index ${idx.substring(0, 60)}... already exists`); }
  }

  const created = results.filter(r => r.status === 'CREATED').length;
  const existing = results.filter(r => r.status === 'EXISTS').length;
  const errors = results.filter(r => r.status === 'ERROR').length;
  logger.info(`[INIT-TABLES] Done: ${created} created, ${existing} existing, ${errors} errors`);

  return results;
}

module.exports = { initAllTables, tableExists, ensureColumn };
