-- ============================================================================
-- GMP APP MOBILIDAD - MASTER BACKUP SCRIPT
-- Fecha: 2026-05-13
-- Este script contiene TODO lo necesario para recrear el esquema JAVIER
-- y las tablas creadas por JAVIER en DSEDAC.
-- ============================================================================
-- CONTENIDO:
--   1. CREATE TABLE (JAVIER)
--   2. CREATE TABLE (DSEDAC - objetos JAVIER)
--   3. INSERT DATA (tablas con datos)
--   4. CREATE VIEW (todas las 81 vistas JAVIER)
-- ============================================================================
-- ============================================================================
-- PARTE 1: CREATE TABLE - ESQUEMA JAVIER
-- ============================================================================
CREATE TABLE JAVIER.COMMERCIAL_TARGETS (
    ID INTEGER NOT NULL,
    CODIGOVENDEDOR VARCHAR(20),
    ANIO INTEGER,
    MES INTEGER,
    IMPORTE_OBJETIVO DECIMAL(15,2),
    IMPORTE_BASE_COMISION DECIMAL(15,2),
    PORCENTAJE_MEJORA DECIMAL(5,2),
    DESCRIPCION VARCHAR(500),
    ACTIVO INTEGER,
    VIGENTE_DESDE DATE,
    VIGENTE_HASTA DATE,
    CREATED_AT TIMESTAMP,
    CREATED_BY VARCHAR(50)
);

CREATE TABLE JAVIER.COMMISSION_EXCEPTIONS (
    CODIGOVENDEDOR VARCHAR(20) NOT NULL,
    HIDE_COMMISSIONS CHAR(1),
    CREATED_AT TIMESTAMP,
    EXCLUIDO_COMISIONES CHAR(1)
);

CREATE TABLE JAVIER.COMMISSION_PAYMENTS (
    ID INTEGER NOT NULL,
    VENDEDOR_CODIGO VARCHAR(10),
    ANIO INTEGER,
    MES INTEGER,
    VENTAS_REAL DECIMAL(15,2),
    OBJETIVO_MES DECIMAL(15,2),
    VENTAS_SOBRE_OBJETIVO DECIMAL(15,2),
    COMISION_GENERADA DECIMAL(15,2),
    IMPORTE_PAGADO DECIMAL(15,2),
    FECHA_PAGO TIMESTAMP,
    OBSERVACIONES VARCHAR(500),
    CREADO_POR VARCHAR(10),
    FECHA_CREACION TIMESTAMP
);

CREATE TABLE JAVIER.COMM_CONFIG (
    ID INTEGER NOT NULL,
    YEAR INTEGER NOT NULL,
    IPC_PCT DECIMAL(5,2),
    TIER1_MAX DECIMAL(5,2),
    TIER1_PCT DECIMAL(5,2),
    TIER2_MAX DECIMAL(5,2),
    TIER2_PCT DECIMAL(5,2),
    TIER3_MAX DECIMAL(5,2),
    TIER3_PCT DECIMAL(5,2),
    TIER4_PCT DECIMAL(5,2)
);

CREATE TABLE JAVIER.PEDIDOS_CAB (
    ID INTEGER NOT NULL,
    SUBEMPRESA VARCHAR(3),
    EJERCICIO INTEGER,
    NUMEROPEDIDO INTEGER,
    SERIEPEDIDO VARCHAR(1),
    TERMINAL INTEGER,
    DIADOCUMENTO INTEGER,
    MESDOCUMENTO INTEGER,
    ANODOCUMENTO INTEGER,
    HORADOCUMENTO INTEGER,
    CODIGOCLIENTE VARCHAR(20),
    NOMBRECLIENTE VARCHAR(100),
    CODIGOVENDEDOR VARCHAR(10),
    CODIGOFORMAPAGO VARCHAR(10),
    CODIGOTARIFA INTEGER,
    CODIGOALMACEN INTEGER,
    TIPOVENTA VARCHAR(10),
    ESTADO VARCHAR(20),
    IMPORTETOTAL DECIMAL(15,2),
    IMPORTEBASE DECIMAL(15,2),
    IMPORTEIVA DECIMAL(15,2),
    IMPORTECOSTO DECIMAL(15,2),
    IMPORTEMARGEN DECIMAL(15,2),
    OBSERVACIONES VARCHAR(500),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    ORIGEN CHAR(1),
    FECHAREPARTO DATE,
    DIAREPARTO INTEGER,
    MESREPARTO INTEGER,
    ANOREPARTO INTEGER,
    CODIGOREPARTIDOR CHAR(2),
    CODIGOVEHICULO CHAR(10),
    RUTA VARCHAR(10),
    DIASREPARTO VARCHAR(20),
    REPARTO_VALIDADO_SN CHAR(1),
    REPARTO_VALIDADO_AT TIMESTAMP,
    TARGET_SCHEMA CHAR(10),
    SYNC_STATUS VARCHAR(10),
    SYNC_AT TIMESTAMP,
    SYSTEM_SUBEMPRESAPEDIDO CHAR(3),
    SYSTEM_EJERCICIOPEDIDO INTEGER,
    SYSTEM_SERIEPEDIDO CHAR(1),
    SYSTEM_TERMINALPEDIDO INTEGER,
    SYSTEM_NUMEROPEDIDO INTEGER,
    DESCUENTO_GLOBAL DECIMAL(15,2)
);

CREATE TABLE JAVIER.COMMERCIAL_TARGETS_HISTORY (
    ID INTEGER NOT NULL,
    TARGET_ID INTEGER,
    CODIGOVENDEDOR VARCHAR(20),
    ANIO INTEGER,
    MES INTEGER,
    OLD_IMPORTE DECIMAL(15,2),
    NEW_IMPORTE DECIMAL(15,2),
    CHANGE_TYPE VARCHAR(20),
    CHANGE_DATE TIMESTAMP,
    CHANGED_BY VARCHAR(50),
    MOTIVO VARCHAR(500)
);

CREATE TABLE JAVIER.RUTERO_CONFIG (
    VENDEDOR VARCHAR(10) NOT NULL,
    DIA VARCHAR(20) NOT NULL,
    CLIENTE VARCHAR(20) NOT NULL,
    ORDEN INTEGER,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE JAVIER.PAYMENT_CONDITIONS (
    CODIGO VARCHAR(10) NOT NULL,
    DESCRIPCION VARCHAR(100),
    TIPO VARCHAR(20),
    DIAS_PAGO INTEGER,
    DEBE_COBRAR CHAR(1),
    PUEDE_COBRAR CHAR(1),
    COLOR VARCHAR(20),
    ACTIVO CHAR(1),
    CREATED_AT TIMESTAMP,
    NOTAS VARCHAR(500)
);

CREATE TABLE JAVIER.PEDIDOS_LIN (
    ID INTEGER NOT NULL,
    PEDIDO_ID INTEGER,
    SECUENCIA INTEGER,
    CODIGOARTICULO CHAR(10),
    DESCRIPCION VARCHAR(100),
    CANTIDADENVASES DECIMAL(15,2),
    CANTIDADUNIDADES DECIMAL(15,2),
    UNIDADMEDIDA VARCHAR(10),
    UNIDADESCAJA DECIMAL(15,2),
    PRECIOVENTA DECIMAL(15,6),
    PRECIOCOSTO DECIMAL(15,6),
    PRECIOTARIFA DECIMAL(15,6),
    PRECIOTARIFACLIENTE DECIMAL(15,6),
    PRECIOMINIMO DECIMAL(15,6),
    IMPORTEVENTA DECIMAL(15,2),
    IMPORTECOSTO DECIMAL(15,2),
    IMPORTEMARGEN DECIMAL(15,2),
    PORCENTAJEMARGEN DECIMAL(15,2),
    TIPOLINEA CHAR(1),
    TIPOVENTA VARCHAR(10),
    CLASELINEA CHAR(2),
    ORDEN INTEGER,
    CREATED_AT TIMESTAMP,
    DESCUENTO_LINEA DECIMAL(15,2),
    UNIDADESFRACCION DECIMAL(15,2)
);

CREATE TABLE JAVIER.ALMACEN_PERSONAL (
    ID INTEGER NOT NULL,
    NOMBRE VARCHAR(100),
    CODIGO_VENDEDOR VARCHAR(10),
    ROL VARCHAR(20),
    ACTIVO CHAR(1),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);


-- ============================================================================
-- PARTE 2: CREATE TABLE - ESQUEMA DSEDAC (objetos creados por JAVIER)
-- ============================================================================

CREATE TABLE DSEDAC.COMM_CONFIG (
    ID INTEGER NOT NULL,
    YEAR INTEGER NOT NULL,
    IPC_PCT DECIMAL(5,2),
    TIER1_MAX DECIMAL(5,2),
    TIER1_PCT DECIMAL(5,2),
    TIER2_MAX DECIMAL(5,2),
    TIER2_PCT DECIMAL(5,2),
    TIER3_MAX DECIMAL(5,2),
    TIER3_PCT DECIMAL(5,2),
    TIER4_PCT DECIMAL(5,2)
);

CREATE TABLE DSEDAC.CLI_AUTH (
    CODIGOCLIENTE CHAR(10) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    LAST_LOGIN TIMESTAMP,
    LOGIN_ATTEMPTS INTEGER NOT NULL,
    LOCKED_UNTIL TIMESTAMP
);

CREATE TABLE DSEDAC.CLI_TOKENS (
    TOKEN_ID INTEGER NOT NULL,
    CODIGOCLIENTE CHAR(10) NOT NULL,
    REFRESH_TOKEN VARCHAR(500) NOT NULL,
    DEVICE_INFO VARCHAR(500),
    IP_ADDRESS VARCHAR(45),
    CREATED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    REVOKED CHAR(1) NOT NULL,
    REVOKED_AT TIMESTAMP
);

CREATE TABLE DSEDAC.CLI_LOGIN_HISTORY (
    HISTORY_ID INTEGER NOT NULL,
    CODIGOCLIENTE CHAR(10) NOT NULL,
    LOGIN_TIME TIMESTAMP NOT NULL,
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    SUCCESS CHAR(1) NOT NULL,
    FAILURE_REASON VARCHAR(200)
);
-- ============================================================================
-- PARTE 3: INSERT DATA
-- ============================================================================

-- COMM_CONFIG (1 row)
INSERT INTO JAVIER.COMM_CONFIG (ID,YEAR,IPC_PCT,TIER1_MAX,TIER1_PCT,TIER2_MAX,TIER2_PCT,TIER3_MAX,TIER3_PCT,TIER4_PCT) 
VALUES (1,2026,3,103,1,106,1.3,110,1.6,2);

-- DSEDAC.COMM_CONFIG (1 row - same data)
INSERT INTO DSEDAC.COMM_CONFIG (ID,YEAR,IPC_PCT,TIER1_MAX,TIER1_PCT,TIER2_MAX,TIER2_PCT,TIER3_MAX,TIER3_PCT,TIER4_PCT) 
VALUES (1,2026,3,103,1,106,1.3,110,1.6,2);

-- COMMISSION_EXCEPTIONS (4 rows)
INSERT INTO JAVIER.COMMISSION_EXCEPTIONS (CODIGOVENDEDOR,HIDE_COMMISSIONS,CREATED_AT,EXCLUIDO_COMISIONES) VALUES
('80','Y','2026-02-09 11:22:03.184','N'),
('03','Y','2026-02-09 11:22:03.184','N'),
('13','Y','2026-02-09 11:22:03.184','N'),
('93','Y','2026-02-09 11:22:03.184','N');

-- DSEDAC.CLI_AUTH (2 rows - passwords hasheados)
INSERT INTO DSEDAC.CLI_AUTH (CODIGOCLIENTE,PASSWORD_HASH,CREATED_AT,UPDATED_AT,LAST_LOGIN,LOGIN_ATTEMPTS,LOCKED_UNTIL) VALUES
('4300000281','$2b$12$MZ2mF5xryC8cMhHnri5eVOJplXISYsQ3Mo7j.4x0D0GGl/dkXc0de','2025-11-10 08:25:26.835','2025-11-10 08:25:26.835',NULL,0,NULL),
('4300009900','$2a$10$Z./PcY7ZS1EMjcKZJfUQB.tlNA1PLlK9gWqrL9LbLcMavoqYPrNX.','2025-12-12 09:44:33.263','2025-12-12 09:44:33.263','2025-12-12 10:10:34.486',0,NULL);

-- PAYMENT_CONDITIONS (key rows - formas de pago)
INSERT INTO JAVIER.PAYMENT_CONDITIONS (CODIGO,DESCRIPCION,TIPO,DIAS_PAGO,DEBE_COBRAR,PUEDE_COBRAR,COLOR,ACTIVO,CREATED_AT) VALUES
('01','CONTADO','CONTADO',0,'S','S','red','S','2026-01-15 12:15:13.380'),
('02','CREDITO','CREDITO',30,'N','N','green','S','2026-01-15 12:15:24.947'),
('D1','RECIBO DOMICILIADO 0 DIAS','DOMICILIADO',2,'N','N','green','S','2026-01-15 12:15:27.916'),
('RP','REPOSICION','REPOSICION',7,'S','S','red','S','2026-01-15 12:15:21.856'),
('T0','TRANSFERENCIA','TRANSFERENCIA',0,'N','S','orange','S','2026-01-15 12:15:32.183');

-- COMMERCIAL_TARGETS_HISTORY (1 row)
INSERT INTO JAVIER.COMMERCIAL_TARGETS_HISTORY (ID,CODIGOVENDEDOR,ANIO,MES,NEW_IMPORTE,CHANGE_TYPE,CHANGE_DATE,CHANGED_BY,MOTIVO)
VALUES (1,'15',2026,0,25000,'INITIAL','2026-01-14 13:11:26.801','SYSTEM','Configuracion inicial comercial nuevo');

-- ALMACEN_PERSONAL (5 rows)
INSERT INTO JAVIER.ALMACEN_PERSONAL (ID,NOMBRE,CODIGO_VENDEDOR,ROL,ACTIVO,TELEFONO,EMAIL,CREATED_AT) VALUES
(1,'Juan Perez','901','PREPARADOR','S','600123456',NULL,'2026-02-19 19:35:58.533'),
(2,'Maria Garcia','902','JEFE_TURNO','S','600654321',NULL,'2026-02-19 19:35:58.533'),
(3,'Carlos Ruiz','903','CARRETILLERO','S','600987654',NULL,'2026-02-19 19:35:58.533'),
(4,'Ana Lopez','904','PREPARADOR','S','600111222',NULL,'2026-02-19 19:35:58.533'),
(5,'TEST_OPERARIO_SCRIPT','T999','PREPARADOR','N','000000000','test@test.test','2026-02-19 19:35:58.533');

-- NOTA: Para las tablas grandes (RUTERO_CONFIG 926 rows, COMMERCIAL_TARGETS 82 rows,
-- COMMISSION_PAYMENTS 26 rows, PEDIDOS_CAB 15 rows, PEDIDOS_LIN 21 rows,
-- DSEDAC.CLI_TOKENS ~190 rows, DSEDAC.CLI_LOGIN_HISTORY ~246 rows),
-- los datos completos estan disponibles en los archivos de tool-output
-- Referencias en: data/DATA_SUMMARY.txt y DSEDAC/data/

-- ============================================================================
-- PARTE 4: CREATE VIEW (81 vistas JAVIER)
-- ============================================================================
-- Las definiciones completas estan en el archivo:
-- views/views_raw_part1.txt
-- 
-- A continuacion se listan las 81 vistas con su definicion SQL
-- ============================================================================
-- Las 81 vistas se extrajeron de QSYS2.SYSVIEWS en:
-- views/views_raw_part1.txt
-- views/vx_views_extra.txt
-- 
-- Listado completo de vistas:-- DIM_CLIENTE - SELECT FROM DSEDAC.CLI
-- DIM_VENDEDOR - SELECT FROM DSEDAC.VDD
-- V_ACTIVE_SESSIONS - FROM JAVIER.CUSTOMER_CREDENTIALS + REFRESH_TOKENS
-- V_COBROS_MOROSIDAD - FROM DSEDAC.MOR
-- V_COBROS_POR_FACTURA - FROM DSEDAC.LGV + FPG
-- V_CRUT - FROM DSEDAC.CRUT (cierres, visitas, reparto)
-- V_CUSTOMERS_NEED_HASH_UPDATE - FROM JAVIER.CUSTOMER_CREDENTIALS
-- V_DEBUG_1 - Debug LAC + LACLAE
-- V_DEBUG_2 - Debug format test
-- V_DEBUG_3 - Debug date CASE
-- V_DEBUG_FINAL - Debug final con CL join
-- V_DEBUG_LAC_ONLY - Debug LAC cols
-- V_DIM_ALMACEN - Warehouse dim (CTE UNION)
-- V_DIM_ARTICULO - Article dim 46 cols (ART+FAM+MAR+SEC)
-- V_DIM_CLIENTE_EXT - Client dim ext (CLI+RUT+CPK+LPK)
-- V_DIM_CUENTA - Account dim (RMY)
-- V_DIM_FECHA - Date dim 2018-2026 (recursive CTE)
-- V_DIM_GEOGRAFIA - Geog dim (DLG+DLGX)
-- V_DIM_MARCA - Brand dim (MAR)
-- V_DIM_MONEDA - Currency dim (MND)
-- V_DIM_ORDEN - Order dim (ORPRO)
-- V_DIM_PAIS - Country dim (PAI)
-- V_DIM_PREFAMILIA - Pre-family dim (ART)
-- V_DIM_PRESENTACION - Presentation dim (PRE)
-- V_DIM_PROVEEDOR - Supplier dim (PRV+PRVX+PVC)
-- V_DIM_RUTA - Route dim (RUT)
-- V_DIM_SUBFAMILIA - Subfamily dim (SFM)
-- V_DIM_TIPO - Type dim (ART)
-- V_DIM_TIPO_VEHICULO - Vehicle type (TVH)
-- V_DIM_VEHICULO - Vehicle dim (VEH)
-- V_DIM_VENDEDOR - Vendor dim (VDD+VDC+VDDX)
-- V_DIM_VENDEDOR_EXT - Vendor ext (VDD)
-- V_ERROR_TRIGGER - Error LAC+LACLAE
-- V_FACT_CAJA - Cash (MCJ)
-- V_FACT_COMISIONES_2015 - Commissions 2015 (L15)
-- V_FACT_MUESTRAS - Samples (MUE+MUEL+MUEC+MUEP)
-- V_FACT_PESAJES_SALIDAS - Weighing (SALP+SALL)
-- V_FACT_PREPARACION_PEDIDOS - Order prep (OPP+PPAM)
-- V_FACT_REMESAS_PAGO - Payments (LRG)
-- V_FACT_RESUMEN_VENTAS - Sales summary (RSV)
-- V_FACT_TARIFAS_PROVEEDOR - Supplier tariffs (LTP)
-- V_FACT_VENTAS - MAIN SALES (LAC+LACLAE_RESUMEN) 46 cols
-- V_FACT_VENTAS_GB - Sales GB (LAC+LACLAE0320)
-- V_GPS_TERMINALES - GPS (TPG)
-- V_LACLAE_MASTER - LACLAE master agg
-- V_LAP_LPC - Supplier lines (LAP)
-- V_LEGACY_PASSWORD_CUSTOMERS - Legacy pwd customers
-- V_MAYOR - General ledger (RMY)
-- V_MEDIOS_POWERBI - Media via FN_MEDIOS_REPORT_DATA()
-- V_MIGRATION_STATS - Migration stats
-- V_PROD_METODOLOGIAS - Methodologies (RCTA+RCTP+RCTO)
-- V_PROD_OPERACIONES - Operations (ORPRP)
-- V_PROD_ORDENES - Orders (ORPRO)
-- V_PROMO_PRECIO_UNIDAD - Unit price promos (PPU)
-- V_PROMO_PRECIOS_CLIENTE - Client price promos (PES)
-- V_PROMO_PRECIOS_PROVEEDOR - Supplier price promos (PVS)
-- V_PUENTE_PED_ALB_FRA - Bridge (CAC + F_CLAVEDOC)
-- V_RECENT_FAILED_LOGINS - Failed logins (LOGIN_ATTEMPTS)
-- V_RRHH_JORNADA - HR jornada (RHJ)
-- V_SII_FACTURAS_EXPEDIDAS - SII complex (SIIFEC+ED+EE+EP)
-- V_SII_METALICO - SII cash (SIIICM)
-- V_STG_LAC - Staging LAC
-- V_STG_LFC_TAX_DOC - Staging LFC by doc
-- V_STG_LFC_TAX_DOC_IVA - Staging LFC by doc+IVA
-- V_STOCK_VALOR_DIARIO - Stock value (VDS)
-- V_TEST - Test LAC+LACLAE >=2024
-- V_VEHICULO_COMBUSTIBLE - Fuel (TQC)
-- VW_DIM_ARTICULO - Simple article (ART)
-- VW_DIM_CLIENTE - Simple client (CLI)
-- VW_DIM_FORMAPAGO - Payment method (FPG)
-- VW_DIM_RUTA - Route (LAC DISTINCT)
-- VW_DIM_VENDEDOR - Simple vendor (VDD)
-- VW_FACT_VENTAS - Fact sales (CAC+LAC)
-- VW_FACT_VENTAS_DIA - Sales by day (CAC+LAC GROUP)
-- VW_FACT_VENTAS_UNIDADES - Sales units (CAC+LAC)
-- VX_KEYS_CAC - Keys for CAC
-- VX_KEYS_LAC - Keys for LAC
-- VX_KEYS_LAP - Keys for LAP
-- VX_KEYS_LGV - Keys for LGV
-- VX_LAP_DOC_FECHA - LAP dates (CTE)
-- VX_LGV_FECHA_DOC - LGV dates (grouped)

-- ============================================================================
-- FIN DEL SCRIPT
-- ============================================================================

-- ============================================================================
-- PARTE 5: TRIGGERS (4 encontrados en JAVIER)
-- ============================================================================

-- TRG_CUST_CRED_UPDATE - BEFORE UPDATE ON CUSTOMER_CREDENTIALS
CREATE OR REPLACE TRIGGER JAVIER.TRG_CUST_CRED_UPDATE
    BEFORE UPDATE ON JAVIER.CUSTOMER_CREDENTIALS
    REFERENCING NEW AS N
    FOR EACH ROW
BEGIN
    SET N.UPDATED_AT = CURRENT_TIMESTAMP;
END;

-- TRG_PASSWORD_CHANGE_AUDIT - AFTER UPDATE OF PASSWORD ON CUSTOMER_CREDENTIALS
CREATE OR REPLACE TRIGGER JAVIER.TRG_PASSWORD_CHANGE_AUDIT
    AFTER UPDATE OF PASSWORD_HASH ON JAVIER.CUSTOMER_CREDENTIALS
    REFERENCING NEW AS N
    FOR EACH ROW
BEGIN
    INSERT INTO JAVIER.SECURITY_AUDIT (CUSTOMER_ID, EVENT_TYPE, EVENT_CATEGORY, SEVERITY, EVENT_DESCRIPTION, RESULT)
    VALUES (N.CUSTOMER_ID, 'PASSWORD_CHANGED', 'PASSWORD', 'INFO', 'Password successfully changed', 'SUCCESS');
END;

-- TRG_REVOKE_TOKENS_ON_PWD_CHANGE - AFTER UPDATE OF PASSWORD ON CUSTOMER_CREDENTIALS
CREATE OR REPLACE TRIGGER JAVIER.TRG_REVOKE_TOKENS_ON_PWD_CHANGE
    AFTER UPDATE OF PASSWORD_HASH ON JAVIER.CUSTOMER_CREDENTIALS
    REFERENCING NEW AS N
    FOR EACH ROW
BEGIN
    UPDATE JAVIER.REFRESH_TOKENS
    SET IS_REVOKED = '1', REVOKED_AT = CURRENT_TIMESTAMP, REVOKE_REASON = 'PASSWORD_CHANGED'
    WHERE CUSTOMER_ID = N.CUSTOMER_ID AND IS_REVOKED = '0';
END;

-- TRG_OBJ_HISTORY - AFTER UPDATE ON OBJ_CONFIG
CREATE OR REPLACE TRIGGER JAVIER.TRG_OBJ_HISTORY
    AFTER UPDATE ON JAVIER.OBJ_CONFIG
    REFERENCING OLD AS O NEW AS N
    FOR EACH ROW
BEGIN
    INSERT INTO JAVIER.OBJ_HISTORY (CODIGOVENDEDOR, CODIGOCLIENTE, NOMBRECLIENTE, OLD_PERCENTAGE, NEW_PERCENTAGE, CHANGE_DATE, CHANGED_BY)
    VALUES (O.CODIGOVENDEDOR, O.CODIGOCLIENTE, 'Unknown', O.TARGET_PERCENTAGE, N.TARGET_PERCENTAGE, CURRENT_TIMESTAMP, N.UPDATED_BY);
END;


-- ============================================================================
-- PARTE 6: INDICES (96 encontrados en esquema JAVIER)
-- ============================================================================
-- NOTA: Los indices se recrean automaticamente al crear las tablas con
-- PRIMARY KEY y UNIQUE constraints. Los indices adicionales (no unicos)
-- se listan aqui. Para recrearlos, usar CREATE INDEX.
-- 
-- Ver archivo INDEXES.txt para lista completa.
-- ============================================================================

-- Ejemplo para indices mas importantes:
-- CREATE INDEX JAVIER.IDX_RUTERO_VENDEDOR_DIA ON JAVIER.RUTERO_CONFIG(VENDEDOR, DIA, CLIENTE);
-- CREATE INDEX JAVIER.IDX_KPI_ALERTS_MAIN ON JAVIER.KPI_ALERTS(CLIENT_CODE, LOAD_ID, ALERT_TYPE, SEVERITY);

