-- ============================================
-- SCRIPT SQL: CONFIGURACIÓN DE ROLES Y REPARTIDORES
-- ============================================
-- Ejecutar en IBM i (ACS o similar)

-- 1. CREAR TABLA DE USUARIOS DE LA APP
CREATE TABLE JAVIER.APP_ROLES (
  CODIGO VARCHAR(20) NOT NULL PRIMARY KEY,
  ROL VARCHAR(20) NOT NULL DEFAULT 'COMERCIAL',
  -- Valores: 'JEFE', 'COMERCIAL', 'REPARTIDOR'
  CODIGO_CONDUCTOR VARCHAR(10),
  -- Para repartidores: su código de conductor (viene de CAC.CODIGOCONDUCTOR)
  ACTIVO CHAR(1) DEFAULT 'S',
  FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  NOTAS VARCHAR(200)
);

-- 2. INSERTAR USUARIOS DE EJEMPLO
-- Jefe de Ventas (tu usuario)
INSERT INTO JAVIER.APP_ROLES (CODIGO, ROL, NOTAS) VALUES 
('9900', 'JEFE', 'Usuario administrador principal');

-- Comerciales (ejemplo con códigos de vendedor existentes)
INSERT INTO JAVIER.APP_ROLES (CODIGO, ROL) VALUES 
('80', 'COMERCIAL'),
('95', 'COMERCIAL'),
('02', 'COMERCIAL');

-- Repartidores (usar códigos de CODIGOCONDUCTOR de CAC)
-- Primero, consulta qué conductores existen:
-- SELECT DISTINCT TRIM(CODIGOCONDUCTOR) FROM DSEDAC.CAC 
-- WHERE EJERCICIOALBARAN = 2026 AND CODIGOCONDUCTOR IS NOT NULL

INSERT INTO JAVIER.APP_ROLES (CODIGO, ROL, CODIGO_CONDUCTOR) VALUES 
('REP01', 'REPARTIDOR', 'COND001'),
('REP02', 'REPARTIDOR', 'COND002');

-- 3. CONSULTA PARA VER FORMAS DE PAGO (identificar CTR)
-- SELECT DISTINCT CODIGOFORMAPAGO, COUNT(*) as TOTAL
-- FROM DSEDAC.CAC 
-- WHERE EJERCICIOALBARAN = 2026
-- GROUP BY CODIGOFORMAPAGO
-- ORDER BY TOTAL DESC;

-- El código '01' suele ser CONTADO/CTR (Contra Reembolso)
-- Verificar con: SELECT * FROM DSEDAC.FPA WHERE CODIGOFPA = '01'

-- 4. CONSULTA PARA VER CONDUCTORES ACTUALES
-- SELECT DISTINCT 
--   TRIM(CODIGOCONDUCTOR) as CONDUCTOR,
--   COUNT(*) as ALBARANES
-- FROM DSEDAC.CAC 
-- WHERE EJERCICIOALBARAN = 2026 
--   AND CODIGOCONDUCTOR IS NOT NULL 
--   AND TRIM(CODIGOCONDUCTOR) <> ''
-- GROUP BY CODIGOCONDUCTOR
-- ORDER BY ALBARANES DESC
-- FETCH FIRST 20 ROWS ONLY;

-- 5. ÍNDICE PARA BÚSQUEDAS RÁPIDAS
CREATE INDEX JAVIER.IDX_APP_ROLES_ROL ON JAVIER.APP_ROLES (ROL);
