-- ============================================
-- SCRIPT SQL: TABLAS PARA MÓDULO REPARTIDOR
-- Esquema: JAVIER
-- ============================================
-- Ejecutar en IBM i (ACS o similar)
-- Estas tablas almacenan firmas digitales, observaciones,
-- y el estado de entregas artículo por artículo

-- ============================================
-- 1. TABLA DE ENTREGAS (cabecera)
-- Registra cada entrega completada por un repartidor
-- ============================================
CREATE TABLE JAVIER.REPARTIDOR_ENTREGAS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- Referencia al albarán original
  NUMERO_ALBARAN INTEGER NOT NULL,
  EJERCICIO_ALBARAN INTEGER NOT NULL,
  SERIE_ALBARAN VARCHAR(5) NOT NULL DEFAULT 'A',
  -- Cliente
  CODIGO_CLIENTE VARCHAR(20) NOT NULL,
  NOMBRE_CLIENTE VARCHAR(100),
  -- Repartidor
  CODIGO_REPARTIDOR VARCHAR(20) NOT NULL,
  CODIGO_CONDUCTOR VARCHAR(20),
  -- Estado de la entrega
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  -- Valores: 'PENDIENTE', 'ENTREGADO', 'PARCIAL', 'NO_ENTREGADO', 'RECHAZADO'
  -- Fechas
  FECHA_PREVISTA DATE,
  FECHA_ENTREGA TIMESTAMP,
  FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- Importes
  IMPORTE_TOTAL DECIMAL(15, 2) DEFAULT 0,
  IMPORTE_COBRADO DECIMAL(15, 2) DEFAULT 0,
  -- CTR (Contra Reembolso)
  ES_CTR CHAR(1) DEFAULT 'N',
  CTR_COBRADO CHAR(1) DEFAULT 'N',
  -- Observaciones generales
  OBSERVACIONES VARCHAR(500),
  -- Índices para búsquedas
  CONSTRAINT UK_ENTREGA_ALBARAN UNIQUE (NUMERO_ALBARAN, EJERCICIO_ALBARAN, SERIE_ALBARAN)
);

-- Índices
CREATE INDEX JAVIER.IDX_RE_REPARTIDOR ON JAVIER.REPARTIDOR_ENTREGAS (CODIGO_REPARTIDOR);
CREATE INDEX JAVIER.IDX_RE_CLIENTE ON JAVIER.REPARTIDOR_ENTREGAS (CODIGO_CLIENTE);
CREATE INDEX JAVIER.IDX_RE_FECHA ON JAVIER.REPARTIDOR_ENTREGAS (FECHA_PREVISTA);
CREATE INDEX JAVIER.IDX_RE_ESTADO ON JAVIER.REPARTIDOR_ENTREGAS (ESTADO);

-- ============================================
-- 2. TABLA DE FIRMAS DIGITALES
-- Almacena las firmas capturadas en entregas
-- ============================================
CREATE TABLE JAVIER.REPARTIDOR_FIRMAS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- Referencia a la entrega
  ENTREGA_ID INTEGER NOT NULL,
  -- Datos de la firma
  FIRMA_BASE64 CLOB(1M),
  -- Formato base64 del PNG de la firma
  FIRMA_FORMATO VARCHAR(10) DEFAULT 'PNG',
  -- Metadatos
  FIRMANTE_NOMBRE VARCHAR(100),
  FIRMANTE_DNI VARCHAR(20),
  -- Captura
  FECHA_FIRMA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DISPOSITIVO VARCHAR(100),
  -- GPS si está disponible
  LATITUD DECIMAL(10, 7),
  LONGITUD DECIMAL(10, 7),
  -- Clave foránea
  CONSTRAINT FK_FIRMA_ENTREGA FOREIGN KEY (ENTREGA_ID) 
    REFERENCES JAVIER.REPARTIDOR_ENTREGAS (ID) ON DELETE CASCADE
);

CREATE INDEX JAVIER.IDX_RF_ENTREGA ON JAVIER.REPARTIDOR_FIRMAS (ENTREGA_ID);

-- ============================================
-- 3. TABLA DE ARTÍCULOS POR ENTREGA
-- Registra el estado de cada línea del albarán
-- ============================================
CREATE TABLE JAVIER.REPARTIDOR_ENTREGA_LINEAS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- Referencia a la entrega
  ENTREGA_ID INTEGER NOT NULL,
  -- Referencia al artículo original
  LINEA_ALBARAN INTEGER NOT NULL,
  CODIGO_ARTICULO VARCHAR(20) NOT NULL,
  DESCRIPCION_ARTICULO VARCHAR(200),
  -- Cantidades
  CANTIDAD_PEDIDA DECIMAL(10, 2) NOT NULL,
  CANTIDAD_ENTREGADA DECIMAL(10, 2) DEFAULT 0,
  CANTIDAD_RECHAZADA DECIMAL(10, 2) DEFAULT 0,
  -- Estado de la línea
  ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
  -- Valores: 'PENDIENTE', 'ENTREGADO', 'PARCIAL', 'NO_ENTREGADO'
  -- Observaciones (obligatorias si no entregado)
  OBSERVACIONES VARCHAR(500),
  MOTIVO_NO_ENTREGA VARCHAR(50),
  -- Valores: 'SIN_STOCK', 'RECHAZADO_CLIENTE', 'DAÑADO', 'OTRO'
  -- Fechas
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- Clave foránea
  CONSTRAINT FK_LINEA_ENTREGA FOREIGN KEY (ENTREGA_ID) 
    REFERENCES JAVIER.REPARTIDOR_ENTREGAS (ID) ON DELETE CASCADE
);

CREATE INDEX JAVIER.IDX_REL_ENTREGA ON JAVIER.REPARTIDOR_ENTREGA_LINEAS (ENTREGA_ID);
CREATE INDEX JAVIER.IDX_REL_ARTICULO ON JAVIER.REPARTIDOR_ENTREGA_LINEAS (CODIGO_ARTICULO);

-- ============================================
-- 4. TABLA DE LOG DE COBROS
-- Registra cada cobro realizado por el repartidor
-- ============================================
CREATE TABLE JAVIER.REPARTIDOR_COBROS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- Referencia a la entrega
  ENTREGA_ID INTEGER,
  -- Cliente
  CODIGO_CLIENTE VARCHAR(20) NOT NULL,
  NOMBRE_CLIENTE VARCHAR(100),
  -- Repartidor
  CODIGO_REPARTIDOR VARCHAR(20) NOT NULL,
  -- Documento cobrado
  TIPO_DOCUMENTO VARCHAR(10) NOT NULL,
  -- 'ALBARAN', 'FACTURA'
  NUMERO_DOCUMENTO INTEGER NOT NULL,
  EJERCICIO_DOCUMENTO INTEGER NOT NULL,
  -- Importe
  IMPORTE_COBRADO DECIMAL(15, 2) NOT NULL,
  IMPORTE_PENDIENTE DECIMAL(15, 2) DEFAULT 0,
  -- Forma de pago
  FORMA_PAGO VARCHAR(20),
  -- 'EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'BIZUM'
  -- Fechas
  FECHA_COBRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- Validación
  VALIDADO CHAR(1) DEFAULT 'N',
  FECHA_VALIDACION TIMESTAMP,
  VALIDADO_POR VARCHAR(50),
  -- Notas
  NOTAS VARCHAR(500),
  -- FK opcional
  CONSTRAINT FK_COBRO_ENTREGA FOREIGN KEY (ENTREGA_ID) 
    REFERENCES JAVIER.REPARTIDOR_ENTREGAS (ID) ON DELETE SET NULL
);

CREATE INDEX JAVIER.IDX_RC_REPARTIDOR ON JAVIER.REPARTIDOR_COBROS (CODIGO_REPARTIDOR);
CREATE INDEX JAVIER.IDX_RC_CLIENTE ON JAVIER.REPARTIDOR_COBROS (CODIGO_CLIENTE);
CREATE INDEX JAVIER.IDX_RC_FECHA ON JAVIER.REPARTIDOR_COBROS (FECHA_COBRO);

-- ============================================
-- 5. TABLA DE OBJETIVOS MENSUALES
-- 30% threshold tracking por repartidor
-- ============================================
CREATE TABLE JAVIER.REPARTIDOR_OBJETIVOS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- Repartidor
  CODIGO_REPARTIDOR VARCHAR(20) NOT NULL,
  -- Período
  ANIO INTEGER NOT NULL,
  MES INTEGER NOT NULL,
  -- Importes
  IMPORTE_COBRABLE DECIMAL(15, 2) DEFAULT 0,
  IMPORTE_COBRADO DECIMAL(15, 2) DEFAULT 0,
  -- Cálculo
  PORCENTAJE_COBRADO DECIMAL(5, 2) DEFAULT 0,
  UMBRAL_ALCANZADO CHAR(1) DEFAULT 'N',
  -- 'S' si >= 30%
  -- Comisión
  TIER_COMISION INTEGER DEFAULT 0,
  -- 0=sin comisión, 1-4 según tramos
  COMISION_CALCULADA DECIMAL(15, 2) DEFAULT 0,
  -- Fechas
  FECHA_CALCULO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  -- Unicidad
  CONSTRAINT UK_RO_PERIODO UNIQUE (CODIGO_REPARTIDOR, ANIO, MES)
);

CREATE INDEX JAVIER.IDX_RO_REPARTIDOR ON JAVIER.REPARTIDOR_OBJETIVOS (CODIGO_REPARTIDOR);
CREATE INDEX JAVIER.IDX_RO_PERIODO ON JAVIER.REPARTIDOR_OBJETIVOS (ANIO, MES);

-- ============================================
-- VISTAS ÚTILES
-- ============================================

-- Vista: Entregas del día con resumen
CREATE VIEW JAVIER.V_ENTREGAS_HOY AS
SELECT 
  e.ID,
  e.NUMERO_ALBARAN,
  e.CODIGO_CLIENTE,
  e.NOMBRE_CLIENTE,
  e.CODIGO_REPARTIDOR,
  e.ESTADO,
  e.IMPORTE_TOTAL,
  e.ES_CTR,
  e.CTR_COBRADO,
  (SELECT COUNT(*) FROM JAVIER.REPARTIDOR_ENTREGA_LINEAS l WHERE l.ENTREGA_ID = e.ID) AS TOTAL_LINEAS,
  (SELECT COUNT(*) FROM JAVIER.REPARTIDOR_ENTREGA_LINEAS l WHERE l.ENTREGA_ID = e.ID AND l.ESTADO = 'ENTREGADO') AS LINEAS_ENTREGADAS,
  (SELECT COUNT(*) FROM JAVIER.REPARTIDOR_FIRMAS f WHERE f.ENTREGA_ID = e.ID) AS TIENE_FIRMA
FROM JAVIER.REPARTIDOR_ENTREGAS e
WHERE e.FECHA_PREVISTA = CURRENT_DATE;

-- Vista: Comisiones por repartidor
CREATE VIEW JAVIER.V_COMISIONES_REPARTIDOR AS
SELECT 
  o.CODIGO_REPARTIDOR,
  o.ANIO,
  o.MES,
  o.IMPORTE_COBRABLE,
  o.IMPORTE_COBRADO,
  o.PORCENTAJE_COBRADO,
  CASE 
    WHEN o.PORCENTAJE_COBRADO < 30 THEN 'Sin comisión (< 30%)'
    WHEN o.TIER_COMISION = 1 THEN 'Tier 1: 1.0%'
    WHEN o.TIER_COMISION = 2 THEN 'Tier 2: 1.3%'
    WHEN o.TIER_COMISION = 3 THEN 'Tier 3: 1.6%'
    WHEN o.TIER_COMISION = 4 THEN 'Tier 4: 2.0%'
    ELSE 'Pendiente'
  END AS DESCRIPCION_TIER,
  o.COMISION_CALCULADA
FROM JAVIER.REPARTIDOR_OBJETIVOS o;

-- ============================================
-- FIN DEL SCRIPT
-- ============================================
