-- Repartidor finance suite schema.
-- Manual DB2 migration for DSN=GMP.
--
-- Important:
--   JAVIER.REPARTIDOR_COBROS already exists in 002_create_repartidor_tables.sql.
--   This migration extends that table instead of recreating it, so historical
--   delivery/payment data and the existing FK to REPARTIDOR_ENTREGAS survive.
--
-- DB2 for i ODBC compatibility:
--   - ADD CONSTRAINT fails with SQL5051 (qualifier mismatch bug).
--   - Use CREATE UNIQUE INDEX instead of UNIQUE constraints.
--   - Use ALTER TABLE ... CHECK (...) (unnamed) instead of CHECK constraints.
--   - ALTER COLUMN SET NOT NULL fails with HY008; rely on UNIQUE INDEX for
--     implicit NOT NULL enforcement.
--
-- Execution rule:
--   Run statements in order. If DB2 returns "column/object already exists"
--   for an ADD COLUMN, CREATE INDEX, CREATE TABLE, or ADD CONSTRAINT statement,
--   skip only that statement and continue with the next one.

-- ---------------------------------------------------------------------------
-- 1. Delivery status table used by Rutero confirmations
-- ---------------------------------------------------------------------------

CREATE TABLE JAVIER.DELIVERY_STATUS (
  ID VARCHAR(160) NOT NULL PRIMARY KEY,
  STATUS VARCHAR(20) DEFAULT 'PENDIENTE',
  OBSERVACIONES VARCHAR(512),
  FIRMA_PATH VARCHAR(255),
  LATITUD DECIMAL(10, 8),
  LONGITUD DECIMAL(11, 8),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  REPARTIDOR_ID VARCHAR(20)
);

CREATE INDEX JAVIER.IDX_DELIVERY_STATUS_REP
  ON JAVIER.DELIVERY_STATUS (REPARTIDOR_ID, UPDATED_AT);

-- ---------------------------------------------------------------------------
-- 2. LQD shadow table for test mode.
--    Same physical structure as DSEDAC.LQD, but isolated in JAVIER.
--    Backend default: REPARTIDOR_FINANCE_ERP_SCHEMA=JAVIER.
--    Production cutover: set REPARTIDOR_FINANCE_ERP_SCHEMA=DSEDAC.
-- ---------------------------------------------------------------------------

CREATE TABLE JAVIER.LQD LIKE DSEDAC.LQD;

CREATE INDEX JAVIER.IDX_LQD_REP_TEST_NUMERO
  ON JAVIER.LQD (
    SUBEMPRESALIQUIDACION,
    EJERCICIOLIQUIDACION,
    SERIELIQUIDACION,
    TERMINALLIQUIDACION,
    NUMEROLIQUIDACION
  );

CREATE INDEX JAVIER.IDX_LQD_REP_TEST_IDMARCA
  ON JAVIER.LQD (IDMARCALIQUIDACION);

-- ---------------------------------------------------------------------------
-- 3. Extend existing JAVIER.REPARTIDOR_COBROS for app finance flows
-- ---------------------------------------------------------------------------

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN ENTREGA_APP_ID VARCHAR(160);

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN ORIGEN_DOCUMENTO CHAR(1) DEFAULT 'B';

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN SUBEMPRESA_DOCUMENTO CHAR(3) DEFAULT 'GMP';

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN SERIE_DOCUMENTO VARCHAR(5) DEFAULT '';

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN TERMINAL_DOCUMENTO INTEGER DEFAULT 0;

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN XDE_DOCUMENTO INTEGER DEFAULT 1;

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN DEX_DOCUMENTO INTEGER DEFAULT 1;

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN IDEMPOTENCY_TOKEN VARCHAR(128);

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN PANTALLA_ORIGEN VARCHAR(20) DEFAULT 'LEGACY';

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN OPERADOR VARCHAR(50) DEFAULT 'legacy';

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN LIQUIDADO_SN CHAR(1) DEFAULT 'N';

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN LIQUIDACION_TOKEN VARCHAR(128);

ALTER TABLE JAVIER.REPARTIDOR_COBROS
  ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE JAVIER.REPARTIDOR_COBROS
SET IDEMPOTENCY_TOKEN = 'LEGACY-' || TRIM(CHAR(ID))
WHERE IDEMPOTENCY_TOKEN IS NULL
   OR TRIM(IDEMPOTENCY_TOKEN) = '';

UPDATE JAVIER.REPARTIDOR_COBROS
SET LIQUIDADO_SN = 'N'
WHERE LIQUIDADO_SN IS NULL
   OR TRIM(LIQUIDADO_SN) = '';

UPDATE JAVIER.REPARTIDOR_COBROS
SET PANTALLA_ORIGEN = 'LEGACY'
WHERE PANTALLA_ORIGEN IS NULL
   OR TRIM(PANTALLA_ORIGEN) = '';

UPDATE JAVIER.REPARTIDOR_COBROS
SET OPERADOR = 'legacy'
WHERE OPERADOR IS NULL
   OR TRIM(OPERADOR) = '';

-- NOTE: ALTER COLUMN SET NOT NULL skipped due to DB2 for i ODBC HY008.
-- UNIQUE INDEX below enforces non-null implicitly.

CREATE UNIQUE INDEX JAVIER.UX_REP_COBROS_TOKEN
  ON JAVIER.REPARTIDOR_COBROS (IDEMPOTENCY_TOKEN);

CREATE INDEX JAVIER.IDX_REP_COBROS_REP_LIQ_FECHA
  ON JAVIER.REPARTIDOR_COBROS (CODIGO_REPARTIDOR, LIQUIDADO_SN, FECHA_COBRO);

CREATE INDEX JAVIER.IDX_REP_COBROS_APP_ENTREGA
  ON JAVIER.REPARTIDOR_COBROS (ENTREGA_APP_ID);

CREATE INDEX JAVIER.IDX_REP_COBROS_LIQ_TOKEN
  ON JAVIER.REPARTIDOR_COBROS (LIQUIDACION_TOKEN);

-- ---------------------------------------------------------------------------
-- 4. Pending balance carried to the next daily liquidation
-- ---------------------------------------------------------------------------

CREATE TABLE JAVIER.REPARTIDOR_FINANCIAL_BALANCES (
  CODIGO_REPARTIDOR VARCHAR(20) NOT NULL PRIMARY KEY,
  SALDO_PENDIENTE DECIMAL(15, 2) NOT NULL DEFAULT 0,
  UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'system',
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 5. Local operation ledger for ERP LQD writes and idempotency
-- ---------------------------------------------------------------------------

CREATE TABLE JAVIER.REPARTIDOR_LIQUIDACION_OPS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY,
  IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL,
  SUBEMPRESA_LIQ CHAR(3) NOT NULL DEFAULT 'GMP',
  EJERCICIO_LIQ INTEGER NOT NULL,
  SERIE_LIQ VARCHAR(5) NOT NULL DEFAULT 'A',
  TERMINAL_LIQ INTEGER NOT NULL,
  NUMERO_LIQ INTEGER NOT NULL,
  CODIGO_REPARTIDOR VARCHAR(20) NOT NULL,
  TOTAL_EFECTIVO DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TOTAL_CHEQUES DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TOTAL_TARJETA DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TOTAL_POSTDATADOS DECIMAL(15, 2) NOT NULL DEFAULT 0,
  SALDO_ANTERIOR DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TOTAL_COBROS_DIA DECIMAL(15, 2) NOT NULL DEFAULT 0,
  GASTOS DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TOTAL_A_INGRESAR DECIMAL(15, 2) NOT NULL DEFAULT 0,
  INGRESO_BANCO DECIMAL(15, 2) NOT NULL DEFAULT 0,
  EFECTIVO_2 DECIMAL(15, 2) NOT NULL DEFAULT 0,
  ENTREGADO_2 DECIMAL(15, 2) NOT NULL DEFAULT 0,
  SALDO_RESULTANTE DECIMAL(15, 2) NOT NULL DEFAULT 0,
  PANTALLA_ORIGEN VARCHAR(20) NOT NULL DEFAULT 'LIQUIDACION_DIARIA',
  CREADO_POR VARCHAR(50) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'CLOSED',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE JAVIER.REPARTIDOR_LIQUIDACION_OPS ADD PRIMARY KEY (ID);

CREATE UNIQUE INDEX JAVIER.UX_REP_LIQ_TOKEN
  ON JAVIER.REPARTIDOR_LIQUIDACION_OPS (IDEMPOTENCY_TOKEN);

CREATE UNIQUE INDEX JAVIER.UX_REP_LIQ_NUMERO
  ON JAVIER.REPARTIDOR_LIQUIDACION_OPS (
    SUBEMPRESA_LIQ,
    EJERCICIO_LIQ,
    SERIE_LIQ,
    TERMINAL_LIQ,
    NUMERO_LIQ
  );

ALTER TABLE JAVIER.REPARTIDOR_LIQUIDACION_OPS
  CHECK (STATUS IN ('CLOSED', 'VOID'));

CREATE INDEX JAVIER.IDX_REP_LIQ_REP_FECHA
  ON JAVIER.REPARTIDOR_LIQUIDACION_OPS (CODIGO_REPARTIDOR, CREATED_AT);

-- ---------------------------------------------------------------------------
-- 6. Email delivery log. Email failure never rolls back financial closing.
-- ---------------------------------------------------------------------------

CREATE TABLE JAVIER.REPARTIDOR_LIQUIDACION_EMAILS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY,
  LIQUIDACION_OP_ID BIGINT NOT NULL,
  RECIPIENT_EMAIL VARCHAR(180) NOT NULL,
  EMAIL_KIND VARCHAR(20) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  ERROR_MESSAGE VARCHAR(1000),
  SENT_AT TIMESTAMP,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE JAVIER.REPARTIDOR_LIQUIDACION_EMAILS ADD PRIMARY KEY (ID);

ALTER TABLE JAVIER.REPARTIDOR_LIQUIDACION_EMAILS
  CHECK (EMAIL_KIND IN ('REPARTIDOR', 'INTERNO'));

ALTER TABLE JAVIER.REPARTIDOR_LIQUIDACION_EMAILS
  CHECK (STATUS IN ('PENDING', 'SENT', 'FAILED'));

CREATE INDEX JAVIER.IDX_REP_LIQ_EMAIL_OP
  ON JAVIER.REPARTIDOR_LIQUIDACION_EMAILS (LIQUIDACION_OP_ID, STATUS);

-- ---------------------------------------------------------------------------
-- 7. Editable commission tiers for repartidores
-- ---------------------------------------------------------------------------

CREATE TABLE JAVIER.REPARTIDOR_COMMISSION_TIERS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY,
  THRESHOLD_PCT DECIMAL(7, 3) NOT NULL,
  COMMISSION_PCT DECIMAL(7, 3) NOT NULL,
  SORT_ORDER INTEGER NOT NULL,
  ACTIVE_SN CHAR(1) NOT NULL DEFAULT 'S',
  CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'migration',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(50),
  UPDATED_AT TIMESTAMP
);

ALTER TABLE JAVIER.REPARTIDOR_COMMISSION_TIERS ADD PRIMARY KEY (ID);

ALTER TABLE JAVIER.REPARTIDOR_COMMISSION_TIERS
  CHECK (ACTIVE_SN IN ('S', 'N'));

CREATE INDEX JAVIER.IDX_REP_COMM_ACTIVE
  ON JAVIER.REPARTIDOR_COMMISSION_TIERS (ACTIVE_SN, SORT_ORDER);

INSERT INTO JAVIER.REPARTIDOR_COMMISSION_TIERS
  (THRESHOLD_PCT, COMMISSION_PCT, SORT_ORDER, ACTIVE_SN, CREATED_BY)
SELECT 20.000, 0.500, 1, 'S', 'migration'
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (
  SELECT 1
  FROM JAVIER.REPARTIDOR_COMMISSION_TIERS
  WHERE ACTIVE_SN = 'S'
    AND THRESHOLD_PCT = 20.000
    AND COMMISSION_PCT = 0.500
);

INSERT INTO JAVIER.REPARTIDOR_COMMISSION_TIERS
  (THRESHOLD_PCT, COMMISSION_PCT, SORT_ORDER, ACTIVE_SN, CREATED_BY)
SELECT 30.000, 0.700, 2, 'S', 'migration'
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (
  SELECT 1
  FROM JAVIER.REPARTIDOR_COMMISSION_TIERS
  WHERE ACTIVE_SN = 'S'
    AND THRESHOLD_PCT = 30.000
    AND COMMISSION_PCT = 0.700
);

INSERT INTO JAVIER.REPARTIDOR_COMMISSION_TIERS
  (THRESHOLD_PCT, COMMISSION_PCT, SORT_ORDER, ACTIVE_SN, CREATED_BY)
SELECT 50.000, 0.800, 3, 'S', 'migration'
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (
  SELECT 1
  FROM JAVIER.REPARTIDOR_COMMISSION_TIERS
  WHERE ACTIVE_SN = 'S'
    AND THRESHOLD_PCT = 50.000
    AND COMMISSION_PCT = 0.800
);

INSERT INTO JAVIER.REPARTIDOR_COMMISSION_TIERS
  (THRESHOLD_PCT, COMMISSION_PCT, SORT_ORDER, ACTIVE_SN, CREATED_BY)
SELECT 70.000, 1.000, 4, 'S', 'migration'
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (
  SELECT 1
  FROM JAVIER.REPARTIDOR_COMMISSION_TIERS
  WHERE ACTIVE_SN = 'S'
    AND THRESHOLD_PCT = 70.000
    AND COMMISSION_PCT = 1.000
);
