-- Repartidor finance suite schema.
-- Manual migration only. Run against DSN=GMP after reviewing the target schema.
-- If any object already exists, skip that CREATE and only apply missing ALTER/INDEX statements.

CREATE TABLE JAVIER.REPARTIDOR_COBROS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ENTREGA_ID VARCHAR(120),
  CODIGO_CLIENTE VARCHAR(20) NOT NULL,
  NOMBRE_CLIENTE VARCHAR(160),
  CODIGO_REPARTIDOR VARCHAR(20) NOT NULL,
  TIPO_DOCUMENTO VARCHAR(10) NOT NULL,
  ORIGEN_DOCUMENTO CHAR(1) NOT NULL DEFAULT 'B',
  SUBEMPRESA_DOCUMENTO CHAR(3) NOT NULL DEFAULT 'GMP',
  EJERCICIO_DOCUMENTO INTEGER NOT NULL,
  SERIE_DOCUMENTO VARCHAR(5) NOT NULL,
  TERMINAL_DOCUMENTO INTEGER NOT NULL,
  NUMERO_DOCUMENTO INTEGER NOT NULL,
  XDE_DOCUMENTO INTEGER NOT NULL DEFAULT 1,
  DEX_DOCUMENTO INTEGER NOT NULL DEFAULT 1,
  FECHA_COBRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IMPORTE_COBRADO DECIMAL(15, 2) NOT NULL DEFAULT 0,
  IMPORTE_PENDIENTE DECIMAL(15, 2) NOT NULL DEFAULT 0,
  FORMA_PAGO VARCHAR(20) NOT NULL,
  IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL,
  PANTALLA_ORIGEN VARCHAR(20) NOT NULL,
  OPERADOR VARCHAR(50) NOT NULL,
  NOTAS VARCHAR(500),
  LIQUIDADO_SN CHAR(1) NOT NULL DEFAULT 'N',
  LIQUIDACION_TOKEN VARCHAR(128),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UK_REP_COBROS_TOKEN UNIQUE (IDEMPOTENCY_TOKEN),
  CONSTRAINT CK_REP_COBROS_LIQ CHECK (LIQUIDADO_SN IN ('S', 'N')),
  CONSTRAINT CK_REP_COBROS_ORIGEN CHECK (PANTALLA_ORIGEN IN ('RUTERO', 'VENCIMIENTOS'))
);

CREATE INDEX JAVIER.IDX_REP_COBROS_REP_FECHA
  ON JAVIER.REPARTIDOR_COBROS (CODIGO_REPARTIDOR, FECHA_COBRO);

CREATE INDEX JAVIER.IDX_REP_COBROS_CLIENTE
  ON JAVIER.REPARTIDOR_COBROS (CODIGO_CLIENTE, FECHA_COBRO);

CREATE INDEX JAVIER.IDX_REP_COBROS_LIQ
  ON JAVIER.REPARTIDOR_COBROS (LIQUIDACION_TOKEN);

CREATE TABLE JAVIER.REPARTIDOR_FINANCIAL_BALANCES (
  CODIGO_REPARTIDOR VARCHAR(20) NOT NULL PRIMARY KEY,
  SALDO_PENDIENTE DECIMAL(15, 2) NOT NULL DEFAULT 0,
  UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'system',
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE JAVIER.REPARTIDOR_LIQUIDACION_OPS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL,
  SUBEMPRESA_LIQ CHAR(3) NOT NULL DEFAULT 'GMP',
  EJERCICIO_LIQ INTEGER NOT NULL,
  SERIE_LIQ VARCHAR(5) NOT NULL DEFAULT 'A',
  TERMINAL_LIQ INTEGER NOT NULL,
  NUMERO_LIQ INTEGER NOT NULL,
  CODIGO_REPARTIDOR VARCHAR(20) NOT NULL,
  TOTAL_EFECTIVO DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TOTAL_CHEQUES DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TOTAL_TARJETA DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TOTAL_POSTDATADOS DECIMAL(15, 2) NOT NULL DEFAULT 0,
  SALDO_ANTERIOR DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TOTAL_COBROS_DIA DECIMAL(15, 2) NOT NULL DEFAULT 0,
  GASTOS DECIMAL(15, 2) NOT NULL DEFAULT 0,
  TOTAL_A_INGRESAR DECIMAL(15, 2) NOT NULL DEFAULT 0,
  INGRESO_BANCO DECIMAL(15, 2) NOT NULL DEFAULT 0,
  EFECTIVO_2 DECIMAL(15, 2) NOT NULL DEFAULT 0,
  ENTREGADO_2 DECIMAL(15, 2) NOT NULL DEFAULT 0,
  SALDO_RESULTANTE DECIMAL(15, 2) NOT NULL DEFAULT 0,
  CREADO_POR VARCHAR(50) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'CLOSED',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UK_REP_LIQ_TOKEN UNIQUE (IDEMPOTENCY_TOKEN),
  CONSTRAINT UK_REP_LIQ_NUMERO UNIQUE (SUBEMPRESA_LIQ, EJERCICIO_LIQ, SERIE_LIQ, TERMINAL_LIQ, NUMERO_LIQ),
  CONSTRAINT CK_REP_LIQ_STATUS CHECK (STATUS IN ('CLOSED', 'VOID'))
);

CREATE INDEX JAVIER.IDX_REP_LIQ_REP_FECHA
  ON JAVIER.REPARTIDOR_LIQUIDACION_OPS (CODIGO_REPARTIDOR, CREATED_AT);

CREATE TABLE JAVIER.REPARTIDOR_LIQUIDACION_EMAILS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  LIQUIDACION_OP_ID BIGINT NOT NULL,
  RECIPIENT_EMAIL VARCHAR(180) NOT NULL,
  EMAIL_KIND VARCHAR(20) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  ERROR_MESSAGE VARCHAR(1000),
  SENT_AT TIMESTAMP,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CK_REP_LIQ_EMAIL_KIND CHECK (EMAIL_KIND IN ('REPARTIDOR', 'INTERNO')),
  CONSTRAINT CK_REP_LIQ_EMAIL_STATUS CHECK (STATUS IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX JAVIER.IDX_REP_LIQ_EMAIL_OP
  ON JAVIER.REPARTIDOR_LIQUIDACION_EMAILS (LIQUIDACION_OP_ID, STATUS);

CREATE TABLE JAVIER.REPARTIDOR_COMMISSION_TIERS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  THRESHOLD_PCT DECIMAL(7, 3) NOT NULL,
  COMMISSION_PCT DECIMAL(7, 3) NOT NULL,
  SORT_ORDER INTEGER NOT NULL,
  ACTIVE_SN CHAR(1) NOT NULL DEFAULT 'S',
  CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'migration',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(50),
  UPDATED_AT TIMESTAMP,
  CONSTRAINT CK_REP_COMM_ACTIVE CHECK (ACTIVE_SN IN ('S', 'N'))
);

CREATE INDEX JAVIER.IDX_REP_COMM_ACTIVE
  ON JAVIER.REPARTIDOR_COMMISSION_TIERS (ACTIVE_SN, SORT_ORDER);

INSERT INTO JAVIER.REPARTIDOR_COMMISSION_TIERS
  (THRESHOLD_PCT, COMMISSION_PCT, SORT_ORDER, ACTIVE_SN, CREATED_BY)
VALUES
  (20.000, 0.500, 1, 'S', 'migration'),
  (30.000, 0.700, 2, 'S', 'migration'),
  (50.000, 0.800, 3, 'S', 'migration'),
  (70.000, 1.000, 4, 'S', 'migration');
