-- Verificacion ACS del esquema de Repartidor Finanzas.
-- Ejecutar despues de 020_repartidor_finance_tables.sql.
-- Resultado esperado: todas las filas con STATUS = OK.

SELECT CHECK_NAME, STATUS
FROM (
  SELECT
    'TABLE JAVIER.REPARTIDOR_COBROS' AS CHECK_NAME,
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSTABLES
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
    ) THEN 'OK' ELSE 'MISSING' END AS STATUS
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'TABLE JAVIER.DELIVERY_STATUS',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSTABLES
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'DELIVERY_STATUS'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'TABLE JAVIER.REPARTIDOR_FINANCIAL_BALANCES',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSTABLES
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_FINANCIAL_BALANCES'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'TABLE JAVIER.REPARTIDOR_LIQUIDACION_OPS',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSTABLES
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_LIQUIDACION_OPS'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'TABLE JAVIER.REPARTIDOR_LIQUIDACION_EMAILS',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSTABLES
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_LIQUIDACION_EMAILS'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'TABLE JAVIER.REPARTIDOR_COMMISSION_TIERS',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSTABLES
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COMMISSION_TIERS'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.IDEMPOTENCY_TOKEN',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'IDEMPOTENCY_TOKEN'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.LIQUIDACION_TOKEN',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'LIQUIDACION_TOKEN'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.OPERADOR',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'OPERADOR'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.PANTALLA_ORIGEN',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'PANTALLA_ORIGEN'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.ENTREGA_APP_ID',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'ENTREGA_APP_ID'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.TIPO_DOCUMENTO',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'TIPO_DOCUMENTO'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.ORIGEN_DOCUMENTO',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'ORIGEN_DOCUMENTO'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.SUBEMPRESA_DOCUMENTO',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'SUBEMPRESA_DOCUMENTO'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.SERIE_DOCUMENTO',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'SERIE_DOCUMENTO'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.TERMINAL_DOCUMENTO',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'TERMINAL_DOCUMENTO'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.XDE_DOCUMENTO',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'XDE_DOCUMENTO'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.DEX_DOCUMENTO',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'DEX_DOCUMENTO'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.LIQUIDADO_SN',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'LIQUIDADO_SN'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COBROS.CREATED_AT',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COBROS'
        AND COLUMN_NAME = 'CREATED_AT'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_LIQUIDACION_OPS.SALDO_RESULTANTE',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_LIQUIDACION_OPS'
        AND COLUMN_NAME = 'SALDO_RESULTANTE'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN JAVIER.REPARTIDOR_COMMISSION_TIERS.THRESHOLD_PCT',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'REPARTIDOR_COMMISSION_TIERS'
        AND COLUMN_NAME = 'THRESHOLD_PCT'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN DSEDAC.LQD.IDMARCALIQUIDACION',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'DSEDAC'
        AND TABLE_NAME = 'LQD'
        AND COLUMN_NAME = 'IDMARCALIQUIDACION'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'TABLE DSEDAC.CLCL1',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSTABLES
      WHERE TABLE_SCHEMA = 'DSEDAC'
        AND TABLE_NAME = 'CLCL1'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN DSEDAC.CLCL1.DIASLIMITECREDITO',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'DSEDAC'
        AND TABLE_NAME = 'CLCL1'
        AND COLUMN_NAME = 'DIASLIMITECREDITO'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN DSEDAC.CLCL1.DIASLIMITECREDITOCONFECHAALB',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'DSEDAC'
        AND TABLE_NAME = 'CLCL1'
        AND COLUMN_NAME = 'DIASLIMITECREDITOCONFECHAALB'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'COLUMN DSEDAC.CLX.COBRORIGUROSOSN',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'DSEDAC'
        AND TABLE_NAME = 'CLX'
        AND COLUMN_NAME = 'COBRORIGUROSOSN'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'INDEX JAVIER.UX_REP_COBROS_TOKEN',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSINDEXES
      WHERE INDEX_SCHEMA = 'JAVIER'
        AND INDEX_NAME = 'UX_REP_COBROS_TOKEN'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'INDEX JAVIER.IDX_REP_COBROS_REP_LIQ_FECHA',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSINDEXES
      WHERE INDEX_SCHEMA = 'JAVIER'
        AND INDEX_NAME = 'IDX_REP_COBROS_REP_LIQ_FECHA'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'INDEX JAVIER.IDX_REP_COBROS_LIQ_TOKEN',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSINDEXES
      WHERE INDEX_SCHEMA = 'JAVIER'
        AND INDEX_NAME = 'IDX_REP_COBROS_LIQ_TOKEN'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'INDEX JAVIER.IDX_REP_LIQ_REP_FECHA',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSINDEXES
      WHERE INDEX_SCHEMA = 'JAVIER'
        AND INDEX_NAME = 'IDX_REP_LIQ_REP_FECHA'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'INDEX JAVIER.IDX_REP_COMM_ACTIVE',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSINDEXES
      WHERE INDEX_SCHEMA = 'JAVIER'
        AND INDEX_NAME = 'IDX_REP_COMM_ACTIVE'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'CONSTRAINT JAVIER.UK_REP_LIQ_TOKEN',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCST
      WHERE CONSTRAINT_SCHEMA = 'JAVIER'
        AND CONSTRAINT_NAME = 'UK_REP_LIQ_TOKEN'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1

  UNION ALL
  SELECT 'CONSTRAINT JAVIER.UK_REP_LIQ_NUMERO',
    CASE WHEN EXISTS (
      SELECT 1 FROM QSYS2.SYSCST
      WHERE CONSTRAINT_SCHEMA = 'JAVIER'
        AND CONSTRAINT_NAME = 'UK_REP_LIQ_NUMERO'
    ) THEN 'OK' ELSE 'MISSING' END
  FROM SYSIBM.SYSDUMMY1
) CHECKS
ORDER BY CHECK_NAME;
