-- Plantilla ACS para borrar una prueba de Repartidor Finanzas.
-- No ejecutar sin sustituir los placeholders.
--
-- 1. Sustituir <IDEMPOTENCY_TOKEN> por el token exacto de la prueba.
-- 2. Para una liquidacion, usar el token liq_...
-- 2b. Esta plantilla asume modo test: REPARTIDOR_FINANCE_ERP_SCHEMA=JAVIER,
--     por tanto borra de JAVIER.LQD. Si en produccion se usa DSEDAC,
--     cambia manualmente JAVIER.LQD por DSEDAC.LQD antes de ejecutar.
-- 3. Para un cobro Rutero, usar el token rutero_... y opcionalmente
--    sustituir <ENTREGA_APP_ID> si tambien hay que liberar DELIVERY_STATUS.
-- 4. Ejecutar primero los SELECT. Ejecutar DELETE/UPDATE solo si las filas
--    encontradas son exclusivamente de la prueba.

-- Revision previa
SELECT *
FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS
WHERE IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>';

SELECT *
FROM JAVIER.LQD
WHERE IDMARCALIQUIDACION = '<IDEMPOTENCY_TOKEN>';

SELECT *
FROM JAVIER.REPARTIDOR_COBROS
WHERE IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>'
   OR LIQUIDACION_TOKEN = '<IDEMPOTENCY_TOKEN>';

SELECT B.*
FROM JAVIER.REPARTIDOR_FINANCIAL_BALANCES B
WHERE B.CODIGO_REPARTIDOR IN (
  SELECT CODIGO_REPARTIDOR
  FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS
  WHERE IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>'
);

-- Si esta consulta devuelve filas, NO ejecutar la limpieza de esa
-- liquidacion: restauraria un saldo anterior y pisaria cierres posteriores.
SELECT NEWER.*
FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS BASE
INNER JOIN JAVIER.REPARTIDOR_LIQUIDACION_OPS NEWER
  ON NEWER.CODIGO_REPARTIDOR = BASE.CODIGO_REPARTIDOR
 AND NEWER.CREATED_AT > BASE.CREATED_AT
 AND NEWER.STATUS = 'CLOSED'
WHERE BASE.IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>';

-- Limpieza de liquidacion de prueba
DELETE FROM JAVIER.REPARTIDOR_LIQUIDACION_EMAILS
WHERE LIQUIDACION_OP_ID IN (
  SELECT BASE.ID
  FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS BASE
  WHERE BASE.IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>'
    AND NOT EXISTS (
      SELECT 1
      FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS NEWER
      WHERE NEWER.CODIGO_REPARTIDOR = BASE.CODIGO_REPARTIDOR
        AND NEWER.CREATED_AT > BASE.CREATED_AT
        AND NEWER.STATUS = 'CLOSED'
    )
);

UPDATE JAVIER.REPARTIDOR_COBROS
SET LIQUIDADO_SN = 'N',
    LIQUIDACION_TOKEN = NULL
WHERE LIQUIDACION_TOKEN = '<IDEMPOTENCY_TOKEN>'
  AND EXISTS (
    SELECT 1
    FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS BASE
    WHERE BASE.IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>'
      AND NOT EXISTS (
        SELECT 1
        FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS NEWER
        WHERE NEWER.CODIGO_REPARTIDOR = BASE.CODIGO_REPARTIDOR
          AND NEWER.CREATED_AT > BASE.CREATED_AT
          AND NEWER.STATUS = 'CLOSED'
      )
  );

-- Restaurar saldo acumulado si la prueba fue una liquidacion.
-- Ejecutar antes de borrar REPARTIDOR_LIQUIDACION_OPS.
MERGE INTO JAVIER.REPARTIDOR_FINANCIAL_BALANCES B
USING (
  SELECT BASE.CODIGO_REPARTIDOR, BASE.SALDO_ANTERIOR
  FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS BASE
  WHERE BASE.IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>'
    AND NOT EXISTS (
      SELECT 1
      FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS NEWER
      WHERE NEWER.CODIGO_REPARTIDOR = BASE.CODIGO_REPARTIDOR
        AND NEWER.CREATED_AT > BASE.CREATED_AT
        AND NEWER.STATUS = 'CLOSED'
    )
) O
  ON B.CODIGO_REPARTIDOR = O.CODIGO_REPARTIDOR
WHEN MATCHED THEN
  UPDATE SET SALDO_PENDIENTE = O.SALDO_ANTERIOR,
             UPDATED_BY = 'cleanup',
             UPDATED_AT = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (CODIGO_REPARTIDOR, SALDO_PENDIENTE, UPDATED_BY)
  VALUES (O.CODIGO_REPARTIDOR, O.SALDO_ANTERIOR, 'cleanup');

DELETE FROM JAVIER.LQD
WHERE IDMARCALIQUIDACION = '<IDEMPOTENCY_TOKEN>'
  AND EXISTS (
    SELECT 1
    FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS BASE
    WHERE BASE.IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>'
      AND NOT EXISTS (
        SELECT 1
        FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS NEWER
        WHERE NEWER.CODIGO_REPARTIDOR = BASE.CODIGO_REPARTIDOR
          AND NEWER.CREATED_AT > BASE.CREATED_AT
          AND NEWER.STATUS = 'CLOSED'
      )
  );

DELETE FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS
WHERE IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>'
  AND ID IN (
    SELECT BASE.ID
    FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS BASE
    WHERE BASE.IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>'
      AND NOT EXISTS (
        SELECT 1
        FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS NEWER
        WHERE NEWER.CODIGO_REPARTIDOR = BASE.CODIGO_REPARTIDOR
          AND NEWER.CREATED_AT > BASE.CREATED_AT
          AND NEWER.STATUS = 'CLOSED'
      )
  );

-- Limpieza de cobro Rutero de prueba independiente
DELETE FROM JAVIER.REPARTIDOR_COBROS
WHERE IDEMPOTENCY_TOKEN = '<IDEMPOTENCY_TOKEN>'
  AND (LIQUIDACION_TOKEN IS NULL OR TRIM(LIQUIDACION_TOKEN) = '');

-- Opcional: liberar estado de entrega de una prueba Rutero.
-- Ejecutar solo si la entrega fue usada para una prueba y debe reintentarse.
DELETE FROM JAVIER.DELIVERY_STATUS
WHERE ID = '<ENTREGA_APP_ID>';
