-- ============================================================================
-- Migration 024: Align JAVIER repartidor tables to EXACTLY match DSEDAC structure
-- ============================================================================
-- DSEDAC is the source of truth. This script:
--   1. Backs up existing JAVIER table data to JAVIER.BKP_<table>_YYYYMMDD
--   2. Drops existing JAVIER tables
--   3. Recreates them with ALL DSEDAC columns (same names, types, lengths)
--   4. Adds app-specific columns for mobile app functionality
--   5. Creates indexes for performance
--
-- Tables affected (REPARTIDOR ONLY):
--   1. REPARTIDOR_COBROS          ← DSEDAC.CVC (104 cols + 8 app cols = 112)
--   2. REPARTIDOR_LIQUIDACION_OPS ← DSEDAC.LQD (32 cols + 6 app cols = 38)
--   3. REPARTIDOR_ENTREGAS        ← DSEDAC.OPP (44 cols + 6 app cols = 50)
--   4. REPARTIDOR_ENTREGA_LINEAS  ← DSEDAC.LAC (126 cols + 6 app cols = 132)
--   5. REPARTIDOR_FIRMAS          ← DSEDAC.CACFIRMAS (17 cols + 6 app cols = 23)
--   6. REPARTIDOR_OBJETIVOS       ← DSEDAC.CMV (9 cols + 6 app cols = 15)
--   7. DELIVERY_STATUS            ← DSEDAC.CPC (140 cols + 8 app cols = 148)
--   8. CLIENT_SIGNERS             ← DSEDAC.CLI (50 cols + 6 app cols = 56)
--   9. REPARTIDOR_FINANCIAL_BALANCES (app-only, 4 cols)
--  10. REPARTIDOR_COMMISSION_TIERS    (app-only, 9 cols)
--  11. REPARTIDOR_LIQUIDACION_EMAILS  (app-only, 9 cols)
--
-- DO NOT TOUCH: COMMISSION_EXCEPTIONS, COMMISSION_PAYMENTS, COMMISSION_SNAPSHOT_*
--
-- DB2 for i ODBC compatibility:
--   - Use CREATE UNIQUE INDEX instead of UNIQUE constraints
--   - ALTER COLUMN SET NOT NULL fails with HY008; rely on NOT NULL in CREATE
--   - SQL5051 = qualifier mismatch (DB2 for i ODBC bug with ADD CONSTRAINT)
--   - SQLSTATE 42710/42711 = object/column already exists (skippable)
-- ============================================================================

-- ============================================================================
-- PHASE 1: BACKUP EXISTING DATA
-- ============================================================================

-- Backup REPARTIDOR_COBROS
CREATE TABLE JAVIER.BKP_REPARTIDOR_COBROS_20260427 AS
  (SELECT * FROM JAVIER.REPARTIDOR_COBROS) WITH DATA;

-- Backup REPARTIDOR_LIQUIDACION_OPS
CREATE TABLE JAVIER.BKP_REPARTIDOR_LIQUIDACION_OPS_20260427 AS
  (SELECT * FROM JAVIER.REPARTIDOR_LIQUIDACION_OPS) WITH DATA;

-- Backup REPARTIDOR_ENTREGAS
CREATE TABLE JAVIER.BKP_REPARTIDOR_ENTREGAS_20260427 AS
  (SELECT * FROM JAVIER.REPARTIDOR_ENTREGAS) WITH DATA;

-- Backup REPARTIDOR_ENTREGA_LINEAS
CREATE TABLE JAVIER.BKP_REPARTIDOR_ENTREGA_LINEAS_20260427 AS
  (SELECT * FROM JAVIER.REPARTIDOR_ENTREGA_LINEAS) WITH DATA;

-- Backup REPARTIDOR_FIRMAS
CREATE TABLE JAVIER.BKP_REPARTIDOR_FIRMAS_20260427 AS
  (SELECT * FROM JAVIER.REPARTIDOR_FIRMAS) WITH DATA;

-- Backup REPARTIDOR_OBJETIVOS
CREATE TABLE JAVIER.BKP_REPARTIDOR_OBJETIVOS_20260427 AS
  (SELECT * FROM JAVIER.REPARTIDOR_OBJETIVOS) WITH DATA;

-- Backup DELIVERY_STATUS
CREATE TABLE JAVIER.BKP_DELIVERY_STATUS_20260427 AS
  (SELECT * FROM JAVIER.DELIVERY_STATUS) WITH DATA;

-- Backup CLIENT_SIGNERS
CREATE TABLE JAVIER.BKP_CLIENT_SIGNERS_20260427 AS
  (SELECT * FROM JAVIER.CLIENT_SIGNERS) WITH DATA;

-- ============================================================================
-- PHASE 2: DROP EXISTING TABLES
-- ============================================================================

DROP TABLE JAVIER.REPARTIDOR_COBROS;
DROP TABLE JAVIER.REPARTIDOR_LIQUIDACION_OPS;
DROP TABLE JAVIER.REPARTIDOR_ENTREGAS;
DROP TABLE JAVIER.REPARTIDOR_ENTREGA_LINEAS;
DROP TABLE JAVIER.REPARTIDOR_FIRMAS;
DROP TABLE JAVIER.REPARTIDOR_OBJETIVOS;
DROP TABLE JAVIER.DELIVERY_STATUS;
DROP TABLE JAVIER.CLIENT_SIGNERS;

-- ============================================================================
-- PHASE 3: RECREATE TABLES WITH DSEDAC STRUCTURE + APP COLUMNS
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. REPARTIDOR_COBROS ← DSEDAC.CVC (104 DSEDAC cols + 6 app cols)
-- ---------------------------------------------------------------------------
CREATE TABLE JAVIER.REPARTIDOR_COBROS (
  -- DSEDAC.CVC columns (exact match)
  TIPODOCUMENTO CHAR(3) NOT NULL DEFAULT ' ',
  ORIGENDOCUMENTO CHAR(1) NOT NULL DEFAULT ' ',
  SUBEMPRESADOCUMENTO CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIODOCUMENTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIEDOCUMENTO CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALDOCUMENTO NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMERODOCUMENTO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  XDEDOCUMENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  DEXDOCUMENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  SITUACION CHAR(1) NOT NULL DEFAULT ' ',
  CLAVEAGRUPAMIENTO CHAR(1) NOT NULL DEFAULT ' ',
  CODIGOFORMATOIMPRESION CHAR(3) NOT NULL DEFAULT ' ',
  CUENTABANCOREMESA CHAR(10) NOT NULL DEFAULT ' ',
  DIAREMESABANCO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESREMESABANCO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOREMESABANCO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  DIAREMESACLIENTE NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESREMESACLIENTE NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOREMESACLIENTE NUMERIC(4, 0) NOT NULL DEFAULT 0,
  CUENTALIBRADO CHAR(10) NOT NULL DEFAULT ' ',
  CUENTAPAGO CHAR(10) NOT NULL DEFAULT ' ',
  CUENTABANCO CHAR(10) NOT NULL DEFAULT ' ',
  CUENTABANCOEFECTOSDESCONTADOS CHAR(10) NOT NULL DEFAULT ' ',
  CUENTAEFECTOSDESCONTADOS CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOCLIENTEALBARAN CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOCLIENTEFACTURA CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOCLIENTECADENA CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOVENDEDOR CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOVENDEDORCOBRO CHAR(2) NOT NULL DEFAULT ' ',
  CODIGORUTA CHAR(4) NOT NULL DEFAULT ' ',
  CODIGOFORMAPAGO CHAR(2) NOT NULL DEFAULT ' ',
  DIAVENCIMIENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESVENCIMIENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOVENCIMIENTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  DIAEMISION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESEMISION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOEMISION NUMERIC(4, 0) NOT NULL DEFAULT 0,
  IMPORTEVENCIMIENTO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTECANCELADO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEPENDIENTE NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IBAN01 CHAR(4) NOT NULL DEFAULT ' ',
  IBAN02 CHAR(4) NOT NULL DEFAULT ' ',
  IBAN03 CHAR(4) NOT NULL DEFAULT ' ',
  IBAN04 CHAR(4) NOT NULL DEFAULT ' ',
  IBAN05 CHAR(4) NOT NULL DEFAULT ' ',
  IBAN06 CHAR(20) NOT NULL DEFAULT ' ',
  CLAUSULASBANCO CHAR(20) NOT NULL DEFAULT ' ',
  DIRECCIONBANCO CHAR(60) NOT NULL DEFAULT ' ',
  CODIGOPOSTALBANCO CHAR(5) NOT NULL DEFAULT ' ',
  SECUENCIACODIGOPOSTALBANCO CHAR(4) NOT NULL DEFAULT ' ',
  POBLACIONBANCO CHAR(25) NOT NULL DEFAULT ' ',
  PROVINCIABANCO CHAR(34) NOT NULL DEFAULT ' ',
  OBSERVACIONES CHAR(60) NOT NULL DEFAULT ' ',
  EMPRESACONTABLE CHAR(2) NOT NULL DEFAULT ' ',
  EMPRESACONTABLE2 CHAR(2) NOT NULL DEFAULT ' ',
  DIACOBRO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESCOBRO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOCOBRO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  NUMEROLIQUIDACION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  EJERCICIODELDOCUMENTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  DOCUMENTO CHAR(20) NOT NULL DEFAULT ' ',
  LUGAREMISION CHAR(15) NOT NULL DEFAULT ' ',
  DESDESERIENROPAG CHAR(4) NOT NULL DEFAULT ' ',
  DESDENUMERONROPAG NUMERIC(7, 0) NOT NULL DEFAULT 0,
  DESDECTRLNUMERONROPAG NUMERIC(1, 0) NOT NULL DEFAULT 0,
  DESDENUMERO2NROPAG NUMERIC(4, 0) NOT NULL DEFAULT 0,
  DESDECTRLNUMERO2NROPAG NUMERIC(1, 0) NOT NULL DEFAULT 0,
  CODIGOCONCEPTO CHAR(2) NOT NULL DEFAULT ' ',
  DESCRIPCIONCONCEPTO CHAR(30) NOT NULL DEFAULT ' ',
  DESCRIPCIONCONCEPTO_1 CHAR(30) NOT NULL DEFAULT ' ',
  NUMEROASIGNADO NUMERIC(10, 0) NOT NULL DEFAULT 0,
  SUBEMPRESADOCUMENTOASOCIADO CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIODOCUMENTOASOCIADO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIEDOCUMENTOASOCIADO CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALDOCUMENTOASOCIADO NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMERODOCUMENTOASOCIADO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  CODIGOMETODOPAGO CHAR(2) NOT NULL DEFAULT ' ',
  REFERENCIACARTERA CHAR(20) NOT NULL DEFAULT ' ',
  REFERENCIATIPODOCUMENTO CHAR(5) NOT NULL DEFAULT ' ',
  COMISIONESSN CHAR(1) NOT NULL DEFAULT ' ',
  IMPORTECOMISION NUMERIC(10, 2) NOT NULL DEFAULT 0,
  CODIGOIVA CHAR(1) NOT NULL DEFAULT ' ',
  IMPORTEIVACOMISION NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEOTROS NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEGASTOS NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPUTARGASTOSSN CHAR(1) NOT NULL DEFAULT ' ',
  CUENTAACREEDORA CHAR(10) NOT NULL DEFAULT ' ',
  CUENTAGASTOS CHAR(10) NOT NULL DEFAULT ' ',
  CUENTAOTROS CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOCANAL CHAR(5) NOT NULL DEFAULT ' ',
  ANULADOSN CHAR(1) NOT NULL DEFAULT ' ',
  CODIGOFORMAPAGOORIGINAL CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOMETODOPAGOORIGINAL CHAR(2) NOT NULL DEFAULT ' ',
  CUENTACARGOABONO CHAR(10) NOT NULL DEFAULT ' ',
  SUBEMPRESAASIENTO CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIOASIENTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIEASIENTO CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALASIENTO NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMEROASIENTO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  SECUENCIAASIENTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SITUACIONORIGINAL CHAR(1) NOT NULL DEFAULT ' ',
  CODIGOVENDEDORPOSEEDOR CHAR(2) NOT NULL DEFAULT ' ',
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  MARCAACTUALIZACION VARCHAR(50) NOT NULL DEFAULT ' ',
  -- App-specific columns
  ENTREGA_APP_ID VARCHAR(160),
  LIQUIDADO_SN CHAR(1) DEFAULT 'N',
  LIQUIDACION_TOKEN VARCHAR(128),
  IDEMPOTENCY_TOKEN VARCHAR(128),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'PENDIENTE',
  OPERADOR VARCHAR(50) DEFAULT 'legacy',
  PANTALLA_ORIGEN VARCHAR(20) DEFAULT 'LEGACY',
  FIRMA_PATH VARCHAR(255)
);

ALTER TABLE JAVIER.REPARTIDOR_COBROS ADD PRIMARY KEY (ID);

CREATE UNIQUE INDEX JAVIER.UX_REP_COBROS_TOKEN
  ON JAVIER.REPARTIDOR_COBROS (IDEMPOTENCY_TOKEN);

CREATE INDEX JAVIER.IDX_REP_COBROS_DOC
  ON JAVIER.REPARTIDOR_COBROS (SUBEMPRESADOCUMENTO, EJERCICIODOCUMENTO, SERIEDOCUMENTO, TERMINALDOCUMENTO, NUMERODOCUMENTO);

CREATE INDEX JAVIER.REP_COBROS_VENDEDOR
  ON JAVIER.REPARTIDOR_COBROS (CODIGOVENDEDOR, CODIGOVENDEDORCOBRO);

CREATE INDEX JAVIER.IDX_REP_COBROS_REP_LIQ_FECHA
  ON JAVIER.REPARTIDOR_COBROS (CODIGOVENDEDOR, NUMEROLIQUIDACION, DIACOBRO, MESCOBRO, ANOCOBRO);

CREATE INDEX JAVIER.IDX_REP_COBROS_CLIENTE
  ON JAVIER.REPARTIDOR_COBROS (CODIGOCLIENTEALBARAN, CODIGOCLIENTEFACTURA);

-- ---------------------------------------------------------------------------
-- 2. REPARTIDOR_LIQUIDACION_OPS ← DSEDAC.LQD (32 DSEDAC cols + 6 app cols)
-- ---------------------------------------------------------------------------
CREATE TABLE JAVIER.REPARTIDOR_LIQUIDACION_OPS (
  -- DSEDAC.LQD columns (exact match)
  SUBEMPRESALIQUIDACION CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIOLIQUIDACION NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIELIQUIDACION CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALLIQUIDACION NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMEROLIQUIDACION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  DIALIQUIDACION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESLIQUIDACION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOLIQUIDACION NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORALIQUIDACION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  CODIGOVENDEDOR CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOVENDEDORUSUARIO CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOUSUARIO CHAR(10) NOT NULL DEFAULT ' ',
  MATRICULA CHAR(20) NOT NULL DEFAULT ' ',
  KILOMETROSSALIDA NUMERIC(11, 3) NOT NULL DEFAULT 0,
  KILOMETROSLLEGADA NUMERIC(11, 3) NOT NULL DEFAULT 0,
  KILOMETROSRECORRIDOS NUMERIC(11, 3) NOT NULL DEFAULT 0,
  IMPORTEEFECTIVO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTECHEQUES NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEPOSTDATADOS NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTESALDOACTUAL NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTETOTALAINGRESAR NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEINGRESOENBANCO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEGASTOS NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPRESOSN CHAR(1) NOT NULL DEFAULT ' ',
  CODIGOVEHICULO CHAR(10) NOT NULL DEFAULT ' ',
  REVISADOSN CHAR(1) NOT NULL DEFAULT ' ',
  IDMARCALIQUIDACION CHAR(30) NOT NULL DEFAULT ' ',
  IMPORTEEFECTIVO2 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEENTREGADO2 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTETARJETA NUMERIC(10, 2) NOT NULL DEFAULT 0,
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  MARCAACTUALIZACION VARCHAR(50) NOT NULL DEFAULT ' ',
  -- App-specific columns
  FIRMA_PATH VARCHAR(255),
  REPARTIDOR_ID VARCHAR(20),
  IDEMPOTENCY_TOKEN VARCHAR(128),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'PENDIENTE',
  OPERADOR VARCHAR(50) DEFAULT 'system',
  PANTALLA_ORIGEN VARCHAR(20) DEFAULT 'RUTERO'
);

ALTER TABLE JAVIER.REPARTIDOR_LIQUIDACION_OPS ADD PRIMARY KEY (ID);

CREATE UNIQUE INDEX JAVIER.UX_REP_LIQ_TOKEN
  ON JAVIER.REPARTIDOR_LIQUIDACION_OPS (IDEMPOTENCY_TOKEN);

CREATE UNIQUE INDEX JAVIER.UX_REP_LIQ_NUMERO
  ON JAVIER.REPARTIDOR_LIQUIDACION_OPS (
    SUBEMPRESALIQUIDACION,
    EJERCICIOLIQUIDACION,
    SERIELIQUIDACION,
    TERMINALLIQUIDACION,
    NUMEROLIQUIDACION
  );

CREATE INDEX JAVIER.IDX_REP_LIQ_REP_FECHA
  ON JAVIER.REPARTIDOR_LIQUIDACION_OPS (CODIGOVENDEDOR, DIALIQUIDACION, MESLIQUIDACION, ANOLIQUIDACION);

CREATE INDEX JAVIER.IDX_REP_LIQ_IDMARCA
  ON JAVIER.REPARTIDOR_LIQUIDACION_OPS (IDMARCALIQUIDACION);

-- ---------------------------------------------------------------------------
-- 3. REPARTIDOR_ENTREGAS ← DSEDAC.OPP (44 DSEDAC cols + 6 app cols)
-- ---------------------------------------------------------------------------
CREATE TABLE JAVIER.REPARTIDOR_ENTREGAS (
  -- DSEDAC.OPP columns (exact match)
  SUBEMPRESA CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIOORDENPREPARACION NUMERIC(4, 0) NOT NULL DEFAULT 0,
  NUMEROORDENPREPARACION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  DIAREPARTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESREPARTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOREPARTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORACREACION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  CODIGOREPARTIDOR CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOVEHICULO CHAR(10) NOT NULL DEFAULT ' ',
  VOLUMEN NUMERIC(9, 6) NOT NULL DEFAULT 0,
  ESTADOORDENPREPARACION CHAR(1) NOT NULL DEFAULT ' ',
  FILTROTIPO CHAR(1) NOT NULL DEFAULT ' ',
  DIACREACION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESCREACION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOCREACION NUMERIC(4, 0) NOT NULL DEFAULT 0,
  VOLUMENCONTENEDORES NUMERIC(5, 2) NOT NULL DEFAULT 0,
  VEHICULOCONTENEDORES NUMERIC(5, 0) NOT NULL DEFAULT 0,
  VEHICULOCONTENEDORVOLUMEN NUMERIC(9, 6) NOT NULL DEFAULT 0,
  CODIGOPREPARADOR CHAR(2) NOT NULL DEFAULT ' ',
  DIAIMPRESION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESIMPRESION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOIMPRESION NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORAIMPRESION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  DIAINICIOPREPARACION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESINICIOPREPARACION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOINICIOPREPARACION NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORAINICIOPREPARACION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  DIAFINPREPARACION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESFINPREPARACION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOFINPREPARACION NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORAFINPREPARACION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  TIEMPOPREPARACION NUMERIC(9, 0) NOT NULL DEFAULT 0,
  CODIGOPICADOR CHAR(2) NOT NULL DEFAULT ' ',
  DIAINICIOPICADO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESINICIOPICADO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOINICIOPICADO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORAINICIOPICADO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  DIAFINPICADO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESFINPICADO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOFINPICADO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORAFINPICADO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  TIEMPOPICADO NUMERIC(9, 0) NOT NULL DEFAULT 0,
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  MARCAACTUALIZACION VARCHAR(50) NOT NULL DEFAULT ' ',
  -- App-specific columns
  IDEMPOTENCY_TOKEN VARCHAR(128),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'PENDIENTE',
  OPERADOR VARCHAR(50) DEFAULT 'system',
  PANTALLA_ORIGEN VARCHAR(20) DEFAULT 'RUTERO'
);

ALTER TABLE JAVIER.REPARTIDOR_ENTREGAS ADD PRIMARY KEY (ID);

CREATE UNIQUE INDEX JAVIER.UX_REP_ENTREGAS_TOKEN
  ON JAVIER.REPARTIDOR_ENTREGAS (IDEMPOTENCY_TOKEN);

CREATE UNIQUE INDEX JAVIER.UX_REP_ENTREGAS_OPP
  ON JAVIER.REPARTIDOR_ENTREGAS (SUBEMPRESA, EJERCICIOORDENPREPARACION, NUMEROORDENPREPARACION);

CREATE INDEX JAVIER.IDX_REP_ENTREGAS_REPARTIDOR
  ON JAVIER.REPARTIDOR_ENTREGAS (CODIGOREPARTIDOR, DIAREPARTO, MESREPARTO, ANOREPARTO);

CREATE INDEX JAVIER.IDX_REP_ENTREGAS_ESTADO
  ON JAVIER.REPARTIDOR_ENTREGAS (ESTADOORDENPREPARACION);

CREATE INDEX JAVIER.IDX_REP_ENTREGAS_VEHICULO
  ON JAVIER.REPARTIDOR_ENTREGAS (CODIGOVEHICULO);

-- ---------------------------------------------------------------------------
-- 4. REPARTIDOR_ENTREGA_LINEAS ← DSEDAC.LAC (126 DSEDAC cols + 6 app cols)
-- ---------------------------------------------------------------------------
CREATE TABLE JAVIER.REPARTIDOR_ENTREGA_LINEAS (
  -- DSEDAC.LAC columns (exact match)
  SUBEMPRESAALBARAN CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIOALBARAN NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIEALBARAN CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALALBARAN NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMEROALBARAN NUMERIC(6, 0) NOT NULL DEFAULT 0,
  SECUENCIA NUMERIC(4, 0) NOT NULL DEFAULT 0,
  DIADOCUMENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESDOCUMENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANODOCUMENTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORADOCUMENTO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  CODIGOCLIENTEALBARAN CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOCLIENTEFACTURA CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOCLIENTECADENA CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOVENDEDOR CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOVENDEDORCOBRO CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOPROMOTORPREVENTA CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOCOMERCIAL CHAR(2) NOT NULL DEFAULT ' ',
  CODIGORUTA CHAR(4) NOT NULL DEFAULT ' ',
  CODIGOFORMAPAGO CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOTARIFA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  CODIGOALMACEN NUMERIC(4, 0) NOT NULL DEFAULT 0,
  RECARGOSN CHAR(1) NOT NULL DEFAULT ' ',
  SUBEMPRESADOCUMENTO CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIODOCUMENTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIEDOCUMENTO CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALDOCUMENTO NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMERODOCUMENTO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  TIPOLINEA CHAR(1) NOT NULL DEFAULT ' ',
  TIPOVENTA CHAR(2) NOT NULL DEFAULT ' ',
  CLASELINEA CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOESTIBA CHAR(20) NOT NULL DEFAULT ' ',
  CODIGOLOTE CHAR(30) NOT NULL DEFAULT ' ',
  CODIGOARTICULO CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOCONCEPTOFACTURACION CHAR(3) NOT NULL DEFAULT ' ',
  CODIGOSECCION CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOIVA CHAR(1) NOT NULL DEFAULT ' ',
  DESCRIPCION CHAR(40) NOT NULL DEFAULT ' ',
  CANTIDADENVASESPEDIDOS NUMERIC(7, 2) NOT NULL DEFAULT 0,
  CANTIDADUNIDADESPEDIDAS NUMERIC(10, 5) NOT NULL DEFAULT 0,
  CANTIDADENVASES NUMERIC(7, 2) NOT NULL DEFAULT 0,
  CANTIDADUNIDADES NUMERIC(10, 5) NOT NULL DEFAULT 0,
  PRECIOVENTA NUMERIC(9, 4) NOT NULL DEFAULT 0,
  PORCENTAJEDESCUENTO NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTEDESCUENTOUNIDAD NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTEVENTA NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PRECIOCOSTO NUMERIC(9, 4) NOT NULL DEFAULT 0,
  IMPORTECOSTO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PRECIOMEDIO NUMERIC(9, 4) NOT NULL DEFAULT 0,
  IMPORTEMEDIO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PRECIOTARIFACLIENTE NUMERIC(9, 4) NOT NULL DEFAULT 0,
  PRECIOTARIFA01 NUMERIC(9, 4) NOT NULL DEFAULT 0,
  ORDENPREPARACION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  CODIGODELEGACION CHAR(2) NOT NULL DEFAULT ' ',
  CODIGODESTRUCCIONPRODUCTO CHAR(1) NOT NULL DEFAULT ' ',
  VALORDESTRUCCIONPRODUCTO NUMERIC(9, 4) NOT NULL DEFAULT 0,
  PRECIOKILOS CHAR(1) NOT NULL DEFAULT ' ',
  IMPORTEDESTRUCCIONPRODUCTO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  CODIGOTIPOLOGIA CHAR(2) NOT NULL DEFAULT ' ',
  KILOGRAMOSINCREMENTO NUMERIC(10, 5) NOT NULL DEFAULT 0,
  UNIDADMEDIDA CHAR(10) NOT NULL DEFAULT ' ',
  DIAENTREGA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESENTREGA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOENTREGA NUMERIC(4, 0) NOT NULL DEFAULT 0,
  CODIGOLOCALIZACIONENTREGA CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOSILOENTREGA CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOVEHICULOENTREGA CHAR(10) NOT NULL DEFAULT ' ',
  CANTIDADFIJASN CHAR(1) NOT NULL DEFAULT ' ',
  SECUENCIAORIGEN NUMERIC(4, 0) NOT NULL DEFAULT 0,
  CODIGOTRATAMIENTOMEDICO CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOVETERINARIO CHAR(10) NOT NULL DEFAULT ' ',
  DIASSUPRESION NUMERIC(3, 0) NOT NULL DEFAULT 0,
  OBSERVACIONES CHAR(75) NOT NULL DEFAULT ' ',
  CODIGOPRESENTACION CHAR(10) NOT NULL DEFAULT ' ',
  UNIDADESCAJA NUMERIC(10, 5) NOT NULL DEFAULT 0,
  CODIGOENGORDE CHAR(10) NOT NULL DEFAULT ' ',
  CODIGONAVE CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOREGA CHAR(20) NOT NULL DEFAULT ' ',
  VIAJE CHAR(3) NOT NULL DEFAULT ' ',
  ALTRIXSYNCLOGID NUMERIC(9, 0) NOT NULL DEFAULT 0,
  SITUACION CHAR(2) NOT NULL DEFAULT ' ',
  DIAENTREGAASIGNADA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESENTREGAASIGNADA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOENTREGAASIGNADA NUMERIC(4, 0) NOT NULL DEFAULT 0,
  CODIGORUTAREPARTO CHAR(6) NOT NULL DEFAULT ' ',
  CODIGOTIPOALBARAN CHAR(3) NOT NULL DEFAULT ' ',
  SECUENCIAPEDIDO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  DOSIS NUMERIC(10, 5) NOT NULL DEFAULT 0,
  REFERENCIADOCUMENTO CHAR(20) NOT NULL DEFAULT ' ',
  DIAREFERENCIADOCUMENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESREFERENCIADOCUMENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOREFERENCIADOCUMENTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORAREFERENCIADOCUMENTO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  NUMERORECETAEXTERNA CHAR(20) NOT NULL DEFAULT ' ',
  CANTIDADENVASESRECIBIDOS NUMERIC(7, 2) NOT NULL DEFAULT 0,
  CANTIDADUNIDADESRECIBIDAS NUMERIC(10, 5) NOT NULL DEFAULT 0,
  VENTAMUESTRASN CHAR(1) NOT NULL DEFAULT ' ',
  SITUACIONPDA CHAR(2) NOT NULL DEFAULT ' ',
  PORCENTAJEDESCUENTO02 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  NUMEROELEMENTOS NUMERIC(9, 0) NOT NULL DEFAULT 0,
  IDENTIFICACIONELEMENTOS CHAR(40) NOT NULL DEFAULT ' ',
  CODIGOPROVEEDOR CHAR(10) NOT NULL DEFAULT ' ',
  DOCUMENTO CHAR(20) NOT NULL DEFAULT ' ',
  SUBEMPRESAFACTURA CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIOFACTURA NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIEFACTURA CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALFACTURA NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMEROFACTURA NUMERIC(6, 0) NOT NULL DEFAULT 0,
  LISTADO CHAR(10) NOT NULL DEFAULT ' ',
  CANTIDADENVASESPDTEABONO NUMERIC(7, 2) NOT NULL DEFAULT 0,
  CANTIDADUNIDADESPDTEABONO NUMERIC(10, 5) NOT NULL DEFAULT 0,
  REFERENCIADOCUMENTOSIMPLIFIC CHAR(20) NOT NULL DEFAULT ' ',
  CANTIDADPIEZAS NUMERIC(10, 5) NOT NULL DEFAULT 0,
  CANTIDADPALES NUMERIC(9, 0) NOT NULL DEFAULT 0,
  NUMEROPROYECTO CHAR(20) NOT NULL DEFAULT ' ',
  CODIGOEMPLEADOENTREGA CHAR(10) NOT NULL DEFAULT ' ',
  HORAENTREGA NUMERIC(6, 0) NOT NULL DEFAULT 0,
  CODIGOPROMOCIONREGALO CHAR(10) NOT NULL DEFAULT ' ',
  SECUENCIAPROMOCIONREGALO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  CAJASUNIDADES CHAR(1) NOT NULL DEFAULT ' ',
  CODIGOSECCIONEXPLOTACION CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOFASE CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOOPERACION CHAR(10) NOT NULL DEFAULT ' ',
  SECUENCIAMANOOBRA NUMERIC(4, 0) NOT NULL DEFAULT 0,
  CODIGOKIT CHAR(10) NOT NULL DEFAULT ' ',
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  MARCAACTUALIZACION VARCHAR(50) NOT NULL DEFAULT ' ',
  -- App-specific columns
  IDEMPOTENCY_TOKEN VARCHAR(128),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'PENDIENTE',
  OPERADOR VARCHAR(50) DEFAULT 'system',
  PANTALLA_ORIGEN VARCHAR(20) DEFAULT 'RUTERO'
);

ALTER TABLE JAVIER.REPARTIDOR_ENTREGA_LINEAS ADD PRIMARY KEY (ID);

CREATE UNIQUE INDEX JAVIER.UX_REP_LINEAS_TOKEN
  ON JAVIER.REPARTIDOR_ENTREGA_LINEAS (IDEMPOTENCY_TOKEN);

CREATE UNIQUE INDEX JAVIER.UX_REP_LINEAS_ALBARAN_SEQ
  ON JAVIER.REPARTIDOR_ENTREGA_LINEAS (SUBEMPRESAALBARAN, EJERCICIOALBARAN, SERIEALBARAN, TERMINALALBARAN, NUMEROALBARAN, SECUENCIA);

CREATE INDEX JAVIER.IDX_REP_LINEAS_ALBARAN
  ON JAVIER.REPARTIDOR_ENTREGA_LINEAS (SUBEMPRESAALBARAN, EJERCICIOALBARAN, SERIEALBARAN, TERMINALALBARAN, NUMEROALBARAN);

CREATE INDEX JAVIER.IDX_REP_LINEAS_ARTICULO
  ON JAVIER.REPARTIDOR_ENTREGA_LINEAS (CODIGOARTICULO);

CREATE INDEX JAVIER.IDX_REP_LINEAS_SITUACION
  ON JAVIER.REPARTIDOR_ENTREGA_LINEAS (SITUACION, SITUACIONPDA);

CREATE INDEX JAVIER.IDX_REP_LINEAS_ENTREGA
  ON JAVIER.REPARTIDOR_ENTREGA_LINEAS (DIAENTREGA, MESENTREGA, ANOENTREGA);

-- ---------------------------------------------------------------------------
-- 5. REPARTIDOR_FIRMAS ← DSEDAC.CACFIRMAS (17 DSEDAC cols + 6 app cols)
-- ---------------------------------------------------------------------------
CREATE TABLE JAVIER.REPARTIDOR_FIRMAS (
  -- DSEDAC.CACFIRMAS columns (exact match)
  SUBEMPRESAALBARAN CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIOALBARAN NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIEALBARAN CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALALBARAN NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMEROALBARAN NUMERIC(6, 0) NOT NULL DEFAULT 0,
  CODIGOVENDEDOR CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOUSUARIO CHAR(2) NOT NULL DEFAULT ' ',
  DIA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MES NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORA NUMERIC(6, 0) NOT NULL DEFAULT 0,
  FIRMANOMBRE CHAR(100) NOT NULL DEFAULT ' ',
  FIRMADNI CHAR(20) NOT NULL DEFAULT ' ',
  FIRMABASE64 CLOB(1M) NOT NULL DEFAULT ' ',
  LATITUD NUMERIC(15, 6) NOT NULL DEFAULT 0,
  LONGITUD NUMERIC(15, 6) NOT NULL DEFAULT 0,
  TIPOREGISTRO CHAR(1) NOT NULL DEFAULT ' ',
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  MARCAACTUALIZACION VARCHAR(50) NOT NULL DEFAULT ' ',
  -- App-specific columns
  IDEMPOTENCY_TOKEN VARCHAR(128),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'CAPTURADA',
  OPERADOR VARCHAR(50) DEFAULT 'system',
  PANTALLA_ORIGEN VARCHAR(20) DEFAULT 'ENTREGA'
);

ALTER TABLE JAVIER.REPARTIDOR_FIRMAS ADD PRIMARY KEY (ID);

CREATE UNIQUE INDEX JAVIER.UX_REP_FIRMAS_TOKEN
  ON JAVIER.REPARTIDOR_FIRMAS (IDEMPOTENCY_TOKEN);

CREATE UNIQUE INDEX JAVIER.UX_REP_FIRMAS_ALBARAN
  ON JAVIER.REPARTIDOR_FIRMAS (SUBEMPRESAALBARAN, EJERCICIOALBARAN, SERIEALBARAN, TERMINALALBARAN, NUMEROALBARAN, TIPOREGISTRO);

CREATE INDEX JAVIER.IDX_REP_FIRMAS_ALBARAN
  ON JAVIER.REPARTIDOR_FIRMAS (SUBEMPRESAALBARAN, EJERCICIOALBARAN, SERIEALBARAN, TERMINALALBARAN, NUMEROALBARAN);

CREATE INDEX JAVIER.IDX_REP_FIRMAS_VENDEDOR
  ON JAVIER.REPARTIDOR_FIRMAS (CODIGOVENDEDOR, DIA, MES, ANO);

-- ---------------------------------------------------------------------------
-- 6. REPARTIDOR_OBJETIVOS ← DSEDAC.CMV (9 DSEDAC cols + 6 app cols)
-- ---------------------------------------------------------------------------
CREATE TABLE JAVIER.REPARTIDOR_OBJETIVOS (
  -- DSEDAC.CMV columns (exact match)
  CODIGOVENDEDOR CHAR(2) NOT NULL DEFAULT ' ',
  PORCENTAJEPREVENTA NUMERIC(5, 2) NOT NULL DEFAULT 0,
  PORCENTAJEREPARTO NUMERIC(5, 2) NOT NULL DEFAULT 0,
  PORCENTAJEOBJETIVO NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTEOBJETIVO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJEPREVENTAENDOSO NUMERIC(5, 2) NOT NULL DEFAULT 0,
  PORCENTAJEREPARTOENDOSO NUMERIC(5, 2) NOT NULL DEFAULT 0,
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  MARCAACTUALIZACION VARCHAR(50) NOT NULL DEFAULT ' ',
  -- App-specific columns
  IDEMPOTENCY_TOKEN VARCHAR(128),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'ACTIVO',
  OPERADOR VARCHAR(50) DEFAULT 'system',
  PANTALLA_ORIGEN VARCHAR(20) DEFAULT 'OBJETIVOS'
);

ALTER TABLE JAVIER.REPARTIDOR_OBJETIVOS ADD PRIMARY KEY (ID);

CREATE UNIQUE INDEX JAVIER.UX_REP_OBJETIVOS_TOKEN
  ON JAVIER.REPARTIDOR_OBJETIVOS (IDEMPOTENCY_TOKEN);

CREATE UNIQUE INDEX JAVIER.UX_REP_OBJETIVOS_VENDEDOR
  ON JAVIER.REPARTIDOR_OBJETIVOS (CODIGOVENDEDOR);

CREATE INDEX JAVIER.IDX_REP_OBJETIVOS_PORCENTAJE
  ON JAVIER.REPARTIDOR_OBJETIVOS (PORCENTAJEOBJETIVO, PORCENTAJEREPARTO);

-- ---------------------------------------------------------------------------
-- 7. DELIVERY_STATUS ← DSEDAC.CPC (140 DSEDAC cols + 6 app cols)
-- ---------------------------------------------------------------------------
CREATE TABLE JAVIER.DELIVERY_STATUS (
  -- DSEDAC.CPC columns (exact match)
  SUBEMPRESAPEDIDO CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIOPEDIDO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIEPEDIDO CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALPEDIDO NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMEROPEDIDO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  DIADOCUMENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESDOCUMENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANODOCUMENTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORADOCUMENTO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  CODIGOCLIENTEALBARAN CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOCLIENTEFACTURA CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOCLIENTECADENA CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOVENDEDOR CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOVENDEDORCOBRO CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOPROMOTORPREVENTA CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOCOMERCIAL CHAR(2) NOT NULL DEFAULT ' ',
  CODIGORUTA CHAR(4) NOT NULL DEFAULT ' ',
  CODIGOFORMAPAGO CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOTARIFA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  CODIGOALMACEN NUMERIC(4, 0) NOT NULL DEFAULT 0,
  RECARGOSN CHAR(1) NOT NULL DEFAULT ' ',
  IMPORTEBASEIMPONIBLEBRUTA1 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBASEIMPONIBLE1 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJEIVA1 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTEIVA1 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJERECARGO1 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTERECARGO1 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBASEIMPONIBLEBRUTA2 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBASEIMPONIBLE2 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJEIVA2 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTEIVA2 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJERECARGO2 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTERECARGO2 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBASEIMPONIBLEBRUTA3 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBASEIMPONIBLE3 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJEIVA3 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTEIVA3 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJERECARGO3 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTERECARGO3 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBASEIMPONIBLEBRUTA4 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBASEIMPONIBLE4 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJEIVA4 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTEIVA4 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJERECARGO4 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTERECARGO4 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBASEIMPONIBLEBRUTA5 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBASEIMPONIBLE5 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJEIVA5 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTEIVA5 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJERECARGO5 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTERECARGO5 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTETOTAL NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTECOSTO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEMARGEN NUMERIC(10, 2) NOT NULL DEFAULT 0,
  PORCENTAJEDESCUENTO1 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  PORCENTAJEDESCUENTO2 NUMERIC(5, 2) NOT NULL DEFAULT 0,
  IMPORTEBRUTO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEDEVOLUCION NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEDESCUENTO1 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEDESCUENTO2 NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBONIFICACION NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTESINCARGO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  EMPRESACONTABLE CHAR(2) NOT NULL DEFAULT ' ',
  SITUACIONALBARAN CHAR(1) NOT NULL DEFAULT ' ',
  SUBEMPRESAALBARAN CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIOALBARAN NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIEALBARAN CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALALBARAN NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMEROALBARAN NUMERIC(6, 0) NOT NULL DEFAULT 0,
  SITUACIONCARGA CHAR(1) NOT NULL DEFAULT ' ',
  SUBEMPRESACARGA CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIOCARGA NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIECARGA CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALCARGA NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMEROCARGA NUMERIC(6, 0) NOT NULL DEFAULT 0,
  SITUACIONPEDIDO CHAR(1) NOT NULL DEFAULT ' ',
  CODIGOSUBDISTRIBUIDOR CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOOPERACION CHAR(1) NOT NULL DEFAULT ' ',
  OBSERVACION1 CHAR(50) NOT NULL DEFAULT ' ',
  OBSERVACION2 CHAR(50) NOT NULL DEFAULT ' ',
  DIACREACION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESCREACION NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOCREACION NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORACREACION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  LATITUD NUMERIC(15, 6) NOT NULL DEFAULT 0,
  LONGITUD NUMERIC(15, 6) NOT NULL DEFAULT 0,
  EJERCICIOORDENPREPARACION NUMERIC(4, 0) NOT NULL DEFAULT 0,
  NUMEROORDENPREPARACION NUMERIC(6, 0) NOT NULL DEFAULT 0,
  ESTADOORDENPREPARACION CHAR(1) NOT NULL DEFAULT ' ',
  CODIGOVENDEDORUSUARIO CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOVENDEDORPUNTEO CHAR(2) NOT NULL DEFAULT ' ',
  EFECTIVOTALON CHAR(1) NOT NULL DEFAULT ' ',
  IMPORTECOBRADO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEREDONDEO NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IMPORTEBONIFICACIONDIRECTA NUMERIC(10, 2) NOT NULL DEFAULT 0,
  IDENTICKETCLIENTE CHAR(15) NOT NULL DEFAULT ' ',
  IDENTICKET CHAR(15) NOT NULL DEFAULT ' ',
  LINEASKILOSN CHAR(1) NOT NULL DEFAULT ' ',
  PROCESADOSN CHAR(1) NOT NULL DEFAULT ' ',
  REMOTOSN CHAR(1) NOT NULL DEFAULT ' ',
  DIALLEGADA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESLLEGADA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOLLEGADA NUMERIC(4, 0) NOT NULL DEFAULT 0,
  HORALLEGADA NUMERIC(6, 0) NOT NULL DEFAULT 0,
  CODIGOUSUARIO CHAR(10) NOT NULL DEFAULT ' ',
  DIAPRIMERPAGO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESPRIMERPAGO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOPRIMERPAGO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  CODIGOTIPOPEDIDO CHAR(3) NOT NULL DEFAULT ' ',
  REFERENCIAPEDIDOCLIENTE CHAR(17) NOT NULL DEFAULT ' ',
  TRAZABILIDADPEDIDO CHAR(30) NOT NULL DEFAULT ' ',
  CODIGOLOCALIZACIONENTREGA CHAR(10) NOT NULL DEFAULT ' ',
  DIASERVICIO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESSERVICIO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOSERVICIO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  CODIGODELEGACION CHAR(2) NOT NULL DEFAULT ' ',
  ESTADOPRODUCCION CHAR(10) NOT NULL DEFAULT ' ',
  ESTADOPRODUCCIONWEB CHAR(10) NOT NULL DEFAULT ' ',
  CONFORMADOSN CHAR(1) NOT NULL DEFAULT ' ',
  FACTORCONVERSION NUMERIC(10, 4) NOT NULL DEFAULT 0,
  DIAESTADO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESESTADO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOESTADO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SUBEMPRESAPROYECTO CHAR(3) NOT NULL DEFAULT ' ',
  EJERCICIOPROYECTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  SERIEPROYECTO CHAR(1) NOT NULL DEFAULT ' ',
  TERMINALPROYECTO NUMERIC(3, 0) NOT NULL DEFAULT 0,
  NUMEROPROYECTO NUMERIC(6, 0) NOT NULL DEFAULT 0,
  MATRICULA CHAR(20) NOT NULL DEFAULT ' ',
  IMPRESOSN CHAR(1) NOT NULL DEFAULT ' ',
  DIAIMPRESO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESIMPRESO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOIMPRESO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  ENVIADOSN CHAR(1) NOT NULL DEFAULT ' ',
  DIAENVIADO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESENVIADO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOENVIADO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  NUMEROBULTOS NUMERIC(5, 0) NOT NULL DEFAULT 0,
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  MARCAACTUALIZACION VARCHAR(50) NOT NULL DEFAULT ' ',
  -- App-specific columns
  IDEMPOTENCY_TOKEN VARCHAR(128),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'PENDIENTE',
  OPERADOR VARCHAR(50) DEFAULT 'system',
  PANTALLA_ORIGEN VARCHAR(20) DEFAULT 'RUTERO'
);

ALTER TABLE JAVIER.DELIVERY_STATUS ADD PRIMARY KEY (ID);

CREATE UNIQUE INDEX JAVIER.UX_DELIVERY_STATUS_TOKEN
  ON JAVIER.DELIVERY_STATUS (IDEMPOTENCY_TOKEN);

CREATE UNIQUE INDEX JAVIER.UX_DELIVERY_STATUS_PEDIDO
  ON JAVIER.DELIVERY_STATUS (SUBEMPRESAPEDIDO, EJERCICIOPEDIDO, SERIEPEDIDO, TERMINALPEDIDO, NUMEROPEDIDO);

CREATE INDEX JAVIER.IDX_DELIVERY_STATUS_REP
  ON JAVIER.DELIVERY_STATUS (CODIGOVENDEDOR, DIADOCUMENTO, MESDOCUMENTO, ANODOCUMENTO);

CREATE INDEX JAVIER.IDX_DELIVERY_STATUS_SITUACION
  ON JAVIER.DELIVERY_STATUS (SITUACIONPEDIDO, SITUACIONALBARAN);

CREATE INDEX JAVIER.IDX_DELIVERY_STATUS_CLIENTE
  ON JAVIER.DELIVERY_STATUS (CODIGOCLIENTEALBARAN);

CREATE INDEX JAVIER.IDX_DELIVERY_STATUS_RUTA
  ON JAVIER.DELIVERY_STATUS (CODIGORUTA);

CREATE INDEX JAVIER.IDX_DELIVERY_STATUS_OPP
  ON JAVIER.DELIVERY_STATUS (EJERCICIOORDENPREPARACION, NUMEROORDENPREPARACION);

-- ---------------------------------------------------------------------------
-- 8. CLIENT_SIGNERS ← DSEDAC.CLI (50 DSEDAC cols + 6 app cols)
-- ---------------------------------------------------------------------------
CREATE TABLE JAVIER.CLIENT_SIGNERS (
  -- DSEDAC.CLI columns (exact match)
  CODIGOCLIENTE CHAR(10) NOT NULL DEFAULT ' ',
  NOMBRECLIENTE CHAR(60) NOT NULL DEFAULT ' ',
  DIRECCION CHAR(60) NOT NULL DEFAULT ' ',
  CODIGOPOSTAL CHAR(5) NOT NULL DEFAULT ' ',
  SECUENCIACODIGOPOSTAL CHAR(4) NOT NULL DEFAULT ' ',
  POBLACION CHAR(40) NOT NULL DEFAULT ' ',
  PROVINCIA CHAR(34) NOT NULL DEFAULT ' ',
  APARTADOCORREOS CHAR(6) NOT NULL DEFAULT ' ',
  NIF CHAR(20) NOT NULL DEFAULT ' ',
  TELEFONO1 CHAR(20) NOT NULL DEFAULT ' ',
  TELEFONO2 CHAR(20) NOT NULL DEFAULT ' ',
  TELEFONOFAX CHAR(20) NOT NULL DEFAULT ' ',
  TIPOEMPRESA CHAR(35) NOT NULL DEFAULT ' ',
  OBSERVACIONESEMPRESA CHAR(34) NOT NULL DEFAULT ' ',
  OBSERVACIONES1 CHAR(60) NOT NULL DEFAULT ' ',
  OBSERVACIONES2 CHAR(60) NOT NULL DEFAULT ' ',
  OBSERVACIONES3 CHAR(60) NOT NULL DEFAULT ' ',
  CLAVE1 CHAR(6) NOT NULL DEFAULT ' ',
  CLAVE2 CHAR(6) NOT NULL DEFAULT ' ',
  RECARGOSN CHAR(1) NOT NULL DEFAULT ' ',
  DIAALTA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESALTA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOALTA NUMERIC(4, 0) NOT NULL DEFAULT 0,
  DIABAJA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESBAJA NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOBAJA NUMERIC(4, 0) NOT NULL DEFAULT 0,
  DIAINICIOVACACIONES NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESINICIOVACACIONES NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOINICIOVACACIONES NUMERIC(4, 0) NOT NULL DEFAULT 0,
  DIAFINALVACACIONES NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESFINALVACACIONES NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANOFINALVACACIONES NUMERIC(4, 0) NOT NULL DEFAULT 0,
  NOMBREALTERNATIVO CHAR(60) NOT NULL DEFAULT ' ',
  EXENTOIVASN CHAR(1) NOT NULL DEFAULT ' ',
  CODIGORUTA CHAR(4) NOT NULL DEFAULT ' ',
  PERSONACONTACTO CHAR(25) NOT NULL DEFAULT ' ',
  DIANACIMIENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  MESNACIMIENTO NUMERIC(2, 0) NOT NULL DEFAULT 0,
  ANONACIMIENTO NUMERIC(4, 0) NOT NULL DEFAULT 0,
  CODIGODELEGACION CHAR(2) NOT NULL DEFAULT ' ',
  CODIGOCLIENTEENLAZADO CHAR(10) NOT NULL DEFAULT ' ',
  CODIGOIVA CHAR(1) NOT NULL DEFAULT ' ',
  CODIGOIDIOMA CHAR(6) NOT NULL DEFAULT ' ',
  CODIGOMONEDA CHAR(6) NOT NULL DEFAULT ' ',
  CODIGOPAIS CHAR(2) NOT NULL DEFAULT ' ',
  INTRACOMUNITARIOSN CHAR(1) NOT NULL DEFAULT ' ',
  CLAVELINEAFACTURA CHAR(2) NOT NULL DEFAULT ' ',
  EXPORTACIONSN CHAR(1) NOT NULL DEFAULT ' ',
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  MARCAACTUALIZACION VARCHAR(50) NOT NULL DEFAULT ' ',
  -- App-specific columns
  IDEMPOTENCY_TOKEN VARCHAR(128),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'ACTIVO',
  OPERADOR VARCHAR(50) DEFAULT 'system',
  PANTALLA_ORIGEN VARCHAR(20) DEFAULT 'CLIENTES'
);

ALTER TABLE JAVIER.CLIENT_SIGNERS ADD PRIMARY KEY (ID);

CREATE UNIQUE INDEX JAVIER.UX_CLIENT_SIGNERS_TOKEN
  ON JAVIER.CLIENT_SIGNERS (IDEMPOTENCY_TOKEN);

CREATE UNIQUE INDEX JAVIER.UX_CLIENT_SIGNERS_CODIGO
  ON JAVIER.CLIENT_SIGNERS (CODIGOCLIENTE);

CREATE INDEX JAVIER.IDX_CLIENT_SIGNERS_NOMBRE
  ON JAVIER.CLIENT_SIGNERS (NOMBRECLIENTE);

CREATE INDEX JAVIER.IDX_CLIENT_SIGNERS_RUTA
  ON JAVIER.CLIENT_SIGNERS (CODIGORUTA);

CREATE INDEX JAVIER.IDX_CLIENT_SIGNERS_POBLACION
  ON JAVIER.CLIENT_SIGNERS (POBLACION, PROVINCIA);

-- ============================================================================
-- 9. REPARTIDOR_FINANCIAL_BALANCES (app-only table)
-- ============================================================================
CREATE TABLE JAVIER.REPARTIDOR_FINANCIAL_BALANCES (
  CODIGOVENDEDOR VARCHAR(20) NOT NULL PRIMARY KEY,
  SALDO_PENDIENTE DECIMAL(15, 2) NOT NULL DEFAULT 0,
  UPDATED_BY VARCHAR(50) NOT NULL DEFAULT 'system',
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX JAVIER.IDX_REP_FIN_SALDO
  ON JAVIER.REPARTIDOR_FINANCIAL_BALANCES (SALDO_PENDIENTE);

-- ============================================================================
-- 10. REPARTIDOR_COMMISSION_TIERS (app-only table)
-- ============================================================================
CREATE TABLE JAVIER.REPARTIDOR_COMMISSION_TIERS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  THRESHOLD_PCT DECIMAL(7, 3) NOT NULL,
  COMMISSION_PCT DECIMAL(7, 3) NOT NULL,
  SORT_ORDER INTEGER NOT NULL,
  ACTIVE_SN CHAR(1) NOT NULL DEFAULT 'S',
  CREATED_BY VARCHAR(50) NOT NULL DEFAULT 'migration',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(50),
  UPDATED_AT TIMESTAMP,
  CHECK (ACTIVE_SN IN ('S', 'N'))
);

CREATE INDEX JAVIER.IDX_REP_COMM_TIERS_ACTIVE
  ON JAVIER.REPARTIDOR_COMMISSION_TIERS (ACTIVE_SN, SORT_ORDER);

-- ============================================================================
-- 11. REPARTIDOR_LIQUIDACION_EMAILS (app-only table)
-- ============================================================================
CREATE TABLE JAVIER.REPARTIDOR_LIQUIDACION_EMAILS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CODIGOVENDEDOR VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  LIQUIDACION_NUM NUMERIC(6, 0),
  LIQUIDACION_EJERCICIO NUMERIC(4, 0),
  SENT_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'PENDING',
  ERROR_MSG VARCHAR(500),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX JAVIER.IDX_REP_LIQ_EMAILS_VENDEDOR
  ON JAVIER.REPARTIDOR_LIQUIDACION_EMAILS (CODIGOVENDEDOR);

CREATE INDEX JAVIER.IDX_REP_LIQ_EMAILS_STATUS
  ON JAVIER.REPARTIDOR_LIQUIDACION_EMAILS (STATUS, SENT_AT);

-- ============================================================================
-- PHASE 4: VERIFICATION QUERIES
-- ============================================================================

-- Verify column counts match DSEDAC + app columns
SELECT
  TABLE_NAME,
  COUNT(*) AS COLUMN_COUNT,
  CASE TABLE_NAME
    WHEN 'REPARTIDOR_COBROS'            THEN 112  -- 104 DSEDAC (incl ID+MARCA) + 8 app
    WHEN 'REPARTIDOR_LIQUIDACION_OPS'   THEN 38   -- 32 DSEDAC (incl ID+MARCA) + 6 app
    WHEN 'REPARTIDOR_ENTREGAS'          THEN 50   -- 44 DSEDAC (incl ID+MARCA) + 6 app
    WHEN 'REPARTIDOR_ENTREGA_LINEAS'    THEN 132  -- 126 DSEDAC (incl ID+MARCA) + 6 app
    WHEN 'REPARTIDOR_FIRMAS'            THEN 25   -- 17 DSEDAC + ID + MARCA + 6 app
    WHEN 'REPARTIDOR_OBJETIVOS'         THEN 15   -- 9 DSEDAC (incl ID+MARCA) + 6 app
    WHEN 'DELIVERY_STATUS'              THEN 148  -- 140 DSEDAC (incl ID+MARCA) + 8 app
    WHEN 'CLIENT_SIGNERS'               THEN 56   -- 50 DSEDAC (incl ID+MARCA) + 6 app
    WHEN 'REPARTIDOR_FINANCIAL_BALANCES' THEN 4
    WHEN 'REPARTIDOR_COMMISSION_TIERS'  THEN 9
    WHEN 'REPARTIDOR_LIQUIDACION_EMAILS' THEN 9
    ELSE 0
  END AS EXPECTED_COUNT,
  CASE
    WHEN COUNT(*) = CASE TABLE_NAME
      WHEN 'REPARTIDOR_COBROS'            THEN 112
      WHEN 'REPARTIDOR_LIQUIDACION_OPS'   THEN 38
      WHEN 'REPARTIDOR_ENTREGAS'          THEN 50
      WHEN 'REPARTIDOR_ENTREGA_LINEAS'    THEN 132
      WHEN 'REPARTIDOR_FIRMAS'            THEN 25
      WHEN 'REPARTIDOR_OBJETIVOS'         THEN 15
      WHEN 'DELIVERY_STATUS'              THEN 148
      WHEN 'CLIENT_SIGNERS'               THEN 56
      WHEN 'REPARTIDOR_FINANCIAL_BALANCES' THEN 4
      WHEN 'REPARTIDOR_COMMISSION_TIERS'  THEN 9
      WHEN 'REPARTIDOR_LIQUIDACION_EMAILS' THEN 9
      ELSE 0
    END THEN 'OK'
    ELSE 'MISMATCH'
  END AS STATUS
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN (
    'REPARTIDOR_COBROS',
    'REPARTIDOR_LIQUIDACION_OPS',
    'REPARTIDOR_ENTREGAS',
    'REPARTIDOR_ENTREGA_LINEAS',
    'REPARTIDOR_FIRMAS',
    'REPARTIDOR_OBJETIVOS',
    'DELIVERY_STATUS',
    'CLIENT_SIGNERS',
    'REPARTIDOR_FINANCIAL_BALANCES',
    'REPARTIDOR_COMMISSION_TIERS',
    'REPARTIDOR_LIQUIDACION_EMAILS'
  )
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME;

-- Verify backup tables exist
SELECT TABLE_NAME, TABLE_TEXT
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME LIKE 'BKP_%_20260427'
ORDER BY TABLE_NAME;

-- ============================================================================
-- END OF MIGRATION 024
-- ============================================================================
