-- 025_pedidos_reparto_linkage.sql
-- Adds delivery-date and provisional truck linkage fields to JAVIER.PEDIDOS_CAB.
--
-- DB2/i note: run statements one by one in ACS or deployment tooling.
-- If a column already exists, ignore SQL0205/duplicate-column errors.

ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN FECHAREPARTO DATE;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN DIAREPARTO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN MESREPARTO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ANOREPARTO NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOREPARTIDOR CHAR(2) DEFAULT ' ';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOVEHICULO CHAR(10) DEFAULT ' ';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN RUTA VARCHAR(10) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN DIASREPARTO VARCHAR(80) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN REPARTO_VALIDADO_SN CHAR(1) DEFAULT 'N';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN REPARTO_VALIDADO_AT TIMESTAMP;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN TARGET_SCHEMA CHAR(10) DEFAULT 'JAVIER';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SYNC_STATUS VARCHAR(16) DEFAULT 'LOCAL';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SYNC_AT TIMESTAMP;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SYSTEM_SUBEMPRESAPEDIDO CHAR(3) DEFAULT ' ';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SYSTEM_EJERCICIOPEDIDO NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SYSTEM_SERIEPEDIDO CHAR(1) DEFAULT ' ';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SYSTEM_TERMINALPEDIDO NUMERIC(3) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SYSTEM_NUMEROPEDIDO NUMERIC(6) DEFAULT 0;

-- Optional indexes for dispatch review. Ignore duplicate-index errors if present.
CREATE INDEX JAVIER.IX_PEDIDOS_CAB_REPARTO_FECHA
  ON JAVIER.PEDIDOS_CAB (ANOREPARTO, MESREPARTO, DIAREPARTO);

CREATE INDEX JAVIER.IX_PEDIDOS_CAB_REPARTO_CAMION
  ON JAVIER.PEDIDOS_CAB (CODIGOVEHICULO, CODIGOREPARTIDOR);
