-- ============================================================================
-- Migration 026: Fixes inmediatos detectados por erp_diff_condensed.js (2026-05-15)
-- ============================================================================
-- Resuelve:
--   1. JAVIER.BOLSA_COMERCIAL no existe en produccion (la app no puede grabar)
--   2. JAVIER.CUENTAS_LIQUIDACION no existe en produccion
--   3. PEDIDOS_CAB.IMPORTETOTAL/COSTO/MARGEN tipo distinto a DSEDAC.CPC:
--      JAVIER usa NUMERIC(11,2), DSEDAC.CPC usa NUMERIC(10,2). Rompe export
--      si los importes superan 99.999.999,99 EUR (caso teorico).
--   4. JAVIER.V_ENTREGAS_HOY y JAVIER.V_COMISIONES_REPARTIDOR no existen,
--      pero el codigo del backend las referencia.
--
-- Idempotente: si una tabla/vista ya existe, el bloque falla con SQLSTATE 42710
-- (objeto duplicado) y el siguiente continua. En DB2 for i, los errores no
-- detienen el script si se ejecuta con -tf y "STOP_ON_ERROR=N" o similar.
-- En psql/db2 cli usar `;` como delimitador.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. JAVIER.BOLSA_COMERCIAL
-- ----------------------------------------------------------------------------
-- INTENTIONAL: bolsa siempre en JAVIER, incluso en produccion. NO usar APP_SCHEMA.
CREATE TABLE JAVIER.BOLSA_COMERCIAL (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CODIGOVENDEDOR VARCHAR(10) NOT NULL,
  EJERCICIO NUMERIC(4) NOT NULL,
  MES NUMERIC(2) NOT NULL,
  LIMITE_PCT DECIMAL(5,2) DEFAULT 3.00,
  LIMITE_IMPORTE DECIMAL(11,2) DEFAULT 0,
  SALDO_DISPONIBLE DECIMAL(11,2) DEFAULT 0,
  CONSUMIDO DECIMAL(11,2) DEFAULT 0,
  ACUMULADO DECIMAL(11,2) DEFAULT 0,
  CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  CONSTRAINT UQ_BOLSA_VND_MES UNIQUE (CODIGOVENDEDOR, EJERCICIO, MES)
);

CREATE INDEX JAVIER.IDX_BOLSA_VND ON JAVIER.BOLSA_COMERCIAL (CODIGOVENDEDOR, EJERCICIO);

-- ----------------------------------------------------------------------------
-- 2. JAVIER.CUENTAS_LIQUIDACION
-- ----------------------------------------------------------------------------
CREATE TABLE JAVIER.CUENTAS_LIQUIDACION (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CODIGO_REPARTIDOR VARCHAR(10) NOT NULL,
  EJERCICIO NUMERIC(4) NOT NULL,
  SALDO_ACUMULADO DECIMAL(11,2) DEFAULT 0,
  ULTIMO_CIERRE DATE,
  ULTIMO_TOKEN VARCHAR(128),
  NUM_CIERRES INTEGER DEFAULT 0,
  TOTAL_COBRADO_ANO DECIMAL(13,2) DEFAULT 0,
  TOTAL_INGRESADO_ANO DECIMAL(13,2) DEFAULT 0,
  OBSERVACIONES VARCHAR(500),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UQ_CL_REP_EJER UNIQUE (CODIGO_REPARTIDOR, EJERCICIO)
);

CREATE INDEX JAVIER.IDX_CL_REP ON JAVIER.CUENTAS_LIQUIDACION (CODIGO_REPARTIDOR);

-- ----------------------------------------------------------------------------
-- 3. PEDIDOS_CAB: alinear tipos numericos con DSEDAC.CPC (NUMERIC(10,2))
-- ----------------------------------------------------------------------------
-- DB2 for i no permite ALTER COLUMN SET DATA TYPE de NUMERIC(11,2) -> NUMERIC(10,2)
-- en sentido reductor sin truncar. Usamos un staging:
--   a. Anadir columnas _NEW con el tipo destino
--   b. UPDATE copiando valores (sin truncar - garantizado por datos actuales)
--   c. DROP de las viejas; RENAME de las nuevas
-- Si en algun momento hubiera un importe > 99.999.999,99 el UPDATE fallaria.
-- Verifica primero:  SELECT MAX(IMPORTETOTAL), MAX(IMPORTECOSTO), MAX(IMPORTEMARGEN)
--                    FROM JAVIER.PEDIDOS_CAB;

ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTETOTAL_NEW NUMERIC(10,2);
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTECOSTO_NEW NUMERIC(10,2);
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEMARGEN_NEW NUMERIC(10,2);

UPDATE JAVIER.PEDIDOS_CAB SET
  IMPORTETOTAL_NEW = IMPORTETOTAL,
  IMPORTECOSTO_NEW = IMPORTECOSTO,
  IMPORTEMARGEN_NEW = IMPORTEMARGEN;

ALTER TABLE JAVIER.PEDIDOS_CAB DROP COLUMN IMPORTETOTAL;
ALTER TABLE JAVIER.PEDIDOS_CAB DROP COLUMN IMPORTECOSTO;
ALTER TABLE JAVIER.PEDIDOS_CAB DROP COLUMN IMPORTEMARGEN;

-- DB2 for i: RENAME COLUMN no esta soportado en todas las versiones; usamos
-- un segundo paso ADD + UPDATE + DROP si RENAME no funciona.
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTETOTAL NUMERIC(10,2);
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTECOSTO NUMERIC(10,2);
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEMARGEN NUMERIC(10,2);

UPDATE JAVIER.PEDIDOS_CAB SET
  IMPORTETOTAL = IMPORTETOTAL_NEW,
  IMPORTECOSTO = IMPORTECOSTO_NEW,
  IMPORTEMARGEN = IMPORTEMARGEN_NEW;

ALTER TABLE JAVIER.PEDIDOS_CAB DROP COLUMN IMPORTETOTAL_NEW;
ALTER TABLE JAVIER.PEDIDOS_CAB DROP COLUMN IMPORTECOSTO_NEW;
ALTER TABLE JAVIER.PEDIDOS_CAB DROP COLUMN IMPORTEMARGEN_NEW;

-- ----------------------------------------------------------------------------
-- 4. Vistas faltantes
-- ----------------------------------------------------------------------------
-- V_ENTREGAS_HOY: entregas del dia para el dashboard de repartidor.
-- Anclamos a DSEDAC.CAC (cabecera albaran cliente) por dia/mes/ano = hoy.
CREATE VIEW JAVIER.V_ENTREGAS_HOY AS
SELECT
  CAC.SUBEMPRESAALBARAN,
  CAC.EJERCICIOALBARAN,
  CAC.SERIEALBARAN,
  CAC.TERMINALALBARAN,
  CAC.NUMEROALBARAN,
  CAC.DIADOCUMENTO,
  CAC.MESDOCUMENTO,
  CAC.ANODOCUMENTO,
  TRIM(CAC.CODIGOCLIENTEALBARAN) AS CODIGOCLIENTE,
  TRIM(CAC.CODIGOVENDEDOR) AS CODIGOVENDEDOR,
  TRIM(CAC.CODIGOVENDEDORREPARTORUTERO) AS CODIGOREPARTIDOR,
  TRIM(CAC.CODIGORUTA) AS CODIGORUTA,
  CAC.IMPORTETOTAL,
  CAC.SITUACIONALBARAN,
  CAC.MARCALIQUIDADO,
  CAC.DIAENTREGA,
  CAC.MESENTREGA,
  CAC.ANOENTREGA
FROM DSEDAC.CAC CAC
WHERE CAC.ANODOCUMENTO = YEAR(CURRENT_DATE)
  AND CAC.MESDOCUMENTO = MONTH(CURRENT_DATE)
  AND CAC.DIADOCUMENTO = DAY(CURRENT_DATE)
  AND CAC.ELIMINADOSN <> 'S';

-- V_COMISIONES_REPARTIDOR: agregado de cobros liquidados del repartidor
-- para calcular comisiones. Lee de DSEDAC.CVC filtrado por liquidacion.
CREATE VIEW JAVIER.V_COMISIONES_REPARTIDOR AS
SELECT
  TRIM(CVC.CODIGOVENDEDORCOBRO) AS CODIGO_REPARTIDOR,
  CVC.ANOCOBRO AS EJERCICIO,
  CVC.MESCOBRO AS MES,
  COUNT(*) AS NUM_COBROS,
  SUM(CVC.IMPORTECANCELADO) AS TOTAL_COBRADO,
  SUM(CASE WHEN CVC.ANULADOSN = 'S' THEN CVC.IMPORTECANCELADO ELSE 0 END) AS TOTAL_ANULADO
FROM DSEDAC.CVC CVC
WHERE CVC.IMPORTECANCELADO > 0
  AND CVC.ANOCOBRO > 0
  AND CVC.NUMEROLIQUIDACION > 0
GROUP BY TRIM(CVC.CODIGOVENDEDORCOBRO), CVC.ANOCOBRO, CVC.MESCOBRO;

-- ============================================================================
-- VERIFICACION (ejecuta tras correr la migracion)
-- ============================================================================
-- SELECT 'BOLSA_COMERCIAL' AS OBJETO,
--        CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'FALTA' END AS STATUS
-- FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME = 'BOLSA_COMERCIAL'
-- UNION ALL
-- SELECT 'CUENTAS_LIQUIDACION',
--        CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'FALTA' END
-- FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME = 'CUENTAS_LIQUIDACION'
-- UNION ALL
-- SELECT 'V_ENTREGAS_HOY',
--        CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'FALTA' END
-- FROM QSYS2.SYSVIEWS WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME = 'V_ENTREGAS_HOY'
-- UNION ALL
-- SELECT 'V_COMISIONES_REPARTIDOR',
--        CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'FALTA' END
-- FROM QSYS2.SYSVIEWS WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME = 'V_COMISIONES_REPARTIDOR';
-- ============================================================================
