-- 027_team_commission_config.sql
-- Parametriza comisiones de equipo (lider comercial 80 - Almeria)
-- Elimina hardcodeo de miembros, ratio y umbral de crecimiento.

-- Tabla de configuracion de reglas de equipo
CREATE TABLE JAVIER.TEAM_COMMISSION_RULES (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    LEADER_CODE VARCHAR(20) NOT NULL,
    YEAR INTEGER NOT NULL,
    COMMISSION_RATE DECIMAL(5,2) NOT NULL DEFAULT 0.70,
    GROWTH_THRESHOLD_PCT DECIMAL(5,2) NOT NULL DEFAULT 10.00,
    ALL_MUST_QUALIFY CHAR(1) NOT NULL DEFAULT 'Y',
    ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

-- Tabla de miembros de cada equipo
CREATE TABLE JAVIER.TEAM_COMMISSION_MEMBERS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    RULE_ID INTEGER NOT NULL,
    MEMBER_CODE VARCHAR(20) NOT NULL,
    ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (RULE_ID) REFERENCES JAVIER.TEAM_COMMISSION_RULES(ID) ON DELETE CASCADE
);

-- Datos iniciales: equipo de comercial 80 (Almeria)
-- Regla: 0.70% sobre exceso del 10% YoY, todos deben calificar
INSERT INTO JAVIER.TEAM_COMMISSION_RULES
    (LEADER_CODE, YEAR, COMMISSION_RATE, GROWTH_THRESHOLD_PCT, ALL_MUST_QUALIFY, ACTIVE)
VALUES ('80', 2026, 0.70, 10.00, 'Y', 'Y');

-- Miembros del equipo (se vinculan a la regla recien creada)
-- Nota: RULE_ID se resolve con la subquery para evitar hardcodeo del ID
INSERT INTO JAVIER.TEAM_COMMISSION_MEMBERS (RULE_ID, MEMBER_CODE)
SELECT ID, '72' FROM JAVIER.TEAM_COMMISSION_RULES WHERE LEADER_CODE = '80' AND YEAR = 2026;

INSERT INTO JAVIER.TEAM_COMMISSION_MEMBERS (RULE_ID, MEMBER_CODE)
SELECT ID, '73' FROM JAVIER.TEAM_COMMISSION_RULES WHERE LEADER_CODE = '80' AND YEAR = 2026;

INSERT INTO JAVIER.TEAM_COMMISSION_MEMBERS (RULE_ID, MEMBER_CODE)
SELECT ID, '80' FROM JAVIER.TEAM_COMMISSION_RULES WHERE LEADER_CODE = '80' AND YEAR = 2026;

INSERT INTO JAVIER.TEAM_COMMISSION_MEMBERS (RULE_ID, MEMBER_CODE)
SELECT ID, '81' FROM JAVIER.TEAM_COMMISSION_RULES WHERE LEADER_CODE = '80' AND YEAR = 2026;

INSERT INTO JAVIER.TEAM_COMMISSION_MEMBERS (RULE_ID, MEMBER_CODE)
SELECT ID, '83' FROM JAVIER.TEAM_COMMISSION_RULES WHERE LEADER_CODE = '80' AND YEAR = 2026;

INSERT INTO JAVIER.TEAM_COMMISSION_MEMBERS (RULE_ID, MEMBER_CODE)
SELECT ID, '86' FROM JAVIER.TEAM_COMMISSION_RULES WHERE LEADER_CODE = '80' AND YEAR = 2026;
