-- ============================================================================
-- Migration 027: Paridad estructural JAVIER.PEDIDOS_CAB <-> DSEDAC.CPC
-- ============================================================================
-- Anade a JAVIER.PEDIDOS_CAB las columnas que faltan respecto a DSEDAC.CPC,
-- para que la estructura sea identica (mismas columnas, mismos tipos). Esto
-- permite que cualquier proceso del ERP que lea JAVIER.PEDIDOS_CAB encuentre
-- la misma forma que en CPC, y al hacer migracion de datos JAVIER -> DSEDAC
-- no haya transformaciones intermedias.
--
-- Mantiene las columnas EXTRA de JAVIER (CREATED_AT, SYNC_STATUS, ESTADO,
-- ORIGEN, SYSTEM_*, DESCUENTO_GLOBAL, etc.) - estas son metadata local que
-- no existen en CPC pero tampoco molestan.
--
-- ALTER TABLE ADD COLUMN es seguro: en DB2 for i el ADD no rompe datos, solo
-- inicializa la columna nueva con NULL (o el default). Si una columna ya
-- existe el comando falla con SQLSTATE 42711 y el runner lo ignora.
-- ============================================================================

-- Identificadores de cabecera CPC
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SUBEMPRESAPEDIDO CHAR(3) DEFAULT 'GMP';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN EJERCICIOPEDIDO NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN TERMINALPEDIDO NUMERIC(3) DEFAULT 0;

-- Codigos de cliente / vendedor / ruta
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOCLIENTEALBARAN CHAR(10) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOCLIENTEFACTURA CHAR(10) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOCLIENTECADENA CHAR(10) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOVENDEDORCOBRO CHAR(2) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOPROMOTORPREVENTA CHAR(2) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOCOMERCIAL CHAR(2) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGORUTA CHAR(4) DEFAULT '';

-- IVA 1-5 (5 tramos)
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN RECARGOSN CHAR(1) DEFAULT 'N';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBASEIMPONIBLEBRUTA1 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBASEIMPONIBLE1 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJEIVA1 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEIVA1 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJERECARGO1 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTERECARGO1 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBASEIMPONIBLEBRUTA2 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBASEIMPONIBLE2 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJEIVA2 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEIVA2 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJERECARGO2 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTERECARGO2 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBASEIMPONIBLEBRUTA3 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBASEIMPONIBLE3 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJEIVA3 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEIVA3 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJERECARGO3 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTERECARGO3 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBASEIMPONIBLEBRUTA4 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBASEIMPONIBLE4 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJEIVA4 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEIVA4 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJERECARGO4 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTERECARGO4 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBASEIMPONIBLEBRUTA5 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBASEIMPONIBLE5 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJEIVA5 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEIVA5 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJERECARGO5 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTERECARGO5 NUMERIC(10,2) DEFAULT 0;

-- Descuentos y bonificaciones agregadas
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJEDESCUENTO1 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PORCENTAJEDESCUENTO2 NUMERIC(5,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBRUTO NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEDEVOLUCION NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEDESCUENTO1 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEDESCUENTO2 NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBONIFICACION NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEBONIFICACIONDIRECTA NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTESINCARGO NUMERIC(10,2) DEFAULT 0;

-- Empresa / Albaran (relacion al albaran cuando se entrega)
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN EMPRESACONTABLE CHAR(2) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SITUACIONALBARAN CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SUBEMPRESAALBARAN CHAR(3) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN EJERCICIOALBARAN NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SERIEALBARAN CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN TERMINALALBARAN NUMERIC(3) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN NUMEROALBARAN NUMERIC(6) DEFAULT 0;

-- Carga (informacion logistica)
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SITUACIONCARGA CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SUBEMPRESACARGA CHAR(3) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN EJERCICIOCARGA NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SERIECARGA CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN TERMINALCARGA NUMERIC(3) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN NUMEROCARGA NUMERIC(6) DEFAULT 0;

-- Pedido ERP situacion / observaciones / fechas / usuario
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SITUACIONPEDIDO CHAR(1) DEFAULT 'A';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOSUBDISTRIBUIDOR CHAR(10) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOOPERACION CHAR(1) DEFAULT 'V';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN OBSERVACION1 CHAR(50) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN OBSERVACION2 CHAR(50) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN DIACREACION NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN MESCREACION NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ANOCREACION NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN HORACREACION NUMERIC(6) DEFAULT 0;

-- Geolocalizacion (latitud/longitud cliente)
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN LATITUD NUMERIC(15,6) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN LONGITUD NUMERIC(15,6) DEFAULT 0;

-- Orden de preparacion
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN EJERCICIOORDENPREPARACION NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN NUMEROORDENPREPARACION NUMERIC(6) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ESTADOORDENPREPARACION CHAR(1) DEFAULT '';

-- Usuario / vendedor
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOVENDEDORUSUARIO CHAR(2) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOVENDEDORPUNTEO CHAR(2) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOUSUARIO CHAR(10) DEFAULT '';

-- Cobro asociado al pedido
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN EFECTIVOTALON CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTECOBRADO NUMERIC(10,2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEREDONDEO NUMERIC(10,2) DEFAULT 0;

-- Ticket / referencia / control
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IDENTICKETCLIENTE CHAR(15) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IDENTICKET CHAR(15) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN LINEASKILOSN CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN PROCESADOSN CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN REMOTOSN CHAR(1) DEFAULT '';

-- Fechas servicio / llegada / primer pago
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN DIALLEGADA NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN MESLLEGADA NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ANOLLEGADA NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN HORALLEGADA NUMERIC(6) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN DIAPRIMERPAGO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN MESPRIMERPAGO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ANOPRIMERPAGO NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOTIPOPEDIDO CHAR(3) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN REFERENCIAPEDIDOCLIENTE CHAR(17) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN TRAZABILIDADPEDIDO CHAR(30) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGOLOCALIZACIONENTREGA CHAR(10) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN DIASERVICIO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN MESSERVICIO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ANOSERVICIO NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CODIGODELEGACION CHAR(2) DEFAULT '';

-- Estado produccion / produccion web
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ESTADOPRODUCCION CHAR(10) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ESTADOPRODUCCIONWEB CHAR(10) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN CONFORMADOSN CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN FACTORCONVERSION NUMERIC(10,4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN DIAESTADO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN MESESTADO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ANOESTADO NUMERIC(4) DEFAULT 0;

-- Proyecto (vinculacion contable)
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SUBEMPRESAPROYECTO CHAR(3) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN EJERCICIOPROYECTO NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN SERIEPROYECTO CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN TERMINALPROYECTO NUMERIC(3) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN NUMEROPROYECTO NUMERIC(6) DEFAULT 0;

-- Vehiculo + impreso + enviado
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN MATRICULA CHAR(20) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPRESOSN CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN DIAIMPRESO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN MESIMPRESO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ANOIMPRESO NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ENVIADOSN CHAR(1) DEFAULT '';
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN DIAENVIADO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN MESENVIADO NUMERIC(2) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN ANOENVIADO NUMERIC(4) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN NUMEROBULTOS NUMERIC(5) DEFAULT 0;
ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN MARCAACTUALIZACION VARCHAR(50) DEFAULT '';

-- ============================================================================
-- VERIFICACION (tras correr la migracion):
--   SELECT COUNT(*) AS COLS_NEW
--   FROM QSYS2.SYSCOLUMNS
--   WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='PEDIDOS_CAB';
-- ============================================================================
