-- 031_prepare_dsedac_app_buffers.sql
-- Purpose: prepare optional DSEDAC app-buffer tables for DB2_WRITE_SCHEMA=DSEDAC
-- Scope: copy app-buffer table structures from JAVIER only. No data copy. No DROP. No CPC/LPC/CRC mutation.
-- Verified source metadata on 2026-06-22 via QSYS2:
--   JAVIER.PEDIDOS_CAB: 176 columns, 1 identity, 36 defaults
--   JAVIER.PEDIDOS_LIN: 83 columns, 1 identity, 22 defaults
--   JAVIER.PEDIDOS_SEQ: 2 columns, 0 identity, 1 default
--   JAVIER.PEDIDOS_STOCK_RESERVE: 6 columns, 1 identity, 3 defaults
--   JAVIER.COBROS: 43 columns, 0 identity, 2 defaults
--   JAVIER.REPARTIDOR_COBROS: 130 columns, 1 identity, 108 defaults
--   JAVIER.BOLSA_COMERCIAL and JAVIER.MOVIMIENTOS_BOLSA exist, but current code writes them explicitly in JAVIER.
-- Note: CREATE TABLE ... LIKE does not copy indexes. Indexes needed by pedidos/cobros are created below.

--#SET TERMINATOR @

-- =============================
-- 0) PRECHECK: source/target tables
-- =============================
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA IN ('JAVIER', 'DSEDAC')
  AND TABLE_NAME IN (
    'PEDIDOS_CAB', 'PEDIDOS_LIN', 'PEDIDOS_SEQ', 'PEDIDOS_STOCK_RESERVE',
    'PEDIDOS_IDEMPOTENCY', 'COBROS', 'REPARTIDOR_COBROS',
    'BOLSA_COMERCIAL', 'MOVIMIENTOS_BOLSA'
  )
ORDER BY TABLE_SCHEMA, TABLE_NAME@

-- PRECHECK: source structure summary. Expected rows: all except PEDIDOS_IDEMPOTENCY.
SELECT TABLE_NAME,
       COUNT(*) AS COLUMN_COUNT,
       SUM(CASE WHEN IS_IDENTITY = 'YES' THEN 1 ELSE 0 END) AS IDENTITY_COLUMNS,
       SUM(CASE WHEN COLUMN_DEFAULT IS NOT NULL THEN 1 ELSE 0 END) AS DEFAULT_COLUMNS
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN (
    'PEDIDOS_CAB', 'PEDIDOS_LIN', 'PEDIDOS_SEQ', 'PEDIDOS_STOCK_RESERVE',
    'COBROS', 'REPARTIDOR_COBROS', 'BOLSA_COMERCIAL', 'MOVIMIENTOS_BOLSA'
  )
GROUP BY TABLE_NAME
ORDER BY TABLE_NAME@

-- =====================================
-- 1) CREATE missing DSEDAC app buffers
-- =====================================
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM QSYS2.SYSTABLES
    WHERE TABLE_SCHEMA = 'DSEDAC' AND TABLE_NAME = 'PEDIDOS_SEQ'
  ) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE DSEDAC.PEDIDOS_SEQ LIKE JAVIER.PEDIDOS_SEQ INCLUDING COLUMN DEFAULTS';
  END IF;
END@

BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM QSYS2.SYSTABLES
    WHERE TABLE_SCHEMA = 'DSEDAC' AND TABLE_NAME = 'PEDIDOS_CAB'
  ) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE DSEDAC.PEDIDOS_CAB LIKE JAVIER.PEDIDOS_CAB INCLUDING IDENTITY COLUMN ATTRIBUTES INCLUDING COLUMN DEFAULTS';
  END IF;
END@

BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM QSYS2.SYSTABLES
    WHERE TABLE_SCHEMA = 'DSEDAC' AND TABLE_NAME = 'PEDIDOS_LIN'
  ) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE DSEDAC.PEDIDOS_LIN LIKE JAVIER.PEDIDOS_LIN INCLUDING IDENTITY COLUMN ATTRIBUTES INCLUDING COLUMN DEFAULTS';
  END IF;
END@

BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM QSYS2.SYSTABLES
    WHERE TABLE_SCHEMA = 'DSEDAC' AND TABLE_NAME = 'PEDIDOS_STOCK_RESERVE'
  ) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE DSEDAC.PEDIDOS_STOCK_RESERVE LIKE JAVIER.PEDIDOS_STOCK_RESERVE INCLUDING IDENTITY COLUMN ATTRIBUTES INCLUDING COLUMN DEFAULTS';
  END IF;
END@

BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM QSYS2.SYSTABLES
    WHERE TABLE_SCHEMA = 'DSEDAC' AND TABLE_NAME = 'COBROS'
  ) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE DSEDAC.COBROS LIKE JAVIER.COBROS INCLUDING COLUMN DEFAULTS';
  END IF;
END@

BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM QSYS2.SYSTABLES
    WHERE TABLE_SCHEMA = 'DSEDAC' AND TABLE_NAME = 'REPARTIDOR_COBROS'
  ) THEN
    EXECUTE IMMEDIATE 'CREATE TABLE DSEDAC.REPARTIDOR_COBROS LIKE JAVIER.REPARTIDOR_COBROS INCLUDING IDENTITY COLUMN ATTRIBUTES INCLUDING COLUMN DEFAULTS';
  END IF;
END@

-- =====================================
-- 2) CREATE missing DSEDAC indexes
-- =====================================
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_PCAB_CLI') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_PCAB_CLI ON DSEDAC.PEDIDOS_CAB (CODIGOCLIENTE)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_PCAB_VND') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_PCAB_VND ON DSEDAC.PEDIDOS_CAB (CODIGOVENDEDOR)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_PCAB_EST') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_PCAB_EST ON DSEDAC.PEDIDOS_CAB (ESTADO)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_PLIN_PID') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_PLIN_PID ON DSEDAC.PEDIDOS_LIN (PEDIDO_ID)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_PLIN_ART') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_PLIN_ART ON DSEDAC.PEDIDOS_LIN (CODIGOARTICULO)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_PSR_PID') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_PSR_PID ON DSEDAC.PEDIDOS_STOCK_RESERVE (PEDIDO_ID)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_COB_CLI') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_COB_CLI ON DSEDAC.COBROS (CODIGO_CLIENTE)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_COB_IDEM') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_COB_IDEM ON DSEDAC.COBROS (IDEMPOTENCY_TOKEN)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'UX031_REPCOB_TOK') THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX DSEDAC.UX031_REPCOB_TOK ON DSEDAC.REPARTIDOR_COBROS (IDEMPOTENCY_TOKEN)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_REPCOB_DOC') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_REPCOB_DOC ON DSEDAC.REPARTIDOR_COBROS (SUBEMPRESADOCUMENTO, EJERCICIODOCUMENTO, SERIEDOCUMENTO, TERMINALDOCUMENTO, NUMERODOCUMENTO)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_REPCOB_VND') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_REPCOB_VND ON DSEDAC.REPARTIDOR_COBROS (CODIGOVENDEDOR, CODIGOVENDEDORCOBRO)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_REPCOB_LIQ') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_REPCOB_LIQ ON DSEDAC.REPARTIDOR_COBROS (CODIGOVENDEDOR, NUMEROLIQUIDACION, DIACOBRO, MESCOBRO, ANOCOBRO)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA = 'DSEDAC' AND INDEX_NAME = 'IDX031_REPCOB_CLI') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX DSEDAC.IDX031_REPCOB_CLI ON DSEDAC.REPARTIDOR_COBROS (CODIGOCLIENTEALBARAN, CODIGOCLIENTEFACTURA)';
  END IF;
END@

-- ==========================================================
-- 3) OPTIONAL ONLY: bolsa app buffers are not used by current code
-- ==========================================================
-- Current backend/services/bolsa-comercial.service.js writes explicitly to JAVIER.BOLSA_COMERCIAL
-- and JAVIER.MOVIMIENTOS_BOLSA, so DB2_WRITE_SCHEMA=DSEDAC does not require these tables.
-- If that code is changed later to use DB2_WRITE_SCHEMA, create them with the same pattern:
-- BEGIN
--   IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA = 'DSEDAC' AND TABLE_NAME = 'BOLSA_COMERCIAL') THEN
--     EXECUTE IMMEDIATE 'CREATE TABLE DSEDAC.BOLSA_COMERCIAL LIKE JAVIER.BOLSA_COMERCIAL INCLUDING IDENTITY COLUMN ATTRIBUTES INCLUDING COLUMN DEFAULTS';
--   END IF;
-- END@
-- BEGIN
--   IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA = 'DSEDAC' AND TABLE_NAME = 'MOVIMIENTOS_BOLSA') THEN
--     EXECUTE IMMEDIATE 'CREATE TABLE DSEDAC.MOVIMIENTOS_BOLSA LIKE JAVIER.MOVIMIENTOS_BOLSA INCLUDING IDENTITY COLUMN ATTRIBUTES INCLUDING COLUMN DEFAULTS';
--   END IF;
-- END@

-- =============================
-- 4) POSTCHECK
-- =============================
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'DSEDAC'
  AND TABLE_NAME IN (
    'PEDIDOS_CAB', 'PEDIDOS_LIN', 'PEDIDOS_SEQ', 'PEDIDOS_STOCK_RESERVE',
    'COBROS', 'REPARTIDOR_COBROS'
  )
ORDER BY TABLE_NAME@

SELECT s.TABLE_NAME,
       s.COLUMN_COUNT AS JAVIER_COLUMNS,
       t.COLUMN_COUNT AS DSEDAC_COLUMNS,
       s.IDENTITY_COLUMNS AS JAVIER_IDENTITY_COLUMNS,
       t.IDENTITY_COLUMNS AS DSEDAC_IDENTITY_COLUMNS,
       s.DEFAULT_COLUMNS AS JAVIER_DEFAULT_COLUMNS,
       t.DEFAULT_COLUMNS AS DSEDAC_DEFAULT_COLUMNS
FROM (
  SELECT TABLE_NAME,
         COUNT(*) AS COLUMN_COUNT,
         SUM(CASE WHEN IS_IDENTITY = 'YES' THEN 1 ELSE 0 END) AS IDENTITY_COLUMNS,
         SUM(CASE WHEN COLUMN_DEFAULT IS NOT NULL THEN 1 ELSE 0 END) AS DEFAULT_COLUMNS
  FROM QSYS2.SYSCOLUMNS
  WHERE TABLE_SCHEMA = 'JAVIER'
    AND TABLE_NAME IN ('PEDIDOS_CAB', 'PEDIDOS_LIN', 'PEDIDOS_SEQ', 'PEDIDOS_STOCK_RESERVE', 'COBROS', 'REPARTIDOR_COBROS')
  GROUP BY TABLE_NAME
) s
LEFT JOIN (
  SELECT TABLE_NAME,
         COUNT(*) AS COLUMN_COUNT,
         SUM(CASE WHEN IS_IDENTITY = 'YES' THEN 1 ELSE 0 END) AS IDENTITY_COLUMNS,
         SUM(CASE WHEN COLUMN_DEFAULT IS NOT NULL THEN 1 ELSE 0 END) AS DEFAULT_COLUMNS
  FROM QSYS2.SYSCOLUMNS
  WHERE TABLE_SCHEMA = 'DSEDAC'
    AND TABLE_NAME IN ('PEDIDOS_CAB', 'PEDIDOS_LIN', 'PEDIDOS_SEQ', 'PEDIDOS_STOCK_RESERVE', 'COBROS', 'REPARTIDOR_COBROS')
  GROUP BY TABLE_NAME
) t ON t.TABLE_NAME = s.TABLE_NAME
ORDER BY s.TABLE_NAME@

SELECT INDEX_SCHEMA, INDEX_NAME, TABLE_NAME, IS_UNIQUE, COLUMN_COUNT
FROM QSYS2.SYSINDEXES
WHERE INDEX_SCHEMA = 'DSEDAC'
  AND (INDEX_NAME LIKE 'IDX031_%' OR INDEX_NAME = 'UX031_REPCOB_TOK')
ORDER BY INDEX_NAME@

--#SET TERMINATOR ;

-- ==================================================
-- MANUAL ROLLBACK ONLY - do not run automatically
-- ==================================================
-- DROP INDEX DSEDAC.IDX031_REPCOB_CLI;
-- DROP INDEX DSEDAC.IDX031_REPCOB_LIQ;
-- DROP INDEX DSEDAC.IDX031_REPCOB_VND;
-- DROP INDEX DSEDAC.IDX031_REPCOB_DOC;
-- DROP INDEX DSEDAC.UX031_REPCOB_TOK;
-- DROP INDEX DSEDAC.IDX031_COB_IDEM;
-- DROP INDEX DSEDAC.IDX031_COB_CLI;
-- DROP INDEX DSEDAC.IDX031_PSR_PID;
-- DROP INDEX DSEDAC.IDX031_PLIN_ART;
-- DROP INDEX DSEDAC.IDX031_PLIN_PID;
-- DROP INDEX DSEDAC.IDX031_PCAB_EST;
-- DROP INDEX DSEDAC.IDX031_PCAB_VND;
-- DROP INDEX DSEDAC.IDX031_PCAB_CLI;
-- DROP TABLE DSEDAC.REPARTIDOR_COBROS;
-- DROP TABLE DSEDAC.COBROS;
-- DROP TABLE DSEDAC.PEDIDOS_STOCK_RESERVE;
-- DROP TABLE DSEDAC.PEDIDOS_LIN;
-- DROP TABLE DSEDAC.PEDIDOS_CAB;
-- DROP TABLE DSEDAC.PEDIDOS_SEQ;
