-- 031_prepare_dsedac_app_buffers.sql
-- Purpose: verification-only guardrail for the DSEDAC export architecture.
-- Status: DO-NOT-RUN-DDL. This file must not mutate DB2.
--
-- Production/staging profile:
--   DB2_READ_SCHEMA=DSEDAC
--   DB2_WRITE_SCHEMA=JAVIER
--   PEDIDOS_DSEDAC_STORAGE_APPROVED=true  -- export approval gate; app buffers still stay in JAVIER
--   PEDIDOS_EXPORT_TO_SYSTEM=true
--   PEDIDOS_DSEDAC_EXPORT_APPROVED=true
--
-- Pilot/dev profile:
--   DB2_READ_SCHEMA=DSEDAC
--   DB2_WRITE_SCHEMA=JAVIER
--   PEDIDOS_DSEDAC_STORAGE_APPROVED=false
--   PEDIDOS_EXPORT_TO_SYSTEM=false
--   PEDIDOS_DSEDAC_EXPORT_APPROVED=false
--
-- Architecture:
--   - JAVIER remains the app write buffer for PEDIDOS_*, COBROS and related app tables.
--   - Production export writes explicitly to real DSEDAC ERP tables such as CPC/LPC/CRC.
--   - Do not add DSEDAC copies of JAVIER app-buffer tables by default.

-- ==========================================================
-- 1) Required real DSEDAC ERP tables exist
-- ==========================================================
WITH REQUIRED_TABLES (TABLE_NAME, REQUIRED_LEVEL) AS (
  VALUES
    ('CPC', 'REQUIRED'),
    ('LPC', 'REQUIRED'),
    ('CRC', 'REQUIRED'),
    ('CVC', 'REQUIRED'),
    ('CRCA', 'OPTIONAL_RELATED'),
    ('LRC', 'OPTIONAL_RELATED'),
    ('HCRC', 'OPTIONAL_RELATED'),
    ('HLRC', 'OPTIONAL_RELATED'),
    ('OCPC', 'OPTIONAL_RELATED'),
    ('CLV', 'OPTIONAL_RELATED'),
    ('CAC', 'OPTIONAL_RELATED'),
    ('LAC', 'OPTIONAL_RELATED')
)
SELECT r.REQUIRED_LEVEL,
       'DSEDAC' AS TABLE_SCHEMA,
       r.TABLE_NAME,
       CASE WHEN t.TABLE_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS STATUS,
       t.TABLE_TYPE
FROM REQUIRED_TABLES r
LEFT JOIN QSYS2.SYSTABLES t
  ON t.TABLE_SCHEMA = 'DSEDAC'
 AND t.TABLE_NAME = r.TABLE_NAME
ORDER BY r.REQUIRED_LEVEL, r.TABLE_NAME;

-- ==========================================================
-- 2) JAVIER app-buffer source tables required for export exist
-- ==========================================================
WITH REQUIRED_SOURCE_TABLES (TABLE_NAME) AS (
  VALUES
    ('PEDIDOS_CAB'),
    ('PEDIDOS_LIN'),
    ('COBROS')
)
SELECT 'JAVIER' AS TABLE_SCHEMA,
       r.TABLE_NAME,
       CASE WHEN t.TABLE_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS STATUS,
       t.TABLE_TYPE
FROM REQUIRED_SOURCE_TABLES r
LEFT JOIN QSYS2.SYSTABLES t
  ON t.TABLE_SCHEMA = 'JAVIER'
 AND t.TABLE_NAME = r.TABLE_NAME
ORDER BY r.TABLE_NAME;

-- ==========================================================
-- 3) JAVIER source columns required to export pedidos to DSEDAC.CPC
-- ==========================================================
WITH REQUIRED_COLUMNS (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, EXPORT_TARGET) AS (
  VALUES
    ('JAVIER', 'PEDIDOS_CAB', 'DIADOCUMENTO', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'MESDOCUMENTO', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'ANODOCUMENTO', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'HORADOCUMENTO', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'CODIGOCLIENTE', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'CODIGOVENDEDOR', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'CODIGOFORMAPAGO', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'CODIGOTARIFA', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'CODIGOALMACEN', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'IMPORTEBASE', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'IMPORTETOTAL', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'IMPORTECOSTO', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'IMPORTEMARGEN', 'DSEDAC.CPC'),
    ('JAVIER', 'PEDIDOS_CAB', 'OBSERVACIONES', 'DSEDAC.CPC')
)
SELECT r.TABLE_SCHEMA,
       r.TABLE_NAME,
       r.COLUMN_NAME,
       r.EXPORT_TARGET,
       CASE WHEN c.COLUMN_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS STATUS,
       c.DATA_TYPE,
       c.LENGTH,
       c.NUMERIC_SCALE,
       c.IS_NULLABLE
FROM REQUIRED_COLUMNS r
LEFT JOIN QSYS2.SYSCOLUMNS c
  ON c.TABLE_SCHEMA = r.TABLE_SCHEMA
 AND c.TABLE_NAME = r.TABLE_NAME
 AND c.COLUMN_NAME = r.COLUMN_NAME
ORDER BY r.TABLE_NAME, r.COLUMN_NAME;

-- ==========================================================
-- 4) JAVIER source columns required to export lines to DSEDAC.LPC
-- ==========================================================
WITH REQUIRED_COLUMNS (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, EXPORT_TARGET) AS (
  VALUES
    ('JAVIER', 'PEDIDOS_LIN', 'SECUENCIA', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'ORDEN', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'TIPOLINEA', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'TIPOVENTA', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'CLASELINEA', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'CODIGOARTICULO', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'DESCRIPCION', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'CANTIDADENVASES', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'CANTIDADUNIDADES', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'PRECIOVENTA', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'IMPORTEVENTA', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'PRECIOCOSTO', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'IMPORTECOSTO', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'UNIDADMEDIDA', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'PRECIOTARIFACLIENTE', 'DSEDAC.LPC'),
    ('JAVIER', 'PEDIDOS_LIN', 'PRECIOTARIFA', 'DSEDAC.LPC')
)
SELECT r.TABLE_SCHEMA,
       r.TABLE_NAME,
       r.COLUMN_NAME,
       r.EXPORT_TARGET,
       CASE WHEN c.COLUMN_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS STATUS,
       c.DATA_TYPE,
       c.LENGTH,
       c.NUMERIC_SCALE,
       c.IS_NULLABLE
FROM REQUIRED_COLUMNS r
LEFT JOIN QSYS2.SYSCOLUMNS c
  ON c.TABLE_SCHEMA = r.TABLE_SCHEMA
 AND c.TABLE_NAME = r.TABLE_NAME
 AND c.COLUMN_NAME = r.COLUMN_NAME
ORDER BY r.TABLE_NAME, r.COLUMN_NAME;

-- ==========================================================
-- 5) JAVIER source columns required to export cobros to DSEDAC.CRC
-- ==========================================================
WITH REQUIRED_COLUMNS (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, EXPORT_TARGET) AS (
  VALUES
    ('JAVIER', 'COBROS', 'IDEMPOTENCY_TOKEN', 'DSEDAC.CRC'),
    ('JAVIER', 'COBROS', 'CODIGO_CLIENTE', 'DSEDAC.CRC'),
    ('JAVIER', 'COBROS', 'CODIGO_USUARIO', 'DSEDAC.CRC'),
    ('JAVIER', 'COBROS', 'IMPORTE', 'DSEDAC.CRC')
)
SELECT r.TABLE_SCHEMA,
       r.TABLE_NAME,
       r.COLUMN_NAME,
       r.EXPORT_TARGET,
       CASE WHEN c.COLUMN_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS STATUS,
       c.DATA_TYPE,
       c.LENGTH,
       c.NUMERIC_SCALE,
       c.IS_NULLABLE
FROM REQUIRED_COLUMNS r
LEFT JOIN QSYS2.SYSCOLUMNS c
  ON c.TABLE_SCHEMA = r.TABLE_SCHEMA
 AND c.TABLE_NAME = r.TABLE_NAME
 AND c.COLUMN_NAME = r.COLUMN_NAME
ORDER BY r.TABLE_NAME, r.COLUMN_NAME;

-- ==========================================================
-- 6) DSEDAC target columns used by explicit exports
-- ==========================================================
WITH REQUIRED_COLUMNS (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, EXPORT_FLOW) AS (
  VALUES
    ('DSEDAC', 'CPC', 'SUBEMPRESAPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'CPC', 'EJERCICIOPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'CPC', 'SERIEPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'CPC', 'TERMINALPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'CPC', 'NUMEROPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'CPC', 'CODIGOCLIENTEALBARAN', 'PEDIDOS'),
    ('DSEDAC', 'CPC', 'CODIGOCLIENTEFACTURA', 'PEDIDOS'),
    ('DSEDAC', 'CPC', 'CODIGOVENDEDOR', 'PEDIDOS'),
    ('DSEDAC', 'CPC', 'IMPORTETOTAL', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'SUBEMPRESAPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'EJERCICIOPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'SERIEPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'TERMINALPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'NUMEROPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'SECUENCIAPEDIDO', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'CODIGOARTICULO', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'CANTIDADENVASES', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'CANTIDADUNIDADES', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'PRECIOVENTA', 'PEDIDOS'),
    ('DSEDAC', 'LPC', 'IMPORTEVENTA', 'PEDIDOS'),
    ('DSEDAC', 'CRC', 'SUBEMPRESARECIBO', 'COBROS'),
    ('DSEDAC', 'CRC', 'EJERCICIORECIBO', 'COBROS'),
    ('DSEDAC', 'CRC', 'SERIERECIBO', 'COBROS'),
    ('DSEDAC', 'CRC', 'TERMINALRECIBO', 'COBROS'),
    ('DSEDAC', 'CRC', 'NUMERORECIBO', 'COBROS'),
    ('DSEDAC', 'CRC', 'CODIGOCLIENTEFACTURA', 'COBROS'),
    ('DSEDAC', 'CRC', 'CODIGOVENDEDOR', 'COBROS'),
    ('DSEDAC', 'CRC', 'IMPORTECOBRADO', 'COBROS'),
    ('DSEDAC', 'CRC', 'IDMARCALIQUIDACION', 'COBROS')
)
SELECT r.TABLE_SCHEMA,
       r.TABLE_NAME,
       r.COLUMN_NAME,
       r.EXPORT_FLOW,
       CASE WHEN c.COLUMN_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS STATUS,
       c.DATA_TYPE,
       c.LENGTH,
       c.NUMERIC_SCALE,
       c.IS_NULLABLE
FROM REQUIRED_COLUMNS r
LEFT JOIN QSYS2.SYSCOLUMNS c
  ON c.TABLE_SCHEMA = r.TABLE_SCHEMA
 AND c.TABLE_NAME = r.TABLE_NAME
 AND c.COLUMN_NAME = r.COLUMN_NAME
ORDER BY r.TABLE_SCHEMA, r.TABLE_NAME, r.COLUMN_NAME;
