-- 031_prepare_dsedac_app_buffers.sql
-- Purpose: sequential safe alignment for JAVIER test/write tables vs real DSEDAC ERP tables.
-- Scope: pedidos/cobros only. Default executable SQL must not mutate DSEDAC.
-- Run in IBM i ACS Run SQL Scripts against DSN GMP. Stop if any PRECHECK row is MISSING.
--
-- PILOTO profile:
--   DB2_READ_SCHEMA=DSEDAC
--   DB2_WRITE_SCHEMA=JAVIER
--   PEDIDOS_EXPORT_TO_SYSTEM=false
--
-- STAGING/PROD profile, until a separate export refactor changes this:
--   DB2_READ_SCHEMA=DSEDAC
--   DB2_WRITE_SCHEMA=JAVIER
--   PEDIDOS_EXPORT_TO_SYSTEM=true
--   PEDIDOS_DSEDAC_EXPORT_APPROVED=true
--
-- Non-goals:
--   - Do not create DSEDAC.PEDIDOS_CAB, DSEDAC.PEDIDOS_LIN or DSEDAC.COBROS.
--   - Do not rename/drop/swap live ERP objects in DSEDAC.

-- ==========================================================
-- 1) PRECHECK: required real ERP and JAVIER app tables exist
-- ==========================================================
WITH REQUIRED_TABLES (TABLE_SCHEMA, TABLE_NAME, FLOW) AS (
  VALUES
    ('DSEDAC', 'CPC', 'PEDIDOS_HEADER_TARGET'),
    ('DSEDAC', 'LPC', 'PEDIDOS_LINE_TARGET'),
    ('DSEDAC', 'CRC', 'COBROS_TARGET'),
    ('DSEDAC', 'CVC', 'COBROS_RELATED_TARGET'),
    ('JAVIER', 'PEDIDOS_CAB', 'PEDIDOS_HEADER_SOURCE'),
    ('JAVIER', 'PEDIDOS_LIN', 'PEDIDOS_LINE_SOURCE'),
    ('JAVIER', 'COBROS', 'COBROS_SOURCE')
)
SELECT 'PRECHECK_TABLES' AS CHECK_NAME,
       r.TABLE_SCHEMA,
       r.TABLE_NAME,
       r.FLOW,
       CASE WHEN t.TABLE_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS STATUS,
       t.TABLE_TYPE
FROM REQUIRED_TABLES r
LEFT JOIN QSYS2.SYSTABLES t
  ON t.TABLE_SCHEMA = r.TABLE_SCHEMA
 AND t.TABLE_NAME = r.TABLE_NAME
ORDER BY r.TABLE_SCHEMA, r.TABLE_NAME;

-- ==========================================================
-- 2) PRECHECK: required columns and missing-column summary
-- ==========================================================
WITH REQUIRED_COLUMNS (TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, FLOW) AS (
  VALUES
    ('JAVIER', 'PEDIDOS_CAB', 'CODIGOCLIENTE', 'PEDIDOS_HEADER_SOURCE'),
    ('JAVIER', 'PEDIDOS_CAB', 'CODIGOVENDEDOR', 'PEDIDOS_HEADER_SOURCE'),
    ('JAVIER', 'PEDIDOS_CAB', 'IMPORTEBASE', 'PEDIDOS_HEADER_SOURCE'),
    ('JAVIER', 'PEDIDOS_CAB', 'IMPORTETOTAL', 'PEDIDOS_HEADER_SOURCE'),
    ('JAVIER', 'PEDIDOS_CAB', 'IMPORTECOSTO', 'PEDIDOS_HEADER_SOURCE'),
    ('JAVIER', 'PEDIDOS_CAB', 'IMPORTEMARGEN', 'PEDIDOS_HEADER_SOURCE'),
    ('JAVIER', 'PEDIDOS_LIN', 'CODIGOARTICULO', 'PEDIDOS_LINE_SOURCE'),
    ('JAVIER', 'PEDIDOS_LIN', 'CANTIDADENVASES', 'PEDIDOS_LINE_SOURCE'),
    ('JAVIER', 'PEDIDOS_LIN', 'CANTIDADUNIDADES', 'PEDIDOS_LINE_SOURCE'),
    ('JAVIER', 'PEDIDOS_LIN', 'PRECIOVENTA', 'PEDIDOS_LINE_SOURCE'),
    ('JAVIER', 'PEDIDOS_LIN', 'IMPORTEVENTA', 'PEDIDOS_LINE_SOURCE'),
    ('JAVIER', 'COBROS', 'CODIGO_CLIENTE', 'COBROS_SOURCE'),
    ('JAVIER', 'COBROS', 'CODIGO_USUARIO', 'COBROS_SOURCE'),
    ('JAVIER', 'COBROS', 'IMPORTE', 'COBROS_SOURCE'),
    ('DSEDAC', 'CPC', 'CODIGOCLIENTEFACTURA', 'PEDIDOS_HEADER_TARGET'),
    ('DSEDAC', 'CPC', 'CODIGOVENDEDOR', 'PEDIDOS_HEADER_TARGET'),
    ('DSEDAC', 'CPC', 'IMPORTETOTAL', 'PEDIDOS_HEADER_TARGET'),
    ('DSEDAC', 'LPC', 'CODIGOARTICULO', 'PEDIDOS_LINE_TARGET'),
    ('DSEDAC', 'LPC', 'CANTIDADENVASES', 'PEDIDOS_LINE_TARGET'),
    ('DSEDAC', 'LPC', 'CANTIDADUNIDADES', 'PEDIDOS_LINE_TARGET'),
    ('DSEDAC', 'LPC', 'PRECIOVENTA', 'PEDIDOS_LINE_TARGET'),
    ('DSEDAC', 'LPC', 'IMPORTEVENTA', 'PEDIDOS_LINE_TARGET'),
    ('DSEDAC', 'CRC', 'CODIGOCLIENTEFACTURA', 'COBROS_TARGET'),
    ('DSEDAC', 'CRC', 'CODIGOVENDEDOR', 'COBROS_TARGET'),
    ('DSEDAC', 'CRC', 'IMPORTECOBRADO', 'COBROS_TARGET')
)
SELECT 'PRECHECK_COLUMNS' AS CHECK_NAME,
       r.TABLE_SCHEMA,
       r.TABLE_NAME,
       r.COLUMN_NAME,
       r.FLOW,
       CASE WHEN c.COLUMN_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS STATUS,
       c.DATA_TYPE,
       c.LENGTH,
       c.NUMERIC_SCALE,
       c.IS_NULLABLE
FROM REQUIRED_COLUMNS r
LEFT JOIN QSYS2.SYSCOLUMNS c
  ON c.TABLE_SCHEMA = r.TABLE_SCHEMA
 AND c.TABLE_NAME = r.TABLE_NAME
 AND c.COLUMN_NAME = r.COLUMN_NAME
ORDER BY r.TABLE_SCHEMA, r.TABLE_NAME, r.COLUMN_NAME;

-- ==========================================================
-- 3) Difference summary: mapped JAVIER columns vs DSEDAC columns
-- ==========================================================
WITH COLUMN_MAP (SOURCE_TABLE, SOURCE_COLUMN, TARGET_TABLE, TARGET_COLUMN, FLOW) AS (
  VALUES
    ('PEDIDOS_CAB', 'CODIGOCLIENTE', 'CPC', 'CODIGOCLIENTEFACTURA', 'PEDIDOS_HEADER'),
    ('PEDIDOS_CAB', 'CODIGOVENDEDOR', 'CPC', 'CODIGOVENDEDOR', 'PEDIDOS_HEADER'),
    ('PEDIDOS_CAB', 'IMPORTETOTAL', 'CPC', 'IMPORTETOTAL', 'PEDIDOS_HEADER'),
    ('PEDIDOS_LIN', 'CODIGOARTICULO', 'LPC', 'CODIGOARTICULO', 'PEDIDOS_LINE'),
    ('PEDIDOS_LIN', 'CANTIDADENVASES', 'LPC', 'CANTIDADENVASES', 'PEDIDOS_LINE'),
    ('PEDIDOS_LIN', 'CANTIDADUNIDADES', 'LPC', 'CANTIDADUNIDADES', 'PEDIDOS_LINE'),
    ('PEDIDOS_LIN', 'PRECIOVENTA', 'LPC', 'PRECIOVENTA', 'PEDIDOS_LINE'),
    ('PEDIDOS_LIN', 'IMPORTEVENTA', 'LPC', 'IMPORTEVENTA', 'PEDIDOS_LINE'),
    ('COBROS', 'CODIGO_CLIENTE', 'CRC', 'CODIGOCLIENTEFACTURA', 'COBROS'),
    ('COBROS', 'CODIGO_USUARIO', 'CRC', 'CODIGOVENDEDOR', 'COBROS'),
    ('COBROS', 'IMPORTE', 'CRC', 'IMPORTECOBRADO', 'COBROS')
)
SELECT 'TYPE_DIFF_SUMMARY' AS CHECK_NAME,
       m.FLOW,
       'JAVIER.' CONCAT m.SOURCE_TABLE CONCAT '.' CONCAT m.SOURCE_COLUMN AS SOURCE_COLUMN,
       s.DATA_TYPE AS SOURCE_TYPE,
       s.LENGTH AS SOURCE_LENGTH,
       s.NUMERIC_SCALE AS SOURCE_SCALE,
       'DSEDAC.' CONCAT m.TARGET_TABLE CONCAT '.' CONCAT m.TARGET_COLUMN AS TARGET_COLUMN,
       d.DATA_TYPE AS TARGET_TYPE,
       d.LENGTH AS TARGET_LENGTH,
       d.NUMERIC_SCALE AS TARGET_SCALE,
       CASE
         WHEN s.COLUMN_NAME IS NULL THEN 'SOURCE_MISSING'
         WHEN d.COLUMN_NAME IS NULL THEN 'TARGET_MISSING'
         WHEN COALESCE(s.DATA_TYPE, '') <> COALESCE(d.DATA_TYPE, '')
           OR COALESCE(s.LENGTH, -1) <> COALESCE(d.LENGTH, -1)
           OR COALESCE(s.NUMERIC_SCALE, -1) <> COALESCE(d.NUMERIC_SCALE, -1)
           THEN 'TYPE_DIFF'
         ELSE 'OK'
       END AS STATUS
FROM COLUMN_MAP m
LEFT JOIN QSYS2.SYSCOLUMNS s
  ON s.TABLE_SCHEMA = 'JAVIER'
 AND s.TABLE_NAME = m.SOURCE_TABLE
 AND s.COLUMN_NAME = m.SOURCE_COLUMN
LEFT JOIN QSYS2.SYSCOLUMNS d
  ON d.TABLE_SCHEMA = 'DSEDAC'
 AND d.TABLE_NAME = m.TARGET_TABLE
 AND d.COLUMN_NAME = m.TARGET_COLUMN
ORDER BY m.FLOW, m.SOURCE_TABLE, m.SOURCE_COLUMN;

-- ==========================================================
-- 4) Non-destructive JAVIER repair: add *_NEW numeric columns if missing
--    Known safe pending issue: keep DSEDAC untouched; do not drop/rename originals.
-- ==========================================================
--#SET TERMINATOR @
BEGIN
  IF EXISTS (
      SELECT 1 FROM QSYS2.SYSTABLES
      WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME = 'PEDIDOS_CAB'
    )
    AND NOT EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME = 'PEDIDOS_CAB'
        AND COLUMN_NAME = 'IMPORTETOTAL_NEW'
    ) THEN
    EXECUTE IMMEDIATE 'ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTETOTAL_NEW NUMERIC(10,2)';
  END IF;

  IF EXISTS (
      SELECT 1 FROM QSYS2.SYSTABLES
      WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME = 'PEDIDOS_CAB'
    )
    AND NOT EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME = 'PEDIDOS_CAB'
        AND COLUMN_NAME = 'IMPORTECOSTO_NEW'
    ) THEN
    EXECUTE IMMEDIATE 'ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTECOSTO_NEW NUMERIC(10,2)';
  END IF;

  IF EXISTS (
      SELECT 1 FROM QSYS2.SYSTABLES
      WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME = 'PEDIDOS_CAB'
    )
    AND NOT EXISTS (
      SELECT 1 FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME = 'PEDIDOS_CAB'
        AND COLUMN_NAME = 'IMPORTEMARGEN_NEW'
    ) THEN
    EXECUTE IMMEDIATE 'ALTER TABLE JAVIER.PEDIDOS_CAB ADD COLUMN IMPORTEMARGEN_NEW NUMERIC(10,2)';
  END IF;
END @

BEGIN
  IF 6 = (
      SELECT COUNT(*)
      FROM QSYS2.SYSCOLUMNS
      WHERE TABLE_SCHEMA = 'JAVIER'
        AND TABLE_NAME = 'PEDIDOS_CAB'
        AND COLUMN_NAME IN (
          'IMPORTETOTAL', 'IMPORTECOSTO', 'IMPORTEMARGEN',
          'IMPORTETOTAL_NEW', 'IMPORTECOSTO_NEW', 'IMPORTEMARGEN_NEW'
        )
        AND DATA_TYPE IN ('DECIMAL', 'NUMERIC', 'INTEGER', 'SMALLINT', 'BIGINT', 'DECFLOAT', 'DOUBLE', 'REAL')
    ) THEN
    UPDATE JAVIER.PEDIDOS_CAB
       SET IMPORTETOTAL_NEW = DECIMAL(COALESCE(IMPORTETOTAL, 0), 10, 2)
     WHERE IMPORTETOTAL_NEW IS NULL
       AND ABS(COALESCE(IMPORTETOTAL, 0)) <= 99999999.99;

    UPDATE JAVIER.PEDIDOS_CAB
       SET IMPORTECOSTO_NEW = DECIMAL(COALESCE(IMPORTECOSTO, 0), 10, 2)
     WHERE IMPORTECOSTO_NEW IS NULL
       AND ABS(COALESCE(IMPORTECOSTO, 0)) <= 99999999.99;

    UPDATE JAVIER.PEDIDOS_CAB
       SET IMPORTEMARGEN_NEW = DECIMAL(COALESCE(IMPORTEMARGEN, 0), 10, 2)
     WHERE IMPORTEMARGEN_NEW IS NULL
       AND ABS(COALESCE(IMPORTEMARGEN, 0)) <= 99999999.99;
  END IF;
END @
--#SET TERMINATOR ;

-- ==========================================================
-- 5) PASS queries for the JAVIER repair
--    Expected PASS: NULLS_IN_NEW=0, DIFF_ROWS=0, OVER_LIMIT_ROWS=0.
-- ==========================================================
WITH CHECKS (COLUMN_NAME, NULLS_IN_NEW, DIFF_ROWS, OVER_LIMIT_ROWS) AS (
  SELECT 'IMPORTETOTAL_NEW',
         COALESCE(SUM(CASE WHEN IMPORTETOTAL_NEW IS NULL THEN 1 ELSE 0 END), 0),
         COALESCE(SUM(CASE
           WHEN ABS(COALESCE(IMPORTETOTAL, 0)) > 99999999.99 THEN 0
           WHEN DECIMAL(COALESCE(IMPORTETOTAL, 0), 10, 2) <> IMPORTETOTAL_NEW THEN 1
           ELSE 0
         END), 0),
         COALESCE(SUM(CASE WHEN ABS(COALESCE(IMPORTETOTAL, 0)) > 99999999.99 THEN 1 ELSE 0 END), 0)
  FROM JAVIER.PEDIDOS_CAB
  UNION ALL
  SELECT 'IMPORTECOSTO_NEW',
         COALESCE(SUM(CASE WHEN IMPORTECOSTO_NEW IS NULL THEN 1 ELSE 0 END), 0),
         COALESCE(SUM(CASE
           WHEN ABS(COALESCE(IMPORTECOSTO, 0)) > 99999999.99 THEN 0
           WHEN DECIMAL(COALESCE(IMPORTECOSTO, 0), 10, 2) <> IMPORTECOSTO_NEW THEN 1
           ELSE 0
         END), 0),
         COALESCE(SUM(CASE WHEN ABS(COALESCE(IMPORTECOSTO, 0)) > 99999999.99 THEN 1 ELSE 0 END), 0)
  FROM JAVIER.PEDIDOS_CAB
  UNION ALL
  SELECT 'IMPORTEMARGEN_NEW',
         COALESCE(SUM(CASE WHEN IMPORTEMARGEN_NEW IS NULL THEN 1 ELSE 0 END), 0),
         COALESCE(SUM(CASE
           WHEN ABS(COALESCE(IMPORTEMARGEN, 0)) > 99999999.99 THEN 0
           WHEN DECIMAL(COALESCE(IMPORTEMARGEN, 0), 10, 2) <> IMPORTEMARGEN_NEW THEN 1
           ELSE 0
         END), 0),
         COALESCE(SUM(CASE WHEN ABS(COALESCE(IMPORTEMARGEN, 0)) > 99999999.99 THEN 1 ELSE 0 END), 0)
  FROM JAVIER.PEDIDOS_CAB
)
SELECT 'JAVIER_REPAIR_PASS' AS CHECK_NAME,
       COLUMN_NAME,
       NULLS_IN_NEW,
       DIFF_ROWS,
       OVER_LIMIT_ROWS,
       CASE
         WHEN NULLS_IN_NEW = 0 AND DIFF_ROWS = 0 AND OVER_LIMIT_ROWS = 0 THEN 'PASS'
         ELSE 'BLOCK'
       END AS STATUS
FROM CHECKS
ORDER BY COLUMN_NAME;

WITH EXPECTED_REPAIR_COLUMNS (COLUMN_NAME) AS (
  VALUES
    ('IMPORTETOTAL_NEW'),
    ('IMPORTECOSTO_NEW'),
    ('IMPORTEMARGEN_NEW')
)
SELECT 'REPAIR_COLUMN_TYPE_PASS' AS CHECK_NAME,
       e.COLUMN_NAME,
       c.DATA_TYPE,
       c.LENGTH,
       c.NUMERIC_SCALE,
       CASE
         WHEN c.COLUMN_NAME IS NOT NULL
          AND c.DATA_TYPE IN ('DECIMAL', 'NUMERIC')
          AND c.LENGTH = 10
          AND c.NUMERIC_SCALE = 2
           THEN 'PASS'
         ELSE 'BLOCK'
       END AS STATUS
FROM EXPECTED_REPAIR_COLUMNS e
LEFT JOIN QSYS2.SYSCOLUMNS c
  ON c.TABLE_SCHEMA = 'JAVIER'
 AND c.TABLE_NAME = 'PEDIDOS_CAB'
 AND c.COLUMN_NAME = e.COLUMN_NAME
ORDER BY e.COLUMN_NAME;

-- ==========================================================
-- 6) COMMENTED manual operator-only destructive swap notes
-- ==========================================================
-- IBM i may reject DROP/RENAME while dependent objects exist, commonly with CPD32CC.
-- Keep this section commented. Use only from ACS with an operator-approved window,
-- dependency review and backup. This is a JAVIER-only cleanup path, not DSEDAC.
--
-- -- Example manual outline after PASS above and dependency review:
-- -- ALTER TABLE JAVIER.PEDIDOS_CAB DROP COLUMN IMPORTETOTAL;
-- -- ALTER TABLE JAVIER.PEDIDOS_CAB DROP COLUMN IMPORTECOSTO;
-- -- ALTER TABLE JAVIER.PEDIDOS_CAB DROP COLUMN IMPORTEMARGEN;
-- -- ALTER TABLE JAVIER.PEDIDOS_CAB RENAME COLUMN IMPORTETOTAL_NEW TO IMPORTETOTAL;
-- -- ALTER TABLE JAVIER.PEDIDOS_CAB RENAME COLUMN IMPORTECOSTO_NEW TO IMPORTECOSTO;
-- -- ALTER TABLE JAVIER.PEDIDOS_CAB RENAME COLUMN IMPORTEMARGEN_NEW TO IMPORTEMARGEN;
--
-- If CPD32CC occurs: do not force. Record dependent object names from the job log,
-- reschedule with the IBM i operator, and leave *_NEW columns in place until cleared.
