-- Parametrizacion de precio minimo, coste y margen por producto.
-- No ejecutar directamente en produccion sin ventana aprobada.
-- DSEDAC.PES/PPU siguen siendo fuente de precios especiales/promociones en lectura.
-- No se crea tabla propia de precios especiales por cliente.

CREATE TABLE JAVIER.BOLSA_PRODUCTO_PRECIO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGOARTICULO CHAR(10) NOT NULL,
    UNIDAD_BASE VARCHAR(12) DEFAULT 'CAJAS',
    FECHA_DESDE DATE NOT NULL,
    FECHA_HASTA DATE,
    COSTE_FABRICACION DECIMAL(11,4) DEFAULT 0,
    MARGEN_OBJETIVO_PCT DECIMAL(7,4) DEFAULT 20,
    PRECIO_MINIMO DECIMAL(11,4) DEFAULT 0,
    ACTIVO CHAR(1) DEFAULT 'S',
    SOURCE VARCHAR(40) DEFAULT 'MANUAL',
    OBSERVACIONES VARCHAR(200) DEFAULT '',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX JAVIER.UQ_BPP_ART_UNIT_DATE
    ON JAVIER.BOLSA_PRODUCTO_PRECIO (CODIGOARTICULO, UNIDAD_BASE, FECHA_DESDE);

CREATE INDEX JAVIER.IX_BPP_ACTIVE_LOOKUP
    ON JAVIER.BOLSA_PRODUCTO_PRECIO (CODIGOARTICULO, ACTIVO, FECHA_DESDE, FECHA_HASTA);
