-- 033_cobros_mirror_tables_DBA_RUN.sql
-- Execute in IBM i ACS Run SQL Scripts.
-- Execute sections 1_PRECHECK, 2_FORWARD, 3_POSTVALIDATION.
-- Do NOT execute rollback unless explicitly instructed.

-- ============================================================
-- 1_PRECHECK
-- ============================================================

SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME IN ('COBROCABEC', 'COBROLINEA', 'LIQUIDIARI')
ORDER BY TABLE_NAME;

SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS', 'COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
ORDER BY TABLE_NAME;

SELECT TABLE_SCHEMA, TABLE_NAME, COUNT(*) AS COLUMN_COUNT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME IN ('COBROCABEC', 'COBROLINEA', 'LIQUIDIARI')
GROUP BY TABLE_SCHEMA, TABLE_NAME
ORDER BY TABLE_NAME;

SELECT TABLE_SCHEMA, TABLE_NAME, COUNT(*) AS COLUMN_COUNT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS', 'COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
GROUP BY TABLE_SCHEMA, TABLE_NAME
ORDER BY TABLE_NAME;

-- ============================================================
-- 2_FORWARD
-- ============================================================

CREATE TABLE JAVIER.COBROS_CAB LIKE DSTMOVIL.COBROCABEC;
CREATE INDEX JAVIER.COBROS_CAB_IX1 ON JAVIER.COBROS_CAB (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO);
CREATE INDEX JAVIER.COBROS_CAB_IX2 ON JAVIER.COBROS_CAB (CLIENTE, FECHAEMISIONANO, FECHAEMISIONMES, FECHAEMISIONDIA);
CREATE INDEX JAVIER.COBROS_CAB_IX3 ON JAVIER.COBROS_CAB (VENDEDOR, FECHAEMISIONANO, FECHAEMISIONMES, FECHAEMISIONDIA);
CREATE INDEX JAVIER.COBROS_CAB_IX4 ON JAVIER.COBROS_CAB (LIQUIDACIONSUBEMPRESA, LIQUIDACIONEJERCICIO, LIQUIDACIONSERIE, LIQUIDACIONTERMINAL, LIQUIDACIONNUMERO);

CREATE TABLE JAVIER.COBROS_LIN LIKE DSTMOVIL.COBROLINEA;
CREATE INDEX JAVIER.COBROS_LIN_IX1 ON JAVIER.COBROS_LIN (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, SECUENCIA);
CREATE INDEX JAVIER.COBROS_LIN_IX2 ON JAVIER.COBROS_LIN (CLIENTE);
CREATE INDEX JAVIER.COBROS_LIN_IX3 ON JAVIER.COBROS_LIN (DOCUMENTOSUBEMPRESA, DOCUMENTOEJERCICIO, DOCUMENTOSERIE, DOCUMENTOTERMINAL, DOCUMENTONUMERO);

CREATE TABLE JAVIER.COBROS_LIQ LIKE DSTMOVIL.LIQUIDIARI;
CREATE INDEX JAVIER.COBROS_LIQ_IX1 ON JAVIER.COBROS_LIQ (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO);
CREATE INDEX JAVIER.COBROS_LIQ_IX2 ON JAVIER.COBROS_LIQ (VENDEDOR, FECHAANO, FECHAMES, FECHADIA);
CREATE INDEX JAVIER.COBROS_LIQ_IX3 ON JAVIER.COBROS_LIQ (USUARIO, FECHAANO, FECHAMES, FECHADIA);
CREATE INDEX JAVIER.COBROS_LIQ_IX4 ON JAVIER.COBROS_LIQ (MARCASINCRONIZACION);

-- ============================================================
-- 3_POSTVALIDATION
-- ============================================================

SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS', 'COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
ORDER BY TABLE_NAME;

SELECT TABLE_SCHEMA, TABLE_NAME, COUNT(*) AS COLUMN_COUNT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS', 'COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
GROUP BY TABLE_SCHEMA, TABLE_NAME
ORDER BY TABLE_NAME;

SELECT 'COBROCABEC_MINUS_COBROS_CAB' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROCABEC'
EXCEPT
SELECT 'COBROCABEC_MINUS_COBROS_CAB' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_CAB'
ORDER BY COLUMN_NAME;

SELECT 'COBROS_CAB_MINUS_COBROCABEC' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_CAB'
EXCEPT
SELECT 'COBROS_CAB_MINUS_COBROCABEC' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROCABEC'
ORDER BY COLUMN_NAME;

SELECT 'COBROLINEA_MINUS_COBROS_LIN' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROLINEA'
EXCEPT
SELECT 'COBROLINEA_MINUS_COBROS_LIN' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIN'
ORDER BY COLUMN_NAME;

SELECT 'COBROS_LIN_MINUS_COBROLINEA' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIN'
EXCEPT
SELECT 'COBROS_LIN_MINUS_COBROLINEA' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROLINEA'
ORDER BY COLUMN_NAME;

SELECT 'LIQUIDIARI_MINUS_COBROS_LIQ' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'LIQUIDIARI'
EXCEPT
SELECT 'LIQUIDIARI_MINUS_COBROS_LIQ' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIQ'
ORDER BY COLUMN_NAME;

SELECT 'COBROS_LIQ_MINUS_LIQUIDIARI' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIQ'
EXCEPT
SELECT 'COBROS_LIQ_MINUS_LIQUIDIARI' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'LIQUIDIARI'
ORDER BY COLUMN_NAME;

SELECT COUNT(*) AS EXPECTED_INDEX_COUNT
FROM QSYS2.SYSINDEXES
WHERE INDEX_SCHEMA = 'JAVIER'
  AND INDEX_NAME IN (
    'COBROS_CAB_IX1', 'COBROS_CAB_IX2', 'COBROS_CAB_IX3', 'COBROS_CAB_IX4',
    'COBROS_LIN_IX1', 'COBROS_LIN_IX2', 'COBROS_LIN_IX3',
    'COBROS_LIQ_IX1', 'COBROS_LIQ_IX2', 'COBROS_LIQ_IX3', 'COBROS_LIQ_IX4'
  );

SELECT INDEX_SCHEMA, INDEX_NAME, TABLE_SCHEMA, TABLE_NAME
FROM QSYS2.SYSINDEXES
WHERE INDEX_SCHEMA = 'JAVIER'
  AND INDEX_NAME IN (
    'COBROS_CAB_IX1', 'COBROS_CAB_IX2', 'COBROS_CAB_IX3', 'COBROS_CAB_IX4',
    'COBROS_LIN_IX1', 'COBROS_LIN_IX2', 'COBROS_LIN_IX3',
    'COBROS_LIQ_IX1', 'COBROS_LIQ_IX2', 'COBROS_LIQ_IX3', 'COBROS_LIQ_IX4'
  )
ORDER BY INDEX_NAME;

SELECT TABLE_SCHEMA, TABLE_NAME, COUNT(*) AS COLUMN_COUNT,
       CASE WHEN COUNT(*) = 43 THEN 'PASS' ELSE 'FAIL' END AS EXPECTED_43_COLUMNS
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS'
GROUP BY TABLE_SCHEMA, TABLE_NAME;

-- ============================================================
-- 4_ROLLBACK_NOT_FOR_NORMAL_EXECUTION
-- WARNING: Do NOT execute rollback unless explicitly instructed.
-- ============================================================

-- DROP TABLE JAVIER.COBROS_LIQ;
-- DROP TABLE JAVIER.COBROS_LIN;
-- DROP TABLE JAVIER.COBROS_CAB;
