-- 033_cobros_mirror_tables.sql
-- Static DB2 for i migration artifact only. DO NOT execute without approved DB2 change window.
-- NO DB2 execution was performed while creating this file.
-- Allowed writes in this artifact: CREATE/DROP objects in JAVIER only for COBROS_CAB, COBROS_LIN, COBROS_LIQ.
-- DSTMOVIL is source-read/catalog-read only. Source schema is never the DDL target.
-- JAVIER.COBROS is intentionally left unchanged.
-- LIQDIACUE intentionally omitted: verified as 0-row detail view in planning; separate child table needs separate approval.

-- ============================================================================
-- PREFLIGHT: run manually before FORWARD SQL. Read-only QSYS2/catalog checks.
-- ============================================================================

-- Source and target table presence. Expected source rows: 3. Expected target rows before first run: 0.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE (TABLE_SCHEMA = 'DSTMOVIL' AND TABLE_NAME IN ('COBROCABEC', 'COBROLINEA', 'LIQUIDIARI'))
   OR (TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME IN ('COBROS', 'COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ'))
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- Source column counts must match approval: COBROCABEC=27, COBROLINEA=17, LIQUIDIARI=27.
SELECT TABLE_SCHEMA,
       TABLE_NAME,
       COUNT(*) AS COLUMN_COUNT,
       CASE TABLE_NAME
         WHEN 'COBROCABEC' THEN 27
         WHEN 'COBROLINEA' THEN 17
         WHEN 'LIQUIDIARI' THEN 27
       END AS EXPECTED_COLUMN_COUNT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME IN ('COBROCABEC', 'COBROLINEA', 'LIQUIDIARI')
GROUP BY TABLE_SCHEMA, TABLE_NAME
ORDER BY TABLE_NAME;

-- Target column counts, if tables already exist. Must match source after FORWARD SQL.
SELECT TABLE_SCHEMA, TABLE_NAME, COUNT(*) AS COLUMN_COUNT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
GROUP BY TABLE_SCHEMA, TABLE_NAME
ORDER BY TABLE_NAME;

-- JAVIER.COBROS must remain present and unchanged by this migration.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS';

SELECT TABLE_SCHEMA, TABLE_NAME, COUNT(*) AS COLUMN_COUNT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS'
GROUP BY TABLE_SCHEMA, TABLE_NAME;

-- ============================================================================
-- FORWARD SQL: creates JAVIER mirror tables and explicit idempotent indexes.
-- ============================================================================

--#SET TERMINATOR @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE TABLE JAVIER.COBROS_CAB LIKE DSTMOVIL.COBROCABEC;
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE TABLE JAVIER.COBROS_LIN LIKE DSTMOVIL.COBROLINEA;
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE TABLE JAVIER.COBROS_LIQ LIKE DSTMOVIL.LIQUIDIARI;
END @

-- Explicit indexes. Each block is idempotent for re-runs.
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE UNIQUE INDEX JAVIER.UX_COBROS_CAB_KEY ON JAVIER.COBROS_CAB (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO);
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE INDEX JAVIER.IX_COBROS_CAB_CLIENTE_FECHA ON JAVIER.COBROS_CAB (CLIENTE, FECHAEMISIONANO, FECHAEMISIONMES, FECHAEMISIONDIA);
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE INDEX JAVIER.IX_COBROS_CAB_LIQ ON JAVIER.COBROS_CAB (LIQUIDACIONSUBEMPRESA, LIQUIDACIONEJERCICIO, LIQUIDACIONSERIE, LIQUIDACIONTERMINAL, LIQUIDACIONNUMERO);
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE UNIQUE INDEX JAVIER.UX_COBROS_LIN_KEY ON JAVIER.COBROS_LIN (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, SECUENCIA);
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE INDEX JAVIER.IX_COBROS_LIN_CAB ON JAVIER.COBROS_LIN (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO);
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE INDEX JAVIER.IX_COBROS_LIN_DOC ON JAVIER.COBROS_LIN (DOCUMENTOSUBEMPRESA, DOCUMENTOEJERCICIO, DOCUMENTOSERIE, DOCUMENTOTERMINAL, DOCUMENTONUMERO);
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE UNIQUE INDEX JAVIER.UX_COBROS_LIQ_KEY ON JAVIER.COBROS_LIQ (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO);
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE INDEX JAVIER.IX_COBROS_LIQ_VEND_FECHA ON JAVIER.COBROS_LIQ (VENDEDOR, FECHAANO, FECHAMES, FECHADIA);
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  CREATE INDEX JAVIER.IX_COBROS_LIQ_MARCA ON JAVIER.COBROS_LIQ (MARCASINCRONIZACION);
END @
--#SET TERMINATOR ;

-- ============================================================================
-- POST-VALIDATION: run manually after FORWARD SQL. Read-only checks.
-- ============================================================================

-- Expected target rows: 3.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
ORDER BY TABLE_NAME;

-- Expected counts: COBROS_CAB=27, COBROS_LIN=17, COBROS_LIQ=27.
SELECT TABLE_SCHEMA, TABLE_NAME, COUNT(*) AS COLUMN_COUNT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
GROUP BY TABLE_SCHEMA, TABLE_NAME
ORDER BY TABLE_NAME;

-- Source-minus-target metadata drift. Expected: 0 rows for each EXCEPT query.
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROCABEC'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_CAB';

SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_CAB'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROCABEC';

SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROLINEA'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIN';

SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIN'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROLINEA';

SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'LIQUIDIARI'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIQ';

SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIQ'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'LIQUIDIARI';

-- JAVIER.COBROS remains untouched by this artifact.
SELECT TABLE_SCHEMA, TABLE_NAME, COUNT(*) AS COLUMN_COUNT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS'
GROUP BY TABLE_SCHEMA, TABLE_NAME;

-- ============================================================================
-- ROLLBACK: guarded. Drops only empty mirror tables; leaves JAVIER.COBROS intact.
-- ============================================================================

--#SET TERMINATOR @

BEGIN
  DECLARE v_exists INTEGER DEFAULT 0;
  DECLARE v_rows BIGINT DEFAULT 0;

  SELECT COUNT(*) INTO v_exists
  FROM QSYS2.SYSTABLES
  WHERE TABLE_SCHEMA = 'JAVIER'
    AND TABLE_NAME = 'COBROS_LIQ';

  IF v_exists = 1 THEN
    SELECT COUNT(*) INTO v_rows FROM JAVIER.COBROS_LIQ;
    IF v_rows = 0 THEN
      DROP TABLE JAVIER.COBROS_LIQ;
    ELSE
      SIGNAL SQLSTATE '75001' SET MESSAGE_TEXT = 'Rollback blocked: JAVIER.COBROS_LIQ is not empty';
    END IF;
  END IF;
END @

BEGIN
  DECLARE v_exists INTEGER DEFAULT 0;
  DECLARE v_rows BIGINT DEFAULT 0;

  SELECT COUNT(*) INTO v_exists
  FROM QSYS2.SYSTABLES
  WHERE TABLE_SCHEMA = 'JAVIER'
    AND TABLE_NAME = 'COBROS_LIN';

  IF v_exists = 1 THEN
    SELECT COUNT(*) INTO v_rows FROM JAVIER.COBROS_LIN;
    IF v_rows = 0 THEN
      DROP TABLE JAVIER.COBROS_LIN;
    ELSE
      SIGNAL SQLSTATE '75002' SET MESSAGE_TEXT = 'Rollback blocked: JAVIER.COBROS_LIN is not empty';
    END IF;
  END IF;
END @

BEGIN
  DECLARE v_exists INTEGER DEFAULT 0;
  DECLARE v_rows BIGINT DEFAULT 0;

  SELECT COUNT(*) INTO v_exists
  FROM QSYS2.SYSTABLES
  WHERE TABLE_SCHEMA = 'JAVIER'
    AND TABLE_NAME = 'COBROS_CAB';

  IF v_exists = 1 THEN
    SELECT COUNT(*) INTO v_rows FROM JAVIER.COBROS_CAB;
    IF v_rows = 0 THEN
      DROP TABLE JAVIER.COBROS_CAB;
    ELSE
      SIGNAL SQLSTATE '75003' SET MESSAGE_TEXT = 'Rollback blocked: JAVIER.COBROS_CAB is not empty';
    END IF;
  END IF;
END @

--#SET TERMINATOR ;

