-- Self-contained isolated finance schema for canonical daily liquidation.
-- Prepared DDL only: execution requires the DB2 approval gate. No data copy.
-- Existing objects are accepted only when their complete manifest is exact.

--#SET TERMINATOR @
BEGIN
  IF EXISTS (
    SELECT 1 FROM (
      VALUES
        ('TEST_REPARTIDOR_COBROS','ID','INTEGER',4,9,0,'NO','NO','','YES','ALWAYS'),
        ('TEST_REPARTIDOR_COBROS','CODIGOVENDEDOR','CHAR',2,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_COBROS','DIACOBRO','NUMERIC',2,2,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_COBROS','MESCOBRO','NUMERIC',2,2,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_COBROS','ANOCOBRO','NUMERIC',3,4,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_COBROS','IMPORTEVENCIMIENTO','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_COBROS','CODIGOFORMAPAGO','CHAR',2,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_COBROS','CREATED_AT','TIMESTAMP',10,-1,-1,'YES','YES','CURRENTTIMESTAMP','NO',''),
        ('TEST_REPARTIDOR_COBROS','LIQUIDADO_SN','CHAR',1,-1,-1,'YES','YES','N','NO',''),
        ('TEST_REPARTIDOR_COBROS','LIQUIDACION_TOKEN','VARCHAR',128,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_COBROS','NUMEROLIQUIDACION','NUMERIC',4,6,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_COBROS_AUDIT','ID','INTEGER',4,9,0,'NO','NO','','YES','ALWAYS'),
        ('TEST_REPARTIDOR_COBROS_AUDIT','EVENT_TYPE','VARCHAR',40,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_COBROS_AUDIT','OPERADOR','VARCHAR',40,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_COBROS_AUDIT','CODIGO_REPARTIDOR','VARCHAR',10,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_COBROS_AUDIT','PAYLOAD_PREVIEW','VARCHAR',500,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_COBROS_AUDIT','CREATED_AT','TIMESTAMP',10,-1,-1,'YES','YES','CURRENTTIMESTAMP','NO',''),
        ('TEST_REPARTIDOR_FINANCIAL_BALANCES','CODIGO_REPARTIDOR','VARCHAR',20,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_FINANCIAL_BALANCES','SALDO_PENDIENTE','DECIMAL',8,15,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','SUBEMPRESALIQUIDACION','CHAR',3,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','EJERCICIOLIQUIDACION','NUMERIC',3,4,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','SERIELIQUIDACION','CHAR',1,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','TERMINALLIQUIDACION','NUMERIC',2,3,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','NUMEROLIQUIDACION','NUMERIC',4,6,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','DIALIQUIDACION','NUMERIC',2,2,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','MESLIQUIDACION','NUMERIC',2,2,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','ANOLIQUIDACION','NUMERIC',3,4,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','HORALIQUIDACION','NUMERIC',4,6,0,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','CODIGOVENDEDOR','CHAR',2,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','CODIGOVENDEDORUSUARIO','CHAR',2,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','CODIGOUSUARIO','CHAR',10,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','MATRICULA','CHAR',20,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','KILOMETROSSALIDA','NUMERIC',6,11,3,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','KILOMETROSLLEGADA','NUMERIC',6,11,3,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','KILOMETROSRECORRIDOS','NUMERIC',6,11,3,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPORTEEFECTIVO','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPORTECHEQUES','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPORTEPOSTDATADOS','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPORTESALDOACTUAL','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPORTETOTALAINGRESAR','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPORTEINGRESOENBANCO','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPORTEGASTOS','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPRESOSN','CHAR',1,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','CODIGOVEHICULO','CHAR',10,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','REVISADOSN','CHAR',1,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IDMARCALIQUIDACION','CHAR',30,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPORTEEFECTIVO2','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPORTEENTREGADO2','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IMPORTETARJETA','NUMERIC',6,10,2,'NO','YES','0','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','ID','INTEGER',4,9,0,'NO','NO','','YES','ALWAYS'),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','MARCAACTUALIZACION','VARCHAR',50,-1,-1,'NO','YES','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','IDEMPOTENCY_TOKEN','VARCHAR',128,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','REPLAY_IDENTITY_JSON','CLOB',8192,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','SNAPSHOT_JSON','CLOB',65536,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','STATUS','VARCHAR',20,-1,-1,'YES','YES','CLOSED','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','OPERADOR','VARCHAR',50,-1,-1,'YES','YES','SYSTEM','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','PANTALLA_ORIGEN','VARCHAR',20,-1,-1,'YES','YES','LIQUIDACIONDIARIA','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','CREATED_AT','TIMESTAMP',10,-1,-1,'YES','YES','CURRENTTIMESTAMP','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','UPDATED_AT','TIMESTAMP',10,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','ID','BIGINT',8,18,0,'NO','NO','','YES','ALWAYS'),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','IDEMPOTENCY_TOKEN','VARCHAR',128,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CODIGO_REPARTIDOR','CHAR',2,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','DIA','NUMERIC',2,2,0,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','MES','NUMERIC',2,2,0,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','ANO','NUMERIC',3,4,0,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','IMPORTE','DECIMAL',6,10,2,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CATEGORIA','VARCHAR',40,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','OBSERVACION','VARCHAR',250,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','STATUS','VARCHAR',12,-1,-1,'NO','YES','PENDING','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','LIQUIDACION_ID','BIGINT',8,18,0,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','LIQUIDACION_MARKER','CHAR',30,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','ACTOR_ID','VARCHAR',40,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','ACTOR_ROLE','VARCHAR',30,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CREATED_AT','TIMESTAMP',10,-1,-1,'NO','YES','CURRENTTIMESTAMP','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','ID','BIGINT',8,18,0,'NO','NO','','YES','ALWAYS'),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','IDEMPOTENCY_TOKEN','VARCHAR',128,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','CODIGO_REPARTIDOR','CHAR',2,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','DIA','NUMERIC',2,2,0,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','MES','NUMERIC',2,2,0,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','ANO','NUMERIC',3,4,0,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','IMPORTE','DECIMAL',6,10,2,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','MOTIVO','VARCHAR',120,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','OBSERVACION','VARCHAR',250,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','STATUS','VARCHAR',12,-1,-1,'NO','YES','PENDING','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','LIQUIDACION_ID','BIGINT',8,18,0,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','LIQUIDACION_MARKER','CHAR',30,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','ACTOR_ID','VARCHAR',40,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','ACTOR_ROLE','VARCHAR',30,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','CREATED_AT','TIMESTAMP',10,-1,-1,'NO','YES','CURRENTTIMESTAMP','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','ID','BIGINT',8,18,0,'NO','NO','','YES','ALWAYS'),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','IDEMPOTENCY_TOKEN','VARCHAR',128,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','CODIGO_REPARTIDOR','CHAR',2,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','DIA','NUMERIC',2,2,0,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','MES','NUMERIC',2,2,0,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','ANO','NUMERIC',3,4,0,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','IMPORTE','DECIMAL',6,10,2,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','REFERENCIA','VARCHAR',80,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','OBSERVACION','VARCHAR',250,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','STATUS','VARCHAR',12,-1,-1,'NO','YES','PENDING','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','LIQUIDACION_ID','BIGINT',8,18,0,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','LIQUIDACION_MARKER','CHAR',30,-1,-1,'YES','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','ACTOR_ID','VARCHAR',40,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','ACTOR_ROLE','VARCHAR',30,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','CREATED_AT','TIMESTAMP',10,-1,-1,'NO','YES','CURRENTTIMESTAMP','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','ID','BIGINT',8,18,0,'NO','NO','','YES','ALWAYS'),
        ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','LIQUIDACION_ID','BIGINT',8,18,0,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','OUTBOX_TYPE','VARCHAR',50,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','STATUS','VARCHAR',20,-1,-1,'NO','YES','PENDING','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','PAYLOAD_JSON','CLOB',16384,-1,-1,'NO','NO','','NO',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','CREATED_AT','TIMESTAMP',10,-1,-1,'NO','YES','CURRENTTIMESTAMP','NO','')
    ) AS E(TABLE_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, IS_NULLABLE, HAS_DEFAULT, COLUMN_DEFAULT, IS_IDENTITY, IDENTITY_GENERATION)
    FULL OUTER JOIN (
      SELECT TABLE_NAME, COLUMN_NAME,
        CASE WHEN TRIM(DATA_TYPE)='TIMESTMP' THEN 'TIMESTAMP' ELSE TRIM(DATA_TYPE) END AS DATA_TYPE,
        CASE WHEN TRIM(DATA_TYPE) IN ('NUMERIC','DECIMAL')
          THEN INTEGER(NUMERIC_PRECISION / 2) + 1 ELSE LENGTH END AS LENGTH,
        COALESCE(NUMERIC_PRECISION,-1) AS NUMERIC_PRECISION,
        COALESCE(NUMERIC_SCALE,-1) AS NUMERIC_SCALE,
        CASE IS_NULLABLE WHEN 'Y' THEN 'YES' WHEN 'N' THEN 'NO' ELSE IS_NULLABLE END AS IS_NULLABLE,
        CASE WHEN HAS_DEFAULT='Y' AND COLUMN_DEFAULT IS NOT NULL THEN 'YES' ELSE 'NO' END AS HAS_DEFAULT,
        UPPER(REPLACE(REPLACE(REPLACE(COALESCE(TRIM(COLUMN_DEFAULT),''),'''',''),'_',''),' ','')) AS COLUMN_DEFAULT,
        IS_IDENTITY, COALESCE(IDENTITY_GENERATION,'') AS IDENTITY_GENERATION
      FROM QSYS2.SYSCOLUMNS2
      WHERE TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME LIKE 'TEST_REPARTIDOR_%'
    ) AS A
      ON A.TABLE_NAME = E.TABLE_NAME AND A.COLUMN_NAME = E.COLUMN_NAME
    WHERE COALESCE(E.TABLE_NAME,A.TABLE_NAME) IN (
      SELECT TABLE_NAME FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA = 'JAVIER'
    ) AND (E.COLUMN_NAME IS NULL OR A.COLUMN_NAME IS NULL OR E.DATA_TYPE <> A.DATA_TYPE
      OR E.LENGTH <> A.LENGTH OR E.NUMERIC_PRECISION <> A.NUMERIC_PRECISION
      OR E.NUMERIC_SCALE <> A.NUMERIC_SCALE OR E.IS_NULLABLE <> A.IS_NULLABLE
      OR E.HAS_DEFAULT <> A.HAS_DEFAULT OR E.COLUMN_DEFAULT <> A.COLUMN_DEFAULT
      OR E.IS_IDENTITY <> A.IS_IDENTITY OR E.IDENTITY_GENERATION <> A.IDENTITY_GENERATION)
    FETCH FIRST 1 ROW ONLY
  ) THEN
    SIGNAL SQLSTATE '75010' SET MESSAGE_TEXT = 'STOP_TEST_TABLE_METADATA_MISMATCH';
  END IF;
END@

BEGIN
  IF EXISTS (
    SELECT 1 FROM QSYS2.SYSCOLUMNS2
    WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME LIKE 'TEST_REPARTIDOR_%'
      AND ((IS_IDENTITY='YES' AND (COALESCE(IDENTITY_GENERATION,'')<>'ALWAYS'
        OR COALESCE(IDENTITY_START,0)<>1 OR COALESCE(IDENTITY_INCREMENT,0)<>1))
        OR (IS_IDENTITY='NO' AND (IDENTITY_START IS NOT NULL OR IDENTITY_INCREMENT IS NOT NULL)))
    FETCH FIRST 1 ROW ONLY
  ) THEN
    SIGNAL SQLSTATE '75015' SET MESSAGE_TEXT = 'STOP_TEST_IDENTITY_METADATA_MISMATCH';
  END IF;
END@

BEGIN
  IF EXISTS (
    SELECT 1 FROM (
      VALUES
        ('TEST_REPARTIDOR_COBROS','PRIMARY KEY','ID',''),
        ('TEST_REPARTIDOR_COBROS_AUDIT','PRIMARY KEY','ID',''),
        ('TEST_REPARTIDOR_FINANCIAL_BALANCES','PRIMARY KEY','CODIGO_REPARTIDOR',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OPS','PRIMARY KEY','ID',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','PRIMARY KEY','ID',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','UNIQUE','IDEMPOTENCY_TOKEN',''),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CHECK','','IMPORTE>0'),
        ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','PRIMARY KEY','ID',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','UNIQUE','IDEMPOTENCY_TOKEN',''),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','CHECK','','IMPORTE<>0'),
        ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','PRIMARY KEY','ID',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','UNIQUE','IDEMPOTENCY_TOKEN',''),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','CHECK','','IMPORTE>0'),
        ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
        ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','PRIMARY KEY','ID',''),
        ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','CHECK','','STATUSIN''PENDING'',''SENT'',''FAILED''')
    ) AS E(TABLE_NAME, CONSTRAINT_TYPE, KEYS, CHECK_CONDITION)
    LEFT JOIN (
      SELECT X.TABLE_NAME,
        CASE X.CONSTRAINT_TYPE
          WHEN 'P' THEN 'PRIMARY KEY'
          WHEN 'U' THEN 'UNIQUE'
          WHEN 'C' THEN 'CHECK'
          WHEN 'F' THEN 'FOREIGN KEY'
          ELSE TRIM(X.CONSTRAINT_TYPE)
        END AS CONSTRAINT_TYPE,
        COALESCE(LISTAGG(K.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION),'') AS KEYS,
        COALESCE(MAX(UPPER(REPLACE(REPLACE(REPLACE(COALESCE(CAST(C.CHECK_CLAUSE AS VARCHAR(4096)),''),' ',''),'(',''),')',''))),'') AS CHECK_CONDITION
      FROM QSYS2.SYSCST X
      LEFT JOIN QSYS2.SYSKEYCST K
        ON K.CONSTRAINT_SCHEMA = X.CONSTRAINT_SCHEMA AND K.CONSTRAINT_NAME = X.CONSTRAINT_NAME
      LEFT JOIN QSYS2.SYSCHKCST C
        ON C.CONSTRAINT_SCHEMA = X.CONSTRAINT_SCHEMA AND C.CONSTRAINT_NAME = X.CONSTRAINT_NAME
      WHERE X.TABLE_SCHEMA = 'JAVIER' AND X.TABLE_NAME LIKE 'TEST_REPARTIDOR_%'
      GROUP BY X.TABLE_NAME, X.CONSTRAINT_NAME, X.CONSTRAINT_TYPE
    ) AS A ON A.TABLE_NAME = E.TABLE_NAME
      AND A.CONSTRAINT_TYPE = E.CONSTRAINT_TYPE AND A.KEYS = E.KEYS
      AND A.CHECK_CONDITION = E.CHECK_CONDITION
    WHERE E.TABLE_NAME IN (SELECT TABLE_NAME FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER')
      AND A.TABLE_NAME IS NULL FETCH FIRST 1 ROW ONLY
  ) THEN
    SIGNAL SQLSTATE '75011' SET MESSAGE_TEXT = 'STOP_TEST_CONSTRAINT_METADATA_MISMATCH';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='TEST_REPARTIDOR_COBROS') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.TEST_REPARTIDOR_COBROS (ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, CODIGOVENDEDOR CHAR(2) NOT NULL DEFAULT '' '', DIACOBRO NUMERIC(2) NOT NULL DEFAULT 0, MESCOBRO NUMERIC(2) NOT NULL DEFAULT 0, ANOCOBRO NUMERIC(4) NOT NULL DEFAULT 0, IMPORTEVENCIMIENTO NUMERIC(10,2) NOT NULL DEFAULT 0, CODIGOFORMAPAGO CHAR(2) NOT NULL DEFAULT '' '', CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP, LIQUIDADO_SN CHAR(1) DEFAULT ''N'', LIQUIDACION_TOKEN VARCHAR(128), NUMEROLIQUIDACION NUMERIC(6) NOT NULL DEFAULT 0)';
  END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='TEST_REPARTIDOR_COBROS_AUDIT') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.TEST_REPARTIDOR_COBROS_AUDIT (ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, EVENT_TYPE VARCHAR(40) NOT NULL, OPERADOR VARCHAR(40), CODIGO_REPARTIDOR VARCHAR(10), PAYLOAD_PREVIEW VARCHAR(500), CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP)';
  END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='TEST_REPARTIDOR_FINANCIAL_BALANCES') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.TEST_REPARTIDOR_FINANCIAL_BALANCES (CODIGO_REPARTIDOR VARCHAR(20) NOT NULL PRIMARY KEY, SALDO_PENDIENTE DECIMAL(15,2) NOT NULL DEFAULT 0)';
  END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='TEST_REPARTIDOR_LIQUIDACION_OPS') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.TEST_REPARTIDOR_LIQUIDACION_OPS (SUBEMPRESALIQUIDACION CHAR(3) NOT NULL DEFAULT '' '', EJERCICIOLIQUIDACION NUMERIC(4) NOT NULL DEFAULT 0, SERIELIQUIDACION CHAR(1) NOT NULL DEFAULT '' '', TERMINALLIQUIDACION NUMERIC(3) NOT NULL DEFAULT 0, NUMEROLIQUIDACION NUMERIC(6) NOT NULL DEFAULT 0, DIALIQUIDACION NUMERIC(2) NOT NULL DEFAULT 0, MESLIQUIDACION NUMERIC(2) NOT NULL DEFAULT 0, ANOLIQUIDACION NUMERIC(4) NOT NULL DEFAULT 0, HORALIQUIDACION NUMERIC(6) NOT NULL DEFAULT 0, CODIGOVENDEDOR CHAR(2) NOT NULL DEFAULT '' '', CODIGOVENDEDORUSUARIO CHAR(2) NOT NULL DEFAULT '' '', CODIGOUSUARIO CHAR(10) NOT NULL DEFAULT '' '', MATRICULA CHAR(20) NOT NULL DEFAULT '' '', KILOMETROSSALIDA NUMERIC(11,3) NOT NULL DEFAULT 0, KILOMETROSLLEGADA NUMERIC(11,3) NOT NULL DEFAULT 0, KILOMETROSRECORRIDOS NUMERIC(11,3) NOT NULL DEFAULT 0, IMPORTEEFECTIVO NUMERIC(10,2) NOT NULL DEFAULT 0, IMPORTECHEQUES NUMERIC(10,2) NOT NULL DEFAULT 0, IMPORTEPOSTDATADOS NUMERIC(10,2) NOT NULL DEFAULT 0, IMPORTESALDOACTUAL NUMERIC(10,2) NOT NULL DEFAULT 0, IMPORTETOTALAINGRESAR NUMERIC(10,2) NOT NULL DEFAULT 0, IMPORTEINGRESOENBANCO NUMERIC(10,2) NOT NULL DEFAULT 0, IMPORTEGASTOS NUMERIC(10,2) NOT NULL DEFAULT 0, IMPRESOSN CHAR(1) NOT NULL DEFAULT '' '', CODIGOVEHICULO CHAR(10) NOT NULL DEFAULT '' '', REVISADOSN CHAR(1) NOT NULL DEFAULT '' '', IDMARCALIQUIDACION CHAR(30) NOT NULL DEFAULT '' '', IMPORTEEFECTIVO2 NUMERIC(10,2) NOT NULL DEFAULT 0, IMPORTEENTREGADO2 NUMERIC(10,2) NOT NULL DEFAULT 0, IMPORTETARJETA NUMERIC(10,2) NOT NULL DEFAULT 0, ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, MARCAACTUALIZACION VARCHAR(50) NOT NULL DEFAULT '' '', IDEMPOTENCY_TOKEN VARCHAR(128), REPLAY_IDENTITY_JSON CLOB(8K), SNAPSHOT_JSON CLOB(64K), STATUS VARCHAR(20) DEFAULT ''CLOSED'', OPERADOR VARCHAR(50) DEFAULT ''system'', PANTALLA_ORIGEN VARCHAR(20) DEFAULT ''LIQUIDACION_DIARIA'', CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP, UPDATED_AT TIMESTAMP)';
  END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='TEST_REPARTIDOR_LIQUIDACION_GASTOS') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.TEST_REPARTIDOR_LIQUIDACION_GASTOS (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL UNIQUE, CODIGO_REPARTIDOR CHAR(2) NOT NULL, DIA NUMERIC(2) NOT NULL, MES NUMERIC(2) NOT NULL, ANO NUMERIC(4) NOT NULL, IMPORTE DECIMAL(10,2) NOT NULL, CATEGORIA VARCHAR(40) NOT NULL, OBSERVACION VARCHAR(250), STATUS VARCHAR(12) NOT NULL DEFAULT ''PENDING'', LIQUIDACION_ID BIGINT, LIQUIDACION_MARKER CHAR(30), ACTOR_ID VARCHAR(40) NOT NULL, ACTOR_ROLE VARCHAR(30) NOT NULL, CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, CONSTRAINT CK_T_LIQ_GASTO_IMP CHECK (IMPORTE > 0), CONSTRAINT CK_T_LIQ_GASTO_STATUS CHECK (STATUS IN (''PENDING'', ''LIQUIDATED'')))';
  END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='TEST_REPARTIDOR_LIQUIDACION_AJUSTES') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.TEST_REPARTIDOR_LIQUIDACION_AJUSTES (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL UNIQUE, CODIGO_REPARTIDOR CHAR(2) NOT NULL, DIA NUMERIC(2) NOT NULL, MES NUMERIC(2) NOT NULL, ANO NUMERIC(4) NOT NULL, IMPORTE DECIMAL(10,2) NOT NULL, MOTIVO VARCHAR(120) NOT NULL, OBSERVACION VARCHAR(250), STATUS VARCHAR(12) NOT NULL DEFAULT ''PENDING'', LIQUIDACION_ID BIGINT, LIQUIDACION_MARKER CHAR(30), ACTOR_ID VARCHAR(40) NOT NULL, ACTOR_ROLE VARCHAR(30) NOT NULL, CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, CONSTRAINT CK_T_LIQ_AJUSTE_NZ CHECK (IMPORTE <> 0), CONSTRAINT CK_T_LIQ_AJUSTE_STATUS CHECK (STATUS IN (''PENDING'', ''LIQUIDATED'')))';
  END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='TEST_REPARTIDOR_LIQUIDACION_INGRESOS') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.TEST_REPARTIDOR_LIQUIDACION_INGRESOS (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL UNIQUE, CODIGO_REPARTIDOR CHAR(2) NOT NULL, DIA NUMERIC(2) NOT NULL, MES NUMERIC(2) NOT NULL, ANO NUMERIC(4) NOT NULL, IMPORTE DECIMAL(10,2) NOT NULL, REFERENCIA VARCHAR(80) NOT NULL, OBSERVACION VARCHAR(250), STATUS VARCHAR(12) NOT NULL DEFAULT ''PENDING'', LIQUIDACION_ID BIGINT, LIQUIDACION_MARKER CHAR(30), ACTOR_ID VARCHAR(40) NOT NULL, ACTOR_ROLE VARCHAR(30) NOT NULL, CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, CONSTRAINT CK_T_LIQ_INGRESO_IMP CHECK (IMPORTE > 0), CONSTRAINT CK_T_LIQ_INGRESO_STATUS CHECK (STATUS IN (''PENDING'', ''LIQUIDATED'')))';
  END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='TEST_REPARTIDOR_LIQUIDACION_OUTBOX') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.TEST_REPARTIDOR_LIQUIDACION_OUTBOX (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, LIQUIDACION_ID BIGINT NOT NULL, OUTBOX_TYPE VARCHAR(50) NOT NULL, STATUS VARCHAR(20) NOT NULL DEFAULT ''PENDING'', PAYLOAD_JSON CLOB(16K) NOT NULL, CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, CONSTRAINT CK_T_LIQ_OUTBOX_STATUS CHECK (STATUS IN (''PENDING'', ''SENT'', ''FAILED'')))';
  END IF;
END@

-- Each existing named index is checked before it can be accepted.
BEGIN
  IF EXISTS (
    SELECT 1 FROM (
      VALUES
      ('UX_T_RLO_TOKEN','TEST_REPARTIDOR_LIQUIDACION_OPS','YES','IDEMPOTENCY_TOKEN:A'),
      ('UX_T_RLO_MARKER','TEST_REPARTIDOR_LIQUIDACION_OPS','YES','IDMARCALIQUIDACION:A'),
      ('UX_T_RLO_REP_DAY','TEST_REPARTIDOR_LIQUIDACION_OPS','YES','CODIGOVENDEDOR:A,DIALIQUIDACION:A,MESLIQUIDACION:A,ANOLIQUIDACION:A'),
      ('IX_T_LIQ_GASTO_DAY','TEST_REPARTIDOR_LIQUIDACION_GASTOS','NO','CODIGO_REPARTIDOR:A,DIA:A,MES:A,ANO:A,STATUS:A'),
      ('IX_T_LIQ_AJUSTE_DAY','TEST_REPARTIDOR_LIQUIDACION_AJUSTES','NO','CODIGO_REPARTIDOR:A,DIA:A,MES:A,ANO:A,STATUS:A'),
      ('IX_T_LIQ_INGRESO_DAY','TEST_REPARTIDOR_LIQUIDACION_INGRESOS','NO','CODIGO_REPARTIDOR:A,DIA:A,MES:A,ANO:A,STATUS:A'),
      ('IX_T_LIQ_OUTBOX_STATUS','TEST_REPARTIDOR_LIQUIDACION_OUTBOX','NO','STATUS:A,CREATED_AT:A')
    ) AS E(INDEX_NAME,TABLE_NAME,IS_UNIQUE,KEYS)
    JOIN (
      SELECT I.INDEX_NAME,I.TABLE_NAME,CASE I.IS_UNIQUE WHEN 'U' THEN 'YES' WHEN 'D' THEN 'NO' ELSE I.IS_UNIQUE END AS IS_UNIQUE,
        LISTAGG(K.COLUMN_NAME || ':' || K.ORDERING,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION) AS KEYS
      FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K
        ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME
      WHERE I.INDEX_SCHEMA='JAVIER'
      GROUP BY I.INDEX_NAME,I.TABLE_NAME,I.IS_UNIQUE
    ) AS A ON A.INDEX_NAME=E.INDEX_NAME
      WHERE A.TABLE_NAME<>E.TABLE_NAME OR A.IS_UNIQUE<>E.IS_UNIQUE OR A.KEYS<>E.KEYS
      FETCH FIRST 1 ROW ONLY
  ) THEN SIGNAL SQLSTATE '75012' SET MESSAGE_TEXT='STOP_TEST_INDEX_METADATA_MISMATCH'; END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME WHERE I.TABLE_SCHEMA='JAVIER' AND I.TABLE_NAME='TEST_REPARTIDOR_LIQUIDACION_OPS' AND I.IS_UNIQUE IN ('YES','U') GROUP BY I.INDEX_SCHEMA,I.INDEX_NAME HAVING LISTAGG(K.COLUMN_NAME,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION)='IDEMPOTENCY_TOKEN') THEN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX JAVIER.UX_T_RLO_TOKEN ON JAVIER.TEST_REPARTIDOR_LIQUIDACION_OPS (IDEMPOTENCY_TOKEN)'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME WHERE I.TABLE_SCHEMA='JAVIER' AND I.TABLE_NAME='TEST_REPARTIDOR_LIQUIDACION_OPS' AND I.IS_UNIQUE IN ('YES','U') GROUP BY I.INDEX_SCHEMA,I.INDEX_NAME HAVING LISTAGG(K.COLUMN_NAME,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION)='IDMARCALIQUIDACION') THEN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX JAVIER.UX_T_RLO_MARKER ON JAVIER.TEST_REPARTIDOR_LIQUIDACION_OPS (IDMARCALIQUIDACION)'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME WHERE I.TABLE_SCHEMA='JAVIER' AND I.TABLE_NAME='TEST_REPARTIDOR_LIQUIDACION_OPS' AND I.IS_UNIQUE IN ('YES','U') GROUP BY I.INDEX_SCHEMA,I.INDEX_NAME HAVING LISTAGG(K.COLUMN_NAME,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION)='CODIGOVENDEDOR,DIALIQUIDACION,MESLIQUIDACION,ANOLIQUIDACION') THEN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX JAVIER.UX_T_RLO_REP_DAY ON JAVIER.TEST_REPARTIDOR_LIQUIDACION_OPS (CODIGOVENDEDOR,DIALIQUIDACION,MESLIQUIDACION,ANOLIQUIDACION)'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA='JAVIER' AND INDEX_NAME='IX_T_LIQ_GASTO_DAY') THEN EXECUTE IMMEDIATE 'CREATE INDEX JAVIER.IX_T_LIQ_GASTO_DAY ON JAVIER.TEST_REPARTIDOR_LIQUIDACION_GASTOS (CODIGO_REPARTIDOR,DIA,MES,ANO,STATUS)'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA='JAVIER' AND INDEX_NAME='IX_T_LIQ_AJUSTE_DAY') THEN EXECUTE IMMEDIATE 'CREATE INDEX JAVIER.IX_T_LIQ_AJUSTE_DAY ON JAVIER.TEST_REPARTIDOR_LIQUIDACION_AJUSTES (CODIGO_REPARTIDOR,DIA,MES,ANO,STATUS)'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA='JAVIER' AND INDEX_NAME='IX_T_LIQ_INGRESO_DAY') THEN EXECUTE IMMEDIATE 'CREATE INDEX JAVIER.IX_T_LIQ_INGRESO_DAY ON JAVIER.TEST_REPARTIDOR_LIQUIDACION_INGRESOS (CODIGO_REPARTIDOR,DIA,MES,ANO,STATUS)'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA='JAVIER' AND INDEX_NAME='IX_T_LIQ_OUTBOX_STATUS') THEN EXECUTE IMMEDIATE 'CREATE INDEX JAVIER.IX_T_LIQ_OUTBOX_STATUS ON JAVIER.TEST_REPARTIDOR_LIQUIDACION_OUTBOX (STATUS,CREATED_AT)'; END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSSEQUENCES WHERE SEQUENCE_SCHEMA='JAVIER' AND SEQUENCE_NAME='TEST_REPARTIDOR_LIQUIDACION_SEQ') THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE JAVIER.TEST_REPARTIDOR_LIQUIDACION_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER';
  ELSEIF EXISTS (SELECT 1 FROM QSYS2.SYSSEQUENCES WHERE SEQUENCE_SCHEMA='JAVIER' AND SEQUENCE_NAME='TEST_REPARTIDOR_LIQUIDACION_SEQ' AND (DATA_TYPE<>'BIGINT' OR NUMERIC_PRECISION<>19 OR START<>1 OR INCREMENT<>1 OR MINIMUM_VALUE<>1 OR MAXIMUM_VALUE<>9223372036854775807 OR CYCLE_OPTION<>'NO' OR CACHE<>20 OR "ORDER"<>'NO')) THEN
    SIGNAL SQLSTATE '75013' SET MESSAGE_TEXT='STOP_TEST_SEQUENCE_METADATA_MISMATCH';
  END IF;
END@

--#SET TERMINATOR ;
