-- 034_cobros_mirror_drop_defaults_DBA_RUN.sql
-- Execute in IBM i ACS Run SQL Scripts.
-- Optional strict-parity correction after 033_cobros_mirror_tables_DBA_RUN.sql.
-- Purpose: remove COLUMN_DEFAULT drift between DSTMOVIL source views and JAVIER mirror tables.
-- WARNING: Dropping defaults changes insert semantics: omitted NOT NULL columns will fail instead of defaulting to ' ' or 0.
-- NO DB2 execution was performed while creating this file.
-- Active statements allowed in this artifact: SELECT and ALTER TABLE JAVIER.COBROS_CAB/LIN/LIQ ALTER COLUMN ... DROP DEFAULT only.

-- ============================================================
-- 1_PRECHECK
-- ============================================================

SELECT TABLE_NAME, COLUMN_NAME, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
  AND COLUMN_DEFAULT IS NOT NULL
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- ============================================================
-- 2_FORWARD
-- ============================================================

ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN SUBEMPRESA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN EJERCICIO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN SERIE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN TERMINAL DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN NUMERO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN TIPO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN SUBDISTRIBUIDOR DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN CLIENTE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN VENDEDOR DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN USUARIO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN FORMAPAGO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN NUMEROTALON DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN BANCO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN FECHAEMISIONDIA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN FECHAEMISIONMES DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN FECHAEMISIONANO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN HORAEMISION DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN FECHAVENCIMIENTODIA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN FECHAVENCIMIENTOMES DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN FECHAVENCIMIENTOANO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN IMPORTECOBRADO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN LIQUIDACIONMARCASINCRONIZACION DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN LIQUIDACIONSUBEMPRESA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN LIQUIDACIONEJERCICIO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN LIQUIDACIONSERIE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN LIQUIDACIONTERMINAL DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN LIQUIDACIONNUMERO DROP DEFAULT;

ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN SUBEMPRESA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN EJERCICIO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN SERIE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN TERMINAL DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN NUMERO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN SECUENCIA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN CLIENTE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN FORMAPAGO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN BANCONOMBRE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN BANCOCUENTA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN DOCUMENTOSUBEMPRESA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN DOCUMENTOEJERCICIO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN DOCUMENTOSERIE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN DOCUMENTOTERMINAL DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN DOCUMENTONUMERO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN IMPORTECOBRADO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIN ALTER COLUMN IMPORTEPENDIENTE DROP DEFAULT;

ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN SUBEMPRESA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN EJERCICIO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN SERIE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN TERMINAL DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN NUMERO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN FECHADIA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN FECHAMES DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN FECHAANO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN HORA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN VENDEDOR DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN USUARIO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN VEHICULO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN VEHICULOMATRICULA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN KILOMETROSSALIDA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN KILOMETROSLLEGADA DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN KILOMETROSRECORRIDOS DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN EFECTIVOIMPORTE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN CHEQUESIMPORTE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN POSTDATADOSIMPORTE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN SALDOACTUAL DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN TOTALAINGRESAR DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN INGRESOENBANCO DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN GASTOSIMPORTE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN IMPRESOSN DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN MARCASINCRONIZACION DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN ESPECIALEFECTIVOIMPORTE DROP DEFAULT;
ALTER TABLE JAVIER.COBROS_LIQ ALTER COLUMN ESPECIALENTREGADO DROP DEFAULT;

-- ============================================================
-- 3_POSTVALIDATION
-- ============================================================

-- Expected: zero rows.
SELECT TABLE_NAME, COLUMN_NAME, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
  AND COLUMN_DEFAULT IS NOT NULL
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- Source-minus-target metadata drift. Expected: zero rows for each EXCEPT query.
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROCABEC'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_CAB';

SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_CAB'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROCABEC';

SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROLINEA'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIN';

SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIN'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROLINEA';

SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'LIQUIDIARI'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIQ';

SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIQ'
EXCEPT
SELECT COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'LIQUIDIARI';

-- Expected column counts: COBROS_CAB=27, COBROS_LIN=17, COBROS_LIQ=27.
SELECT TABLE_SCHEMA,
       TABLE_NAME,
       COUNT(*) AS COLUMN_COUNT,
       CASE TABLE_NAME
         WHEN 'COBROS_CAB' THEN 27
         WHEN 'COBROS_LIN' THEN 17
         WHEN 'COBROS_LIQ' THEN 27
       END AS EXPECTED_COLUMN_COUNT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
GROUP BY TABLE_SCHEMA, TABLE_NAME
ORDER BY TABLE_NAME;

-- Expected index count after 033 DBA_RUN: 11.
SELECT COUNT(*) AS INDEX_COUNT,
       CASE WHEN COUNT(*) = 11 THEN 'PASS' ELSE 'FAIL' END AS EXPECTED_11_INDEXES
FROM QSYS2.SYSINDEXES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ');

-- ============================================================
-- 4_ROLLBACK_REFERENCE_NOT_FOR_NORMAL_EXECUTION
-- ============================================================
-- Do not execute rollback by default. These examples are intentionally commented.
-- If strict parity breaks an approved insert path, restore prior insert semantics only after DBA/app approval.
-- CHAR columns previously defaulted to blank:
-- ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN SUBEMPRESA SET DEFAULT ' ';
-- NUMERIC columns previously defaulted to zero:
-- ALTER TABLE JAVIER.COBROS_CAB ALTER COLUMN EJERCICIO SET DEFAULT 0;
