-- 035_cobros_runtime_cutover_javier.sql
-- DBA-run IBM i Db2 artifact for GMP cobros runtime cutover support objects.
-- Scope: JAVIER support tables only. No backend/Flutter changes. No production deploy.
-- COBROS_CAB, COBROS_LIN and COBROS_LIQ stay exact mirrors and are not altered here.
-- JAVIER.COBROS stays legacy historical and is not altered here.
-- Do not use MAX(NUMERO)+1. Number reservation must use the atomic UPDATE pattern below.

-- ============================================================================
-- PREFLIGHT: read-only checks before FORWARD. Expected: run in ACS manually.
-- ============================================================================

-- Expected mirrors/runtime tables present in JAVIER. This artifact does not create or alter them.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN (
    'COBROS',
    'COBROS_CAB',
    'COBROS_LIN',
    'COBROS_LIQ',
    'COBROS_NUMERO_COUNTER',
    'COBROS_IDEMPOTENCY'
  )
ORDER BY TABLE_NAME;

-- Expected mirror key columns present. Do not change mirror definitions from this artifact.
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
  AND COLUMN_NAME IN ('SUBEMPRESA', 'EJERCICIO', 'SERIE', 'TERMINAL', 'NUMERO', 'SECUENCIA')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- Current support-object presence. Expected before first run: zero rows.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_NUMERO_COUNTER', 'COBROS_IDEMPOTENCY')
ORDER BY TABLE_NAME;

-- Current runtime row counts for DBA awareness only.
SELECT 'COBROS_CAB' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM JAVIER.COBROS_CAB
UNION ALL
SELECT 'COBROS_LIN' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM JAVIER.COBROS_LIN
UNION ALL
SELECT 'COBROS_LIQ' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM JAVIER.COBROS_LIQ
UNION ALL
SELECT 'COBROS_LEGACY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM JAVIER.COBROS;

-- Duplicate mirror-key checks. Expected: zero rows from each query before runtime cutover.
SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, COUNT(*) AS DUPLICATES
FROM JAVIER.COBROS_CAB
GROUP BY SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO
HAVING COUNT(*) > 1;

SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, SECUENCIA, COUNT(*) AS DUPLICATES
FROM JAVIER.COBROS_LIN
GROUP BY SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, SECUENCIA
HAVING COUNT(*) > 1;

SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, COUNT(*) AS DUPLICATES
FROM JAVIER.COBROS_LIQ
GROUP BY SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO
HAVING COUNT(*) > 1;

-- ============================================================================
-- FORWARD: create support tables only. Use --#SET TERMINATOR @ in ACS.
-- ============================================================================

--#SET TERMINATOR @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;

  CREATE TABLE JAVIER.COBROS_NUMERO_COUNTER (
    SUBEMPRESA VARCHAR(10) NOT NULL,
    EJERCICIO DECIMAL(4, 0) NOT NULL,
    SERIE VARCHAR(10) NOT NULL,
    TERMINAL VARCHAR(20) NOT NULL,
    NEXT_NUMERO DECIMAL(9, 0) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_COBROS_NUMERO_COUNTER PRIMARY KEY (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL),
    CONSTRAINT CK_COBROS_NUMERO_NEXT CHECK (NEXT_NUMERO >= 1)
  );
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;

  CREATE INDEX JAVIER.IX_COBROS_NUMERO_UPDATED
  ON JAVIER.COBROS_NUMERO_COUNTER (UPDATED_AT);
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;

  CREATE TABLE JAVIER.COBROS_IDEMPOTENCY (
    IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL,
    SUBEMPRESA VARCHAR(10) NOT NULL,
    EJERCICIO DECIMAL(4, 0) NOT NULL,
    SERIE VARCHAR(10) NOT NULL,
    TERMINAL VARCHAR(20) NOT NULL,
    NUMERO DECIMAL(9, 0) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'RESERVED',
    REQUEST_HASH VARCHAR(128),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    RESERVED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    FAILED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    ERROR_CODE VARCHAR(64),
    ERROR_MESSAGE VARCHAR(512),
    CONSTRAINT PK_COBROS_IDEMPOTENCY PRIMARY KEY (IDEMPOTENCY_TOKEN),
    CONSTRAINT CK_COBROS_IDEMP_STATUS CHECK (STATUS IN ('RESERVED', 'COMPLETED', 'FAILED', 'CANCELLED'))
  );
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;

  CREATE UNIQUE INDEX JAVIER.UX_COBROS_IDEMP_RECEIPT
  ON JAVIER.COBROS_IDEMPOTENCY (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO);
END @

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;

  CREATE INDEX JAVIER.IX_COBROS_IDEMP_STATUS
  ON JAVIER.COBROS_IDEMPOTENCY (STATUS, UPDATED_AT);
END @

--#SET TERMINATOR ;

-- Atomic numbering pattern for application/DBA runbook, not a seed script:
-- 1) Seed JAVIER.COBROS_NUMERO_COUNTER per SUBEMPRESA/EJERCICIO/SERIE/TERMINAL
--    with an approved NEXT_NUMERO. Do not derive it with MAX(NUMERO)+1.
-- 2) Reserve exactly one number using this single UPDATE statement; FINAL TABLE
--    returns the row changed by this statement while Db2 serializes row updates.
--
-- SELECT NEXT_NUMERO - 1 AS RESERVED_NUMERO
-- FROM FINAL TABLE (
--   UPDATE JAVIER.COBROS_NUMERO_COUNTER
--      SET NEXT_NUMERO = NEXT_NUMERO + 1,
--          UPDATED_AT = CURRENT TIMESTAMP
--    WHERE SUBEMPRESA = '<SUBEMPRESA>'
--      AND EJERCICIO = <EJERCICIO>
--      AND SERIE = '<SERIE>'
--      AND TERMINAL = '<TERMINAL>'
-- );
--
-- If the SELECT returns zero rows, the scope has not been seeded; stop and seed
-- from the approved business counter source, never from runtime mirror MAX().

-- ============================================================================
-- VALIDATION: read-only checks after FORWARD. Expected failures: zero rows.
-- ============================================================================

-- Expected support tables present: 2.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_NUMERO_COUNTER', 'COBROS_IDEMPOTENCY')
ORDER BY TABLE_NAME;

-- Expected support columns and defaults.
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_NUMERO_COUNTER', 'COBROS_IDEMPOTENCY')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- Expected support indexes/constraints present.
SELECT INDEX_SCHEMA, INDEX_NAME, TABLE_SCHEMA, TABLE_NAME
FROM QSYS2.SYSINDEXES
WHERE INDEX_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_NUMERO_COUNTER', 'COBROS_IDEMPOTENCY')
ORDER BY TABLE_NAME, INDEX_NAME;

-- Support row counts. Expected after creation before app cutover: zero rows in both.
SELECT 'COBROS_NUMERO_COUNTER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM JAVIER.COBROS_NUMERO_COUNTER
UNION ALL
SELECT 'COBROS_IDEMPOTENCY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM JAVIER.COBROS_IDEMPOTENCY;

-- Idempotency token duplicate check. Expected: zero rows; PK/unique token also enforces this.
SELECT IDEMPOTENCY_TOKEN, COUNT(*) AS DUPLICATES
FROM JAVIER.COBROS_IDEMPOTENCY
GROUP BY IDEMPOTENCY_TOKEN
HAVING COUNT(*) > 1;

-- Receipt mapping duplicate check. Expected: zero rows; unique receipt index also enforces this.
SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, COUNT(*) AS DUPLICATES
FROM JAVIER.COBROS_IDEMPOTENCY
GROUP BY SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO
HAVING COUNT(*) > 1;

-- Counter natural-scope duplicate check. Expected: zero rows; PK also enforces this.
SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, COUNT(*) AS DUPLICATES
FROM JAVIER.COBROS_NUMERO_COUNTER
GROUP BY SUBEMPRESA, EJERCICIO, SERIE, TERMINAL
HAVING COUNT(*) > 1;

-- Counter sanity. Expected: zero rows.
SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NEXT_NUMERO
FROM JAVIER.COBROS_NUMERO_COUNTER
WHERE NEXT_NUMERO < 1;

-- Mirror/runtime tables and legacy table remain present. This artifact must not alter their columns.
SELECT TABLE_SCHEMA, TABLE_NAME, COUNT(*) AS COLUMN_COUNT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS', 'COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
GROUP BY TABLE_SCHEMA, TABLE_NAME
ORDER BY TABLE_NAME;

-- Duplicate mirror-key checks after cutover setup. Expected: zero rows from each query.
SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, COUNT(*) AS DUPLICATES
FROM JAVIER.COBROS_CAB
GROUP BY SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO
HAVING COUNT(*) > 1;

SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, SECUENCIA, COUNT(*) AS DUPLICATES
FROM JAVIER.COBROS_LIN
GROUP BY SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, SECUENCIA
HAVING COUNT(*) > 1;

SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO, COUNT(*) AS DUPLICATES
FROM JAVIER.COBROS_LIQ
GROUP BY SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO
HAVING COUNT(*) > 1;

-- ============================================================================
-- ROLLBACK: drops only empty JAVIER support objects. Mirrors/legacy untouched.
-- ============================================================================

--#SET TERMINATOR @

BEGIN
  DECLARE v_exists INTEGER DEFAULT 0;
  DECLARE v_rows BIGINT DEFAULT 0;

  SELECT COUNT(*) INTO v_exists
  FROM QSYS2.SYSTABLES
  WHERE TABLE_SCHEMA = 'JAVIER'
    AND TABLE_NAME = 'COBROS_IDEMPOTENCY';

  IF v_exists = 1 THEN
    SELECT COUNT(*) INTO v_rows FROM JAVIER.COBROS_IDEMPOTENCY;
    IF v_rows = 0 THEN
      DROP TABLE JAVIER.COBROS_IDEMPOTENCY;
    ELSE
      SIGNAL SQLSTATE '75035' SET MESSAGE_TEXT = 'Rollback blocked: JAVIER.COBROS_IDEMPOTENCY is not empty';
    END IF;
  END IF;
END @

BEGIN
  DECLARE v_exists INTEGER DEFAULT 0;
  DECLARE v_rows BIGINT DEFAULT 0;

  SELECT COUNT(*) INTO v_exists
  FROM QSYS2.SYSTABLES
  WHERE TABLE_SCHEMA = 'JAVIER'
    AND TABLE_NAME = 'COBROS_NUMERO_COUNTER';

  IF v_exists = 1 THEN
    SELECT COUNT(*) INTO v_rows FROM JAVIER.COBROS_NUMERO_COUNTER;
    IF v_rows = 0 THEN
      DROP TABLE JAVIER.COBROS_NUMERO_COUNTER;
    ELSE
      SIGNAL SQLSTATE '75036' SET MESSAGE_TEXT = 'Rollback blocked: JAVIER.COBROS_NUMERO_COUNTER is not empty';
    END IF;
  END IF;
END @

--#SET TERMINATOR ;

-- Rollback never drops JAVIER.COBROS_CAB, JAVIER.COBROS_LIN, JAVIER.COBROS_LIQ,
-- or JAVIER.COBROS. If support tables contain rows, export/reconcile them first
-- and execute any destructive drop only under a separate approved DBA runbook.
