-- 035_cobros_runtime_cutover_javier_DBA_RUN.sql
-- Execute in IBM i ACS Run SQL Scripts with the default semicolon terminator.
-- Scope: JAVIER support objects only. Mirrors and legacy tables stay untouched.
-- Execute sections 1_PREFLIGHT, 2_FORWARD, 3_VALIDATION.

-- ============================================================
-- 1_PREFLIGHT
-- ============================================================

-- Expected before first run: zero rows. Stop if either support table exists.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_NUMERO_COUNTER', 'COBROS_IDEMPOTENCY')
ORDER BY TABLE_NAME;

-- Source and mirror presence only. This artifact does not create or alter mirrors.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE (TABLE_SCHEMA = 'DSTMOVIL' AND TABLE_NAME IN ('COBROCABEC', 'COBROLINEA', 'LIQUIDIARI'))
   OR (TABLE_SCHEMA = 'JAVIER' AND TABLE_NAME IN ('COBROS', 'COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ'))
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- Mirror key type check. Expected types are CHAR(3), NUMERIC(4,0), CHAR(1), NUMERIC(3,0), NUMERIC(6,0).
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_CAB', 'COBROS_LIN', 'COBROS_LIQ')
  AND COLUMN_NAME IN ('SUBEMPRESA', 'EJERCICIO', 'SERIE', 'TERMINAL', 'NUMERO')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- Strict mirror definition parity vs DSTMOVIL. Expected from each query: zero rows.
SELECT 'COBROCABEC_MINUS_COBROS_CAB' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROCABEC'
EXCEPT
SELECT 'COBROCABEC_MINUS_COBROS_CAB' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_CAB'
ORDER BY COLUMN_NAME;

SELECT 'COBROS_CAB_MINUS_COBROCABEC' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_CAB'
EXCEPT
SELECT 'COBROS_CAB_MINUS_COBROCABEC' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROCABEC'
ORDER BY COLUMN_NAME;

SELECT 'COBROLINEA_MINUS_COBROS_LIN' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROLINEA'
EXCEPT
SELECT 'COBROLINEA_MINUS_COBROS_LIN' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIN'
ORDER BY COLUMN_NAME;

SELECT 'COBROS_LIN_MINUS_COBROLINEA' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIN'
EXCEPT
SELECT 'COBROS_LIN_MINUS_COBROLINEA' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROLINEA'
ORDER BY COLUMN_NAME;

SELECT 'LIQUIDIARI_MINUS_COBROS_LIQ' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'LIQUIDIARI'
EXCEPT
SELECT 'LIQUIDIARI_MINUS_COBROS_LIQ' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIQ'
ORDER BY COLUMN_NAME;

SELECT 'COBROS_LIQ_MINUS_LIQUIDIARI' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIQ'
EXCEPT
SELECT 'COBROS_LIQ_MINUS_LIQUIDIARI' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'LIQUIDIARI'
ORDER BY COLUMN_NAME;

-- ============================================================
-- 2_FORWARD
-- ============================================================

CREATE TABLE JAVIER.COBROS_NUMERO_COUNTER (
  SUBEMPRESA CHAR(3) NOT NULL,
  EJERCICIO NUMERIC(4,0) NOT NULL,
  SERIE CHAR(1) NOT NULL,
  TERMINAL NUMERIC(3,0) NOT NULL,
  NEXT_NUMERO NUMERIC(6,0) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  CONSTRAINT PK_COBROS_NUMERO_COUNTER PRIMARY KEY (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL),
  CONSTRAINT CK_COBROS_NUMERO_NEXT CHECK (NEXT_NUMERO >= 1)
);

CREATE INDEX JAVIER.IX_COBROS_NUMERO_UPDATED
ON JAVIER.COBROS_NUMERO_COUNTER (UPDATED_AT);

CREATE TABLE JAVIER.COBROS_IDEMPOTENCY (
  IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL,
  SUBEMPRESA CHAR(3) NOT NULL,
  EJERCICIO NUMERIC(4,0) NOT NULL,
  SERIE CHAR(1) NOT NULL,
  TERMINAL NUMERIC(3,0) NOT NULL,
  NUMERO NUMERIC(6,0) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'RESERVED',
  REQUEST_HASH VARCHAR(128),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  RESERVED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  COMPLETED_AT TIMESTAMP,
  FAILED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  ERROR_CODE VARCHAR(64),
  ERROR_MESSAGE VARCHAR(512),
  CONSTRAINT PK_COBROS_IDEMPOTENCY PRIMARY KEY (IDEMPOTENCY_TOKEN),
  CONSTRAINT CK_COBROS_IDEMP_STATUS CHECK (STATUS IN ('RESERVED', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

CREATE UNIQUE INDEX JAVIER.UX_COBROS_IDEMP_RECEIPT
ON JAVIER.COBROS_IDEMPOTENCY (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NUMERO);

CREATE INDEX JAVIER.IX_COBROS_IDEMP_STATUS
ON JAVIER.COBROS_IDEMPOTENCY (STATUS, UPDATED_AT);

-- Seed JAVIER.COBROS_NUMERO_COUNTER only from an approved business counter source.
-- Never derive next number from current maximum mirror number.

-- ============================================================
-- 3_VALIDATION
-- ============================================================

-- Expected support tables present: two rows.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_NUMERO_COUNTER', 'COBROS_IDEMPOTENCY')
ORDER BY TABLE_NAME;

-- Expected after creation before app cutover: zero rows in both support tables.
SELECT 'COBROS_NUMERO_COUNTER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM JAVIER.COBROS_NUMERO_COUNTER
UNION ALL
SELECT 'COBROS_IDEMPOTENCY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM JAVIER.COBROS_IDEMPOTENCY;

-- Expected support column definitions.
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_NUMERO_COUNTER', 'COBROS_IDEMPOTENCY')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- Exact support key type validation. Expected: zero rows.
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_NUMERO_COUNTER'
  AND (
    (COLUMN_NAME = 'SUBEMPRESA' AND (DATA_TYPE <> 'CHAR' OR LENGTH <> 3))
    OR (COLUMN_NAME = 'EJERCICIO' AND (DATA_TYPE <> 'NUMERIC' OR LENGTH <> 4 OR NUMERIC_SCALE <> 0))
    OR (COLUMN_NAME = 'SERIE' AND (DATA_TYPE <> 'CHAR' OR LENGTH <> 1))
    OR (COLUMN_NAME = 'TERMINAL' AND (DATA_TYPE <> 'NUMERIC' OR LENGTH <> 3 OR NUMERIC_SCALE <> 0))
    OR (COLUMN_NAME = 'NEXT_NUMERO' AND (DATA_TYPE <> 'NUMERIC' OR LENGTH <> 6 OR NUMERIC_SCALE <> 0))
  )
UNION ALL
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_IDEMPOTENCY'
  AND (
    (COLUMN_NAME = 'SUBEMPRESA' AND (DATA_TYPE <> 'CHAR' OR LENGTH <> 3))
    OR (COLUMN_NAME = 'EJERCICIO' AND (DATA_TYPE <> 'NUMERIC' OR LENGTH <> 4 OR NUMERIC_SCALE <> 0))
    OR (COLUMN_NAME = 'SERIE' AND (DATA_TYPE <> 'CHAR' OR LENGTH <> 1))
    OR (COLUMN_NAME = 'TERMINAL' AND (DATA_TYPE <> 'NUMERIC' OR LENGTH <> 3 OR NUMERIC_SCALE <> 0))
    OR (COLUMN_NAME = 'NUMERO' AND (DATA_TYPE <> 'NUMERIC' OR LENGTH <> 6 OR NUMERIC_SCALE <> 0))
  )
ORDER BY TABLE_NAME, COLUMN_NAME;

-- Expected support indexes and constraints.
SELECT INDEX_SCHEMA, INDEX_NAME, TABLE_SCHEMA, TABLE_NAME, IS_UNIQUE
FROM QSYS2.SYSINDEXES
WHERE INDEX_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_NUMERO_COUNTER', 'COBROS_IDEMPOTENCY')
ORDER BY TABLE_NAME, INDEX_NAME;

-- Strict mirror definition parity vs DSTMOVIL after support creation. Expected from each query: zero rows.
SELECT 'COBROCABEC_MINUS_COBROS_CAB' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROCABEC'
EXCEPT
SELECT 'COBROCABEC_MINUS_COBROS_CAB' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_CAB'
ORDER BY COLUMN_NAME;

SELECT 'COBROS_CAB_MINUS_COBROCABEC' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_CAB'
EXCEPT
SELECT 'COBROS_CAB_MINUS_COBROCABEC' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROCABEC'
ORDER BY COLUMN_NAME;

SELECT 'COBROLINEA_MINUS_COBROS_LIN' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROLINEA'
EXCEPT
SELECT 'COBROLINEA_MINUS_COBROS_LIN' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIN'
ORDER BY COLUMN_NAME;

SELECT 'COBROS_LIN_MINUS_COBROLINEA' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIN'
EXCEPT
SELECT 'COBROS_LIN_MINUS_COBROLINEA' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'COBROLINEA'
ORDER BY COLUMN_NAME;

SELECT 'LIQUIDIARI_MINUS_COBROS_LIQ' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'LIQUIDIARI'
EXCEPT
SELECT 'LIQUIDIARI_MINUS_COBROS_LIQ' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIQ'
ORDER BY COLUMN_NAME;

SELECT 'COBROS_LIQ_MINUS_LIQUIDIARI' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_LIQ'
EXCEPT
SELECT 'COBROS_LIQ_MINUS_LIQUIDIARI' AS CHECK_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE, IS_NULLABLE, COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'DSTMOVIL'
  AND TABLE_NAME = 'LIQUIDIARI'
ORDER BY COLUMN_NAME;

-- ============================================================
-- 4_ROLLBACK_REFERENCE
-- ============================================================

-- Manual reference only. Do not execute unless both support row counts above are zero
-- and Javier has approved a separate rollback window.
-- DROP TABLE JAVIER.COBROS_IDEMPOTENCY;
-- DROP TABLE JAVIER.COBROS_NUMERO_COUNTER;

-- Rollback never drops or alters JAVIER.COBROS_CAB, JAVIER.COBROS_LIN,
-- JAVIER.COBROS_LIQ, JAVIER.COBROS, or any DSTMOVIL object.
