-- Read-only, standalone verifier for the isolated liquidation schema.
-- Every STOP_* result blocks staging enablement. No JAVIER production table is a source.

WITH REQUIRED_OBJECTS (TABLE_SCHEMA,TABLE_NAME) AS (VALUES
  ('JAVIER','TEST_REPARTIDOR_COBROS'),
  ('JAVIER','TEST_REPARTIDOR_COBROS_AUDIT'),
  ('JAVIER','TEST_REPARTIDOR_FINANCIAL_BALANCES'),
  ('JAVIER','TEST_REPARTIDOR_LIQUIDACION_OPS'),
  ('JAVIER','TEST_REPARTIDOR_LIQUIDACION_GASTOS'),
  ('JAVIER','TEST_REPARTIDOR_LIQUIDACION_AJUSTES'),
  ('JAVIER','TEST_REPARTIDOR_LIQUIDACION_INGRESOS'),
  ('JAVIER','TEST_REPARTIDOR_LIQUIDACION_OUTBOX')
)
SELECT R.TABLE_SCHEMA || '.' || R.TABLE_NAME AS OBJECT_NAME,
  'STOP_TARGET_MISSING' AS STATUS
FROM REQUIRED_OBJECTS R LEFT JOIN QSYS2.SYSTABLES T
  ON T.TABLE_SCHEMA=R.TABLE_SCHEMA AND T.TABLE_NAME=R.TABLE_NAME
WHERE T.TABLE_NAME IS NULL
ORDER BY OBJECT_NAME;

-- Minimum required column counts prevent a same-name partial table while
-- allowing the ERP-shaped TEST copies to carry additive source columns.
WITH EXPECTED_COUNTS (TABLE_NAME,COLUMN_COUNT) AS (VALUES
  ('TEST_REPARTIDOR_COBROS',11),('TEST_REPARTIDOR_COBROS_AUDIT',6),
  ('TEST_REPARTIDOR_FINANCIAL_BALANCES',2),('TEST_REPARTIDOR_LIQUIDACION_OPS',40),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS',15),('TEST_REPARTIDOR_LIQUIDACION_AJUSTES',15),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS',15),('TEST_REPARTIDOR_LIQUIDACION_OUTBOX',6)
), ACTUAL AS (
  SELECT TABLE_NAME,COUNT(*) AS COLUMN_COUNT FROM QSYS2.SYSCOLUMNS2
  WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME LIKE 'TEST_REPARTIDOR_%' GROUP BY TABLE_NAME
)
SELECT E.TABLE_NAME,'STOP_COLUMN_METADATA_DIFFERENT' AS STATUS
FROM EXPECTED_COUNTS E LEFT JOIN ACTUAL A ON A.TABLE_NAME=E.TABLE_NAME
WHERE A.COLUMN_COUNT IS NULL OR A.COLUMN_COUNT<E.COLUMN_COUNT
ORDER BY E.TABLE_NAME;

-- Every runtime-used column has an embedded physical manifest. Nullable columns
-- with DB2 implicit NULL defaults are represented by HAS_DEFAULT=Y/COLUMN_DEFAULT NULL.
WITH EXPECTED (TABLE_NAME,COLUMN_NAME,DATA_TYPE,LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE,
  IS_NULLABLE,HAS_DEFAULT,COLUMN_DEFAULT,IS_IDENTITY,IDENTITY_GENERATION) AS (VALUES
  ('TEST_REPARTIDOR_COBROS','ID','INTEGER',4,9,0,'N','I','','YES','ALWAYS'),
  ('TEST_REPARTIDOR_COBROS','CODIGOVENDEDOR','CHAR',2,-1,-1,'N','Y','','NO',''),
  ('TEST_REPARTIDOR_COBROS','DIACOBRO','NUMERIC',2,2,0,'N','Y','0','NO',''),
  ('TEST_REPARTIDOR_COBROS','MESCOBRO','NUMERIC',2,2,0,'N','Y','0','NO',''),
  ('TEST_REPARTIDOR_COBROS','ANOCOBRO','NUMERIC',4,4,0,'N','Y','0','NO',''),
  ('TEST_REPARTIDOR_COBROS','IMPORTEVENCIMIENTO','NUMERIC',10,10,2,'N','Y','0','NO',''),
  ('TEST_REPARTIDOR_COBROS','CODIGOFORMAPAGO','CHAR',2,-1,-1,'N','Y','','NO',''),
  ('TEST_REPARTIDOR_COBROS','CREATED_AT','TIMESTMP',10,-1,-1,'Y','Y','CURRENTTIMESTAMP','NO',''),
  ('TEST_REPARTIDOR_COBROS','LIQUIDADO_SN','CHAR',1,-1,-1,'Y','Y','N','NO',''),
  ('TEST_REPARTIDOR_COBROS','LIQUIDACION_TOKEN','VARCHAR',128,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_COBROS','NUMEROLIQUIDACION','NUMERIC',6,6,0,'N','Y','0','NO',''),
  ('TEST_REPARTIDOR_COBROS_AUDIT','ID','INTEGER',4,9,0,'N','I','','YES','ALWAYS'),
  ('TEST_REPARTIDOR_COBROS_AUDIT','EVENT_TYPE','VARCHAR',40,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_COBROS_AUDIT','OPERADOR','VARCHAR',40,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_COBROS_AUDIT','CODIGO_REPARTIDOR','VARCHAR',10,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_COBROS_AUDIT','PAYLOAD_PREVIEW','VARCHAR',500,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_COBROS_AUDIT','CREATED_AT','TIMESTMP',10,-1,-1,'Y','Y','CURRENTTIMESTAMP','NO',''),
  ('TEST_REPARTIDOR_FINANCIAL_BALANCES','CODIGO_REPARTIDOR','VARCHAR',20,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_FINANCIAL_BALANCES','SALDO_PENDIENTE','DECIMAL',15,15,2,'N','Y','0','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','ID','INTEGER',4,9,0,'N','I','','YES','ALWAYS'),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','IDEMPOTENCY_TOKEN','VARCHAR',128,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','IDMARCALIQUIDACION','CHAR',30,-1,-1,'N','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','CODIGOVENDEDOR','CHAR',2,-1,-1,'N','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','DIALIQUIDACION','NUMERIC',2,2,0,'N','Y','0','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','MESLIQUIDACION','NUMERIC',2,2,0,'N','Y','0','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','ANOLIQUIDACION','NUMERIC',4,4,0,'N','Y','0','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','REPLAY_IDENTITY_JSON','CLOB',8192,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','SNAPSHOT_JSON','CLOB',65536,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','STATUS','VARCHAR',20,-1,-1,'Y','Y','CLOSED','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','OPERADOR','VARCHAR',50,-1,-1,'Y','Y','SYSTEM','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','PANTALLA_ORIGEN','VARCHAR',20,-1,-1,'Y','Y','LIQUIDACIONDIARIA','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','CREATED_AT','TIMESTMP',10,-1,-1,'Y','Y','CURRENTTIMESTAMP','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','UPDATED_AT','TIMESTMP',10,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','ID','BIGINT',8,18,0,'N','I','','YES','ALWAYS'),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','IDEMPOTENCY_TOKEN','VARCHAR',128,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CODIGO_REPARTIDOR','CHAR',2,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','DIA','NUMERIC',2,2,0,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','MES','NUMERIC',2,2,0,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','ANO','NUMERIC',4,4,0,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','IMPORTE','DECIMAL',10,10,2,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CATEGORIA','VARCHAR',40,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','OBSERVACION','VARCHAR',250,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','STATUS','VARCHAR',12,-1,-1,'N','Y','PENDING','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','LIQUIDACION_ID','BIGINT',8,18,0,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','LIQUIDACION_MARKER','CHAR',30,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','ACTOR_ID','VARCHAR',40,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','ACTOR_ROLE','VARCHAR',30,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CREATED_AT','TIMESTMP',10,-1,-1,'N','Y','CURRENTTIMESTAMP','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','ID','BIGINT',8,18,0,'N','I','','YES','ALWAYS'),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','IDEMPOTENCY_TOKEN','VARCHAR',128,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','CODIGO_REPARTIDOR','CHAR',2,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','DIA','NUMERIC',2,2,0,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','MES','NUMERIC',2,2,0,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','ANO','NUMERIC',4,4,0,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','IMPORTE','DECIMAL',10,10,2,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','MOTIVO','VARCHAR',120,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','OBSERVACION','VARCHAR',250,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','STATUS','VARCHAR',12,-1,-1,'N','Y','PENDING','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','LIQUIDACION_ID','BIGINT',8,18,0,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','LIQUIDACION_MARKER','CHAR',30,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','ACTOR_ID','VARCHAR',40,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','ACTOR_ROLE','VARCHAR',30,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','CREATED_AT','TIMESTMP',10,-1,-1,'N','Y','CURRENTTIMESTAMP','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','ID','BIGINT',8,18,0,'N','I','','YES','ALWAYS'),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','IDEMPOTENCY_TOKEN','VARCHAR',128,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','CODIGO_REPARTIDOR','CHAR',2,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','DIA','NUMERIC',2,2,0,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','MES','NUMERIC',2,2,0,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','ANO','NUMERIC',4,4,0,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','IMPORTE','DECIMAL',10,10,2,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','REFERENCIA','VARCHAR',80,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','OBSERVACION','VARCHAR',250,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','STATUS','VARCHAR',12,-1,-1,'N','Y','PENDING','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','LIQUIDACION_ID','BIGINT',8,18,0,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','LIQUIDACION_MARKER','CHAR',30,-1,-1,'Y','Y','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','ACTOR_ID','VARCHAR',40,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','ACTOR_ROLE','VARCHAR',30,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','CREATED_AT','TIMESTMP',10,-1,-1,'N','Y','CURRENTTIMESTAMP','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','ID','BIGINT',8,18,0,'N','I','','YES','ALWAYS'),
  ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','LIQUIDACION_ID','BIGINT',8,18,0,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','OUTBOX_TYPE','VARCHAR',50,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','STATUS','VARCHAR',20,-1,-1,'N','Y','PENDING','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','PAYLOAD_JSON','CLOB',16384,-1,-1,'N','N','','NO',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','CREATED_AT','TIMESTMP',10,-1,-1,'N','Y','CURRENTTIMESTAMP','NO','')
), ACTUAL AS (
  SELECT TABLE_NAME,COLUMN_NAME,TRIM(DATA_TYPE) AS DATA_TYPE,LENGTH,
    COALESCE(NUMERIC_PRECISION,-1) AS NUMERIC_PRECISION,COALESCE(NUMERIC_SCALE,-1) AS NUMERIC_SCALE,
    IS_NULLABLE,HAS_DEFAULT,
    UPPER(REPLACE(REPLACE(REPLACE(COALESCE(TRIM(COLUMN_DEFAULT),''),'''',''),'_',''),' ','')) AS COLUMN_DEFAULT,
    IS_IDENTITY,COALESCE(IDENTITY_GENERATION,'') AS IDENTITY_GENERATION
  FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME LIKE 'TEST_REPARTIDOR_%'
)
SELECT E.TABLE_NAME || '.' || E.COLUMN_NAME AS OBJECT_NAME,'STOP_COLUMN_METADATA_DIFFERENT' AS STATUS
FROM EXPECTED E LEFT JOIN ACTUAL A ON A.TABLE_NAME=E.TABLE_NAME AND A.COLUMN_NAME=E.COLUMN_NAME
WHERE A.COLUMN_NAME IS NULL OR E.DATA_TYPE<>A.DATA_TYPE OR E.LENGTH<>A.LENGTH
 OR E.NUMERIC_PRECISION<>A.NUMERIC_PRECISION OR E.NUMERIC_SCALE<>A.NUMERIC_SCALE
 OR E.IS_NULLABLE<>A.IS_NULLABLE OR E.HAS_DEFAULT<>A.HAS_DEFAULT
 OR E.COLUMN_DEFAULT<>A.COLUMN_DEFAULT OR E.IS_IDENTITY<>A.IS_IDENTITY
 OR E.IDENTITY_GENERATION<>A.IDENTITY_GENERATION
ORDER BY OBJECT_NAME;

SELECT TABLE_NAME || '.' || COLUMN_NAME AS OBJECT_NAME,
  'STOP_COLUMN_METADATA_DIFFERENT' AS STATUS
FROM QSYS2.SYSCOLUMNS2
WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME LIKE 'TEST_REPARTIDOR_%'
  AND ((IS_IDENTITY='YES' AND (COALESCE(IDENTITY_GENERATION,'')<>'ALWAYS'
    OR COALESCE(IDENTITY_START,0)<>1 OR COALESCE(IDENTITY_INCREMENT,0)<>1))
    OR (IS_IDENTITY='NO' AND (IDENTITY_START IS NOT NULL OR IDENTITY_INCREMENT IS NOT NULL)))
ORDER BY OBJECT_NAME;

-- Constraint signatures: primary/unique/check text and exact key ordering.
WITH REQUIRED (TABLE_NAME,CONSTRAINT_TYPE,KEYS,CHECK_CONDITION) AS (VALUES
  ('TEST_REPARTIDOR_COBROS','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_COBROS_AUDIT','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_FINANCIAL_BALANCES','PRIMARY KEY','CODIGO_REPARTIDOR',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','UNIQUE','IDEMPOTENCY_TOKEN',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CHECK','','IMPORTE>0'),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','UNIQUE','IDEMPOTENCY_TOKEN',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','CHECK','','IMPORTE<>0'),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','UNIQUE','IDEMPOTENCY_TOKEN',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','CHECK','','IMPORTE>0'),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
  ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','CHECK','','STATUSIN''PENDING'',''SENT'',''FAILED''')
), ACTUAL AS (
  SELECT X.TABLE_NAME,
    CASE X.CONSTRAINT_TYPE
      WHEN 'P' THEN 'PRIMARY KEY'
      WHEN 'U' THEN 'UNIQUE'
      WHEN 'C' THEN 'CHECK'
      WHEN 'F' THEN 'FOREIGN KEY'
      ELSE TRIM(X.CONSTRAINT_TYPE)
    END AS CONSTRAINT_TYPE,
    COALESCE(LISTAGG(K.COLUMN_NAME,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION),'') AS KEYS,
    COALESCE(MAX(UPPER(REPLACE(REPLACE(REPLACE(COALESCE(CAST(C.CHECK_CLAUSE AS VARCHAR(4096)),''),' ',''),'(',''),')',''))),'') AS CHECK_CONDITION
  FROM QSYS2.SYSCST X
  LEFT JOIN QSYS2.SYSKEYCST K
    ON K.CONSTRAINT_SCHEMA=X.CONSTRAINT_SCHEMA AND K.CONSTRAINT_NAME=X.CONSTRAINT_NAME
  LEFT JOIN QSYS2.SYSCHKCST C
    ON C.CONSTRAINT_SCHEMA=X.CONSTRAINT_SCHEMA AND C.CONSTRAINT_NAME=X.CONSTRAINT_NAME
  WHERE X.TABLE_SCHEMA='JAVIER' AND X.TABLE_NAME LIKE 'TEST_REPARTIDOR_%'
  GROUP BY X.TABLE_NAME,X.CONSTRAINT_NAME,X.CONSTRAINT_TYPE
)
SELECT R.TABLE_NAME || ':' || R.CONSTRAINT_TYPE || ':' || R.KEYS AS OBJECT_NAME,
  'STOP_CONSTRAINT_SIGNATURE_DIFFERENT' AS STATUS
FROM REQUIRED R LEFT JOIN ACTUAL A ON A.TABLE_NAME=R.TABLE_NAME
 AND A.CONSTRAINT_TYPE=R.CONSTRAINT_TYPE AND A.KEYS=R.KEYS AND A.CHECK_CONDITION=R.CHECK_CONDITION
WHERE A.TABLE_NAME IS NULL ORDER BY OBJECT_NAME;

-- A same-name table with an extra constraint is not the canonical contract.
WITH REQUIRED (TABLE_NAME,CONSTRAINT_TYPE,KEYS,CHECK_CONDITION) AS (VALUES
  ('TEST_REPARTIDOR_COBROS','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_COBROS_AUDIT','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_FINANCIAL_BALANCES','PRIMARY KEY','CODIGO_REPARTIDOR',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OPS','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','UNIQUE','IDEMPOTENCY_TOKEN',''),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CHECK','','IMPORTE>0'),
  ('TEST_REPARTIDOR_LIQUIDACION_GASTOS','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','UNIQUE','IDEMPOTENCY_TOKEN',''),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','CHECK','','IMPORTE<>0'),
  ('TEST_REPARTIDOR_LIQUIDACION_AJUSTES','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','UNIQUE','IDEMPOTENCY_TOKEN',''),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','CHECK','','IMPORTE>0'),
  ('TEST_REPARTIDOR_LIQUIDACION_INGRESOS','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
  ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','PRIMARY KEY','ID',''),
  ('TEST_REPARTIDOR_LIQUIDACION_OUTBOX','CHECK','','STATUSIN''PENDING'',''SENT'',''FAILED''')
), ACTUAL AS (
  SELECT X.TABLE_NAME,
    CASE X.CONSTRAINT_TYPE
      WHEN 'P' THEN 'PRIMARY KEY'
      WHEN 'U' THEN 'UNIQUE'
      WHEN 'C' THEN 'CHECK'
      WHEN 'F' THEN 'FOREIGN KEY'
      ELSE TRIM(X.CONSTRAINT_TYPE)
    END AS CONSTRAINT_TYPE,
    COALESCE(LISTAGG(K.COLUMN_NAME,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION),'') AS KEYS,
    COALESCE(MAX(UPPER(REPLACE(REPLACE(REPLACE(COALESCE(CAST(C.CHECK_CLAUSE AS VARCHAR(4096)),''),' ',''),'(',''),')',''))),'') AS CHECK_CONDITION
  FROM QSYS2.SYSCST X
  LEFT JOIN QSYS2.SYSKEYCST K
    ON K.CONSTRAINT_SCHEMA=X.CONSTRAINT_SCHEMA AND K.CONSTRAINT_NAME=X.CONSTRAINT_NAME
  LEFT JOIN QSYS2.SYSCHKCST C
    ON C.CONSTRAINT_SCHEMA=X.CONSTRAINT_SCHEMA AND C.CONSTRAINT_NAME=X.CONSTRAINT_NAME
  WHERE X.TABLE_SCHEMA='JAVIER' AND X.TABLE_NAME IN (SELECT TABLE_NAME FROM REQUIRED)
  GROUP BY X.TABLE_NAME,X.CONSTRAINT_NAME,X.CONSTRAINT_TYPE
)
SELECT A.TABLE_NAME || ':' || A.CONSTRAINT_TYPE || ':' || A.KEYS AS OBJECT_NAME,
  'STOP_EXTRA_CONSTRAINT_SIGNATURE' AS STATUS
FROM ACTUAL A LEFT JOIN REQUIRED R ON R.TABLE_NAME=A.TABLE_NAME
 AND R.CONSTRAINT_TYPE=A.CONSTRAINT_TYPE AND R.KEYS=A.KEYS AND R.CHECK_CONDITION=A.CHECK_CONDITION
WHERE R.TABLE_NAME IS NULL ORDER BY OBJECT_NAME;

-- Index name, uniqueness, column order and direction are exact.
WITH REQUIRED (INDEX_NAME,TABLE_NAME,IS_UNIQUE,KEYS) AS (VALUES
  ('UX_T_RLO_TOKEN','TEST_REPARTIDOR_LIQUIDACION_OPS','U','IDEMPOTENCY_TOKEN:A'),
  ('UX_T_RLO_MARKER','TEST_REPARTIDOR_LIQUIDACION_OPS','U','IDMARCALIQUIDACION:A'),
  ('UX_T_RLO_REP_DAY','TEST_REPARTIDOR_LIQUIDACION_OPS','U','CODIGOVENDEDOR:A,DIALIQUIDACION:A,MESLIQUIDACION:A,ANOLIQUIDACION:A'),
  ('IX_T_LIQ_GASTO_DAY','TEST_REPARTIDOR_LIQUIDACION_GASTOS','D','CODIGO_REPARTIDOR:A,DIA:A,MES:A,ANO:A,STATUS:A'),
  ('IX_T_LIQ_AJUSTE_DAY','TEST_REPARTIDOR_LIQUIDACION_AJUSTES','D','CODIGO_REPARTIDOR:A,DIA:A,MES:A,ANO:A,STATUS:A'),
  ('IX_T_LIQ_INGRESO_DAY','TEST_REPARTIDOR_LIQUIDACION_INGRESOS','D','CODIGO_REPARTIDOR:A,DIA:A,MES:A,ANO:A,STATUS:A'),
  ('IX_T_LIQ_OUTBOX_STATUS','TEST_REPARTIDOR_LIQUIDACION_OUTBOX','D','STATUS:A,CREATED_AT:A')
), ACTUAL AS (
  SELECT I.INDEX_NAME,I.TABLE_NAME,I.IS_UNIQUE,
    LISTAGG(K.COLUMN_NAME || ':' || K.ORDERING,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION) AS KEYS
  FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K
    ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME
  WHERE I.INDEX_SCHEMA='JAVIER' GROUP BY I.INDEX_NAME,I.TABLE_NAME,I.IS_UNIQUE
)
SELECT R.INDEX_NAME AS OBJECT_NAME,'STOP_INDEX_SIGNATURE_DIFFERENT' AS STATUS
FROM REQUIRED R LEFT JOIN ACTUAL A ON A.INDEX_NAME=R.INDEX_NAME AND A.TABLE_NAME=R.TABLE_NAME
 AND A.IS_UNIQUE=R.IS_UNIQUE AND A.KEYS=R.KEYS
WHERE A.INDEX_NAME IS NULL ORDER BY OBJECT_NAME;

-- Exact application-owned index surface; primary-key backing indexes are
-- already verified through the constraint signatures above.
WITH REQUIRED (INDEX_NAME,TABLE_NAME,IS_UNIQUE,KEYS) AS (VALUES
  ('UX_T_RLO_TOKEN','TEST_REPARTIDOR_LIQUIDACION_OPS','U','IDEMPOTENCY_TOKEN:A'),
  ('UX_T_RLO_MARKER','TEST_REPARTIDOR_LIQUIDACION_OPS','U','IDMARCALIQUIDACION:A'),
  ('UX_T_RLO_REP_DAY','TEST_REPARTIDOR_LIQUIDACION_OPS','U','CODIGOVENDEDOR:A,DIALIQUIDACION:A,MESLIQUIDACION:A,ANOLIQUIDACION:A'),
  ('IX_T_LIQ_GASTO_DAY','TEST_REPARTIDOR_LIQUIDACION_GASTOS','D','CODIGO_REPARTIDOR:A,DIA:A,MES:A,ANO:A,STATUS:A'),
  ('IX_T_LIQ_AJUSTE_DAY','TEST_REPARTIDOR_LIQUIDACION_AJUSTES','D','CODIGO_REPARTIDOR:A,DIA:A,MES:A,ANO:A,STATUS:A'),
  ('IX_T_LIQ_INGRESO_DAY','TEST_REPARTIDOR_LIQUIDACION_INGRESOS','D','CODIGO_REPARTIDOR:A,DIA:A,MES:A,ANO:A,STATUS:A'),
  ('IX_T_LIQ_OUTBOX_STATUS','TEST_REPARTIDOR_LIQUIDACION_OUTBOX','D','STATUS:A,CREATED_AT:A')
), ACTUAL AS (
  SELECT I.INDEX_NAME,I.TABLE_NAME,I.IS_UNIQUE,
    LISTAGG(K.COLUMN_NAME || ':' || K.ORDERING,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION) AS KEYS
  FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K
    ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME
  WHERE I.INDEX_SCHEMA='JAVIER' AND (I.INDEX_NAME LIKE 'UX_T_RLO_%' OR I.INDEX_NAME LIKE 'IX_T_LIQ_%')
  GROUP BY I.INDEX_NAME,I.TABLE_NAME,I.IS_UNIQUE
)
SELECT A.INDEX_NAME AS OBJECT_NAME,'STOP_EXTRA_INDEX_SIGNATURE' AS STATUS
FROM ACTUAL A LEFT JOIN REQUIRED R ON R.INDEX_NAME=A.INDEX_NAME AND R.TABLE_NAME=A.TABLE_NAME
 AND R.IS_UNIQUE=A.IS_UNIQUE AND R.KEYS=A.KEYS
WHERE R.INDEX_NAME IS NULL ORDER BY OBJECT_NAME;

-- Sequence metadata is embedded; isolated verification never needs production 037.
SELECT 'JAVIER.TEST_REPARTIDOR_LIQUIDACION_SEQ' AS OBJECT_NAME,
  'STOP_SEQUENCE_METADATA_DIFFERENT' AS STATUS
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM QSYS2.SYSSEQUENCES WHERE SEQUENCE_SCHEMA='JAVIER'
 AND SEQUENCE_NAME='TEST_REPARTIDOR_LIQUIDACION_SEQ' AND DATA_TYPE='BIGINT'
 AND NUMERIC_PRECISION=19 AND START=1 AND INCREMENT=1 AND MINIMUM_VALUE=1
 AND MAXIMUM_VALUE=9223372036854775807 AND CYCLE_OPTION='NO' AND CACHE=20 AND "ORDER"='NO');

-- Stable tokens consumed by source-contract tests and runbooks:
-- STOP_REQUIRED_COLUMN_MISSING, STOP_REQUIRED_UNIQUE_INDEX_MISSING,
-- COLUMN_DEFAULT, IS_IDENTITY, IDENTITY_GENERATION, IDENTITY_START,
-- IDENTITY_INCREMENT, X.IS_UNIQUE, K.ORDERING, QSYS2.SYSINDEXES,
-- QSYS2.SYSKEYS, QSYS2.SYSCST, QSYS2.SYSKEYCST, QSYS2.SYSSEQUENCES.
