-- Production-only persistence for canonical reparto confirmation.
--
-- NOT EXECUTED by this repository. Execute only after a separate DB2 DDL
-- approval and the production confirmation approval gate. This additive DDL
-- owns only JAVIER.REPARTO_*; it never references, copies, or mutates DSEDAC.
-- Before execution compare QSYS2 metadata. If any target exists, STOP: do not
-- alter, drop, recreate, or copy data under this script.

CREATE TABLE JAVIER.REPARTO_CONFIRMACIONES (
  ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
  IDEMPOTENCY_KEY VARCHAR(128) NOT NULL,
  PAYLOAD_FINGERPRINT CHAR(64) NOT NULL,
  DOCUMENT_ID VARCHAR(160) NOT NULL,
  REPARTIDOR_ID VARCHAR(20) NOT NULL,
  ACTOR_USER_ID VARCHAR(80) NOT NULL,
  CLIENTE_CODIGO VARCHAR(40) NOT NULL,
  CLIENTE_NOMBRE VARCHAR(180) NOT NULL,
  PEDIDO_EJERCICIO INTEGER,
  PEDIDO_NUMERO INTEGER,
  DOCUMENTO_TIPO VARCHAR(10), DOCUMENTO_ORIGEN CHAR(1), DOCUMENTO_SUBEMPRESA CHAR(3),
  DOCUMENTO_EJERCICIO INTEGER, DOCUMENTO_SERIE VARCHAR(10), DOCUMENTO_TERMINAL INTEGER,
  DOCUMENTO_NUMERO INTEGER, DOCUMENTO_XDE INTEGER, DOCUMENTO_DEX INTEGER,
  STATUS VARCHAR(20) NOT NULL, OCCURRED_AT TIMESTAMP NOT NULL,
  CONFIRMED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  RECEPTOR_NOMBRE VARCHAR(100), RECEPTOR_APELLIDOS VARCHAR(160), RECEPTOR_DNI VARCHAR(20),
  FIRMA_EVIDENCE_ID VARCHAR(128), RESULT_JSON CLOB(8K),
  INCIDENCIA_CODIGO VARCHAR(60), INCIDENCIA_DESCRIPCION VARCHAR(1000),
  INCIDENCIA_OBSERVACIONES VARCHAR(1000), OBSERVACIONES VARCHAR(2000),
  LATITUD DECIMAL(10,8), LONGITUD DECIMAL(11,8),
  CONSTRAINT PK_REP_CONFIRM PRIMARY KEY (ID),
  CONSTRAINT CK_REP_CONFIRM_STATUS CHECK (STATUS IN ('ENTREGADO', 'PARCIAL', 'NO_ENTREGADO', 'RECHAZADO'))
);
CREATE UNIQUE INDEX JAVIER.UX_REP_CONFIRM_KEY ON JAVIER.REPARTO_CONFIRMACIONES (IDEMPOTENCY_KEY);
CREATE UNIQUE INDEX JAVIER.UX_REP_CONFIRM_DOCUMENT ON JAVIER.REPARTO_CONFIRMACIONES (DOCUMENT_ID);
CREATE INDEX JAVIER.IX_REP_CONFIRM_REPARTIDOR_AT ON JAVIER.REPARTO_CONFIRMACIONES (REPARTIDOR_ID, CONFIRMED_AT);

CREATE TABLE JAVIER.REPARTO_LINEAS (
  CONFIRMACION_ID BIGINT NOT NULL, LINEA_ID VARCHAR(80) NOT NULL,
  CODIGO_ARTICULO VARCHAR(80) NOT NULL, DESCRIPCION VARCHAR(512),
  CANTIDAD_PEDIDA DECIMAL(15,3) NOT NULL, CANTIDAD_ENTREGADA DECIMAL(15,3) NOT NULL,
  CANTIDAD_RECHAZADA DECIMAL(15,3) NOT NULL DEFAULT 0, CANTIDAD_PENDIENTE DECIMAL(15,3) NOT NULL DEFAULT 0,
  MOTIVO_DIFERENCIA VARCHAR(80), OBSERVACIONES VARCHAR(1000), PRECIO_UNITARIO DECIMAL(15,4),
  CONSTRAINT PK_REP_LINEAS PRIMARY KEY (CONFIRMACION_ID, LINEA_ID),
  CONSTRAINT FK_REP_LINEAS_CONFIRM FOREIGN KEY (CONFIRMACION_ID) REFERENCES JAVIER.REPARTO_CONFIRMACIONES (ID),
  CONSTRAINT CK_REP_LINEAS_NONNEGATIVE CHECK (CANTIDAD_PEDIDA >= 0 AND CANTIDAD_ENTREGADA >= 0 AND CANTIDAD_RECHAZADA >= 0 AND CANTIDAD_PENDIENTE >= 0),
  CONSTRAINT CK_REP_LINEAS_TOTAL CHECK (CANTIDAD_PEDIDA = CANTIDAD_ENTREGADA + CANTIDAD_RECHAZADA + CANTIDAD_PENDIENTE),
  CONSTRAINT CK_REP_LINEAS_MOTIVO CHECK ((CANTIDAD_RECHAZADA + CANTIDAD_PENDIENTE = 0 AND MOTIVO_DIFERENCIA IS NULL) OR (CANTIDAD_RECHAZADA + CANTIDAD_PENDIENTE > 0 AND MOTIVO_DIFERENCIA IS NOT NULL))
);

CREATE TABLE JAVIER.REPARTO_EVIDENCIAS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL, EVIDENCE_ID VARCHAR(128) NOT NULL,
  DOCUMENT_ID VARCHAR(160) NOT NULL, REPARTIDOR_ID VARCHAR(20) NOT NULL, EVIDENCE_KIND VARCHAR(20) NOT NULL,
  STORAGE_REFERENCE VARCHAR(140) NOT NULL, MIME_TYPE VARCHAR(30) NOT NULL, CONTENT_SHA256 CHAR(64) NOT NULL,
  CONTENT_BYTES INTEGER NOT NULL, CONTENT_BLOB BLOB(4M) NOT NULL, STATUS VARCHAR(12) NOT NULL DEFAULT 'PENDIENTE',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, LINKED_AT TIMESTAMP, EXPIRES_AT TIMESTAMP,
  CONSTRAINT PK_REP_EVIDENCE PRIMARY KEY (ID), CONSTRAINT UQ_REP_EVIDENCE_ID UNIQUE (EVIDENCE_ID),
  CONSTRAINT CK_REP_EVIDENCE_KIND CHECK (EVIDENCE_KIND IN ('FIRMA', 'FOTO', 'OTRA')),
  CONSTRAINT CK_REP_EVIDENCE_MIME CHECK (MIME_TYPE IN ('image/png', 'image/jpeg', 'image/webp')),
  CONSTRAINT CK_REP_EVIDENCE_BYTES CHECK (CONTENT_BYTES BETWEEN 1 AND 4194304),
  CONSTRAINT CK_REP_EVIDENCE_STATUS CHECK ((STATUS = 'PENDIENTE' AND LINKED_AT IS NULL AND EXPIRES_AT IS NOT NULL) OR (STATUS = 'ENLAZADA' AND LINKED_AT IS NOT NULL AND EXPIRES_AT IS NULL)),
  CONSTRAINT CK_REP_EVIDENCE_STORAGE CHECK (STORAGE_REFERENCE = 'DB2_BLOB:' CONCAT EVIDENCE_ID)
);
CREATE INDEX JAVIER.IX_REP_EVIDENCE_OWNER ON JAVIER.REPARTO_EVIDENCIAS (DOCUMENT_ID, REPARTIDOR_ID, EVIDENCE_ID);
CREATE INDEX JAVIER.IX_REP_EVIDENCE_EXPIRY ON JAVIER.REPARTO_EVIDENCIAS (STATUS, EXPIRES_AT, EVIDENCE_ID);

CREATE TABLE JAVIER.REPARTO_CONFIRM_EVIDENCIAS (
  CONFIRMACION_ID BIGINT NOT NULL, EVIDENCE_ID VARCHAR(128) NOT NULL,
  CONSTRAINT PK_REP_CONFIRM_EVIDENCE PRIMARY KEY (CONFIRMACION_ID, EVIDENCE_ID),
  CONSTRAINT FK_REP_CONFIRM_EVIDENCE_CONFIRM FOREIGN KEY (CONFIRMACION_ID) REFERENCES JAVIER.REPARTO_CONFIRMACIONES (ID),
  CONSTRAINT FK_REP_CONFIRM_EVIDENCE_ITEM FOREIGN KEY (EVIDENCE_ID) REFERENCES JAVIER.REPARTO_EVIDENCIAS (EVIDENCE_ID)
);
ALTER TABLE JAVIER.REPARTO_CONFIRMACIONES ADD CONSTRAINT FK_REP_CONFIRM_SIGNATURE
  FOREIGN KEY (FIRMA_EVIDENCE_ID) REFERENCES JAVIER.REPARTO_EVIDENCIAS (EVIDENCE_ID);
