-- 036_cobros_numero_counter_seed_javier_DBA_RUN.sql
-- Execute in IBM i ACS Run SQL Scripts with the default semicolon terminator.
-- Scope: seed JAVIER.COBROS_NUMERO_COUNTER for app-only cobros/liquidacion scopes.
-- No DB2 execution was performed while creating this file.
-- Active statements allowed in this artifact: SELECT and guarded INSERT into JAVIER.COBROS_NUMERO_COUNTER only.

-- ============================================================
-- 1_PREFLIGHT
-- ============================================================

-- Expected support tables present: two rows.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME IN ('COBROS_NUMERO_COUNTER', 'COBROS_IDEMPOTENCY')
ORDER BY TABLE_NAME;

-- Expected before seed: COBROS_NUMERO_COUNTER = 0, COBROS_IDEMPOTENCY = 0.
SELECT 'COBROS_NUMERO_COUNTER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM JAVIER.COBROS_NUMERO_COUNTER
UNION ALL
SELECT 'COBROS_IDEMPOTENCY' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM JAVIER.COBROS_IDEMPOTENCY;

-- Source collision check for cobros scope. Expected: 0 rows.
SELECT 'DSTMOVIL.COBROCABEC GMP/2026/R/10' AS CHECK_NAME, COUNT(*) AS ROW_COUNT
FROM DSTMOVIL.COBROCABEC
WHERE SUBEMPRESA = 'GMP'
  AND EJERCICIO = 2026
  AND SERIE = 'R'
  AND TERMINAL = 10;

-- Source collision check for liquidacion scope. Expected: 0 rows.
SELECT 'DSTMOVIL.LIQUIDIARI GMP/2026/L/10' AS CHECK_NAME, COUNT(*) AS ROW_COUNT
FROM DSTMOVIL.LIQUIDIARI
WHERE SUBEMPRESA = 'GMP'
  AND EJERCICIO = 2026
  AND SERIE = 'L'
  AND TERMINAL = 10;

-- Existing counter rows for these scopes. Expected: 0 rows before seed.
SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NEXT_NUMERO, CREATED_AT, UPDATED_AT
FROM JAVIER.COBROS_NUMERO_COUNTER
WHERE (SUBEMPRESA = 'GMP' AND EJERCICIO = 2026 AND SERIE = 'R' AND TERMINAL = 10)
   OR (SUBEMPRESA = 'GMP' AND EJERCICIO = 2026 AND SERIE = 'L' AND TERMINAL = 10)
ORDER BY SERIE, TERMINAL;

-- Optional support key type validation. Expected: zero rows.
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, LENGTH, NUMERIC_SCALE
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_SCHEMA = 'JAVIER'
  AND TABLE_NAME = 'COBROS_NUMERO_COUNTER'
  AND (
    (COLUMN_NAME = 'SUBEMPRESA' AND (DATA_TYPE <> 'CHAR' OR LENGTH <> 3))
    OR (COLUMN_NAME = 'EJERCICIO' AND (DATA_TYPE <> 'NUMERIC' OR LENGTH <> 4 OR NUMERIC_SCALE <> 0))
    OR (COLUMN_NAME = 'SERIE' AND (DATA_TYPE <> 'CHAR' OR LENGTH <> 1))
    OR (COLUMN_NAME = 'TERMINAL' AND (DATA_TYPE <> 'NUMERIC' OR LENGTH <> 3 OR NUMERIC_SCALE <> 0))
    OR (COLUMN_NAME = 'NEXT_NUMERO' AND (DATA_TYPE <> 'NUMERIC' OR LENGTH <> 6 OR NUMERIC_SCALE <> 0))
  )
ORDER BY COLUMN_NAME;

-- ============================================================
-- 2_FORWARD
-- ============================================================

INSERT INTO JAVIER.COBROS_NUMERO_COUNTER (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NEXT_NUMERO)
SELECT 'GMP', 2026, 'R', 10, 1
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (
  SELECT 1
  FROM JAVIER.COBROS_NUMERO_COUNTER
  WHERE SUBEMPRESA = 'GMP'
    AND EJERCICIO = 2026
    AND SERIE = 'R'
    AND TERMINAL = 10
);

INSERT INTO JAVIER.COBROS_NUMERO_COUNTER (SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NEXT_NUMERO)
SELECT 'GMP', 2026, 'L', 10, 1
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (
  SELECT 1
  FROM JAVIER.COBROS_NUMERO_COUNTER
  WHERE SUBEMPRESA = 'GMP'
    AND EJERCICIO = 2026
    AND SERIE = 'L'
    AND TERMINAL = 10
);

-- ============================================================
-- 3_VALIDATION
-- ============================================================

-- Expected seeded counter rows for these exact scopes: 2.
SELECT COUNT(*) AS SEEDED_ROW_COUNT
FROM JAVIER.COBROS_NUMERO_COUNTER
WHERE (SUBEMPRESA = 'GMP' AND EJERCICIO = 2026 AND SERIE = 'R' AND TERMINAL = 10 AND NEXT_NUMERO = 1)
   OR (SUBEMPRESA = 'GMP' AND EJERCICIO = 2026 AND SERIE = 'L' AND TERMINAL = 10 AND NEXT_NUMERO = 1);

-- Exact seeded rows.
SELECT SUBEMPRESA, EJERCICIO, SERIE, TERMINAL, NEXT_NUMERO, CREATED_AT, UPDATED_AT
FROM JAVIER.COBROS_NUMERO_COUNTER
WHERE (SUBEMPRESA = 'GMP' AND EJERCICIO = 2026 AND SERIE = 'R' AND TERMINAL = 10)
   OR (SUBEMPRESA = 'GMP' AND EJERCICIO = 2026 AND SERIE = 'L' AND TERMINAL = 10)
ORDER BY SERIE, TERMINAL;

-- Expected idempotency rows still: 0.
SELECT COUNT(*) AS IDEMPOTENCY_ROW_COUNT
FROM JAVIER.COBROS_IDEMPOTENCY;

-- ============================================================
-- 4_ROLLBACK_REFERENCE
-- ============================================================

-- Reference only. Do not execute by default.
-- Before deleting these seed rows, COBROS_IDEMPOTENCY must still be 0 and mirror rows for these scopes must not exist.
-- Guard checks expected before rollback: all return 0.
-- SELECT COUNT(*) AS IDEMPOTENCY_ROW_COUNT
-- FROM JAVIER.COBROS_IDEMPOTENCY;
--
-- SELECT COUNT(*) AS COBROS_CAB_MIRROR_ROW_COUNT
-- FROM JAVIER.COBROS_CAB
-- WHERE SUBEMPRESA = 'GMP'
--   AND EJERCICIO = 2026
--   AND SERIE = 'R'
--   AND TERMINAL = 10;
--
-- SELECT COUNT(*) AS COBROS_LIQ_MIRROR_ROW_COUNT
-- FROM JAVIER.COBROS_LIQ
-- WHERE SUBEMPRESA = 'GMP'
--   AND EJERCICIO = 2026
--   AND SERIE = 'L'
--   AND TERMINAL = 10;
--
-- If and only if all guard checks are 0, rollback is:
-- DELETE FROM JAVIER.COBROS_NUMERO_COUNTER
-- WHERE (SUBEMPRESA = 'GMP' AND EJERCICIO = 2026 AND SERIE = 'R' AND TERMINAL = 10 AND NEXT_NUMERO = 1)
--    OR (SUBEMPRESA = 'GMP' AND EJERCICIO = 2026 AND SERIE = 'L' AND TERMINAL = 10 AND NEXT_NUMERO = 1);
