-- Additive JAVIER-only persistence for canonical daily liquidation.
-- Prepared DDL only. Existing objects must match the catalog manifest exactly.
-- The live OPS token index UX_REP_LIQ_TOKEN is authoritative and is never duplicated.

--#SET TERMINATOR @
BEGIN
  IF EXISTS (
    SELECT 1 FROM (
      VALUES
      ('SUBEMPRESALIQUIDACION','CHAR',3,-1,-1,'N','Y','', 'NO',''),
      ('EJERCICIOLIQUIDACION','NUMERIC',4,4,0,'N','Y','0','NO',''),
      ('SERIELIQUIDACION','CHAR',1,-1,-1,'N','Y','','NO',''),
      ('TERMINALLIQUIDACION','NUMERIC',3,3,0,'N','Y','0','NO',''),
      ('NUMEROLIQUIDACION','NUMERIC',6,6,0,'N','Y','0','NO',''),
      ('DIALIQUIDACION','NUMERIC',2,2,0,'N','Y','0','NO',''),
      ('MESLIQUIDACION','NUMERIC',2,2,0,'N','Y','0','NO',''),
      ('ANOLIQUIDACION','NUMERIC',4,4,0,'N','Y','0','NO',''),
      ('HORALIQUIDACION','NUMERIC',6,6,0,'N','Y','0','NO',''),
      ('CODIGOVENDEDOR','CHAR',2,-1,-1,'N','Y','','NO',''),
      ('CODIGOVENDEDORUSUARIO','CHAR',2,-1,-1,'N','Y','','NO',''),
      ('CODIGOUSUARIO','CHAR',10,-1,-1,'N','Y','','NO',''),
      ('MATRICULA','CHAR',20,-1,-1,'N','Y','','NO',''),
      ('KILOMETROSSALIDA','NUMERIC',11,11,3,'N','Y','0','NO',''),
      ('KILOMETROSLLEGADA','NUMERIC',11,11,3,'N','Y','0','NO',''),
      ('KILOMETROSRECORRIDOS','NUMERIC',11,11,3,'N','Y','0','NO',''),
      ('IMPORTEEFECTIVO','NUMERIC',10,10,2,'N','Y','0','NO',''),
      ('IMPORTECHEQUES','NUMERIC',10,10,2,'N','Y','0','NO',''),
      ('IMPORTEPOSTDATADOS','NUMERIC',10,10,2,'N','Y','0','NO',''),
      ('IMPORTESALDOACTUAL','NUMERIC',10,10,2,'N','Y','0','NO',''),
      ('IMPORTETOTALAINGRESAR','NUMERIC',10,10,2,'N','Y','0','NO',''),
      ('IMPORTEINGRESOENBANCO','NUMERIC',10,10,2,'N','Y','0','NO',''),
      ('IMPORTEGASTOS','NUMERIC',10,10,2,'N','Y','0','NO',''),
      ('IMPRESOSN','CHAR',1,-1,-1,'N','Y','','NO',''),
      ('CODIGOVEHICULO','CHAR',10,-1,-1,'N','Y','','NO',''),
      ('REVISADOSN','CHAR',1,-1,-1,'N','Y','','NO',''),
      ('IDMARCALIQUIDACION','CHAR',30,-1,-1,'N','Y','','NO',''),
      ('IMPORTEEFECTIVO2','NUMERIC',10,10,2,'N','Y','0','NO',''),
      ('IMPORTEENTREGADO2','NUMERIC',10,10,2,'N','Y','0','NO',''),
      ('IMPORTETARJETA','NUMERIC',10,10,2,'N','Y','0','NO',''),
      ('ID','INTEGER',4,9,0,'N','I','','YES','ALWAYS'),
      ('MARCAACTUALIZACION','VARCHAR',50,-1,-1,'N','Y','','NO',''),
      ('IDEMPOTENCY_TOKEN','VARCHAR',128,-1,-1,'Y','Y','','NO',''),
      ('CREATED_AT','TIMESTMP',10,-1,-1,'Y','Y','CURRENTTIMESTAMP','NO',''),
      ('UPDATED_AT','TIMESTMP',10,-1,-1,'Y','Y','','NO',''),
      ('STATUS','VARCHAR',20,-1,-1,'Y','Y','CLOSED','NO',''),
      ('OPERADOR','VARCHAR',50,-1,-1,'Y','Y','SYSTEM','NO',''),
      ('PANTALLA_ORIGEN','VARCHAR',20,-1,-1,'Y','Y','LIQUIDACIONDIARIA','NO','')
    ) AS E(COLUMN_NAME,DATA_TYPE,LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE,IS_NULLABLE,HAS_DEFAULT,COLUMN_DEFAULT,IS_IDENTITY,IDENTITY_GENERATION)
    FULL OUTER JOIN (
      SELECT COLUMN_NAME,TRIM(DATA_TYPE) AS DATA_TYPE,LENGTH,
        COALESCE(NUMERIC_PRECISION,-1) AS NUMERIC_PRECISION,
        COALESCE(NUMERIC_SCALE,-1) AS NUMERIC_SCALE,IS_NULLABLE,HAS_DEFAULT,
        UPPER(REPLACE(REPLACE(REPLACE(COALESCE(TRIM(COLUMN_DEFAULT),''),'''',''),'_',''),' ','')) AS COLUMN_DEFAULT,
        IS_IDENTITY,COALESCE(IDENTITY_GENERATION,'') AS IDENTITY_GENERATION
      FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER'
        AND TABLE_NAME='REPARTIDOR_LIQUIDACION_OPS'
        AND COLUMN_NAME NOT IN ('REPLAY_IDENTITY_JSON','SNAPSHOT_JSON')
    ) AS A ON A.COLUMN_NAME=E.COLUMN_NAME
      WHERE E.COLUMN_NAME IS NULL OR A.COLUMN_NAME IS NULL OR E.DATA_TYPE<>A.DATA_TYPE
        OR E.LENGTH<>A.LENGTH OR E.NUMERIC_PRECISION<>A.NUMERIC_PRECISION
        OR E.NUMERIC_SCALE<>A.NUMERIC_SCALE OR E.IS_NULLABLE<>A.IS_NULLABLE
        OR E.HAS_DEFAULT<>A.HAS_DEFAULT OR E.COLUMN_DEFAULT<>A.COLUMN_DEFAULT
        OR E.IS_IDENTITY<>A.IS_IDENTITY OR E.IDENTITY_GENERATION<>A.IDENTITY_GENERATION
      FETCH FIRST 1 ROW ONLY) THEN SIGNAL SQLSTATE '75100' SET MESSAGE_TEXT='STOP_PRODUCTION_TABLE_METADATA_MISMATCH'; END IF;
END@

BEGIN
  IF EXISTS (
    SELECT 1 FROM QSYS2.SYSCOLUMNS2
    WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME IN (
      'REPARTIDOR_LIQUIDACION_OPS','REPARTIDOR_LIQUIDACION_GASTOS',
      'REPARTIDOR_LIQUIDACION_AJUSTES','REPARTIDOR_LIQUIDACION_INGRESOS',
      'REPARTIDOR_LIQUIDACION_OUTBOX'
    ) AND ((IS_IDENTITY='YES' AND (COALESCE(IDENTITY_GENERATION,'')<>'ALWAYS'
      OR COALESCE(IDENTITY_START,0)<>1 OR COALESCE(IDENTITY_INCREMENT,0)<>1))
      OR (IS_IDENTITY='NO' AND (IDENTITY_START IS NOT NULL OR IDENTITY_INCREMENT IS NOT NULL)))
    FETCH FIRST 1 ROW ONLY
  ) THEN SIGNAL SQLSTATE '75113' SET MESSAGE_TEXT='STOP_PRODUCTION_IDENTITY_METADATA_MISMATCH'; END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_OPS' AND COLUMN_NAME='REPLAY_IDENTITY_JSON') THEN
    EXECUTE IMMEDIATE 'ALTER TABLE JAVIER.REPARTIDOR_LIQUIDACION_OPS ADD COLUMN REPLAY_IDENTITY_JSON CLOB(8K)';
  ELSEIF EXISTS (SELECT 1 FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_OPS' AND COLUMN_NAME='REPLAY_IDENTITY_JSON' AND (TRIM(DATA_TYPE)<>'CLOB' OR LENGTH<>8192 OR IS_NULLABLE<>'Y' OR HAS_DEFAULT<>'Y' OR COLUMN_DEFAULT IS NOT NULL OR IS_IDENTITY<>'NO')) THEN
    SIGNAL SQLSTATE '75101' SET MESSAGE_TEXT='STOP_REPLAY_IDENTITY_JSON_MISMATCH';
  END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_OPS' AND COLUMN_NAME='SNAPSHOT_JSON') THEN
    EXECUTE IMMEDIATE 'ALTER TABLE JAVIER.REPARTIDOR_LIQUIDACION_OPS ADD COLUMN SNAPSHOT_JSON CLOB(64K)';
  ELSEIF EXISTS (SELECT 1 FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_OPS' AND COLUMN_NAME='SNAPSHOT_JSON' AND (TRIM(DATA_TYPE)<>'CLOB' OR LENGTH<>65536 OR IS_NULLABLE<>'Y' OR HAS_DEFAULT<>'Y' OR COLUMN_DEFAULT IS NOT NULL OR IS_IDENTITY<>'NO')) THEN
    SIGNAL SQLSTATE '75102' SET MESSAGE_TEXT='STOP_SNAPSHOT_JSON_MISMATCH';
  END IF;
END@

BEGIN
  IF EXISTS (
    SELECT 1 FROM QSYS2.SYSCOLUMNS2 C
    WHERE C.TABLE_SCHEMA='JAVIER' AND C.TABLE_NAME IN
      ('REPARTIDOR_LIQUIDACION_GASTOS','REPARTIDOR_LIQUIDACION_AJUSTES','REPARTIDOR_LIQUIDACION_INGRESOS')
      AND NOT (
        (COLUMN_NAME='ID' AND TRIM(DATA_TYPE)='BIGINT' AND LENGTH=8 AND NUMERIC_PRECISION=18 AND NUMERIC_SCALE=0 AND IS_NULLABLE='N' AND HAS_DEFAULT='I' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='YES' AND IDENTITY_GENERATION='ALWAYS')
        OR (COLUMN_NAME='IDEMPOTENCY_TOKEN' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=128 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='CODIGO_REPARTIDOR' AND TRIM(DATA_TYPE)='CHAR' AND LENGTH=2 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME IN ('DIA','MES') AND TRIM(DATA_TYPE)='NUMERIC' AND LENGTH=2 AND NUMERIC_PRECISION=2 AND NUMERIC_SCALE=0 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='ANO' AND TRIM(DATA_TYPE)='NUMERIC' AND LENGTH=4 AND NUMERIC_PRECISION=4 AND NUMERIC_SCALE=0 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='IMPORTE' AND TRIM(DATA_TYPE)='DECIMAL' AND LENGTH=10 AND NUMERIC_PRECISION=10 AND NUMERIC_SCALE=2 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (TABLE_NAME='REPARTIDOR_LIQUIDACION_GASTOS' AND COLUMN_NAME='CATEGORIA' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=40 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (TABLE_NAME='REPARTIDOR_LIQUIDACION_AJUSTES' AND COLUMN_NAME='MOTIVO' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=120 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (TABLE_NAME='REPARTIDOR_LIQUIDACION_INGRESOS' AND COLUMN_NAME='REFERENCIA' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=80 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='OBSERVACION' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=250 AND IS_NULLABLE='Y' AND HAS_DEFAULT='Y' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='STATUS' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=12 AND IS_NULLABLE='N' AND HAS_DEFAULT='Y' AND TRIM(COLUMN_DEFAULT)='''PENDING''' AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='LIQUIDACION_ID' AND TRIM(DATA_TYPE)='BIGINT' AND LENGTH=8 AND NUMERIC_PRECISION=18 AND NUMERIC_SCALE=0 AND IS_NULLABLE='Y' AND HAS_DEFAULT='Y' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='LIQUIDACION_MARKER' AND TRIM(DATA_TYPE)='CHAR' AND LENGTH=30 AND IS_NULLABLE='Y' AND HAS_DEFAULT='Y' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='ACTOR_ID' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=40 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='ACTOR_ROLE' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=30 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='CREATED_AT' AND TRIM(DATA_TYPE)='TIMESTMP' AND LENGTH=10 AND IS_NULLABLE='N' AND HAS_DEFAULT='Y' AND UPPER(REPLACE(COLUMN_DEFAULT,'_',' '))='CURRENT TIMESTAMP' AND IS_IDENTITY='NO')
      ) FETCH FIRST 1 ROW ONLY
  ) THEN SIGNAL SQLSTATE '75111' SET MESSAGE_TEXT='STOP_PRODUCTION_TABLE_METADATA_MISMATCH'; END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_GASTOS') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.REPARTIDOR_LIQUIDACION_GASTOS (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL UNIQUE, CODIGO_REPARTIDOR CHAR(2) NOT NULL, DIA NUMERIC(2) NOT NULL, MES NUMERIC(2) NOT NULL, ANO NUMERIC(4) NOT NULL, IMPORTE DECIMAL(10,2) NOT NULL, CATEGORIA VARCHAR(40) NOT NULL, OBSERVACION VARCHAR(250), STATUS VARCHAR(12) NOT NULL DEFAULT ''PENDING'', LIQUIDACION_ID BIGINT, LIQUIDACION_MARKER CHAR(30), ACTOR_ID VARCHAR(40) NOT NULL, ACTOR_ROLE VARCHAR(30) NOT NULL, CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, CONSTRAINT CK_LIQ_GASTO_IMP CHECK (IMPORTE > 0), CONSTRAINT CK_LIQ_GASTO_STATUS CHECK (STATUS IN (''PENDING'', ''LIQUIDATED'')))';
  ELSEIF (SELECT COUNT(*) FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_GASTOS')<>15 OR EXISTS (SELECT 1 FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_GASTOS' AND ((COLUMN_NAME='ID' AND (TRIM(DATA_TYPE)<>'BIGINT' OR IS_IDENTITY<>'YES' OR IDENTITY_GENERATION<>'ALWAYS')) OR (COLUMN_NAME='IDEMPOTENCY_TOKEN' AND (TRIM(DATA_TYPE)<>'VARCHAR' OR LENGTH<>128 OR IS_NULLABLE<>'N')) OR (COLUMN_NAME='CODIGO_REPARTIDOR' AND (TRIM(DATA_TYPE)<>'CHAR' OR LENGTH<>2 OR IS_NULLABLE<>'N')) OR (COLUMN_NAME IN ('DIA','MES') AND (TRIM(DATA_TYPE)<>'NUMERIC' OR NUMERIC_PRECISION<>2 OR NUMERIC_SCALE<>0 OR IS_NULLABLE<>'N')) OR (COLUMN_NAME='ANO' AND (TRIM(DATA_TYPE)<>'NUMERIC' OR NUMERIC_PRECISION<>4 OR NUMERIC_SCALE<>0 OR IS_NULLABLE<>'N')) OR (COLUMN_NAME='IMPORTE' AND (TRIM(DATA_TYPE)<>'DECIMAL' OR NUMERIC_PRECISION<>10 OR NUMERIC_SCALE<>2 OR IS_NULLABLE<>'N')) OR (COLUMN_NAME='CATEGORIA' AND (TRIM(DATA_TYPE)<>'VARCHAR' OR LENGTH<>40 OR IS_NULLABLE<>'N')) OR (COLUMN_NAME='OBSERVACION' AND (TRIM(DATA_TYPE)<>'VARCHAR' OR LENGTH<>250 OR IS_NULLABLE<>'Y')) OR (COLUMN_NAME='STATUS' AND (TRIM(DATA_TYPE)<>'VARCHAR' OR LENGTH<>12 OR IS_NULLABLE<>'N' OR TRIM(COLUMN_DEFAULT)<>'''PENDING''')) OR (COLUMN_NAME='LIQUIDACION_ID' AND (TRIM(DATA_TYPE)<>'BIGINT' OR IS_NULLABLE<>'Y')) OR (COLUMN_NAME='LIQUIDACION_MARKER' AND (TRIM(DATA_TYPE)<>'CHAR' OR LENGTH<>30 OR IS_NULLABLE<>'Y')) OR (COLUMN_NAME='ACTOR_ID' AND (TRIM(DATA_TYPE)<>'VARCHAR' OR LENGTH<>40 OR IS_NULLABLE<>'N')) OR (COLUMN_NAME='ACTOR_ROLE' AND (TRIM(DATA_TYPE)<>'VARCHAR' OR LENGTH<>30 OR IS_NULLABLE<>'N')) OR (COLUMN_NAME='CREATED_AT' AND (TRIM(DATA_TYPE)<>'TIMESTMP' OR IS_NULLABLE<>'N' OR UPPER(REPLACE(COLUMN_DEFAULT,'_',' '))<>'CURRENT TIMESTAMP')))) THEN
    SIGNAL SQLSTATE '75103' SET MESSAGE_TEXT='STOP_PRODUCTION_TABLE_METADATA_MISMATCH';
  END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_AJUSTES') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.REPARTIDOR_LIQUIDACION_AJUSTES (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL UNIQUE, CODIGO_REPARTIDOR CHAR(2) NOT NULL, DIA NUMERIC(2) NOT NULL, MES NUMERIC(2) NOT NULL, ANO NUMERIC(4) NOT NULL, IMPORTE DECIMAL(10,2) NOT NULL, MOTIVO VARCHAR(120) NOT NULL, OBSERVACION VARCHAR(250), STATUS VARCHAR(12) NOT NULL DEFAULT ''PENDING'', LIQUIDACION_ID BIGINT, LIQUIDACION_MARKER CHAR(30), ACTOR_ID VARCHAR(40) NOT NULL, ACTOR_ROLE VARCHAR(30) NOT NULL, CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, CONSTRAINT CK_LIQ_AJUSTE_NZ CHECK (IMPORTE <> 0), CONSTRAINT CK_LIQ_AJUSTE_STATUS CHECK (STATUS IN (''PENDING'', ''LIQUIDATED'')))';
  ELSEIF (SELECT COUNT(*) FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_AJUSTES')<>15 OR NOT EXISTS (SELECT 1 FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_AJUSTES' AND COLUMN_NAME='MOTIVO' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=120 AND IS_NULLABLE='N') THEN SIGNAL SQLSTATE '75104' SET MESSAGE_TEXT='STOP_PRODUCTION_TABLE_METADATA_MISMATCH'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_INGRESOS') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.REPARTIDOR_LIQUIDACION_INGRESOS (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, IDEMPOTENCY_TOKEN VARCHAR(128) NOT NULL UNIQUE, CODIGO_REPARTIDOR CHAR(2) NOT NULL, DIA NUMERIC(2) NOT NULL, MES NUMERIC(2) NOT NULL, ANO NUMERIC(4) NOT NULL, IMPORTE DECIMAL(10,2) NOT NULL, REFERENCIA VARCHAR(80) NOT NULL, OBSERVACION VARCHAR(250), STATUS VARCHAR(12) NOT NULL DEFAULT ''PENDING'', LIQUIDACION_ID BIGINT, LIQUIDACION_MARKER CHAR(30), ACTOR_ID VARCHAR(40) NOT NULL, ACTOR_ROLE VARCHAR(30) NOT NULL, CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, CONSTRAINT CK_LIQ_INGRESO_IMP CHECK (IMPORTE > 0), CONSTRAINT CK_LIQ_INGRESO_STATUS CHECK (STATUS IN (''PENDING'', ''LIQUIDATED'')))';
  ELSEIF (SELECT COUNT(*) FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_INGRESOS')<>15 OR NOT EXISTS (SELECT 1 FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_INGRESOS' AND COLUMN_NAME='REFERENCIA' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=80 AND IS_NULLABLE='N') THEN SIGNAL SQLSTATE '75105' SET MESSAGE_TEXT='STOP_PRODUCTION_TABLE_METADATA_MISMATCH'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_OUTBOX') THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JAVIER.REPARTIDOR_LIQUIDACION_OUTBOX (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY, LIQUIDACION_ID BIGINT NOT NULL, OUTBOX_TYPE VARCHAR(50) NOT NULL, STATUS VARCHAR(20) NOT NULL DEFAULT ''PENDING'', PAYLOAD_JSON CLOB(16K) NOT NULL, CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, CONSTRAINT CK_LIQ_OUTBOX_STATUS CHECK (STATUS IN (''PENDING'', ''SENT'', ''FAILED'')))';
  ELSEIF (SELECT COUNT(*) FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_OUTBOX')<>6 OR EXISTS (SELECT 1 FROM QSYS2.SYSCOLUMNS2 WHERE TABLE_SCHEMA='JAVIER' AND TABLE_NAME='REPARTIDOR_LIQUIDACION_OUTBOX' AND ((COLUMN_NAME='ID' AND (TRIM(DATA_TYPE)<>'BIGINT' OR IS_IDENTITY<>'YES' OR IDENTITY_GENERATION<>'ALWAYS')) OR (COLUMN_NAME='PAYLOAD_JSON' AND (TRIM(DATA_TYPE)<>'CLOB' OR LENGTH<>16384 OR IS_NULLABLE<>'N')) OR (COLUMN_NAME='STATUS' AND (TRIM(DATA_TYPE)<>'VARCHAR' OR LENGTH<>20 OR IS_NULLABLE<>'N' OR TRIM(COLUMN_DEFAULT)<>'''PENDING''')))) THEN SIGNAL SQLSTATE '75106' SET MESSAGE_TEXT='STOP_PRODUCTION_TABLE_METADATA_MISMATCH'; END IF;
END@

BEGIN
  IF EXISTS (
    SELECT 1 FROM QSYS2.SYSCOLUMNS2 C WHERE C.TABLE_SCHEMA='JAVIER'
      AND C.TABLE_NAME='REPARTIDOR_LIQUIDACION_OUTBOX' AND NOT (
        (COLUMN_NAME='ID' AND TRIM(DATA_TYPE)='BIGINT' AND LENGTH=8 AND NUMERIC_PRECISION=18 AND NUMERIC_SCALE=0 AND IS_NULLABLE='N' AND HAS_DEFAULT='I' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='YES' AND IDENTITY_GENERATION='ALWAYS')
        OR (COLUMN_NAME='LIQUIDACION_ID' AND TRIM(DATA_TYPE)='BIGINT' AND LENGTH=8 AND NUMERIC_PRECISION=18 AND NUMERIC_SCALE=0 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='OUTBOX_TYPE' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=50 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='STATUS' AND TRIM(DATA_TYPE)='VARCHAR' AND LENGTH=20 AND IS_NULLABLE='N' AND HAS_DEFAULT='Y' AND TRIM(COLUMN_DEFAULT)='''PENDING''' AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='PAYLOAD_JSON' AND TRIM(DATA_TYPE)='CLOB' AND LENGTH=16384 AND IS_NULLABLE='N' AND HAS_DEFAULT='N' AND COLUMN_DEFAULT IS NULL AND IS_IDENTITY='NO')
        OR (COLUMN_NAME='CREATED_AT' AND TRIM(DATA_TYPE)='TIMESTMP' AND LENGTH=10 AND IS_NULLABLE='N' AND HAS_DEFAULT='Y' AND UPPER(REPLACE(COLUMN_DEFAULT,'_',' '))='CURRENT TIMESTAMP' AND IS_IDENTITY='NO')
      ) FETCH FIRST 1 ROW ONLY
  ) THEN SIGNAL SQLSTATE '75112' SET MESSAGE_TEXT='STOP_PRODUCTION_TABLE_METADATA_MISMATCH'; END IF;
END@

-- Constraint text and key signatures are mandatory for every existing app-owned table.
BEGIN
  IF EXISTS (
    SELECT 1 FROM (
      VALUES
      ('REPARTIDOR_LIQUIDACION_GASTOS','PRIMARY KEY','ID',''),
      ('REPARTIDOR_LIQUIDACION_GASTOS','UNIQUE','IDEMPOTENCY_TOKEN',''),
      ('REPARTIDOR_LIQUIDACION_GASTOS','CHECK','','IMPORTE>0'),
      ('REPARTIDOR_LIQUIDACION_GASTOS','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
      ('REPARTIDOR_LIQUIDACION_AJUSTES','PRIMARY KEY','ID',''),
      ('REPARTIDOR_LIQUIDACION_AJUSTES','UNIQUE','IDEMPOTENCY_TOKEN',''),
      ('REPARTIDOR_LIQUIDACION_AJUSTES','CHECK','','IMPORTE<>0'),
      ('REPARTIDOR_LIQUIDACION_AJUSTES','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
      ('REPARTIDOR_LIQUIDACION_INGRESOS','PRIMARY KEY','ID',''),
      ('REPARTIDOR_LIQUIDACION_INGRESOS','UNIQUE','IDEMPOTENCY_TOKEN',''),
      ('REPARTIDOR_LIQUIDACION_INGRESOS','CHECK','','IMPORTE>0'),
      ('REPARTIDOR_LIQUIDACION_INGRESOS','CHECK','','STATUSIN''PENDING'',''LIQUIDATED'''),
      ('REPARTIDOR_LIQUIDACION_OUTBOX','PRIMARY KEY','ID',''),
      ('REPARTIDOR_LIQUIDACION_OUTBOX','CHECK','','STATUSIN''PENDING'',''SENT'',''FAILED''')
    ) AS R(TABLE_NAME,CONSTRAINT_TYPE,KEYS,CHECK_CONDITION)
    LEFT JOIN (
      SELECT X.TABLE_NAME,
        CASE X.CONSTRAINT_TYPE
          WHEN 'P' THEN 'PRIMARY KEY'
          WHEN 'U' THEN 'UNIQUE'
          WHEN 'C' THEN 'CHECK'
          WHEN 'F' THEN 'FOREIGN KEY'
          ELSE TRIM(X.CONSTRAINT_TYPE)
        END AS CONSTRAINT_TYPE,
        COALESCE(LISTAGG(K.COLUMN_NAME,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION),'') AS KEYS,
        COALESCE(MIN(UPPER(REPLACE(REPLACE(REPLACE(COALESCE(CAST(C.CHECK_CLAUSE AS VARCHAR(4096)),''),' ',''),'(',''),')',''))),'') AS CHECK_CONDITION
      FROM QSYS2.SYSCST X
      LEFT JOIN QSYS2.SYSKEYCST K
        ON K.CONSTRAINT_SCHEMA=X.CONSTRAINT_SCHEMA AND K.CONSTRAINT_NAME=X.CONSTRAINT_NAME
      LEFT JOIN QSYS2.SYSCHKCST C
        ON C.CONSTRAINT_SCHEMA=X.CONSTRAINT_SCHEMA AND C.CONSTRAINT_NAME=X.CONSTRAINT_NAME
      WHERE X.TABLE_SCHEMA='JAVIER'
      GROUP BY X.TABLE_NAME,X.CONSTRAINT_NAME,X.CONSTRAINT_TYPE
    ) AS A ON A.TABLE_NAME=R.TABLE_NAME AND A.CONSTRAINT_TYPE=R.CONSTRAINT_TYPE AND A.KEYS=R.KEYS AND A.CHECK_CONDITION=R.CHECK_CONDITION
      WHERE R.TABLE_NAME IN (SELECT TABLE_NAME FROM QSYS2.SYSTABLES WHERE TABLE_SCHEMA='JAVIER') AND A.TABLE_NAME IS NULL FETCH FIRST 1 ROW ONLY) THEN SIGNAL SQLSTATE '75107' SET MESSAGE_TEXT='STOP_PRODUCTION_CONSTRAINT_METADATA_MISMATCH'; END IF;
END@

-- Named indexes fail closed on name collision; equivalent exact signatures avoid duplicates.
BEGIN
  IF EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME WHERE I.INDEX_SCHEMA='JAVIER' AND I.INDEX_NAME='UX_REP_LIQ_TOKEN' GROUP BY I.TABLE_NAME,I.IS_UNIQUE,I.INDEX_SCHEMA,I.INDEX_NAME HAVING I.TABLE_NAME<>'REPARTIDOR_LIQUIDACION_OPS' OR I.IS_UNIQUE NOT IN ('U','YES') OR LISTAGG(K.COLUMN_NAME || ':' || K.ORDERING,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION)<>'IDEMPOTENCY_TOKEN:A') THEN SIGNAL SQLSTATE '75114' SET MESSAGE_TEXT='STOP_PRODUCTION_INDEX_METADATA_MISMATCH';
  ELSEIF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME WHERE I.TABLE_SCHEMA='JAVIER' AND I.TABLE_NAME='REPARTIDOR_LIQUIDACION_OPS' AND I.IS_UNIQUE IN ('U','YES') GROUP BY I.INDEX_SCHEMA,I.INDEX_NAME HAVING LISTAGG(K.COLUMN_NAME || ':' || K.ORDERING,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION)='IDEMPOTENCY_TOKEN:A') THEN SIGNAL SQLSTATE '75115' SET MESSAGE_TEXT='STOP_REQUIRED_UNIQUE_INDEX_MISSING'; END IF;
END@

BEGIN
  IF EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME WHERE I.INDEX_SCHEMA='JAVIER' AND I.INDEX_NAME='UX_RLO_MARKER' GROUP BY I.TABLE_NAME,I.IS_UNIQUE,I.INDEX_SCHEMA,I.INDEX_NAME HAVING I.TABLE_NAME<>'REPARTIDOR_LIQUIDACION_OPS' OR I.IS_UNIQUE NOT IN ('U','YES') OR LISTAGG(K.COLUMN_NAME || ':' || K.ORDERING,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION)<>'IDMARCALIQUIDACION:A') THEN SIGNAL SQLSTATE '75108' SET MESSAGE_TEXT='STOP_PRODUCTION_INDEX_METADATA_MISMATCH';
  ELSEIF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME WHERE I.TABLE_SCHEMA='JAVIER' AND I.TABLE_NAME='REPARTIDOR_LIQUIDACION_OPS' AND I.IS_UNIQUE IN ('U','YES') GROUP BY I.INDEX_SCHEMA,I.INDEX_NAME HAVING LISTAGG(K.COLUMN_NAME || ':' || K.ORDERING,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION)='IDMARCALIQUIDACION:A') THEN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX JAVIER.UX_RLO_MARKER ON JAVIER.REPARTIDOR_LIQUIDACION_OPS (IDMARCALIQUIDACION)'; END IF;
END@
BEGIN
  IF EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME WHERE I.INDEX_SCHEMA='JAVIER' AND I.INDEX_NAME='UX_RLO_REP_DAY' GROUP BY I.TABLE_NAME,I.IS_UNIQUE,I.INDEX_SCHEMA,I.INDEX_NAME HAVING I.TABLE_NAME<>'REPARTIDOR_LIQUIDACION_OPS' OR I.IS_UNIQUE NOT IN ('U','YES') OR LISTAGG(K.COLUMN_NAME || ':' || K.ORDERING,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION)<>'CODIGOVENDEDOR:A,DIALIQUIDACION:A,MESLIQUIDACION:A,ANOLIQUIDACION:A') THEN SIGNAL SQLSTATE '75109' SET MESSAGE_TEXT='STOP_PRODUCTION_INDEX_METADATA_MISMATCH';
  ELSEIF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME WHERE I.TABLE_SCHEMA='JAVIER' AND I.TABLE_NAME='REPARTIDOR_LIQUIDACION_OPS' AND I.IS_UNIQUE IN ('U','YES') GROUP BY I.INDEX_SCHEMA,I.INDEX_NAME HAVING LISTAGG(K.COLUMN_NAME || ':' || K.ORDERING,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION)='CODIGOVENDEDOR:A,DIALIQUIDACION:A,MESLIQUIDACION:A,ANOLIQUIDACION:A') THEN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX JAVIER.UX_RLO_REP_DAY ON JAVIER.REPARTIDOR_LIQUIDACION_OPS (CODIGOVENDEDOR,DIALIQUIDACION,MESLIQUIDACION,ANOLIQUIDACION)'; END IF;
END@

BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSSEQUENCES WHERE SEQUENCE_SCHEMA='JAVIER' AND SEQUENCE_NAME='REPARTIDOR_LIQUIDACION_SEQ') THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE JAVIER.REPARTIDOR_LIQUIDACION_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 20 NO ORDER';
  ELSEIF EXISTS (SELECT 1 FROM QSYS2.SYSSEQUENCES WHERE SEQUENCE_SCHEMA='JAVIER' AND SEQUENCE_NAME='REPARTIDOR_LIQUIDACION_SEQ' AND (DATA_TYPE<>'BIGINT' OR NUMERIC_PRECISION<>19 OR START<>1 OR INCREMENT<>1 OR MINIMUM_VALUE<>1 OR MAXIMUM_VALUE<>9223372036854775807 OR CYCLE_OPTION<>'NO' OR CACHE<>20 OR "ORDER"<>'NO')) THEN SIGNAL SQLSTATE '75110' SET MESSAGE_TEXT='STOP_LIQUIDACION_SEQUENCE_MISMATCH'; END IF;
END@

-- Non-unique operational indexes: a wrong existing name is blocked.
BEGIN
  IF EXISTS (
    SELECT 1 FROM (
      VALUES
      ('IX_LIQ_GASTO_DAY','REPARTIDOR_LIQUIDACION_GASTOS','D','CODIGO_REPARTIDOR,DIA,MES,ANO,STATUS'),
      ('IX_LIQ_AJUSTE_DAY','REPARTIDOR_LIQUIDACION_AJUSTES','D','CODIGO_REPARTIDOR,DIA,MES,ANO,STATUS'),
      ('IX_LIQ_INGRESO_DAY','REPARTIDOR_LIQUIDACION_INGRESOS','D','CODIGO_REPARTIDOR,DIA,MES,ANO,STATUS'),
      ('IX_LIQ_OUTBOX_STATUS','REPARTIDOR_LIQUIDACION_OUTBOX','D','STATUS,CREATED_AT')
    ) AS E(INDEX_NAME,TABLE_NAME,IS_UNIQUE,KEYS)
    JOIN (
      SELECT I.INDEX_NAME,I.TABLE_NAME,I.IS_UNIQUE,
        LISTAGG(K.COLUMN_NAME,',') WITHIN GROUP (ORDER BY K.ORDINAL_POSITION) AS KEYS
      FROM QSYS2.SYSINDEXES I JOIN QSYS2.SYSKEYS K
        ON K.INDEX_SCHEMA=I.INDEX_SCHEMA AND K.INDEX_NAME=I.INDEX_NAME
      WHERE I.INDEX_SCHEMA='JAVIER' GROUP BY I.INDEX_NAME,I.TABLE_NAME,I.IS_UNIQUE
    ) AS A ON A.INDEX_NAME=E.INDEX_NAME
      WHERE A.TABLE_NAME<>E.TABLE_NAME OR A.IS_UNIQUE<>E.IS_UNIQUE OR A.KEYS<>E.KEYS
      FETCH FIRST 1 ROW ONLY) THEN SIGNAL SQLSTATE '75113' SET MESSAGE_TEXT='STOP_PRODUCTION_INDEX_METADATA_MISMATCH'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA='JAVIER' AND INDEX_NAME='IX_LIQ_GASTO_DAY') THEN EXECUTE IMMEDIATE 'CREATE INDEX JAVIER.IX_LIQ_GASTO_DAY ON JAVIER.REPARTIDOR_LIQUIDACION_GASTOS (CODIGO_REPARTIDOR,DIA,MES,ANO,STATUS)'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA='JAVIER' AND INDEX_NAME='IX_LIQ_AJUSTE_DAY') THEN EXECUTE IMMEDIATE 'CREATE INDEX JAVIER.IX_LIQ_AJUSTE_DAY ON JAVIER.REPARTIDOR_LIQUIDACION_AJUSTES (CODIGO_REPARTIDOR,DIA,MES,ANO,STATUS)'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA='JAVIER' AND INDEX_NAME='IX_LIQ_INGRESO_DAY') THEN EXECUTE IMMEDIATE 'CREATE INDEX JAVIER.IX_LIQ_INGRESO_DAY ON JAVIER.REPARTIDOR_LIQUIDACION_INGRESOS (CODIGO_REPARTIDOR,DIA,MES,ANO,STATUS)'; END IF;
END@
BEGIN
  IF NOT EXISTS (SELECT 1 FROM QSYS2.SYSINDEXES WHERE INDEX_SCHEMA='JAVIER' AND INDEX_NAME='IX_LIQ_OUTBOX_STATUS') THEN EXECUTE IMMEDIATE 'CREATE INDEX JAVIER.IX_LIQ_OUTBOX_STATUS ON JAVIER.REPARTIDOR_LIQUIDACION_OUTBOX (STATUS,CREATED_AT)'; END IF;
END@
--#SET TERMINATOR ;
