-- Day-scoped REPARTIDOR rutero order (calendar FECHA_RUTA, not weekday).
--
-- NOT EXECUTED by this repository. Run manually on DB2 after QSYS2 compare.
-- Create only MISSING targets; if a target exists, STOP — do not alter/drop/recreate.
-- Staging / isolated_test → JAVIER.TEST_REPARTIDOR_RUTERO_ORDEN
-- Production → JAVIER.REPARTIDOR_RUTERO_ORDEN
-- Selected via REPARTO_TABLE_SET → runtime.tables.routing.order

CREATE TABLE JAVIER.TEST_REPARTIDOR_RUTERO_ORDEN (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  FECHA_RUTA DATE NOT NULL,
  DOCUMENT_ID VARCHAR(80) NOT NULL,
  CLIENTE_CODIGO VARCHAR(20),
  ORDEN INTEGER NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT PK_TEST_REP_RUT_ORDEN PRIMARY KEY (REPARTIDOR_ID, FECHA_RUTA, DOCUMENT_ID)
);
CREATE INDEX JAVIER.IX_TEST_REP_RUT_ORDEN_FECHA
  ON JAVIER.TEST_REPARTIDOR_RUTERO_ORDEN (REPARTIDOR_ID, FECHA_RUTA, ORDEN);

CREATE TABLE JAVIER.REPARTIDOR_RUTERO_ORDEN (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  FECHA_RUTA DATE NOT NULL,
  DOCUMENT_ID VARCHAR(80) NOT NULL,
  CLIENTE_CODIGO VARCHAR(20),
  ORDEN INTEGER NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT PK_REP_RUT_ORDEN PRIMARY KEY (REPARTIDOR_ID, FECHA_RUTA, DOCUMENT_ID)
);
CREATE INDEX JAVIER.IX_REP_RUT_ORDEN_FECHA
  ON JAVIER.REPARTIDOR_RUTERO_ORDEN (REPARTIDOR_ID, FECHA_RUTA, ORDEN);
