-- Notification role targets (vendor codes only — NO email column) + variance outbox.
--
-- NOT EXECUTED by this repository. Run manually on DB2 after QSYS2 compare.
-- Create only MISSING targets; if a target exists, STOP — do not alter/drop/recreate.
-- Staging / isolated_test → JAVIER.TEST_* tables
-- Production → JAVIER.* tables (no TEST_ prefix)
-- Selected via REPARTO_TABLE_SET → runtime.tables.notifications.*

-- ─── ROLE TARGETS (vendor codes / optional name patterns — emails resolved live) ───

CREATE TABLE JAVIER.TEST_NOTIFICATION_ROLE_TARGETS (
  ROLE_KEY VARCHAR(40) NOT NULL,
  VENDOR_CODE CHAR(2) NOT NULL,
  NAME_MATCH VARCHAR(80),
  ACTIVE CHAR(1) NOT NULL DEFAULT 'S',
  NOTES VARCHAR(200),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  CONSTRAINT PK_TEST_NOTIF_ROLE_TARGETS PRIMARY KEY (ROLE_KEY),
  CONSTRAINT CK_TEST_NOTIF_ROLE_ACTIVE CHECK (ACTIVE IN ('S', 'N'))
);

CREATE TABLE JAVIER.NOTIFICATION_ROLE_TARGETS (
  ROLE_KEY VARCHAR(40) NOT NULL,
  VENDOR_CODE CHAR(2) NOT NULL,
  NAME_MATCH VARCHAR(80),
  ACTIVE CHAR(1) NOT NULL DEFAULT 'S',
  NOTES VARCHAR(200),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  CONSTRAINT PK_NOTIF_ROLE_TARGETS PRIMARY KEY (ROLE_KEY),
  CONSTRAINT CK_NOTIF_ROLE_ACTIVE CHECK (ACTIVE IN ('S', 'N'))
);

-- Seed roles (vendor codes only — never hardcode mailbox addresses)
MERGE INTO JAVIER.TEST_NOTIFICATION_ROLE_TARGETS AS T
USING (
  SELECT 'JAVIER_LACAL' AS ROLE_KEY, 'A2' AS VENDOR_CODE, 'LACAL' AS NAME_MATCH, 'S' AS ACTIVE, 'Javier Lacal' AS NOTES FROM SYSIBM.SYSDUMMY1
  UNION ALL
  SELECT 'CARLOS_CORBALAN', '30', 'CARLOS', 'S', 'Carlos Corbalan vendor 30' FROM SYSIBM.SYSDUMMY1
  UNION ALL
  SELECT 'OFICINA', '32', 'PEDIDOS', 'S', 'Oficina pedidos' FROM SYSIBM.SYSDUMMY1
) AS S
ON T.ROLE_KEY = S.ROLE_KEY
WHEN NOT MATCHED THEN
  INSERT (ROLE_KEY, VENDOR_CODE, NAME_MATCH, ACTIVE, NOTES)
  VALUES (S.ROLE_KEY, S.VENDOR_CODE, S.NAME_MATCH, S.ACTIVE, S.NOTES);

MERGE INTO JAVIER.NOTIFICATION_ROLE_TARGETS AS T
USING (
  SELECT 'JAVIER_LACAL' AS ROLE_KEY, 'A2' AS VENDOR_CODE, 'LACAL' AS NAME_MATCH, 'S' AS ACTIVE, 'Javier Lacal' AS NOTES FROM SYSIBM.SYSDUMMY1
  UNION ALL
  SELECT 'CARLOS_CORBALAN', '30', 'CARLOS', 'S', 'Carlos Corbalan vendor 30' FROM SYSIBM.SYSDUMMY1
  UNION ALL
  SELECT 'OFICINA', '32', 'PEDIDOS', 'S', 'Oficina pedidos' FROM SYSIBM.SYSDUMMY1
) AS S
ON T.ROLE_KEY = S.ROLE_KEY
WHEN NOT MATCHED THEN
  INSERT (ROLE_KEY, VENDOR_CODE, NAME_MATCH, ACTIVE, NOTES)
  VALUES (S.ROLE_KEY, S.VENDOR_CODE, S.NAME_MATCH, S.ACTIVE, S.NOTES);

-- ─── VARIANCE OUTBOX ───

CREATE TABLE JAVIER.TEST_REPARTO_VARIANCE_OUTBOX (
  ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  CONFIRMATION_ID BIGINT NOT NULL,
  DOCUMENT_ID VARCHAR(80) NOT NULL,
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  COMERCIAL_CODE CHAR(2),
  PAYLOAD_JSON CLOB(32K) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  SENT_AT TIMESTAMP,
  ERROR VARCHAR(500),
  DIGEST_INCLUDED CHAR(1) NOT NULL DEFAULT 'N',
  CONSTRAINT CK_TEST_VAR_OUTBOX_STATUS CHECK (STATUS IN ('PENDING', 'SENT', 'FAILED')),
  CONSTRAINT CK_TEST_VAR_OUTBOX_DIGEST CHECK (DIGEST_INCLUDED IN ('S', 'N'))
);
CREATE INDEX JAVIER.IX_TEST_VAR_OUTBOX_STATUS
  ON JAVIER.TEST_REPARTO_VARIANCE_OUTBOX (STATUS, CREATED_AT);
CREATE INDEX JAVIER.IX_TEST_VAR_OUTBOX_DIGEST
  ON JAVIER.TEST_REPARTO_VARIANCE_OUTBOX (DIGEST_INCLUDED, CREATED_AT);

CREATE TABLE JAVIER.REPARTO_VARIANCE_OUTBOX (
  ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  CONFIRMATION_ID BIGINT NOT NULL,
  DOCUMENT_ID VARCHAR(80) NOT NULL,
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  COMERCIAL_CODE CHAR(2),
  PAYLOAD_JSON CLOB(32K) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  SENT_AT TIMESTAMP,
  ERROR VARCHAR(500),
  DIGEST_INCLUDED CHAR(1) NOT NULL DEFAULT 'N',
  CONSTRAINT CK_VAR_OUTBOX_STATUS CHECK (STATUS IN ('PENDING', 'SENT', 'FAILED')),
  CONSTRAINT CK_VAR_OUTBOX_DIGEST CHECK (DIGEST_INCLUDED IN ('S', 'N'))
);
CREATE INDEX JAVIER.IX_VAR_OUTBOX_STATUS
  ON JAVIER.REPARTO_VARIANCE_OUTBOX (STATUS, CREATED_AT);
CREATE INDEX JAVIER.IX_VAR_OUTBOX_DIGEST
  ON JAVIER.REPARTO_VARIANCE_OUTBOX (DIGEST_INCLUDED, CREATED_AT);
