-- Repartidor: reasignación de paradas entre días de la misma semana natural.
--
-- IMPORTANTE:
--   1) Este fichero NO se ejecuta desde Node ni desde el arranque de la API.
--   2) Ejecuta primero el preflight QSYS2 y conserva su salida.
--   3) Si aparece cualquiera de las tablas de producción, detén el proceso y
--      revisa el contrato antes de cambiar nada. No se hace DROP/ALTER.
--   4) El overlay evita escribir DSEDAC.OPP: la fecha efectiva se resuelve en
--      la lectura de la aplicación.
--   5) No hay INSERT ni backfill: la ruta base y los clientes se leen de los
--      datos reales de producción en DSEDAC/DSEMOVIL.
--
SET CURRENT SCHEMA = 'JAVIER';

-- Preflight: las dos consultas siguientes deben devolver cero filas.
SELECT TABLE_SCHEMA, TABLE_NAME
  FROM QSYS2.SYSTABLES
 WHERE TABLE_SCHEMA = 'JAVIER'
   AND TABLE_NAME IN (
     'REPARTIDOR_RUTERO_DIA_OVERRIDE',
     'REPARTIDOR_RUTERO_MOVE_REQUESTS'
   );

SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
  FROM QSYS2.SYSCOLUMNS
 WHERE TABLE_SCHEMA = 'JAVIER'
   AND TABLE_NAME IN (
     'REPARTIDOR_RUTERO_DIA_OVERRIDE',
     'REPARTIDOR_RUTERO_MOVE_REQUESTS'
   )
 ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;

-- Auditoría informativa: no se crean ni se inicializan tablas de prueba.
SELECT TABLE_SCHEMA, TABLE_NAME
  FROM QSYS2.SYSTABLES
 WHERE TABLE_SCHEMA = 'JAVIER'
   AND TABLE_NAME LIKE 'TEST_REPARTIDOR_RUTERO_%';

-- Producción. Estas tablas son únicamente el overlay y la auditoría de los
-- cambios de ruta. La ruta base y los clientes se leen de DSEDAC en tiempo
-- real; esta migración no copia ni inventa datos de clientes.
CREATE TABLE JAVIER.REPARTIDOR_RUTERO_DIA_OVERRIDE (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  WEEK_START DATE NOT NULL,
  DOCUMENT_ID VARCHAR(80) NOT NULL,
  SOURCE_DATE DATE NOT NULL,
  TARGET_DATE DATE NOT NULL,
  TARGET_POSITION INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT CK_REP_RUT_DIA_POSITION CHECK (TARGET_POSITION BETWEEN 0 AND 499),
  CONSTRAINT PK_REP_RUT_DIA PRIMARY KEY
    (REPARTIDOR_ID, WEEK_START, DOCUMENT_ID)
);

CREATE INDEX JAVIER.IX_REP_RUT_DIA_TARGET
  ON JAVIER.REPARTIDOR_RUTERO_DIA_OVERRIDE
     (REPARTIDOR_ID, WEEK_START, TARGET_DATE, TARGET_POSITION);

CREATE TABLE JAVIER.REPARTIDOR_RUTERO_MOVE_REQUESTS (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  WEEK_START DATE NOT NULL,
  IDEMPOTENCY_KEY VARCHAR(128) NOT NULL,
  REQUEST_HASH CHAR(64) NOT NULL,
  STATUS VARCHAR(12) NOT NULL,
  DOCUMENT_IDS VARCHAR(12000) NOT NULL,
  TARGET_DATE DATE NOT NULL,
  TARGET_POSITION INTEGER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  COMPLETED_AT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT CK_REP_RUT_MOVE_POSITION CHECK (TARGET_POSITION BETWEEN 0 AND 499),
  CONSTRAINT CK_REP_RUT_MOVE_STATUS CHECK (STATUS IN ('APPLIED', 'PENDING', 'FAILED')),
  CONSTRAINT PK_REP_RUT_MOVE PRIMARY KEY
    (REPARTIDOR_ID, WEEK_START, IDEMPOTENCY_KEY)
);

-- Activación explícita después de verificar DDL, privilegios, CAS/idempotencia,
-- smoke tests de lectura y monitorización:
-- REPARTIDOR_DAY_MOVE_ENABLED=true