-- Repartidor: reasignación de paradas entre días de la misma semana natural.
--
-- IMPORTANTE:
--   1) Este fichero NO se ejecuta desde Node ni desde el arranque de la API.
--   2) Ejecuta primero el preflight QSYS2 y conserva su salida.
--   3) Si aparece cualquier tabla/columna existente, detén el proceso y revisa
--      el contrato antes de cambiar nada. No se hace DROP/ALTER.
--   4) El overlay evita escribir DSEDAC.OPP: la fecha efectiva se resuelve en
--      la lectura de la aplicación.
--
-- Preflight: el resultado esperado de cada consulta es cero filas.
SELECT TABLE_SCHEMA, TABLE_NAME
  FROM QSYS2.SYSTABLES
 WHERE (TABLE_SCHEMA, TABLE_NAME) IN (
   ('JAVIER', 'TEST_REPARTIDOR_RUTERO_DIA_OVERRIDE'),
   ('JAVIER', 'REPARTIDOR_RUTERO_DIA_OVERRIDE'),
   ('JAVIER', 'TEST_REPARTIDOR_RUTERO_MOVE_REQUESTS'),
   ('JAVIER', 'REPARTIDOR_RUTERO_MOVE_REQUESTS')
 );

SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
  FROM QSYS2.SYSCOLUMNS
 WHERE (TABLE_SCHEMA, TABLE_NAME) IN (
   ('JAVIER', 'TEST_REPARTIDOR_RUTERO_DIA_OVERRIDE'),
   ('JAVIER', 'REPARTIDOR_RUTERO_DIA_OVERRIDE'),
   ('JAVIER', 'TEST_REPARTIDOR_RUTERO_MOVE_REQUESTS'),
   ('JAVIER', 'REPARTIDOR_RUTERO_MOVE_REQUESTS')
 )
 ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;

-- Aislado para staging/test. Ejecutar solo si el preflight anterior no
-- devolvió ninguna fila y la versión de las columnas está aprobada.
CREATE TABLE JAVIER.TEST_REPARTIDOR_RUTERO_DIA_OVERRIDE (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  WEEK_START DATE NOT NULL,
  DOCUMENT_ID VARCHAR(80) NOT NULL,
  SOURCE_DATE DATE NOT NULL,
  TARGET_DATE DATE NOT NULL,
  TARGET_POSITION INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT PK_TEST_REP_RUT_DIA PRIMARY KEY
    (REPARTIDOR_ID, WEEK_START, DOCUMENT_ID)
);

CREATE INDEX JAVIER.IX_TEST_REP_RUT_DIA_TARGET
  ON JAVIER.TEST_REPARTIDOR_RUTERO_DIA_OVERRIDE
     (REPARTIDOR_ID, WEEK_START, TARGET_DATE, TARGET_POSITION);

CREATE TABLE JAVIER.TEST_REPARTIDOR_RUTERO_MOVE_REQUESTS (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  WEEK_START DATE NOT NULL,
  IDEMPOTENCY_KEY VARCHAR(128) NOT NULL,
  REQUEST_HASH CHAR(64) NOT NULL,
  STATUS VARCHAR(12) NOT NULL,
  DOCUMENT_IDS VARCHAR(8000) NOT NULL,
  TARGET_DATE DATE NOT NULL,
  TARGET_POSITION INTEGER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  COMPLETED_AT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT PK_TEST_REP_RUT_MOVE PRIMARY KEY
    (REPARTIDOR_ID, WEEK_START, IDEMPOTENCY_KEY)
);

-- Producción. Ejecutar en una ventana aprobada y solo después de comparar
-- explícitamente QSYS2 en producción. Nunca se ejecuta contra DSEDAC.
CREATE TABLE JAVIER.REPARTIDOR_RUTERO_DIA_OVERRIDE (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  WEEK_START DATE NOT NULL,
  DOCUMENT_ID VARCHAR(80) NOT NULL,
  SOURCE_DATE DATE NOT NULL,
  TARGET_DATE DATE NOT NULL,
  TARGET_POSITION INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT PK_REP_RUT_DIA PRIMARY KEY
    (REPARTIDOR_ID, WEEK_START, DOCUMENT_ID)
);

CREATE INDEX JAVIER.IX_REP_RUT_DIA_TARGET
  ON JAVIER.REPARTIDOR_RUTERO_DIA_OVERRIDE
     (REPARTIDOR_ID, WEEK_START, TARGET_DATE, TARGET_POSITION);

CREATE TABLE JAVIER.REPARTIDOR_RUTERO_MOVE_REQUESTS (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  WEEK_START DATE NOT NULL,
  IDEMPOTENCY_KEY VARCHAR(128) NOT NULL,
  REQUEST_HASH CHAR(64) NOT NULL,
  STATUS VARCHAR(12) NOT NULL,
  DOCUMENT_IDS VARCHAR(8000) NOT NULL,
  TARGET_DATE DATE NOT NULL,
  TARGET_POSITION INTEGER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  COMPLETED_AT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT PK_REP_RUT_MOVE PRIMARY KEY
    (REPARTIDOR_ID, WEEK_START, IDEMPOTENCY_KEY)
);

-- Activación explícita de la capacidad, tras validar tablas, privilegios,
-- pruebas de rollback/CAS/idempotencia y monitorización:
-- REPARTIDOR_DAY_MOVE_ENABLED=true
