-- Repartidor: histórico de posiciones GPS por sesión.
-- No se ejecuta automáticamente. Verifica primero QSYS2.SYSTABLES/SYSCOLUMNS,
-- privilegios, retención y política de privacidad. No escribir DSEDAC.
-- Esta tabla solo guarda eventos reales recibidos desde el móvil; no contiene
-- datos semilla ni copias de clientes.

SET CURRENT SCHEMA = 'JAVIER';

-- Preflight: la consulta debe devolver cero filas.
SELECT TABLE_SCHEMA, TABLE_NAME
  FROM QSYS2.SYSTABLES
 WHERE TABLE_SCHEMA = 'JAVIER'
   AND TABLE_NAME = 'REPARTIDOR_RUTERO_TRACKING';

SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
  FROM QSYS2.SYSCOLUMNS
 WHERE TABLE_SCHEMA = 'JAVIER'
   AND TABLE_NAME = 'REPARTIDOR_RUTERO_TRACKING'
 ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;

-- Auditoría informativa: no se crean ni se inicializan tablas de prueba.
SELECT TABLE_SCHEMA, TABLE_NAME
  FROM QSYS2.SYSTABLES
 WHERE TABLE_SCHEMA = 'JAVIER'
   AND TABLE_NAME LIKE 'TEST_REPARTIDOR_RUTERO_%';

-- Producción. Solo guarda eventos enviados por el móvil para seguimiento;
-- no copia ni sustituye los datos maestros de DSEDAC/DSEMOVIL.
CREATE TABLE JAVIER.REPARTIDOR_RUTERO_TRACKING (
  SESSION_ID VARCHAR(64) NOT NULL,
  EVENT_ID VARCHAR(128) NOT NULL,
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  ROUTE_DATE DATE NOT NULL,
  EVENT_TYPE VARCHAR(12) NOT NULL,
  LATITUDE DECIMAL(10, 7),
  LONGITUDE DECIMAL(10, 7),
  ACCURACY_METERS DECIMAL(8, 2),
  SPEED_KMH DECIMAL(8, 2),
  HEADING_DEGREES DECIMAL(7, 2),
  RECORDED_AT TIMESTAMP NOT NULL,
  RECEIVED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT CK_REP_TRACKING_EVENT_TYPE CHECK (EVENT_TYPE IN ('START', 'POSITION', 'STOP')),
  CONSTRAINT PK_REP_TRACKING PRIMARY KEY (SESSION_ID, EVENT_ID)
);

CREATE INDEX JAVIER.IX_REP_TRACKING_LATEST
  ON JAVIER.REPARTIDOR_RUTERO_TRACKING
     (REPARTIDOR_ID, ROUTE_DATE, EVENT_TYPE, RECORDED_AT);

-- Activación posterior a la verificación, despliegue autorizado y salud:
-- REPARTIDOR_TRACKING_ENABLED=true