-- Isolated test only. Manual execution after QSYS2 preflight.
-- Never run this script in production and never execute it against DSEDAC.
-- Runtime mapping: REPARTO_TABLE_SET=isolated_test.
SET CURRENT SCHEMA = 'JAVIER';

-- Every query below must be reviewed before CREATE. If any object exists,
-- stop and compare its columns before executing the corresponding statement.
SELECT TABLE_SCHEMA, TABLE_NAME
  FROM QSYS2.SYSTABLES
 WHERE TABLE_SCHEMA = 'JAVIER'
   AND TABLE_NAME IN (
     'TEST_REPARTIDOR_RUTERO_DIA_OVERRIDE',
     'TEST_REPARTIDOR_RUTERO_MOVE_REQUESTS',
     'TEST_REPARTIDOR_RUTERO_TRACKING'
   );

SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
  FROM QSYS2.SYSCOLUMNS
 WHERE TABLE_SCHEMA = 'JAVIER'
   AND TABLE_NAME IN (
     'TEST_REPARTIDOR_RUTERO_DIA_OVERRIDE',
     'TEST_REPARTIDOR_RUTERO_MOVE_REQUESTS',
     'TEST_REPARTIDOR_RUTERO_TRACKING'
   )
 ORDER BY TABLE_NAME, ORDINAL_POSITION;

CREATE TABLE JAVIER.TEST_REPARTIDOR_RUTERO_DIA_OVERRIDE (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  WEEK_START DATE NOT NULL,
  DOCUMENT_ID VARCHAR(80) NOT NULL,
  SOURCE_DATE DATE NOT NULL,
  TARGET_DATE DATE NOT NULL,
  TARGET_POSITION INTEGER NOT NULL,
  VERSION INTEGER NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT CK_TEST_REP_RUT_DIA_POSITION CHECK (TARGET_POSITION BETWEEN 0 AND 499),
  CONSTRAINT PK_TEST_REP_RUT_DIA PRIMARY KEY
    (REPARTIDOR_ID, WEEK_START, DOCUMENT_ID)
);

CREATE INDEX JAVIER.IX_TEST_REP_RUT_DIA_TARGET
  ON JAVIER.TEST_REPARTIDOR_RUTERO_DIA_OVERRIDE
     (REPARTIDOR_ID, WEEK_START, TARGET_DATE, TARGET_POSITION);

CREATE TABLE JAVIER.TEST_REPARTIDOR_RUTERO_MOVE_REQUESTS (
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  WEEK_START DATE NOT NULL,
  IDEMPOTENCY_KEY VARCHAR(128) NOT NULL,
  REQUEST_HASH CHAR(64) NOT NULL,
  STATUS VARCHAR(12) NOT NULL,
  DOCUMENT_IDS VARCHAR(12000) NOT NULL,
  TARGET_DATE DATE NOT NULL,
  TARGET_POSITION INTEGER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  COMPLETED_AT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT CK_TEST_REP_RUT_MOVE_POSITION CHECK (TARGET_POSITION BETWEEN 0 AND 499),
  CONSTRAINT CK_TEST_REP_RUT_MOVE_STATUS CHECK (STATUS IN ('APPLIED', 'PENDING', 'FAILED')),
  CONSTRAINT PK_TEST_REP_RUT_MOVE PRIMARY KEY
    (REPARTIDOR_ID, WEEK_START, IDEMPOTENCY_KEY)
);

CREATE TABLE JAVIER.TEST_REPARTIDOR_RUTERO_TRACKING (
  SESSION_ID VARCHAR(64) NOT NULL,
  EVENT_ID VARCHAR(128) NOT NULL,
  REPARTIDOR_ID VARCHAR(10) NOT NULL,
  ROUTE_DATE DATE NOT NULL,
  EVENT_TYPE VARCHAR(12) NOT NULL,
  LATITUDE DECIMAL(10, 7),
  LONGITUDE DECIMAL(10, 7),
  ACCURACY_METERS DECIMAL(8, 2),
  SPEED_KMH DECIMAL(8, 2),
  HEADING_DEGREES DECIMAL(7, 2),
  RECORDED_AT TIMESTAMP NOT NULL,
  RECEIVED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  UPDATED_BY VARCHAR(40),
  CONSTRAINT CK_TEST_REP_TRACKING_EVENT_TYPE CHECK (EVENT_TYPE IN ('START', 'POSITION', 'STOP')),
  CONSTRAINT PK_TEST_REP_TRACKING PRIMARY KEY (SESSION_ID, EVENT_ID)
);

CREATE INDEX JAVIER.IX_TEST_REP_TRACKING_LATEST
  ON JAVIER.TEST_REPARTIDOR_RUTERO_TRACKING
     (REPARTIDOR_ID, ROUTE_DATE, EVENT_TYPE, RECORDED_AT);
